kubernetes/samples/scripts/domain-lifecycle/README.md, kubernetes/samples/scripts/domain-lifecycle/helper.sh, kubernetes/samples/scripts/domain-lifecycle/scaleCluster.sh
OWLS-87849 - The `scaleCluster.sh` script is similar to the cluster stop/start scripts and it patches the replicas attribute for the cluster with the specified value. It performs validations to ensure that clusterName exists in domain topology and that the specified value of replica count is in the allowed range. If the cluster doesn't exist under `.spec.clusters` in the domain resource, it adds the cluster. 
The PR also changes the logic for the cluster stop/start scripts to add the cluster under `.spec.clusters` in the domain resource if it doesn't exist.
Integration test run URL - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4171/
=> OWLS-87849 - scaleCluster.sh script to patch the 'replicas' attribute of the WLS cluster

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java
In the nightly Jenkins run, sometime we will get the test failure from ITMiiDynamicUpdate#testMiiChangeListenPort, testMiiChangeListenAddress and testMiiChangeSSL. 
The reason of the failure:
Those tests are negative tests and at the end of tests, I updated the config map with correct contents and verify the introspector pod is created, runs and deleted. However if the content change in the config map is too small and the introspector runs very fast, the test will not detect the introspector got created. 
How to fix it:
Just verify the introspector pod was deleted after the config map is updated.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4207/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4206/ …
=> fix intermittent test issue in ITMiiDynamicUpdate testMiiChangeListenPort

operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsServerConfig.java, operator/src/main/resources/scripts/introspectDomain.py, operator/src/test/java/oracle/kubernetes/operator/helpers/ClusterServiceHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ManagerServerServiceHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTest.java
We received an enhancement request from the mobile communications business unit to better support the sip and sips protocols by updating our container and Service ports to specify both TCP and UDP ports when a network access point supports one of these protocols.
The ports will share a listenAddress, which is legal, but can't share a name, so I've chosen to prefix the UDP port's name with "udp-" since this is also consistent with the Istio port naming convention.
Update:
I figured out why we previously needed the testNodePort filtering behavior... The use of a ports variable created state in the context. If I remove this variable and check for duplication in the generated ports of the model then we can both prevent duplication and allow for the two different SIP service ports that share a …
=> The sip and sips protocols support both TCP and UPD on the same channel

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java, kubernetes/samples/scripts/domain-lifecycle/README.md, kubernetes/samples/scripts/domain-lifecycle/helper.sh, kubernetes/samples/scripts/domain-lifecycle/scaleCluster.sh, kubernetes/samples/scripts/domain-lifecycle/startCluster.sh, kubernetes/samples/scripts/domain-lifecycle/startDomain.sh, kubernetes/samples/scripts/domain-lifecycle/startServer.sh, kubernetes/samples/scripts/domain-lifecycle/stopCluster.sh, kubernetes/samples/scripts/domain-lifecycle/stopDomain.sh, kubernetes/samples/scripts/domain-lifecycle/stopServer.sh, operator/src/main/java/oracle/kubernetes/operator/IntrospectorConfigMapConstants.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java
Fix for Owls 87307 and change to store the domain topology in JSON format (in addition to YAML format). This change removes the dependency on `yq` and/or `python` when running scripts on Mac OS or with versions of python that don't have YAML module support. This change helps in the documentation of pre-requisites for running domain lifecycle scripts (OWLS-87478).
Integration test run URL - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4235/
=> Owls 87307 fix and change to store the domain topology in json format (for OWLS-87478) 

operator/src/main/java/oracle/kubernetes/operator/helpers/AnnotationHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/http/HttpAsyncRequestStep.java, operator/src/main/java/oracle/kubernetes/operator/http/HttpResponseStep.java, operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java, operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ReadHealthStep.java, operator/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/http/HttpAsyncRequestStepTest.java
The PR contains a fix for a problem in http error handling that is discovered during testing domain secure mode enabled without configuring SSL use case, plus some code cleanup based on warnings in IntelliJ. 
Problem: when a HttpAsyncRequestStep's AsyncProcessing is resumed without a response object, it was always considered as a timeout although sometimes resume is called with an Exception that should be made visible to the user. One example of such exceptions is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. 
With the fix, operator logs a warning message and fails the corresponding step.
(Note: the changes originally contained a fix for a NPE on …
=> Fix http throwable responses

docs-source/content/faq/resource-settings.md, kubernetes/samples/scripts/create-weblogic-domain/manually-create-domain/domain.yaml
Fixed the missing `resources` in the documentation and sample for setting the resource requests and limits in `domain.spec.serverPod` section.
=> Documentation and sample correction for setting the resource requests and limits

operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java, operator/src/main/java/oracle/kubernetes/operator/utils/ChecksumUtils.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/Matchers.java
OWLS-87956 - K8s volume name has a limit of 63 characters. For override secrets, the operator generates volume name by appending "-volume" to the secret name. If the volume name length exceeds the limit, the volume fails to be mounted.  
This change creates a shorter volume name (based on the ordinal suffix) for the override secrets when the secret name exceeds the limit and uses the old naming scheme when the secret name length is less than the limit. 
Added new unit tests in the JobHelperTest and integration test results are at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4264/
=> Owls 87956 - Generate shorter volume name when override secret name is too long

operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/test/java/oracle/kubernetes/operator/helpers/AdminPodHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ExpectedSHA256Values.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
This changes verifies some cases of SHA256 hash computations and ensures that they don't change over time. The hash values used as references are those generated by operator version 3.1.0.
=> Preserve pod SHA256 values

operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/utils.py
I have come up with this so far and I think it is close,  I have some commented code due to refactoring and will remove it later.
=> Network ports resolution between operator and wls runtime

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/K8sEvents.java
Integration test to verify that domain processing completed event is generated after the domain is scaled. The test performs scale down and scale up Integration test run URL - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4285. I'm rerunning the integration test and update the latest URL when the test finishes.
=> Owls 87012 - Domain processing completed event generated after domain scaling operation integration test

operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java
This fix is to avoid introspector job rebuild the domain when nothing changed after upgrading to 3.2.0.  The online update environment variables should only be set when it s online update.
=> Fix to avoid intrsopector rebuild the domain after upgrading to 3.2.0

docs-source/content/userguide/managing-domains/accessing-the-domain/admin-console.md
First draft of doc for using the Remote Console with WLS in Kubernetes. 
@maggiehe00 and @mriccell The bulleted items at the end of the doc, should include cross-references to how to configure those items either in this doc or in a sample doc.
=> Ready for Review - add Remote Console doc

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSessionMigration.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4447/
=> Add max wait time to session migration test

operator/integration-tests/model-in-image/mii-sample-wrapper/stage-tooling.sh
Fix failures in ItMiiSample test:
- testWlsInitialUseCase
- testFmwInitialUseCase
due to https://github.com/oracle/weblogic-deploy-tooling/releases/latest returning more than one entry containing "releases/download"
<a href="/oracle/weblogic-deploy-tooling/releases/download/release-1.9.11/weblogic-deploy.tar.gz" rel="nofollow" class="d-flex flex-items-center min-width-0">
<a href="/oracle/weblogic-deploy-tooling/releases/download/release-1.9.11/weblogic-deploy.zip" rel="nofollow" class="d-flex flex-items-center min-width-0">
causing the resulting url from stage-tooling.sh to become:
'https://github.com//oracle/weblogic-deploy-tooling/releases/download/release-1.9.11/weblogic-deploy.tar.gz
/oracle/weblogic-deploy-tooling/releases/download/release-1.9.11/weblogic-deploy.zip'
causing curl: …
=> Fix failures in ItMiiSample test

operator/src/main/java/oracle/kubernetes/operator/calls/AsyncRequestStep.java, operator/src/test/java/oracle/kubernetes/operator/calls/AsyncRequestStepTest.java
AsyncRequestStep change to make sure that API calls are retried after an exponential backoff for status code 0 (timeout or no response).
=> Exponential back off in retry logic in case of http status code 0 (no response)

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java
Couple of tests currently doesn't carry the domain model changes made in the previous tests, that can cause domain restart for some cases, fixing that with these changes.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4599/
testMiiRemoveTarget - known failure, Johnny is working on it
=> ItMiiDynamicUpdate - maintain model changes in the tests

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCustomSslStore.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiJmsRecovery.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java
testMiiRemoveTarget fails when data home is set at domain resource level because of bug 
https://jira.oraclecorp.com/jira/browse/OWLS-88679
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4615/
=> Fix testMiiRemoveTarget by not setting datahome on domain resource

kubernetes/samples/scripts/common/utility.sh, kubernetes/samples/scripts/common/validate.sh, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-job-template.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain.sh, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/update-domain-job-template.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/update-domain.sh, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/wdt_model_dynamic.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt_k8s_model_template.yaml
When updating the domain-on-pv using wdt sample, DynamicClusterSize was mistakenly set to DynamicClusterSize to initialReplicaCountServers. This caused only 2 servers to be configured. But setting it to ConfiguredManagedServerCount, all the servers were started. The fix is to set DynamicClusterSize to ConfiguredManagedServerCount in the topology section of the model file. Also, set replicas to 2 and added a cluster section with the initial cluster (cluster-1) and its replicas in the kubernetes section. This started the replica count of cluster-1 servers and when a second cluster was added, started 2 server in the second cluster. I also verified scaling up and down both the clusters and they work as expected.
Also fixed the issue - weblogic-deploy.zip fails to download because the proxy is …
=> fix domain on pv with wdt sample

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java
Remove the exit code status check for the curl command. A for loop is used to recursively send http requests to the weblogic servers to populate the http access logs. Retry until the HTTP response code is 200.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4699/
=> Remove the exitcode check and add retry

documentation/staging/content/userguide/managing-domains/domain-events.md, operator/src/main/java/oracle/kubernetes/operator/DomainNamespaces.java, operator/src/main/java/oracle/kubernetes/operator/DomainRecheck.java, operator/src/main/java/oracle/kubernetes/operator/EventConstants.java, operator/src/main/java/oracle/kubernetes/operator/NamespaceStatus.java, operator/src/main/java/oracle/kubernetes/operator/helpers/EventHelper.java, operator/src/test/java/oracle/kubernetes/operator/NamespaceTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/EventHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/EventRetryStrategyStub.java
DomainNamespaces keeps the status of each namespace that the operator manages, which includes a flag to indicate the namespace is starting already. During a regular recheck domain cycle (fullCheck = false), the isNamespaceStarting flag (AtomicBoolean) is set using getAndSet method, and once it is set, the operator never unset it until the namespace is removed from the list of namespaces that the operator manages. 
As a result, when there is an "unrecoverable" failure, such as API server returns a http return code 403,  when the operator starts a namespace, the namespace will be skipped from the subsequent regular retry cycles because it is considered isStarting already. Eventually, a skipped namespace may be started in a fullCheck recheck. But the creation of NamespaceWatchingStarted …
=> Owls88781 continue retry start a namespace in non-fullcheck case after hitting 403

operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java, operator/src/main/java/oracle/kubernetes/operator/Main.java, operator/src/main/java/oracle/kubernetes/operator/ServerStatusReader.java, operator/src/main/java/oracle/kubernetes/operator/TuningParameters.java, operator/src/main/java/oracle/kubernetes/operator/TuningParametersImpl.java, operator/src/main/java/oracle/kubernetes/operator/helpers/AuthorizationSource.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/helpers/EventHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/LastKnownStatus.java, operator/src/main/java/oracle/kubernetes/operator/helpers/SecretHelper.java, operator/src/main/java/oracle/kubernetes/operator/http/HttpResponseStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/HttpRequestProcessing.java, operator/src/main/java/oracle/kubernetes/operator/steps/MonitorExporterSteps.java, operator/src/main/java/oracle/kubernetes/operator/steps/ReadHealthStep.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTestSetup.java, operator/src/test/java/oracle/kubernetes/operator/JobWatcherTest.java, operator/src/test/java/oracle/kubernetes/operator/MainTest.java, operator/src/test/java/oracle/kubernetes/operator/OperatorEventProcessingTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainStatusPatchTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesUtilsTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/SecretHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServicePresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/TuningParametersStub.java, operator/src/test/java/oracle/kubernetes/operator/steps/MonitoringExporterStepsTest.java, operator/src/test/java/oracle/kubernetes/operator/steps/ReadHealthStepTest.java, operator/src/test/java/oracle/kubernetes/utils/SystemClockTestSupport.java
This resolves an observed increase in the operator's network utilization by not reading the webLogicCredentialsSecret every time that it is necessary and, instead, caching the value for a configurable time period. Additionally, the secret is cleared (and then reread on the next iteration) following an auth or authz failure.
=> Cache secret for a configurable time period and reset on auth/authz failure

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
Fix for issue reported in https://github.com/oracle/weblogic-kubernetes-operator/issues/2010
Added integration test covering the use case.
Jenkins results:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4843/ (after adding integration test)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4836/ (with just the product fix)
=> Bug fix for ClusterIP admin service annotations and labels

operator/src/main/java/oracle/kubernetes/operator/DomainRecheck.java, operator/src/main/java/oracle/kubernetes/operator/Main.java, operator/src/main/java/oracle/kubernetes/operator/StuckPodProcessing.java, operator/src/main/java/oracle/kubernetes/operator/calls/AsyncRequestStep.java, operator/src/main/java/oracle/kubernetes/operator/http/HttpAsyncRequestStep.java, operator/src/test/java/oracle/kubernetes/operator/StuckPodTest.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java
Make sure the domain namespace and domainUID (when applicable) are in the log messages that are originated from the following code paths:
1) HttpAsyncRequest response code path;
2) Code path to create start namespaces steps when there is no fiber on the current thread;
3) StuckPodProcessing code path;
4) AsyncRequestStep where operator's namespace is accidentally used in the log messages.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4833/
=> Add NS and domainUID to log messages in more code paths

documentation/staging/content/userguide/base-images/_index.md
As per Monica, OWLS-89082 Add new WKO documentation which describe how to patch WebLogic images using WIT
=> update patching doc

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDedicatedMode.java
We no longer have the "beta" CRD documents. Additionally, the "kubectl version" check was misleading because later Kubernetes versions still contain "1.15" in the output because of some of the other fields.
I have started a jenkin run  
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4912/
=> Remove unnecessary Kubernetes version check from dedicated mode test

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWDT.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWLST.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FmwUtils.java, integration-tests/src/test/resources/bash-scripts/setup_wdt.sh, integration-tests/src/test/resources/bash-scripts/wdt-create-fmwdomain-onpv.sh, integration-tests/src/test/resources/wdt-models/model-fmwdomain-onpv-wdt.yaml
usecase:
* Create a basic FMW domain on PV using WDT.
* Verify Pod is ready and service exists for both admin server and managed servers.
* Verify EM console is accessible.
Jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4867/ (parallel)
latest Jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4872/ (parallel)
=> Create FMW Domain DomainInPv with WDT

operator/src/main/resources/scripts/modelInImage.sh
This fixes an uncommon use case where some models were changed in the online update but the resolved merged model is exactly the same as before and there is no other environment variable changes, then there is no need to rebuild the domain in the introspection job and avoid changing the domain zip hash.
=> Fix domain rolling if there is no real change in the update

operator/src/main/resources/scripts/modelInImage.sh
This fixes the missing output from WDT compareModel tool when the tool failed itself and not creating the compare_model_output file, using redirected terminal output instead.
=> Fix missing error output from WDT compareModel

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java
usecase:
Scale the configured/dynamic cluster using the sample script scaleCluster.sh script
Verify that server(s) in the configured/dynamic cluster are scaled up and in RUNNING state.
Verify that server(s) in the dynamic/configured cluster are not affected.
Restore the env
Jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4934 (parallel)
Passed Jenkins job with latest changes
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4954 (parallel)
=> Added tests to use script scaleCluster.sh/ClusterStatus.sh

operator/src/main/resources/scripts/modelInImage.sh
This fixes the issue the rcu schema password changes must be persisted in the primordial domain, otherwise in next model updates the config zip will inherit the from the primordial domain's rcu datasource configuration which still has the old passwords and it will fail in updateDomain.
=> Fix rcu schema password update logic

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/steps/MonitoringExporterSteps.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java, operator/src/test/java/oracle/kubernetes/operator/steps/MonitoringExporterStepsTest.java
This is a fairly simple change based on an update to the requirements and expected behavior. Previously, the operator injected the monitoring exporter sidecar and created Prometheus annotations only for managed server instances. Now, all servers are included, specifically including the admin server.
The necessary changes were to 1) move tests up from the managed pod suite to the base class so that the tests are included for all servers, and then 2) make the similar change to push behavior up from the managed pod step context to the general pod step context classes.
=> Include monitoring exporter sidecar and Prometheus annotations for admin server

documentation/staging/content/quickstart/create-domain.md, documentation/staging/content/samples/simple/azure-kubernetes-service/domain-on-pv.md, documentation/staging/content/samples/simple/domains/domain-home-in-image/_index.md, documentation/staging/content/samples/simple/domains/domain-home-on-pv/_index.md, documentation/staging/content/samples/simple/domains/fmw-domain-home-in-image/_index.md, documentation/staging/content/samples/simple/domains/fmw-domain/_index.md
As per OWLS-89511: Update doc for samples that use create-domain.sh
=> add note for create-domain.sh

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt_k8s_model_template.yaml
Our samples create a domain with 1 cluster by default, but one of our customers want to be able to create a domain with more than 1 cluster. If the cluster is specified in kubernetes spec section of the wdt model file, then the domain resource spec section only lists that 1 cluster even though MS's belonging to all the clusters do start. So, removing the cluster from the spec section, so that all the clusters will be listed in the domain resource spec section. 
I am commenting out the cluster instead of removing it in case anyone wants to know how to specify clusters in the k8s spec section of the wdt model file.
=> Removing the cluster from the kubernetes spec section of the wdt k8s template file

documentation/staging/content/security/rbac.md, kubernetes/charts/weblogic-operator/templates/_operator-role.tpl
There was a previous effort to limit the permissions given to the operator. We apparently cut too close to the bone. This change restores some permissions. It happens that this makes the Helm chart match what we currently document ;). With these restored permissions then operator can record the internal certificate that it generates.
=> Restore role definition to match documentation

documentation/staging/content/samples/simple/domains/fmw-domain-home-in-image/_index.md, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDiiSample.java, kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-in-image/create-domain-inputs.yaml, kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-in-image/create-domain.sh
- Add -b option to create-domain.sh in FMW domain home in image sample for passing value into -buildNetwork parameter of imagetool.sh:
usage: create-domain.sh -o dir -i file -u username -p password [-q rcuSchemaPassword] [-b buildNetworkParam] [-n encryption-key] [-e] [-v] [-h]
- Update ItFmwDiiSample to use this new option
- Update FMW domain home in image samples doc and add troubleshooting section
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5108/
=> OWLS-89562 - Add option to create-domain.sh in FMW domain home in image sample for use in imagetool --buildNetwork parameter

documentation/domains/Domain.json, documentation/domains/Domain.md, integration-tests/src/test/java/oracle/weblogic/domain/ClusterService.java, kubernetes/crd/domain-crd.yaml, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/Cluster.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ClusterService.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ClusterSpec.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ClusterSpecCommonImpl.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/SessionAffinity.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ClusterServiceHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTestBase.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainV2Test.java, operator/src/test/resources/oracle/kubernetes/weblogic/domain/model/domain-sample-2.yaml
A customer asked for us to support the `sessionAffinity` field for the per-cluster Service. While we've recommended setting session affinity at the ingress controller or load balancer, there is nothing inappropriate about a customer wanting to expose the per-cluster service and doing session affinity at this level. 
While we've had the `cluster.clusterService` field for a long time, this is the first time that it has fields that aren't present under the `serverService` field, so the implementation is introducing a ClusterService class for the first time.
=> Support clusterService.sessionAffinity

operator/scripts/scaling/scalingAction.sh, operator/src/test/sh/scaling/2clusters.json, operator/src/test/sh/scaling/cluster1.json, operator/src/test/sh/scaling/cluster_min3.json, operator/src/test/sh/scaling/cluster_noreplicas.json, operator/src/test/sh/scaling/scalingActionTest.sh
It was caused by a typo in the variable name for domain uid in the Kubernetes API call to retrieve the domain info from Kubernetes. With the typo, info for all domains in the same namespace is being retrieved instead of that of a specified domain. This PR fixes the typo in the API call, and the parsing of the retrieved json.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5130/
=> OWLS-89535 - scalingAction.sh script fails if multiple domains are running in the same namespace

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDiiSample.java
The ItFmwDiiSample and ItFmwSample uses the same temp directory for copying the samples to change files. In sequential run when both these classes are run at the same time one test deletes the temp directory and the other class depending on this fails.
The fix is to use different temp path.
=> use a different directory for temp sample path

documentation/domains/Domain.json, documentation/domains/Domain.md, documentation/domains/index.html, kubernetes/crd/domain-crd.yaml, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainValidationSteps.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java, operator/src/main/java/oracle/kubernetes/operator/steps/MonitoringExporterSteps.java, operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsDynamicServersConfig.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/Domain.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCommonConfigurator.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/MonitoringExporterSpecification.java, operator/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainValidationStepTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ManagerServerServiceHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java, operator/src/test/java/oracle/kubernetes/operator/steps/MonitoringExporterStepsTest.java, operator/src/test/java/oracle/kubernetes/operator/utils/WlsDomainConfigSupport.java
Several improvements to the monitoring exporter integration:
1. Support Istio by having the container port and service port names match and conform to the Istio naming requirements.
2. Support configuring the exporter's port and clarifying the defaulting rules
3. Removed the debug endpoint
4. When the customer configures an explicit port for the exporter, then validate that this port is not used by WebLogic channels or NAP's
=> Monitoring exporter improvements, including port configuration, Istio support, and validation

operator/src/main/resources/scripts/startNodeManager.sh
If the NM fails to start after 60 seconds then provide more help  in the log:
1.  process-id of the NM
2.  thread dump of NM using 'jcmd'.  'jstack' not available in $JAVA_HOME/bin directory of the WLS image.
3.  text output suggeting how to fix the problem if entropy is the root cause
=> OWLS-76974: Add more debugging/help when node manager fails to start

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiSample.java
Minor fix for the common mounts sample generator test `ItMiiSample#testCheckMiiSampleSource` to unset the BASE_IMAGE_NAME parameter before running the test. The external jenkins uses OCIR repo for the BASE_IMAGE_NAME environment variable but the checked-in domain resource template uses OCR. If the BASE_IMAGE_NAME env variable is not set, then it is defaulted to use OCR repo. 
Test results are at https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5231/
=> Fix for the common mounts sample domain resource generator test 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCrossDomainTransaction.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioCrossDomainTransaction.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/resources/istio/istio-cdt-http-template-service.yaml
Here is the change made to the ItCrossDomain classes
a. Added an explicit check for the (mdb) application to active before sending message to distributed Topic
b. Added a new utility method to check if the application is active  by using REST API
Test result  
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5252/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5259
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5260
=> Resolution to intermittent issue on IstioCrossDomain MDB usecase  

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java
When the tests are running in non-kind cluster use the image as is set in MII_BASIC_IMAGE_NAME + ":" + MII_BASIC_IMAGE_TAG;
Test Result 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5261/
=> Image name fix in non kind cluster

documentation/staging/content/userguide/managing-domains/model-in-image/debugging.md, documentation/staging/content/userguide/managing-domains/model-in-image/model-files.md, documentation/staging/content/userguide/managing-domains/model-in-image/overview.md, documentation/staging/content/userguide/managing-domains/model-in-image/runtime-updates.md
Homogenized heading levels in MII user docs.
=> homogenize heading sizes

operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsDynamicServersConfig.java
See [OWLS-83813](https://jira.oraclecorp.com/jira/browse/OWLS-83813).  
Change comes from https://github.com/oracle/weblogic-kubernetes-operator/pull/1933.
=> Fix NPE in WLSClusterConfig for upgrade from 2.5.0 to 2.6.0

operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java
I found this while working with the V8o team. Previously, the ResponseStep was not logging the async failure if there was a retry strategy, but it elected to not retry (e.g. any kind of permanent failure).
=> Ensure that API failures are logged when the retry strategy elects to not retry

operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/operator/steps/MonitoringExporterSteps.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ManagerServerServiceHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
After diagnosing with the V8o team, we've discovered that using the "tcp-" prefix works better because this works when the metrics exporter is addressed with either the DNS address or using the pod's ClusterIP value.
=> Use tcp prefix for metrics exporter

documentation/staging/content/faq/external-clients.md
This is an interim JTA doc update that temporarily adds back JTA notes to the external client FAQ. 
Research continues in this area ([oracle internal link](https://proddev-paas-fmw.slack.com/archives/C998UPSCT/p1622665784137000)), and the doc in this area is blocked until this research completes, so the goal of this pull is to add a recommendation to contact the WKO team if JTA is required to be in the picture.
=> minor doc update

operator/src/main/resources/scripts/model_wdt_mii_filter.py
We need to set the default listenPort/ssl listenPort if one is not provided, otherwise the istio nap injected will use 0 for the port, resulting in validation error during introspection.
=> Fix mii wdt filterpy

operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java
Owls 89909 - In some cases, when the domain is updated with an image that doesn't make any actual changes to the domain, it's considered as a no-op in `modelInImage.sh`, and the domain config parsed from the introspector log is null. However, the domain is rolled because the image name is different. In such cases, the image hash stored in the introspector config map is different from the actual image hash. The make-right cycle checks if the image hash stored in the config map matches the actual image hash when deciding whether a new introspector job needs to be created. This causes the introspector job to be created multiple times. 
This change stores the new image hash in the packet and also patches the config map with the new hash when the introspection is a no-op. Integration test run …
=> Owls 89909 - Fix for repeated introspection after a rolling restart of a MII domain because of image hash mismatch

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
Use case:
* Rerun a WebLogic domain's introspect job by explicitly initiating the introspection
* using the sample script introspectDomain.sh script.
* Test that after running introspectDomain.sh w/wo a introspectVersion value specified,
* the introspection is explicitly initiating and introspectVersion in the domain is changed.
* Use ParameterizedTest to test introspectVersion = "", "v1", "8v", "v.1"
* Verify the introspector pod is created and runs
* Verifies introspection is changed.
* Verifies accessing sample application in admin server works.
Jenkins job passed:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5321 (parallel)
=> Added test for the script introspectDomain.sh located in domain-lifecycle directory

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
Sometimes the curl POST request to change the admin port hangs forever causing the test runs to timeout. Adding a 60 seconds timeout to curl request to fix this.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5421
=> use curl timeout to abort the port change operation after 60 seconds

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCrossDomainTransaction.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwBigCMMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWDT.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWLST.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicClusterMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioCrossClusters.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioCrossDomainTransaction.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiServiceMigration.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOpUpgradeFmwDomainInPV.java
Use getNextFreePort() instead of 0 to avoid port in use when running tests in parallel. The getNextFreePort(0 keeps track of the assigned ports and never reuses the same port in the lifetime of the current run. 
This should avoid errors like
message: '0/2 nodes are available: 1 node(s) didn''t have free ports for the requested pod ports, 1 node(s) had taints that the pod didn''t tolerate.'
reason: FailedScheduling
=> use getNextFreePort() instead of 0 to avoid port in use when running tests in parallel

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalLbTunneling.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalNodePortService.java, integration-tests/src/test/resources/tunneling/nodeport.tunneling.template.yaml, integration-tests/src/test/resources/wdt-models/nodeport.tunneling.model.template.yaml, kubernetes/samples/charts/util/setupLoadBalancer.sh
ref : https://oracle.github.io/weblogic-kubernetes-operator/faq/external-clients/#kubernetes-nodeports
The use case verifies external RMI client access to WebLogic cluster using the NodePort service instead of LoadBalancer tunneling 
Renamed the  the class ItExternalRmiTunneling  to  ItExternalLbTunneling to well represent the usecase
Modified the setupLoadBalaces to use -v as as ingress release version.
Jenkin Result: 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5443/
=> Integration Test :  External RMI access to WebLogic resource using  cluster NodePort Service 

operator/pom.xml
This is a small one. Because of some changes to various libraries, you could no longer build the operator project using JDK 16 even though everything runs well with that JDK. The issue is that the Maven and Surefire plugin environments are more restrictive (with respect to Java modules) then our runtime environment.
We aren't presently using Java modules so instead this PR uses the options to remove these restrictions.
=> Allow build and test with JDK 16

documentation/staging/content/userguide/managing-domains/model-in-image/common-mounts.md, kubernetes/samples/scripts/create-weblogic-domain/model-in-image/cm-docker-file/Dockerfile, operator/integration-tests/model-in-image/mii-sample-wrapper/build-model-image.sh
Removed COMMON_MOUNT_STAGE build arg in common mounts Docker file, `build-image.sh` script, and updated common mounts documentation to reflect this change. This is required since the source dir for the docker COPY command is relative to the docker build context.
=> Removed COMMON_MOUNT_STAGE build arg in common mounts docker-file and updated documentation

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItParameterizedDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java
In the nightly run, ItParameterizedDomain#testOperatorLogSevereMsg failed intermittently when checking the domain status. Sometimes the domain status returns null. Change the test logic to check the operator log directly. 
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/5508/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/5510/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/5511/
=> fix intermittent test issue in ItParameterizedDomain#testOperatorLogSevereMsg

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
Required by upstream pipeline, we need to generate Apache image url from  BASE_IMAGES_REPO variables.
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/5543/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/5545/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/5538/
=> dynamically generate Apache Image URL from BASE_IMAGES_REPO variables

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/resources/wdt-models/model-samples-update-domain.properties, integration-tests/src/test/resources/wdt-models/model-samples-update-domain.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/README, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/update-domain.sh, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh
With the recent refactoring of samples, the update domain script on domain-on-pv no longer worked - the newly created wdt-and-wit-install script was not added to the config map. Also added a test to run the upgrade domain scenario to the existing It wls samples test.
=> Fixupdatedomainscript

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOpUpgradeFmwDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java, kubernetes/samples/charts/util/setupLoadBalancer.sh
Add new test methods to upgrade Operator from v3.2.4 and v3.2.5 to main branch.
Removed Upgrade Tests for OKE Nightly Configuration.
Jenkins Results 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5542
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5574/
=> Integration Test : Upgrade Operartor from v3.2.4 and v3.2.5

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/LabelConstants.java, operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/test/java/oracle/kubernetes/operator/DomainUpPlanTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectorConfigMapTest.java
The changes in this PR are to address the use case where the operator starts a long-running introspector job and then the operator dies and is restarted – the newly restarted operator finds the existing introspector job and waits for those results rather than deleting this job and replacing it. Previously, in this use case, the operator deleted the existing job and replaced it with a new job.
For the case when the operator restarts and finds a failed job with a SEVERE message, it checks if the current time is greater than the sum of job creation time and the `domainPresenceRecheckIntervalSeconds` interval. If so, it deletes the failed job and replaces it with a new job. 
Integration test results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5446/
=> OWLS-90180 Optimize detection of when to run introspection

operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainConditionType.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainStatusTest.java
Adding a condition of type ConfigChangesPendingRestart is currently removing any other statuses. This fixes that and does some code cleanup.
=> Don't remove other conditions when adding ConfigChangesPendingRestart

integration-tests/src/test/java/oracle/weblogic/domain/ServerPod.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCommonMount.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5567/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5568/
=> Added test to update DataSource info via Common Mount

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
From wko-pipeline meeting, "Do we need to verify WLS images which is not passed as parameter in Jenkin e.g. 14.1.1.0-11  even if the IMAGE TAG is 12.2.1.4.0".
Modify the new image name to address the issue.
Jenkins full suite:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5591/testReport/
Single test class:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5588/testReport/
OKE test passed at
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/338/testReport/
=> Modify new image used by testUpdateImageName of ItIntrospectVersion 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java
Single ItMiiAuxiliaryImage Jenkins job passed at:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5626/testReport/
Jenkins full suite with ItMiiAuxiliaryImage passed at:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5627/testReport/
=> Add test to patch the domain with updated base image in a running AI domain

documentation/staging/content/samples/simple/azure-kubernetes-service/includes/create-aks-cluster-storage.txt, kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service/azure-file-pv-template.yaml
- `nobrl`: Do not send byte range lock requests to the server.  Otherwise, when restarting the domain that is persisted to pv, error message could be like following:
```
<Jul 8, 2021 1:44:24,378 AM GMT> <Error> <Store> <BEA-280061> <The store "_WLS_admin-server" could not be deployed: weblogic.store.PersistentStoreFatalException: [Store:280020]There was an error while reading from the storage.
weblogic.store.PersistentStoreFatalException: [Store:280020]There was an error while reading from the storage.
at weblogic.store.internal.PersistentStoreImpl.open(PersistentStoreImpl.java:571)
at weblogic.store.admin.AdminHandler.activate(AdminHandler.java:159)
at weblogic.store.admin.FileAdminHandler.activate(FileAdminHandler.java:230)
at weblogic.store.admin.DefaultStoreService.start(DefaultStoreSe …
```
=> WLS on AKS: apply mountOptions "nobrl" to automation script.

operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerPod.java
OFSS domain has 1 domain with multiple clusters each having 2 replicas. There are init containers defined in each cluster. When the introspectVersion is changed with no other changes, the second pod gets rolled. This is caused because the init container env variables point to the same underlying data structures (and not deep copies). However, we set different values for some variables such as SERVER_NAME and SERVICE_NAME. This causes the server name env variable of the init container for the second server to have an incorrect value of the first server name. This change creates a copy of the init container env variables list so they don't get overwritten when value changes for other pods. Integration test results at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind- …
=> OWLS-90857 - Create copy of init container env variables for each sever pod to avoid the roll issue

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
Added additional verification for a no-op Introspection Run to make sure no pod get rolled if there is no changes to the Domain Resources.  Also covered additional  usecases for introspectDomain.sh  with  custom introspectVersion ( -i option) 
Jenkin Results 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5703 ( Only ItIntrospectVersion class ) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5695  ( complete parallel run )
=> Added additional check for Introspector run

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItParameterizedDomain.java
In the nightly parallel runs, ItParameterizedDomain failed intermittently. In the event log, some managed servers got killed. In the kublet.log, it shows:
Jul 15 09:00:15 kind-worker kubelet[312]: W0715 09:00:15.832773     312 empty_dir.go:421] Warning: Failed to clear quota on /var/lib/kubelet/pods/cc48f103-2b9b-49f0-a9a5-b7c11489d9dd/volumes/kubernetes.io~configmap/mii-weblogic-domain-introspect-cm: ClearQuota called, but quotas disabled
Jul 15 09:00:39 kind-worker kubelet[312]: E0715 09:00:39.973754     312 kuberuntime_container.go:476] preStop hook for container "weblogic-server" failed: command '/weblogic-operator/scripts/stopServer.sh' exited with 137:
Adding the resource request and limit for the server pods to prevent the pods get evicted by the k8s cluster. 
Running the Jenkins …
=> add resource request and limit for server pods

documentation/staging/content/userguide/managing-domains/domain-lifecycle/scaling.md
Update example RBAC role, used with scalingAction.sh script, with permissions for 'services/status' resource.  This change:
1. Adds permissions for 'services/status' resource
2. Removes permissions for 'customresourcedefinitions' resource, as not used by scalingAction.sh script
See https://proddev-paas-fmw.slack.com/archives/CATC0G534/p1625561489454000 for discussion
=> OWLS 90628: Update RBAC ClusterRole example in User Guide - Scaling document with rule for services/status

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java
This change will rerun the introspector if the previous introspection run had failed. The recent changes to optimize the detection of when to run the introspection might prevent introspector from re-running in such cases. 
Integration test run URL - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5738/
=> OWLS-90971 - Fix for admin server restart when Domain CR patched with incorrect auxiliary image command.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java
Increase the introspection deadline timeout from 120 to 300 seconds to fix nightly failure
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5751/
=> increase the introspection deadline timeout

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItInitContainers.java
Refer to  https://jira.oraclecorp.com/jira/browse/OWLS-91062
The following introspect version usecase was added based on issue reported by OFSS team. With initContainer configured, the WebLogic server pod should not roll with modified introspect version without any update to domain resource.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5754/  ( ItInitContainer)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5755/ ( all )
=> Add Integration Test  for Introspepct Version change with InitContainer 

jenkinsScript.sh, kindtest.sh
The jenkinsScript.sh is shared by the basic "kind-new" and nightly jobs. You can see an example of the data that will be captured here: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5776/artifact/logdir/jenkins-weblogic-kubernetes-operator-kind-new-5776/wl_k8s_test_results/journalctl.out/*view*/
=> Add call to journalctl

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/ImageBuilders.java
After a test run deleting the images pushed to OCIR needs to be deleted, the current infra impl doesn't pass the credentials for generating the OCIR repo tokens. The fix involves passing the credentials to the ocirtoke.sh script.
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/366/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5832/
=> Pass credentials to generate OCIR token

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioCoherenceTests.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioManagedCoherence.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManagedCoherence.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/resources/istio/istio-coh-http-template.yaml, integration-tests/src/test/resources/wdt-models/coherence-managed-wdt-config.yaml, integration-tests/src/test/resources/wdt-models/coherence-wdt-config.yaml
Add coherence integration test with istio
The Coherence Integration Test with ISTIO works now with explicit UnicastListenAddress configuration
Ref: https://jira.oraclecorp.com/jira/browse/OWLS-91266  ( dependent JIRA )
Also modified existing Coherance test by removing AfterAll() method 
External Jenkin Result 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5833  ( Only Coherance Test ) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5836
ItIstioManagedCoherence.testIstioMultiClusterCoherenceDomain fails as the coherence cache count mismatch when ISTIO is enabled.  Need to work with coherence  team.
=> Add coherence integration test with istio 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImageCluster.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java, integration-tests/src/test/resources/wdt-models/model-auxiliaryimage-cluster.yaml
Use cases:
Use auxiliary Image at cluster scope, create image with plain text files, use them at cluster scope config and make sure the text files are only available on all pods in the cluster.
Two failures from Jenkins job below are not related to this change
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5848/ (parallel)
=> Added Integration Test to test cluster scoped auxiliary Image

build-tools/dependency-check/dependency-check-suppression.xml, operator/pom.xml, pom.xml
Updated the Kotlin dependency (which previously came transitively from the Kubernetes Java Client) and updated the dependency check suppressions list so that the OWASP check is clean.
=> Update dependency check and Kotlin dependency

integration-tests/src/test/resources/wdt-models/coherence-managed-wdt-config.yaml, operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/model_wdt_mii_filter.py, operator/src/test/python/test_wdt_mii_filter.py
Changes to generate CoherenceMemberConfig.UnicastListenAddress for Istio. These include changes to the model WDT filter file for the MII domain and situational config generator for DII and domain-on-pv domains. 
Jenkins results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5908/
=> Owls 91266 - Changes to generate CoherenceMemberConfig.UnicastListenAddress for Istio

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ItMiiSampleHelper.java
One failure from https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5990/ is not caused by this change
=> Made changes to ItMiiSampleHelper.java to avoid failing test next to it

integration-tests/src/test/resources/wdt-models/coherence-managed-wdt-config-mii.yaml
After PR #2499 is merged, the CoherenceMemberConfig is not needed in the model file. Remove it now.
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/6021/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/6024/
=> remove CoherenceMemberConfig in model file 

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java
This test failed only on OKE. Removed duplicate method as part of another merge and this caused the failure. Fixing the file ownership command for OKE cluster.
=> fix updateDomainConfig test failure in OKE

jenkinsScript.sh
download kubectl from object storage if its not successful download from original location
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/6494/
=> Owls92223 - download kubectl from object storage

documentation/staging/content/userguide/istio/istio.md, operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/model_wdt_mii_filter.py, operator/src/test/python/test_wdt_mii_filter.py
Beginning with Istio v1.10, network changes were made by Istio where the proxy no longer redirects the traffic to the localhost interface, but instead forwards it to the network interface associated with the pod IP (e.g. eth0).  Since the operator has to support all versions of Istio, we are adding additional WebLogic network channels for binding to the localhost and pod IP network interfaces.  This will allow the WebLogic managed servers to continue to receive application traffic through either network interfaces.  During introspection, copies of the readiness probe and any custom WebLogic NAP's are created and listening addresses set to '127.0.0.1' so that the NAP's are bound to the localhost interface.  We continue to customize any existing defined NAPs and override the listening …
=> Support for network changes starting with Istio v1.10 and greater

documentation/staging/content/faq/security-validation.md, documentation/staging/content/security/openshift.md, documentation/staging/content/userguide/managing-operators/using-helm.md, documentation/staging/content/userguide/platforms/environments.md, kubernetes/charts/weblogic-operator/templates/_operator-cm.tpl, kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl, operator/src/main/java/oracle/kubernetes/operator/TuningParameters.java, operator/src/main/java/oracle/kubernetes/operator/TuningParametersImpl.java, operator/src/main/java/oracle/kubernetes/operator/helpers/BasePodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerEnvVars.java, operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/modelInImage.sh, operator/src/main/resources/scripts/startServer.sh, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java, operator/src/test/java/oracle/kubernetes/operator/helpers/TuningParametersStub.java, operator/src/test/sh/modelInImageTest.sh
Backport `OWLS-91448 - Prevent insecure file system warnings by ensuring files are at a minimum of umask 027 and handle Openshift platform` to release 3.3.2.
=> Backport OWLS-91448 to release 3.3.2 branch

operator/src/main/resources/scripts/tailLog.sh
Fix for the security warning issue reported by Pani when `logHome` is disabled.
=> Remove extra permissions for server.pid file created by the operator to avoid umask warning.

operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsClusterConfig.java, operator/src/test/java/oracle/kubernetes/operator/wlsconfig/WlsClusterConfigTest.java
Fixes an NullPointerException in WlsClusterConfig.getServerConfigs() that prevents server pods from starting up, when max dynamic cluster size of a cluster in the domain is configured with a value of 0.
Jenkins (in progress): https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/6523/
Example <cluster> configuration in config.xml that causes the NPE:
```
<cluster>
<name>DockerCluster</name>
<cluster-messaging-mode>unicast</cluster-messaging-mode>
<dynamic-servers>
<name>DockerCluster</name>
<server-template>DockerCluster-template</server-template>
<maximum-dynamic-server-count>0</maximum-dynamic-server-count>
<calculated-listen-ports>false</calculated-listen-ports>
<server-name-prefix>managed-server</server-name-prefix> …
```
=> Fix NPE in WlsClusterConfig when max dynamic cluster size is 0

operator/src/main/java/oracle/kubernetes/operator/helpers/LegalNames.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java, operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsDomainConfig.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/Domain.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainValidationMessages.java, operator/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainValidationTest.java
- Validate the container port name lengths for containers provided by the customers. 
- Truncate the automatically generated port names (based on NAP names) for WebLogic Server containers.
- Added unit tests for the customer-provided container port validation and truncation of generated port names for WLS containers.
- External Jenkins test run is in progress at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/6511/
=> Owls 91563 - Changes to validate the container port names and truncate automatically generated long names

CONTRIBUTING.md, LICENSE.txt, README.md, SECURITY.md
Our top-level files (e.g. SECURITY.md) are supposed to be kept in sync with the samples here: https://github.com/oracle/template-repo. This came up because a question from Microsoft about the weblogic-azure project, so I'll be putting in PR's for each of our projects.
=> Update root files based on templates

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCrossDomainTransaction.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioCrossDomainTransaction.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/BuildApplication.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ImageUtils.java
Recently we are having intermittent issues in ItCohereance/ItCrossDomain tests in parallel run.  Looks like when run in parallel, those step each other with common Image Cache and Target Application directory. 
We had two JIRA(s) to address the issues.
(a) OWLS-93332  - Added a environment variable  WLSIMG_CACHEDIR  
(b) OWLS-93590  - Introduced a custom target directory for application build.
External Jenkins runs (s)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7034
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7035/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7037/
=> Intermittent Integration test failure  with image tool/application build in parallel run

integration-tests/src/test/java/oracle/weblogic/domain/AdminServer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorFmwUpgrade.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java
Ref: https://jira.oraclecorp.com/jira/browse/OWLS-93556
(wko-nightly: kubectl port-forward fails in SecureMode Domain)
Add WLS/FMW upgrade tests from release 3.3.3 to main 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7037/  (parallel) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7088/  (sequential)
=> Resolution to Nightly Failure and  Upgrade Usecases 

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoadBalancerUtils.java, kubernetes/samples/charts/util/setupLoadBalancer.sh
Here the test infra will optionally pull/tag Nginx Image from OCIR if the base image repository is set to phx.ocir.io 
Otherwise the image will be automatically pulled from k8s.gcr.io/ingress-nginx/
This also makes a change to setupLoadBalancer.sh to resolve intermittent issue in ItWlsSample class
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7138 
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/489/  ( OKE run )
=> Option to use Ngnix Ingress Image for ocir   

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsLoadBalancers.java
Currently TwoDomainLoadBalancer test class has method  testDeployAppAndInstallIngressControllers()  which install all three lb ingress  and  deploy the clusterView application.
When one of the loadbalancers fails to install, all the test fail, as each test uses the cluster view application to verify inter-server communication.  If ngnix installation fails, traefik and apache tests also fails. 
So we need to  de associate each test methods to be independent of all type of  lb igrress installation. 
Jenkin Run(s) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7137/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/71334
=> Infra: Refactor TwoDomainLoadBalancer class

operator/integration-tests/model-in-image/deploy-traefik.sh, operator/integration-tests/model-in-image/test-env.sh
Make traefik name unique by adding namespace to the name. 
Jenkins results, MII sample tests are not failing -
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7152/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7151/
=> Fix for intermittent traefik installation failures in parallel run for MII sample tests

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java
1) Use getNextFreePort() for MySQL DB node port; 2) add logging msg to print out MySQL node port.
On kind new cluster single test passed at:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7169/testReport/
Full test suite result:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7170/testReport/
=> Fix the nightly DB port conflict issue

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/SecretHelper.java, operator/src/main/java/oracle/kubernetes/operator/steps/HttpRequestProcessing.java, operator/src/main/java/oracle/kubernetes/operator/work/FiberGate.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/Domain.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java, operator/src/main/resources/Operator.properties, operator/src/main/resources/scripts/modelInImage.sh, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorDelegateStub.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java
This PR is for merging changes from PR 2580 to main. It has below changes -
- Fix for the introspector retry behavior following a introspection job time out.
- Fix for NPE when the domain resource has a missing secret
- Changes to capture the WDT log files to the LOG_HOME directory to facilitate in debugging introspector timeout.
- Improve error message when introspector job times out with suggestion to increase the timeout value.
=> Owls 91212 - Merge fixes for the introspector retry behavior after the job times out and to capture WDT logs. 

operator/src/main/resources/scripts/utils.sh
The permission denied error was because of missing "&" when redirecting the standard error to standard output during `ls -1` command execution. This didn't fail on other platforms but fails on OKD due to different permissions. Maggie has verified that the fix resolves the issue on OKD and entire MIIAuxiliaryImage test suite is passing with this change on OKD.
=> OWLS-93641 - Fix for MII auxiliary image negative test case failure on OKD

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItParameterizedDomain.java
We have to create a new domain for testPortforwardDisabledInMiiDomain but olcne can't handle it. So we decided to move this test to ItMiiDomain.java
Jenkins job: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7195, two failures are not caused by this change
=> Moved testPortforwardDisabledInMiiDomain() to MiiDomain

operator/src/main/resources/scripts/modelInImage.sh, operator/src/main/resources/scripts/utils.sh
The wdt shell script or logFileRotate may return non-zero code and it will go to trap if the trap is on. This change temporarily disables the trap and then restores it in the end.
=> Temporarily disable trap in diff_model as logFileRotate or testLogFileRotate may return non-zero code.

.gitattributes, documentation/staging/content/faq/external-clients.md
We have lots of shell script in samples folder, it 's easy to run into LF ending issue if customer working with Windows WSL, see #2636
This pr contains:   
- small fix for property `TwoWaySSLEnabled` name in documentation/staging/content/faq/external-clients.md
- .[gitattributes](https://www.git-scm.com/docs/gitattributes#_end_of_line_conversion) to normalize .sh and .py files with LF.
The customer should checkout all .sh and .py files  with LF ending in different platforms.
If you have local .gitattributes, please run the following command to refresh files endings.
```
git rm --cached -r
git reset --hard
```
=> Introduce end-of-line normalization

documentation/domains/Domain.json, documentation/domains/Domain.md, documentation/domains/index.html, documentation/domains/k8s1.13.5.md, kubernetes/crd/domain-crd.yaml, operator/src/main/java/oracle/kubernetes/operator/helpers/BasePodStepContext.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/BaseConfiguration.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerPod.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerSpec.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerSpecBase.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerSpecCommonImpl.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
A customer asked us to support the `hostAliases` field as part of our `serverPod`. This field allows you to add elements to the `/etc/hosts` file of the containers. 
We had previously not supported most of the networking related fields that could be on a pod because of concern that they could easily be misused; however, the customer found that other workarounds (such as using ExternalName Services) were insufficient.
=> Support hostAliases

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/WaitForReadyStep.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainValidationSteps.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java, operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java, operator/src/main/java/oracle/kubernetes/operator/work/Fiber.java, operator/src/main/java/oracle/kubernetes/operator/work/FiberGate.java, operator/src/main/java/oracle/kubernetes/operator/work/NextAction.java, operator/src/main/java/oracle/kubernetes/operator/work/Step.java, operator/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java, operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStepTest.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberTest.java, operator/src/test/java/oracle/kubernetes/operator/work/StepChainTest.java
This adds some additional debugging capabilities for fibers:
When returning a NextAction it is now possible to add some static or computed information:
return doNext(getNext(), packet).withDebugComment(() -> "assume presence up-to-date");
indicates that the fiber has chosen a path in which the domain presence is considered to be up-to-date
return doNext(createIntrospectionSteps(), packet)
.withDebugComment(packet, this::introspectionNeededReason);
indicates that the fiber has decided that it needs to run an introspection, along with its reasoning, derived from the packet.
In each case, the comment is actually derived from a method, which is not invoked unless the feature is enabled for the current fiber (intended to avoid excess computation). That means that it may safely be left in the …
=> Enhance fiber breadcrumbs

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainValidationSteps.java, operator/src/main/java/oracle/kubernetes/operator/work/Step.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCondition.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdaterTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainValidationStepTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainStatusTest.java
This addresses multiple issues:
1. It brings the life-cycle of the Available condition in line with that of Completed. Both are now created false when the domain is recognized by the operator. (OWLS-93193, OWLS-94048)
2. It defines all servers shut down (such as start policy = NEVER) as Completed/true (OWLS-93493)
3. It corrects a bug in the detection of ReplicasTooHigh (OWLS-93692), but does not completely solve the issue; thus the JIRA remains open.
=> Correct some status update oversights

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItParameterizedDomain.java
With port forwarding turned on ItParameterizedDomain test passed at full  OKD suite run:
https://build.weblogick8s.org:8443/job/wko-okd-test/81/testReport/
in the log we can see  msg"Start port forward process"
There are some ItMiiAuxiliaryImage tests failed in the same run. I run the test locally and on Jenkins again. It passed at
https://build.weblogick8s.org:8443/job/wko-okd-test/85/
(pani)  Run the ItParameterizedDomain test in non-okd environment,  It is clean
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7410/testReport/oracle.weblogic.kubernetes/ItParameterizedDomain/
=> Turn on Port forwarding test in ItParameterizedDomain

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java
It looks like the event was logged couple of seconds before the timestamp was obtained. The call to now() should be before createNewCluster(), the test should pass without any timing issue.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7417/
=> Fix intermittent events issue

operator/src/main/resources/scripts/utils.sh
- Retain the `$AUXILIARY_IMAGE_PATH/auxiliaryImageLogs` dir after the check in `checkAuxiliaryImage` is finished.
- Change to redirect the output of `ls -1` command to `/dev/null`.
=> OWLS-94812 - Fix for auxiliary image error after the main container crashes and restarts.

integration-tests/src/test/resources/wdt-models/jms.recovery.yaml
Add the TransactionLogJDBCStore configuration to the ServerTemplate  as follow  ...
.....
ServerTemplate:
"cluster-1-template":
Cluster: 'cluster-1'
TransactionLogJDBCStore:
DataSource: "TlogDataSource"
PrefixName: "TLOG${id}"
Enabled: true
....
Run the ItDBOpeator tests which covers JMS/JTA usecase.
Jenkin Run 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7468 (individual)
=> Add a integration usecase with TLOG on DB (Oracle DB Operator) 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDiagnosticsFailedCondition.java
The issue causing the testReplicasTooHigh test in ItDiagnosticsFailedCondition to fail is fixed. 
Enabling the test.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7476/
=> Enabling testReplicasTooHigh test in ItDiagnosticsFailedCondition

operator/src/main/resources/scripts/introspectDomain.sh, operator/src/main/resources/scripts/modelInImage.sh, operator/src/main/resources/scripts/startNodeManager.sh, operator/src/main/resources/scripts/startServer.sh, operator/src/main/resources/scripts/utils.sh
(1) Expand pod start script "create folder" error logging so that a SEVERE includes information about the purpose of the directory and any related configuration for said directory. Such SEVERE messages are parsed out by the operator and reported in the domain status, so it's helpful to add contextual information.
(2) For any mkdir attempt, also try "touch" a test file in the created directory. This verifies write access.
=> Improved mkdir error logging

operator/src/main/resources/scripts/utils.sh
Backport fix for the auxiliary image error after the main container crashes and restarts (OWLS-94812) to release/3.3. 
Integration test run started at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7529/console
=> Backport fix for the auxiliary image error in OWLS-94812 to 3.3 release

documentation/domains/Domain.json, documentation/domains/Domain.md, documentation/domains/index.html, kubernetes/crd/domain-crd.yaml, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/AuxiliaryImageVolume.java, operator/src/main/resources/scripts/utils_base.sh
The change also contains a fix to mention the default value of `domain.spec.auxiliaryImageVolumes.mountPath`.
Integration test run started at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7530/console
=> Backport pr2659 to disable validation for AUXILIARY_IMAGE_PATH (Owls-94624) to 3.3 

operator/src/test/python/test_wdt_mii_filter.py
The auto build is running with Python 3.8, which rejects the old-style syntax.
=> switching to modern python except with argument syntax

operator/src/main/resources/scripts/utils.sh
Increase default sleep interval and provide option to override the value in startServer.sh to avoid high cpu usage reported in the github issue #[2655](https://github.com/oracle/weblogic-kubernetes-operator/issues/2655).
Integration test results at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7594/
=> OWLS-94991 - Increase default sleep interval and provide option to override the value in startServer.sh.

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java, operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectionStatusTest.java
Backport the fix for OWLS-94649 (PR  #[2662](https://github.com/oracle/weblogic-kubernetes-operator/pull/2662)) to update the domain status update in case of auxiliary image pull error and recreate the introspector job after image is fixed.
Integration test run started at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7580/console
Previous run at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7575/
=> Backport OWLS-94649 fix to 3.3 release 

operator/src/main/resources/scripts/utils.sh
Backport fix for GitHub issue #2655 (PR #2682) to increase the default sleep interval and provide an option to override the value to avoid high cpu usage to Operator 3.3 release.
Integration test run for 3.3 - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7610/console .
Previous run with main (had 5 intermittent failures) - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7594/
=> Backport fix for GitHub issue #2655 (OWLS-94991) to 3.3 release

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DbUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
The default DB name and storageclass name is changed in the template yaml file we se for creating the database. This PR should fix the correct strings to look for the db name and storageclass name.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7669/console
=> Fix for DB operator SIDB yaml file changes

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java
OWLS-89857 reported an issue that was observed about six months ago, and the test code that checks DomainRollStarting/Completed events have been commented out. 
This change enables the commented out code because the issue does not exist anymore. The testServerPodsRestartByChaningPodSecurityContext method passes locally and on Jenkins, and both of the DomainRollStarting and DomainRollCompleted events exist as expected.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7675/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7677/
=> owls-89857 enable the commented out integration test code for verifying DomainRollStarting/Completed event

operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ReadHealthStep.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
Backport  PR #2691 to release/3.3.
Changes to reconcile the running servers after a running domain is updated to delete a cluster and/or an independent managed server from the domain topology.. This change removes the server pods for the clustered servers and the independent managed servers which are not part of the domain topology. It also checks if the server config is null before invoking the health check to avoid the NullPointerException.
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7681/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7685/console
=> Backport fix for OWLS 95240 (PR #2691) to release/3.3

operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ReadHealthStep.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
Changes to reconcile the running servers after a running domain is updated to delete a cluster and/or an independent managed server from the domain topology.. This change removes the server pods for the clustered servers and the independent managed servers which are not part of the domain topology. It also checks if the server config is null before invoking the health check to avoid the NullPointerException.
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7681/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7685/console
=> OWLS-95240 - Reconcile running servers after the domain configuration change and fix for NPE

operator/src/main/resources/scripts/modelInImage.sh
Currently the domainBin is expanded by WDT during domain creation.  If the domain is updated with a new archive with only files under archives's wlsdeploy/domainBin changes,  the files are not updated in the domain, changes are to expand the bin before starting the domain
=> Owls 95448 Handle WDT archive domainBin expansion in MII

operator/src/main/resources/scripts/introspectDomain.py
Added a validation check in the introspector WLST script to reject the WebLogic configurations that attempt to use same server prefix name for more than one dynamic clusters.
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7720/console
=> OWLS-95390 - Add validation check to reject domain configurations that use same serverNamePrefix for multiple clusters.

operator/src/main/resources/scripts/modelInImage.sh
back port expand domain bin in mii to release 3.3.
=> backport owls_95448 to release 3.3

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItStickySession.java
The issue is the second http request sent by curl get command doesn't load the cookie file saved by the first HTTP request. the test used -D to Write the received protocol headers to the specified file. the cause is unknown. So i changed the test to use -c to writes and save all cookies from its in-memory cookie storage to the given file at the end of operations. now the test passed again
jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7726/
=> Fixed sticky session failure on nightly

documentation/staging/content/faq/cannot-pull-image.md, documentation/staging/content/samples/credentials/_index.md, documentation/staging/content/samples/database/_index.md, documentation/staging/content/userguide/managing-fmw-domains/_index.md, kubernetes/hands-on-lab/tutorials/deploy.weblogic_short.ocishell.md, kubernetes/samples/scripts/create-rcu-schema/README.md, kubernetes/samples/scripts/create-rcu-schema/drop-rcu-schema.sh, kubernetes/samples/scripts/create-weblogic-domain-credentials/README.md
This change edits the current documentation (and one corresponding shell script) to remove explicit sample passwords, out of concern that uses will use them and thus have well-known passwords in their systems - a possible vulnerability.
=> Remove explicit mention of sample passwords in docs

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorFmwUpgrade.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java
1. Added new release 3.3.7 to upgrade usecase
2. Modified the domain resource creation method to get next free port for admin node port in FMW domain  ( resolution to intermittent nightly failure ) 
The jenkin results 
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/532
=> Added Operator release 3.3.7 to the Upgrade scenerio 

documentation/staging/content/userguide/managing-domains/accessing-the-domain/port-forward.md
Online WLST cannot successfully connect to the Admin Server via k8s port-forward when the WebLogic domain is integrated with Istio versions prior to v1.10.  The generated WebLogic network channels, specifically for use with Istio versions prior to v1.10,  define a public listen address that is only resolvable within the k8s cluster and this prevents online WLST from successfully establishing a 't3' connection.  Since Istio versions prior to v1.10 are not officially supported (have reached end-of-life), we are updating the documentation for Operator release 3.3.x to describe the additional network channel configuration needed to allow k8s port-forwarding to work when Istio version prior to v1.10 is integrated with the WebLogic domain.
=> OWLS-92959: Doc: kubectl port-forward does not allow to access thru WLST in istio-domain for Istio version previous to 1.10

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRemoteConsole.java
Single test:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7750/console
Latest test result
release/3.3 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7949/
you can see ItRemoteConsole failed
My PR branch:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7954/testReport/   ItRemoteConsole passed.
=> Backport remote console PR#2649 to release/3.3

operator/integration-tests/model-in-image/run-test.sh
With this fix,  OKD FMW suite run clean
https://build.weblogick8s.org:8443/job/wko-okd-test/139/
OKD WLS suite run with sample tests clean and only 2 other failures
https://build.weblogick8s.org:8443/job/wko-okd-test/140/
Kind new Mii Sample tests(FMW and WLS) passed at:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8125/testReport/
=> Fix OKD nightly FMW and WLS sample failures

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDiagnosticsCompleteAvailableCondition.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java
Enable the disabled test case that verifies when the replicas are set higher that the max number of servers in the cluster, the domain completed condition is false, and Failed condition is true.
Note that the max number of servers is configured as 5 on WebLogic cluster (not 2 as the test code originally assumed), I changed the test code to align with this.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8130/
=> Owls 93559 enable and fix the disabled test case (no product code change needed)

integration-tests/pom.xml, kindtest.sh
(a) Resolved the syntax error while passing multiple class to IT_TEST parameter in jenkin job.
'[' ItParameterizedDomain, ItMiiUpdateDomainConfig, ItMiiAuxiliaryImage40, ItMiiNewCreateAuxImage40,ItMiiDynamicUpdate*,ItMiiMultiModel '!=' '**/It*' ']'
./kindtest.sh: line 307: [: too many arguments
( https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8272/ )
(b) add a new maven profile toolkits-srg which includes minimum set of tests needed to 
verify a per-release version of WDT and/or WIT
(https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8273/ )
=> Resolution to syntax error in kindtest.sh  and create a new profile to certify WDT/WIT release 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItUsabilityOperatorHelmChart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/SecretUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8260
Fix includes increased itrospect deadline time, cleaning secrets if domain creation fails, and correction of expected messages (3.7.x helm version has minor changes for error msgs) for operator helm chart negative test cases
=> Fix for intermittent failure due left over secrets in case of unsuccessful domain creation

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCoherenceTests.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDBOperator.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDedicatedMode.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDiagnosticsFailedCondition.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwBigCMMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicClusterMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItInitContainers.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioCoherenceTests.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDBOperator.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioManagedCoherence.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMonitoringExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLivenessProbeCustomization.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManagedCoherence.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodTemplates.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsShutdownOption.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItStickySession.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItUsabilityOperatorHelmChart.java
Remove hard-coded credentials from the integration tests.
Replaced all the occurrence to use TestConstants.ADMIN_PASSWORD_DEFAULT and TestConstants.ADMIN_USERNAME_DEFAULT
Jenkin Results 
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/8213/
The failures on the runs are due to OWLS-96042 and OWLS-96112
=> Remove hard-coded credentials from the integration tests

integration-tests/pom.xml, kindtest.sh
Jenkin results with new profile
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8274/
( all 68 Tests in toolkit-srg profile passed within in 1H42M )
=> Backport toolkit-srg profile and updated kindtest.sh to release/3.3

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Operator.java
Currently the test build fails if the branch name contains a "/"  e.g. release/3.3  with the following Error
......
Building image ‘oracle/weblogic-kubernetes-operator:release/3.3’ ...
There was an error building the image.
<01-27-2022 17:48:02> <SEVERE> <oracle.weblogic.kubernetes.actions.impl.primitive.Command execute> <The command execution failed because it returned non-zero exit value: ExecResult: exitValue = 1, stdout = Proxy settings were found and will be used during build.
Building image ‘oracle/weblogic-kubernetes-operator:release/3.3’ ...
There was an error building the image., stderr = invalid argument “oracle/weblogic-kubernetes-operator:release/3.3” for “-t, --tag” flag: invalid reference format
.......
We need to replace the tag with a valid character …
=> Modify shell script to generate a valid tag for the operator image in local run

operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/model_wdt_mii_filter.py, operator/src/test/python/test_wdt_mii_filter.py
OWLS-96198 backport istio generated replication channel with tunneling set to false
=> Backport of istio generated replication channel with tunneling set to false

operator/src/main/resources/scripts/introspectDomain.py
Fix istio sitconfig replication channel regression in integration test.
kind new test 8382 ran successfully and no longer seeing the replication channel error message 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8382/  (ItIstioDomainInPV)
All Istio Tests Results 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8387/
=> Fix integration test failure for sitconfig

operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/NamespaceTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/AdminPodHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/EventHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java, operator/src/test/java/oracle/kubernetes/utils/TestUtils.java
The problem was caused by multiple calls to TestUtils.silenceOperatorLogger. Each one removes the existing log handlers and adds a new test one. The result was to confuse the special handling of log messages in unit tests. This change removes the duplicates and modifies the call to report an error on an attempt to invoke it more than once in a test.
=> Remove duplicate calls to TestUtils.silenceOperatorLogger

integration-tests/pom.xml, kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/wdt_k8s_model_template.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt_k8s_model_template.yaml
This PR covers  
a)  the resolution to issue described in the the JIRA
b) add new Integration test class to toolkit-srg profile
Here are the jenkin run 
(a)  https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8403   ( ItFmwSample only) 
(b) https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8408/  ( toolkits-srg profile ) 
All tests passed.  ItParameterizedDomain.testScaleClustersByPatchingDomainResource fails due to OWLS-96280
=> Resolution to regression on FMW sample with WDT release 2.0 

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/wdt_k8s_model_template.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt_k8s_model_template.yaml
backport the resolution to the issue described in JIRA owls-96203 into release/3.3
Jenkin Run 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8413/ 
One failure oracle.weblogic.kubernetes.ItWlsSamples.testVoyagerIngressController  (Need to comment out this test)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8433/   ( all passed ) 
Removed the Voyager Test
=> backport owls-96203  ( FmwSample Failure ) 

operator/src/main/java/oracle/kubernetes/operator/Main.java, operator/src/main/java/oracle/kubernetes/operator/MainDelegate.java, operator/src/main/java/oracle/kubernetes/operator/helpers/CrdHelper.java, operator/src/test/java/oracle/kubernetes/operator/MainTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/CrdHelperTest.java
We have functionality in Main that trails the behavior in CRDHelper and additionally does a list of domains to validate the the custom type is available. Oddly, I could consistently reproduce getting a 404 trying to list domains immediately after creating the CRD. This meant that most customers would see a SEVERE message in the operator's log when the operator was started pointing at a fresh cluster. 
Looking at the requirement, we added the domain list as a CRD "presence check" in response to use cases where the operator did not have privilege to read the CRD. We don't actually need this extra check if the operator was able to read, create, or update the CRD.
This PR skips the presence check if the operator was able to read, create, or update the CRD.
=> Skip validating domain list ability if operator has already read, created, or updated CRD

integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
In ItInrospectversion class, test tries to create a domain with creating a Deployment job and waits for it finish to completion. Some times the listJobs api call timesout and test fails when a api exception is thrown. The fix handles the issue by not re throwing the exception and wait until the test timeout.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8786/
=> Not throw exception when listJobs fails

operator/src/main/resources/scripts/model_wdt_mii_filter.py, operator/src/test/python/test_wdt_mii_filter.py
Backport of OWLS-96280 to release 3.3 branch.
Integration test run:  [Kind 8785](https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8785/) and [Kind 8799](https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8799/)
=> backport change from OWLS-96280 to release 3.3 branch

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/LoggingExporter.java
Currently the tests fail if elasticsearch was already installed. This PR ignores the error if the elasticsearch was already installed.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8818/
=> Ignore exception if elasticsearch already installed

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
The testUpdateImageName test in ItIntrospectVersion class has 2 clusters and when the test updates the image used by the domain resource it rolls all of the pods in the domain. But the test only waits for one of the cluster pods to roll and it causes failures in subsequent test when the subsequent test checks whether the second cluster has rolled.
The fix is to wait for all pods in the domain to roll and conclude the tests.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9012
=> Fix false failures in ItIntrospectVersion tests due to k8s delay in updating the metadata

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/ActionConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Installer.java
Always use latest version of WebLogic Logging Exporter
Jenkin Run(s) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8975/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8974/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9080
=> Modify Logging Exporter test based on download URL https://github.com/oracle/weblogic-logging-exporter/releases/latest

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java
Fix intermittent ItServerStartPolicy test failure - Warning msg is not logged in operator log
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/9064/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/9061/
=> Fix intermittent ItServerStartPolicy test failure - Warning msg is not logged in operator log

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java
Workaround for the intermittent failures on nightly. Modified the failing tests to check the operator logs instead of introspector logs for error msgs. Also adding debug msgs if in case other tests fail in future.
Jenkins - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9113/
=> check operator logs instead of introspector logs for error msgs

operator/src/main/java/oracle/kubernetes/operator/DomainPresence.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java, operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java, operator/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdaterTest.java, operator/src/test/java/oracle/kubernetes/operator/EventMatcher.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/EventHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectionLoggingTest.java
As we've added a fair bit of changes, we've not kept the code as well-factored as it could be. This is an attempt to improve the code structure that needs to change to deal with the status fixes we've discussed, including better aligning failures and their corresponding events. This change also contains an adjustment to the understanding of maximum retries.
Jenkins run at https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9198/
=> First steps in new status cleanup

operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java, operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServersUpStepTest.java
domainTopology (a WlsDomainConfig) could be null if domain is created with NEVER serverStartPolicy.
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9201/
=> OWLS-96905 - Fixes NPE in ManagedServersUpStep.scaleDownIfNecessary()

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWDT.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWLST.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCustomSslStore.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomainModelInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiServiceMigration.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOpUpgradeFmwDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSystemResOverrides.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItT3Channel.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/UniqueName.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PersistentVolumeUtils.java
Unique names were used to create pv and pvc to avoid test failures due to leftover resources. This was addressed in main branch and this PR backports those changes from main.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9286/
=> create pv and pvc objects with unique names to reduce failures due to existing aftifacts

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLogging.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OKDUtils.java
2 failed test classes ItElasticLogging and ItElasticLoggingFluentd after passed on OKD:
https://build.weblogick8s.org:8443/job/wko-okd-test/237/testReport/
No regression in kind-new Jenkins run:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9306/testReport/
=> Fix OKD nightly Elasticsearch installation failure

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLogging.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/LoggingExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingExporterUtils.java
The Elastic search and kibana were installed in default namespace and it caused issues when tests are running in parallel. It was fixed to use custom namespace in main, this PR backports those changes from main to release/3.3
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9313/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9316/
=> back port elasticlogging and elasticloggingfluentd changes from main

operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java, operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java, operator/src/main/java/oracle/kubernetes/operator/helpers/CrdHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/Model.java, operator/src/test/java/oracle/kubernetes/operator/helpers/CrdHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java
Backport selected changes from PR2816 to allow 3.4 to be compatible with 4.0. The changes include -
1. When both 3.4 and 4.x operators are running in the k8s cluster, the 3.4 operator should not update the CRD that has the conversion webhook added by 4.x conversion webhook.
2. Include compatibility aux image init containers, volume and volume mounts specified in `ServerPod` section in the introspector job pod.
3. Conditionally add the WDT_INSTALL_HOME and WDT_MODEL_HOME env variables to server pod if they are at non-default values.
The change also backports existing unit tests for these changes. There are two integration test failures but they don't seem related to these changes. Results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9321/ …
=> Backport selected changes to CRD helper and introspector job/pod helper from PR2816 to 3.4 branch

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, operator/src/main/resources/scripts/utils_base.sh
OWLS-97124 - This PR fixes the bug that allowed creation of domain with file in auxiliary image 4.0 not accessible by oracle user. The local variable needs to be initialized in the beginning of function instead of initializing during the copy command. Also fixed the validation logic for the integration test. 
Complete integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9349/
Test run for failing test - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9342/
=> Owls 97124 - Fix for a negative auxiliary image 4.0 test case

operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
Owls 97601 - This change adds the WDT_MODEL_HOME env variable to prevent roll during upgrade as this env variable is added in 3.3.8 for auxiliary images. 
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9359/console
=> Owls 97601 - Changes to prevent pod roll when upgrading operator 3.3.8 to 3.4

documentation/domains/Domain.json, documentation/domains/Domain.md, documentation/domains/index.html, kubernetes/crd/domain-crd.yaml, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/helpers/EventHelper.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCondition.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainConditionType.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdaterTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainConditionTest.java
Wherever possible, events are now computed directly from added or removed conditions. Failures are now created in a single place, which will allow us to log them at the appropriate severity level once we add that functionality.
=> Simply computation of events from conditions

documentation/staging/content/userguide/managing-operators/installation.md, documentation/staging/content/userguide/managing-operators/preparation.md, documentation/staging/content/userguide/managing-operators/using-helm.md
PR to update the Installation and Upgrade doc as per [OWLS-95907](https://jira.oraclecorp.com/jira/browse/OWLS-95907) Operator User Guide Feedback and Updates for 4.0. 
**NOTE**: The upgrade section is preliminarily modified _only_: 
- I created JIRA [OWLS-97331](https://jira.oraclecorp.com/jira/browse/OWLS-97331) for development input. 
- In this PR, I removed the section "Upgrading a 2.6 operator to a 3.x operator" as explained in [OWLS-95907](https://jira.oraclecorp.com/jira/browse/OWLS-95907).
- 
@rjeberhard @tbarnes-us 
**ALSO**: Please answer whether this text in the Uninstall section is needed:
After removing the operator deployment,
you should also remove the Domain custom resource definition (CRD) if it is no longer needed:
```text
$ kubectl delete customresourcedefinition …
```
=> first pass at install and upgrade

operator/src/main/java/oracle/kubernetes/operator/ServerStatusReader.java, operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java, operator/src/test/java/oracle/kubernetes/operator/ServerStatusReaderTest.java, operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServersUpStepTest.java
This PR fixes owls-97340 in the release/3.3 branch. The issue cannot be reproduced in main branch. Since the code has been changed quite extensively, I was not able to isolate a subset of changes to backport to the release/3.3 branch. Thus a different fix to address this bug in the release/3.3 branch.
This PR also contains backport for owls-96905 - Fixes NPE in ManagedServersUpStep.scaleDownIfNecessary() from [PR 2825](url) to the release/3.3 branch.
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9375/
_Summary of issue in owls-97340:_
After server pods are shut down, operator were still trying to poll server pods that no longer exist, thus resulting in the warning messages such as:
```
{"timestamp":"2022-03-09T08:55:08.487148894Z","thread":339,"fiber …
```
=> 3.3 branch - OWLS-97340 - HTTP warnings logged continuously after changing serverStartPolicy to NEVER

documentation/staging/content/samples/azure-kubernetes-service/model-in-image.md, documentation/staging/content/samples/domains/model-in-image/initial.md, documentation/staging/content/samples/domains/model-in-image/update1.md, documentation/staging/content/samples/tanzu-kubernetes-service/_index.md, documentation/staging/content/userguide/base-images/_index.md, documentation/staging/content/userguide/managing-domains/configoverrides/_index.md, documentation/staging/content/userguide/managing-domains/domain-resource.md, documentation/staging/content/userguide/managing-domains/model-in-image/debugging.md, documentation/staging/content/userguide/managing-domains/model-in-image/runtime-updates.md, documentation/staging/content/userguide/managing-domains/model-in-image/usage.md, documentation/staging/content/userguide/managing-operators/installation.md, documentation/staging/content/userguide/managing-operators/namespace-management.md, documentation/staging/content/userguide/managing-operators/overview.md, documentation/staging/content/userguide/managing-operators/preparation.md, documentation/staging/content/userguide/managing-operators/troubleshooting.md
Update the Namespace management doc as per [OWLS-95907](https://jira.oraclecorp.com/jira/browse/OWLS-95907): Operator User Guide Feedback and Updates for 4.0. Also, minor edits elsewhere to conform to Oracle Style Guide.
=> update namespace management doc

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItInitContainers.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicyConfigCluster.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicyDynamicCluster.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Pod.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/K8sEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingUtil.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PodUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ServerStartPolicyUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9609
=> Backport ServerStartup Policy tests, fixed domain events retrieval to 3.4 release

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java
The ItPodsRestart test cases patch the domain to trigger a rolling restart. It then uses a timestamp to filter the events to verify if the expected events are generated after this timestamp. In multiple test cases, the timestamp is taken AFTER the domain is patched so that intermittently, so that the expected events are not found. It has caused the test class to fail in different test cases intermittently on Jenkins.
The fix in this branch is to record the timestamp before the domain is patched.
So far, with this change, ItPodsRestart passed in all 8 runs on Jenkins, while with main branch ItPodsRestart failed 4 out of 8 runs.
main: 9648, 9650, 9652, 9654, 9656, 9658, 9664, 9666
it_test_debugging: 9657, 9659, 9660, 9660, 9662, 9663, 9665, 9667
Example runs:
Main - …
=> OWLS-96978 fix intermittent failures in ItPodsRestart

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLogging.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java
with latest changes, the failures are not seen in following jobs
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9765
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9766
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9763
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9756
to https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9761
=> backport fix for Intermittent failure of ItElasticLogging and ItElasticLoggingFluentd

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItAuxV8DomainImplicitUpgrade.java
The ItAuxV8DomainImplicitUpgrade.java had typo in file name causing failure. 
This PR fixes the typo.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9834/artifact/logdir/jenkins-weblogic-kubernetes-operator-kind-new-9834/wl_k8s_test_results/diagnostics/ItAuxV8DomainImplicitUpgrade/ItAuxV8DomainImplicitUpgrade.out/*view*/
=> fix typo in file name

operator/src/test/java/oracle/kubernetes/operator/helpers/CallBuilderTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupportTest.java
These tests share the same underlying "pseudo" web endpoint that needs to be configured per-test with the appropriate canned responses. I've discovered that the JUnit 5 standard pattern is to decorate these tests with an @ResourceLock annotation naming the shared resource, which effectively synchronizes these test methods.
=> Fix asynchronous call builder tests

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWDT.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWLST.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLBTwoDomainsApache.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCustomSslStore.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomainModelInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiServiceMigration.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorFmwUpgrade.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSystemResOverrides.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItT3Channel.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsManagedByTwoOperators.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/ConfigMap.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonLBTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PersistentVolumeUtils.java
Fix crio-pipeline configmap already existing issue when creating in release/3.3
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9851/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9852/
=> Fix crio-pipeline configmap already existing issue when creating in release/3.3

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/K8sEvents.java
Some code simplification (mostly removal of duplicate code) and the addition of a validation that the `Rolling` condition is not present at the end of the run.
=> check rolling condition at test end

documentation/3.0/content/faq/resource-settings.md, documentation/3.1/content/faq/resource-settings.md, documentation/3.2/content/faq/resource-settings.md, documentation/3.2/content/samples/simple/azure-kubernetes-service/domain-on-pv.md, documentation/3.3/content/faq/resource-settings.md, documentation/3.3/content/samples/azure-kubernetes-service/domain-on-pv.md, documentation/staging/content/faq/resource-settings.md, documentation/staging/content/samples/azure-kubernetes-service/domain-on-pv.md, kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service/create-domain-on-aks-inputs.yaml
OWLS-96895 - Changes to documentation and sample file to use `-XX:InitialRAMPercentage` setting instead of `-XX:MinRAMPercentage`. The `-XX:InitialRAMPercentage` setting is equivalent to setting an `-Xms` value that is a percentage of max physical memory, or max container memory. 
The MinRAMPercentage is used to compute Java heap size only if the overall available memory’s size in the physical server (or in the container) is less than 250MB (approximately). For almost all of the WebLogic Server environments, `-XX:InitialRAMPercentage` and `-XX:MaxRAMPercentage` would map to `-Xms` and `-Xmx` based on the max container memory size.
=> OWLS-96895 - Changes to use -XX:InitialRAMPercentage setting instead of -XX:MinRAMPercentage

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java
Adds to selected ItKubernetesEvents tests, the same kinds of checks previously added to ItPodRestart tests - to catch leftover Rolling conditions.
=> Add checks to test

documentation/domains/Domain.json, documentation/domains/Domain.md, documentation/domains/index.html, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, kubernetes/crd/domain-crd.yaml, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCondition.java
Some of the tests already had a check that the rolling condition had been removed, but these weren't wrapped with a `testUntil` pattern.  Now, each of these tests has a check and they are consistently wrapped.
I also noticed that the schema description for the domain status conditions did not include "Rolling".
=> Have rolling tests wait for rolling condition to be removed

kubernetes/charts/weblogic-operator/templates/_operator-external-svc.tpl, kubernetes/charts/weblogic-operator/templates/_operator-internal-svc.tpl, kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorGeneratedFilesTestBase.java
V8o noticed that the ports for the operator's services were causing warnings for Kiali because they don't follow the Istio guidelines on port-naming and/or protocol designation, as described here: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection.
I choose not to rename the ports because the port names are references in some of our scripts, e.g. `scalingAction.sh`, therefore, I choose the other alternative which is to add the `appProtocol` field with the protocol information.
We didn't need to change the operator runtime because Services created by the operator are already sensitive to Istio's port naming requirements.
=> Describe service ports with appProtocol

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java
This PR fixes the tests testScaleClustersAndAdminConsoleLogin in ItMiiAuxiliaryImage.java by changing the dataHome directory to /u01/mydata and testUpdateWDTVersionUsingMultipleAuxiliaryImages in ItMultiDomainModels by creating a adminHost route for the new domain.
=> Fix for failing tests in release/3.4 OKD SRG

operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java
This resolves the test failures: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10090/
Note: the end-to-end monitoring exporter test failure will be resolved by the recent fix in that repo.
=> Resolve NPE in nightly tests and don't warn on not found

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
Refactor ItIntrospectversion class to remove test order so that individual tests can be run without running the entire test suite.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10109/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10116/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10108
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10104
=> Refactor ItIntrospectversion class to remove test Order in release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java
fix dataHome override test issue in release/3.4
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/10156/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/10152/
=> fix datahome override test issue in release/3.4

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManageNameSpace.java
This PR fixes the test failures caused by replaceNameSpaceObject failures. The test will retry the labeling process and replace the namespace object until it succeeds.
In OKD
https://build.weblogick8s.org:8443/job/wko-okd-test/297
https://build.weblogick8s.org:8443/job/wko-okd-test/299
In Kind
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10271
=> Fix ItManageNameSpace test failures.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/resources/auxiliaryimage/Dockerfile, integration-tests/src/test/resources/auxiliaryimage/negative/Dockerfile
Altran is running into pull issues when running okd srg tests with hard coded location for busybox image in Dockerfile.
Reviewers please comment on the BUSYBOX value assigned in this PR. This forces whoever running the tests to upload the busybox image in to their DOMAIN_IMAGES_REPO in location `OCIR_REGISTRY + "/weblogick8s/test-images/docker/busybox";`
Also while running the tests in OKD the dataHome in domain resource configuration must be set to /u01/... instead of /u01/oracle/... This PR fixes these 2 issues in release/3.4
OKD
https://build.weblogick8s.org:8443/job/wko-okd-test/301/
Kind
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10304/
=> Remove hardcoded OCIR in Dockerfile and change dataHome to run tests in OKD

domain-upgrader/src/main/java/oracle/kubernetes/operator/DomainUpgrader.java, operator/src/main/java/oracle/kubernetes/operator/ConversionWebhookMain.java, operator/src/main/java/oracle/kubernetes/operator/KubernetesConstants.java, operator/src/main/java/oracle/kubernetes/operator/helpers/CrdHelper.java, operator/src/test/java/oracle/kubernetes/operator/helpers/CrdHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/utils/InMemoryFileSystem.java
This PR checks if the existing CRD conversion webhook configuration is compatible with the configuration that the current webhook deployment will generate. If webhook configuration is incompatible, it updates the existing CRD webhook configuration. We decided to do this while working on documentation PR 2967 as this makes it easier to troubleshoot and debug the webhook. 
This PR also fixes a potential NPE issue in standalone DomainUpgrader tool for a particular use-case.
=> Changes to update the CRD webhook config if the existing config is incompatible with config generated by runtime

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImageCluster.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/K8sEvents.java
backport triage ItMiiAuxiliaryImage test failure in release/3.4
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/10353/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/10352/
=> backport triage ItMiiAuxiliaryImage test failure in release/3.4

operator/src/test/java/oracle/kubernetes/operator/helpers/CrdHelperTest.java
This change uses the default CRD that has the correst hash value instead of creating a new CRD.
=> Fix for the CrdHelperTest unit test failure

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImageCluster.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomainModelInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/SecretUtils.java
The tests needs to pass multiple secrets if the base image and auxilary images are coming from different repos, this PR creates secrets for OCR as well as OCIR registries if they are different.
Also this PR fixes the Dockerfile used in ItMiiAuxiliaryImageCluster.java is not substituted with BUSYBOX_IMAGE:TAG locations
BUSYBOX issue fixed
-----------------------
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10355/
All tests in Kind job
---------------------
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10367/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10345/
BASE_IMAGES_REPO as OCR
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10359/
OKD …
=> Create multiple secrets if BASE_IMAGES_REPO and REPO_REGISTRY are different

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java
After the It class ItKubernetesEvents was refactored to remove test dependency there were multiple domains created  under the same host path causing test failures. This PR fixes the path issue by using unique host paths for domains
OKD
-----
https://build.weblogick8s.org:8443/job/wko-okd-test/316/
https://build.weblogick8s.org:8443/job/wko-okd-test/318/
Kind
-----
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10401/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10402/
=> Use unique pv path for domains

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCreateAuxImageWithImageTool.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomainModelInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/SecretUtils.java
This PR forward ports the below fixes made in release/3.4 
- Add multiple secrets to domain resource if ocr is used as BASE_IMAGES_REPO and ocir is used as REPO_REGISTRY
- Use unique hostpath in ItKubernetesDomainEvents
Kind
-----
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10403/
=> add multiple secrets to domain resource if ocr and ocir are used, use unique hostpath in ItKubernetesDomainEvents

common/src/main/java/oracle/kubernetes/common/utils/SchemaConversionUtils.java, common/src/test/java/oracle/kubernetes/common/utils/SchemaConversionUtilsTest.java, operator/src/main/java/oracle/kubernetes/operator/rest/model/ConversionRequest.java, operator/src/main/java/oracle/kubernetes/operator/rest/resource/ConversionWebhookResource.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java, operator/src/test/java/oracle/kubernetes/operator/WatcherTestBase.java, operator/src/test/java/oracle/kubernetes/operator/builders/WatchBuilderTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/RollingHelperTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/AdminServerTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainUpgradeConsistencyTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainV2Test.java
The primary intent of this change is to add support to the domain upgrade for the new behavior of condition reasons: since only values from DomainFailureReason are supported, the field was changed from a string to an enum. 
I have also done a bit of code cleanup, especially in the unit tests. This addresses warnings in the build and improves the readability of the domain conversion unit test.
I note some concerns that I did not address:
1.  The class `SchemaConversionUtils` is misleadingly named. It is not, as the name suggests, a set of utilities for doing schema conversion. It is, rather, the set of rules for upgrading an old domain. It should really be renamed and moved to a more appropriate package.
2. There are still some behaviors of the conversion that are not unit-tested. I added …
=> Add domain condition reasons upgrade

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java
OWLS-97729 - Enable ItMultiDomainModelsWithLoadBalancer#testMiiMultiClustersRollingRestart test. I ran the test 10 times after enabling the test and it's always passing.
Build - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10457/
=> OWLS-97729 - Enable ItMultiDomainModelsWithLoadBalancer#testMiiMultiClustersRollingRestart test 

documentation/staging/content/userguide/managing-domains/model-in-image/runtime-updates.md
Re-organized the content in the Model in Image, Runtime Updates doc as per [OWLS-95907](https://jira.oraclecorp.com/jira/browse/OWLS-95907): Operator User Guide Feedback and Updates for 4.0:
⦁	The information provided is really hard to consume due to what feels like lots details about supported, unsupported, online, and offline updates.  What I am not getting is a good sense of what happens if my update includes something I didn’t expect (e.g., an offline-only update or an unsupported update when I thought I was going to apply an online update).  
⦁	Maybe reordering the page to discuss how to do updates and what happens if you mistakenly include an update that doesn’t fit the type of update you think you are doing first (since this is the most important content) and then have reference …
=> re-org doc content

documentation/staging/content/userguide/managing-operators/conversion-webhook.md, documentation/staging/content/userguide/managing-operators/installation.md, documentation/staging/content/userguide/managing-operators/using-helm.md, kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl, kubernetes/charts/weblogic-operator/values.yaml
This change provides `operatorOnly` helm configuration value to only install the operator and skip the webhook installation. This might be needed in multiple operators use-case where cluster-level permissions can't be granted or all operators are deployed concurrently. This also includes a minor change to ignore the `preserveWebhook`  helm config value when `webhookOnly` is set to true.
=> Provide operatorOnly helm config value to only install the operator and skip the webhook installation

documentation/staging/content/samples/domains/fmw-domain/_index.md
Clarify in FMW domain home in PV sample (doc) that both WLST or WDT can be used to create the domain as per [OWLS-99137](https://jira.oraclecorp.com/jira/browse/OWLS-99137).
=> add WDT to sample script info

documentation/staging/content/samples/azure-kubernetes-service/troubleshooting.md, documentation/staging/content/samples/domains/model-in-image/initial.md, documentation/staging/content/samples/domains/model-in-image/update1.md, documentation/staging/content/samples/domains/model-in-image/update2.md, documentation/staging/content/samples/domains/model-in-image/update3.md, documentation/staging/content/samples/domains/model-in-image/update4.md, documentation/staging/content/userguide/managing-domains/debugging.md, documentation/staging/content/userguide/managing-domains/domain-lifecycle/introspection.md, documentation/staging/content/userguide/managing-domains/model-in-image/auxiliary-images.md, documentation/staging/content/userguide/managing-domains/model-in-image/runtime-updates.md, documentation/staging/content/userguide/managing-operators/troubleshooting.md
Moved Domain Debugging doc as per advice in JIRA [OWLS-99150](https://jira.oraclecorp.com/jira/browse/OWLS-99150). However, I chose **not** to rename the document from Domain Debugging to Domain Troubleshooting to avoid confusion with the Manage Operators > Troubleshooting document.
=> move domain debugging doc

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWDT.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWLST.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSystemResOverrides.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/WebLogicRemoteConsole.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java
- Make the domain home path unique for domain on pv usecases
- Wait until remotr console access returns 200 status code
- Remove ItUsabilityOperatorHelmChart and ItManageNameSpace from okd profiles because of intermittent issues
kind
-----
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10565/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10572/
okd
-----
https://build.weblogick8s.org:8443/job/wko-okd-test/326/
https://build.weblogick8s.org:8443/job/wko-okd-test/327/
=> Make the domain home path unique for domain on pv usecases

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModels.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/annotations/DisabledOnSlimImage.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/DisabledOnSlimImageCondition.java
- When tests are running with WebLogic slim image the verifyCredentials method has to be passed with adminSvcExtHost parameter if the platform is OKD in integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java
- The integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModels.java had assumeFalse in the test method causing the test to show as Failed when running with slim image. The fix is to skip the test if the test is running with WebLogic  slim image.
- Fix the domain path in the testDataHomeOverrideDomainOnPV() since the domain resource is changed to use a uniquePath
KIND
-----
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10599/  (testDataHomeOverrideDomainOnPV)
OKD
----- …
=> Fix for slim image and domain path

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingExporterUtils.java
Owls 98836 - Changes for intermittent failure in ItElasticLoggingFluentd due to image pull and API exception. 
- Use the elasticsearch image from OCIR instead of docker hub to reduce image pull latency.
- Increased the wait time for the ELK stack pod to be ready.
- Ignore an intermittent APIException from the Kubernetes API server when verifying service existence.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10583/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10575/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10569/
=> Owls 98836 - Changes for intermittent failure in ItElasticLoggingFluentd due to image pull and API exception

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/OperatorParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/annotations/IntegrationTest.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Operator.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/ImageBuilders.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/InitializationTasks.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java
Add webhookOnly operator installation before integration tests starts in ImageBuilders beforeAll method and delete the installation in close method.
Kind
-----
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10602/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10603/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10608/
=> Add webhookOnly operator installation before integration tests starts

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRemoteConsole.java
- Disable ItRemoteConsole tests on slim image
- Check the `WebLogic version=` message in introspector log only on full image runs, not slim image
Kind
------
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10615/
In the above results the test [oracle.weblogic.kubernetes.ItMiiSampleWlsMain.testCheckMiiSampleSource] will fail since the image version is hard coded in the sample script below. It can be ignored when running tests against 14.1.1.0
https://github.com/oracle/weblogic-kubernetes-operator/blob/release/3.4/kubernetes/samples/scripts/create-weblogic-domain/model-in-image/domain-resources/JRF-AI/mii-initial-d1-JRF-AI-v1.yaml
=> Disable ItRemoteConsole tests on slim image

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalLbTunneling.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalNodePortService.java
Kind new:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10630/ passed  (full image)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10631/ (slim image)  --just to confirm no test got run
OKD:
https://build.weblogick8s.org:8443/job/wko-okd-test/336 (full image) passed 
https://build.weblogick8s.org:8443/job/wko-okd-test/336 (slim image)  skipped
=> skip ItExternalLbTunneling ItExternalNodePortService for slim image

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/IstioUtils.java, integration-tests/src/test/resources/bash-scripts/install-istio.sh
The test infra was pulling istio images from google container registry and at times the pull was failing because of registry issues. The fix is to use authenticated pulls from dockerhub, this should not hit the pull limit issue as seen with unauthenticated pulls.
The change from this PR creates a generic secret from file $HOME/.docker/config.json to use for pulling for the images.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10652/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10653/
=> Use authenticated pull for istio images

operator/src/test/java/oracle/kubernetes/operator/NamespaceTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/EventHelperTest.java
When a NAMESPACE_WATCHING_STARTED event is generated, onSuccess() method expects a DomainNamespaces object. Some unit test cases in EventHelperTest do not use the right constructor to pass in a DomainNamespaces object, which causes a NPE that is not noticeable unless one runs the test with debugging and steps through the line that causes NPE.  This does not impact the test results because the test only checks if the event was generated and the NPE happened after the event was generated.
This PR changed the unit tests in question to use the constructor that takes a DomainNamespaces object.
=> Clean up event helper unit tests

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItInitContainers.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLivenessProbeCustomization.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManageNameSpace.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomainModelInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart1.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart2.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiMultiModel.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModels.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsShutdownOption.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsManagedByTwoOperators.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonLBTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ConfigMapUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ImageUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PodUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ServerStartPolicyUtils.java
Create crio-pipeline profile using tag annotation. Also use unique namespace instead of default namespace in ItTwoDomainsManagedByTwoOperators.java. 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10670/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10664/
https://ci-cloud.us.oracle.com/jenkins/fmwk8s/job/wko-crio-job/167/
Make sure OKD tests are clean
https://build.weblogick8s.org:8443/job/wko-okd-test/340/ ( 10 failure )
=> create crio-pipeline profile and use unique namespace in ItTwoDomainsManagedByTwoOperators

operator/src/main/java/oracle/kubernetes/operator/helpers/BasePodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
OWLS-99380 - This is part 2 of the fix for pod roll issue when domain is upgraded from 3.4 to 4.0 and conversion webhook is pre-created using webhookOnly option. See PR https://github.com/oracle/weblogic-kubernetes-operator/pull/3085 for part 1.
This PR backports some of the changes from 4.0 release and creates the volume, volume mounts and some environment variables in a specific order after the auxiliary images are converted to raw init-containers, volume and mounts by the pre-created conversion webhook.
Integration test results -
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10674/
=> Owls 99380 - Part 2 of the fix for pod roll issue when domain upgraded from 3.4 to 4.0 and conversion webhook pre-created

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/steps/DeleteDomainStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ServerDownIteratorStep.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java
Due to a bug in FiberTestSupport, we did not get an error on unit tests during a change to the server down logic. That logic was changed to run both the pod down steps and the waiters for the pod down complete in the same parallel operation, which works in production, but not in unit tests, where the (null) waiters were completing and clearing the pod from the DPI before the domain down step actually ran, once we added code to send an http shutdown request to the servers.
This worked initially because of the aforementioned bug, in which we were actually skipping some threads when scheduling new ones. Fixing that exposed the issue.
In all probability the waiters should be added to the corresponding down steps, but for now, they are all run once the server down operations have been run. …
=> Clean up server down iterator

operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java, operator/src/main/java/oracle/kubernetes/operator/work/FiberGate.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java
Backport to 3.4 branch the fix for OWLS-96080 - Updated handling of introspector job pod that has failed with `DeadlineExceeded` reason to be the same as that for failed introspector job with the same reason, ie, terminate fiber with `JobWatcher.DeadlineExceeded` exception. (see[ PR 3066](https://github.com/oracle/weblogic-kubernetes-operator/pull/3066/))
This includes backport of fixes to FiberGate.java from [PR 2613](https://github.com/oracle/weblogic-kubernetes-operator/pull/2613).
jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10758/
test results from release/3.4 branch for comparison:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10759/
=> Backport fix for OWLS-96080 to 3.4 branch

operator/src/main/resources/scripts/modelInImage.sh, operator/src/main/resources/scripts/utils.sh
Owls 99654 fix - This change expands the custom folder from the WDT archive in the domain dir before calling updateDomain.sh or createDomain.sh. This PR replaces PR #3108 which has 3.3 as the base release.
=> Owls 99654 - Expand the WDT custom folder from the archive before calling update or create domain

operator/src/main/resources/scripts/modelInImage.sh, operator/src/main/resources/scripts/utils.sh
Forward port Owls 99654 fix (PR #3110) in main. This change expands the custom folder from the WDT archive in the domain dir before calling updateDomain.sh or createDomain.sh.
=> OWLS-99654 - Forward port the fix from PR 3110 into main branch.

integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
Fix NullPointerException in oracle.weblogic.kubernetes.assertions.impl.Kubernetes.isDeploymentReady in release/3.4
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10774/
=> Fix NullPointerException in oracle.weblogic.kubernetes.assertions.impl.Kubernetes.isDeploymentReady in release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
Backport - Fix NullPointerException in oracle.weblogic.kubernetes.assertions.impl.Kubernetes.isDeploymentReady to main
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10807/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10804/
=> Backport - Fix NullPointerException in oracle.weblogic.kubernetes.assertions.impl.Kubernetes.isDeploymentReady to main

common/src/main/java/oracle/kubernetes/common/logging/MessageKeys.java, common/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/logging/MessageIntegrityTest.java
This PR includes two changes:
- Change all webhook messages to use prefix "WLSWH-"; leaving all non-webhook messages unchanged.
- Remove an unused message WLSKO-0206.
- Add back WLSKO-0224 and WLSKO-0225 in Operator.properties, which were removed in PR#3043 because there was a spelling error.
- Add Russ' message integrity unit test
=> Change webhook messages to use prefix WLSWH

operator/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/logging/MessageIntegrityTest.java
Added a unit test to detect missing or misnamed message property entries - and corrected the incorrect ones.
=> Correct message property names

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDiagnosticsFailedCondition.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DbUtils.java
The method assumed there was only one pod in the namespace and it returned a wls pod name when this method was called. This fix will check the pod name prefix and see if that is the right and then return its name.
=> Fix the getPodNameOfDb() method to check the pod name prefix

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
Without overwrite option if the wdt files exist the unzip command is waiting for an answer to prompt.
=> add overwrite option when unzipping wdt files

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/resources/bash-scripts/images.properties, integration-tests/src/test/resources/nginx.template.properties, kubernetes/samples/charts/util/setupLoadBalancer.sh
This PR contains following changes
(a) Modify the kubernetes/samples/charts/util/setupLoadBalancer.sh to download NGINX ingress controller from Test (custom) Repository.
(b) Modify the ItWlsSamples.java to use the new command line option to download NGINX ingress controller image from local repository. 
Jenkin Run 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11026
=> Backport (release/3.4) resolution to intermittent WlsSample tests failures due to NGINX download issue  

documentation/3.4/content/userguide/managing-operators/using-helm.md, kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl, kubernetes/charts/weblogic-operator/values.yaml
merging to release/3.4 branch
resolves #3122 
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11010/
=> owls-99772 - Github issue # 3122 - Provide ablility to specify the UID for the container in helm chart

documentation/staging/content/managing-operators/using-helm.md, kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl, kubernetes/charts/weblogic-operator/values.yaml
Note: runAsUser also applies to webhook container in main
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11028/
resolves #3122
=> owls-99772 - github issue #3122- forward port to main

Jenkinsfile.kindnightly, kubernetes/samples/scripts/create-weblogic-domain/model-in-image/utils/create-secret.sh
Resolution to  MiiSample tests failure
Info: Creating weblogic domain secret
/tmp/workspace/wko-kind-nightly-parallel/logdir/jenkins-wko-kind-nightly-parallel-921/wl_k8s_test_results/workdir/ns-vlgvbx/model-in-image-sample-work-dir/utils/create-secret.sh: line 146: syntax error near unexpected token `('
@@ [2022-06-16T08:10:19] [run-test.sh:302]: Error: Error running command '$MIIWRAPPERDIR/create-secrets.sh', output='/tmp/workspace/wko-kind-nightly-parallel/logdir/jenkins-wko-kind-nightly-parallel-921/wl_k8s_test_results/workdir/ns-vlgvbx/model-in-image-sample-work-dir/test-out/20714.003.2022-06-16T08:10:19.create-secrets.sh.out'. Output dumped above.
Also modified Jenkinfile to remove explicit timer configuration 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-n …
=> Fix script create-secret.sh to use bash instead of sh 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicyDynamicCluster.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11031/
=> backport - add test to scale beyond max cluster size

operator/src/main/java/oracle/kubernetes/operator/webhooks/model/AdmissionRequest.java, operator/src/main/java/oracle/kubernetes/operator/webhooks/resource/AdmissionChecker.java, operator/src/main/java/oracle/kubernetes/operator/webhooks/resource/AdmissionWebhookResource.java, operator/src/main/java/oracle/kubernetes/operator/webhooks/resource/DomainAdmissionChecker.java, operator/src/main/java/oracle/kubernetes/operator/webhooks/utils/GsonBuilderUtils.java, operator/src/test/java/oracle/kubernetes/operator/webhooks/AdmissionCheckerTest.java, operator/src/test/java/oracle/kubernetes/operator/webhooks/WebhookRestTest.java
Refactor the validating webhook in order to support ClusterResource.
- Change each resource object in the request to a raw JSON map so that it can be a DomainResource or a ClusterResource. The webhook converts the JSON map to the corresponding strong-typed resource object when it performs the validation.
- Split AdmissionChecker into AdmissionChecker and DomainAdmissionChecker; prepared to add a ClusterAdmissionChecker.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11029/
=> OWLS-99505 refactoring validating webhook code

documentation/staging/content/quickstart/create-domain.md, documentation/staging/content/quickstart/prepare.md, documentation/staging/content/quickstart/summary.md
In a Quick Start guide, it goes against technical writing best practices to implement duplicate procedures without a **known** benefit. (Please correct me if there is one.) These add to its maintenance and the likelihood of becoming out-of-sync. @ankedia advised me that copy & paste is easier for users, so I removed the procedural duplicate curl commands to download the files in two instances. From discussions with @tbarnes-us, I know he doesn't agree. **NOTE**: I kept the curl command to download the sample domain YAML file because there was no other way for users to view or modify it, if needed.
=> remove duplicate procedures

kubernetes/samples/scripts/common/validate.sh
Backport changes in [PR 3195 ](https://github.com/oracle/weblogic-kubernetes-operator/pull/3195) for issue #3133 to release/3.4 branch
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11105/
same results as release/3.4 branch:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11103/
=> backport owls-99865 to release/3.4 branch

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLiftAndShiftFromOnPremDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java, integration-tests/src/test/resources/bash-scripts/syncTestImagesRepo.sh
The PR covers the following changes 
(a) Added AuxImageUpgrade test from Release 3.4.1
(b) update the script to sync images from OCIR 
(c) Resolution to ItLiftAndShiftFromOnPremDomain failure to check for only single replica 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11147/ (ItLiftAndShiftFromOnPremDomain)
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/709/  (Upgrade Test All PASSED)
=> Added AuxImageUpgrade test from Release 3.4.1

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ItMiiSampleHelper.java, operator/integration-tests/model-in-image/run-test.sh
Owls 100113 - Fix for intermittent nightly failure in ItMiiSampleFmwAux.testAIFmwInitialUseCase. The issue is caused by a race between the check for "no processes" and the "kill existing processes" during cleanup causing exit value to be non-zero. This PR uses an updated trap command.
=> Owls 100113 - Fix for intermittent nightly failure in ItMiiSampleFmwAux.testAIFmwInitialUseCase 

operator/src/main/resources/scripts/introspectDomain.py
backport owls-100118 - Dynamic cluster configured as configured cluster by introspectDomain.py to release/3.4
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11239/testReport/
- all 3 failed tests are known failures
=> owls-100118 - backport PR 3212 to release/3.4 

operator/src/main/java/oracle/kubernetes/operator/DomainFailureMessages.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainValidationSteps.java, operator/src/main/java/oracle/kubernetes/operator/helpers/WlsConfigValidator.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsClusterConfig.java, operator/src/main/java/oracle/kubernetes/operator/work/Fiber.java, operator/src/main/java/oracle/kubernetes/operator/work/NextAction.java, operator/src/main/java/oracle/kubernetes/operator/work/Step.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainValidationMessages.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java, operator/src/test/java/oracle/kubernetes/operator/FluentdUtils.java, operator/src/test/java/oracle/kubernetes/operator/JobWatcherTest.java, operator/src/test/java/oracle/kubernetes/operator/calls/SimulatedStep.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectionTestUtils.java, operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java, operator/src/test/java/oracle/kubernetes/operator/helpers/TopologyValidationStepTest.java, operator/src/test/java/oracle/kubernetes/operator/makeright/FailureReportingTest.java, operator/src/test/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStepTest.java, operator/src/test/java/oracle/kubernetes/operator/wlsconfig/WlsClusterConfigTest.java
This takes advantage of some recent refactoring to create tests that:
- confirm that the make-right is aborted when we get a severe error
- confirm that failures do not "flicker." That is, a subsequent make-right will not remove them and then put them back.
=> Ensure REPLICAS_TOO_HIGH and DOMAIN_VALIDATION failures do not flicker

kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/wdt_k8s_model_template.yaml
We need to specify a value for `replicas` in the `kubernetes` section in WDT model.
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11256/
=> owls-100237 - [wko-nightly] oracle.weblogic.kubernetes.ItFmwSample.testFmwDomainInPv(String)[1] failure

common/src/main/resources/Operator.properties, operator/src/main/java/oracle/kubernetes/operator/WebhookMain.java, operator/src/main/java/oracle/kubernetes/operator/helpers/CrdHelper.java, operator/src/main/java/oracle/kubernetes/operator/tuning/TuningParameters.java, operator/src/test/java/oracle/kubernetes/operator/WebhookMainTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/CrdHelperTest.java
Owls 100376 - This PR fixes the issue with repeated update of the cluster CRD and a race condition during the CRD presence check.  The webhook deployment updates the CRD if the newly created or existing CRD has "None" conversion strategy or if it doesn't have a compatible conversion webhook definition. For the cluster CRD, there is no need for a conversion webhook and conversion strategy should always be None. This PR avoids updating/replacing cluster CRD when it has "None" conversion strategy.
In addition, the webhook does a list of domains to validate that the CRD is available. The list domains call fails with 404 error if it's called immediately after creating the CRD and this results in a SEVERE error in webhook logs. This PR retries the list domain operation 3 times to prevent the …
=> Owls 100376 - Fix repeated Cluster CRD updates and a race condition in CRD presence check

kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/wdt_k8s_model_template.yaml
Backport PR #3228 - owls-100237 - [wko-nightly] oracle.weblogic.kubernetes.ItFmwSample.testFmwDomainInPv(String)[1] failure to release/3.4
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11272/
=> owls-100237 - backport PR 3228 to release/3.4

Jenkinsfile
Show the latest changes for toolkit projects to help with troubleshooting build failures.
=> Show the latest changes for toolkit projects during build

common/src/main/java/oracle/kubernetes/common/logging/MessageKeys.java, common/src/main/resources/Operator.properties, operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java, operator/src/main/java/oracle/kubernetes/operator/http/rest/RestBackendImpl.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/api/WeblogicApi.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ClusterResource.java, operator/src/test/java/oracle/kubernetes/operator/helpers/CallBuilderTest.java, operator/src/test/java/oracle/kubernetes/operator/http/rest/RestBackendImplTest.java
This change allows scaling of clusters through the Operator REST Api by issuing patch commands, ,on the 'scale ' subresource, directly on the corresponding  Cluster Resource.  If Cluster Resource does not exist then it will look for corresponding Cluster spec in the Domain spec (until we're ready to delete the Cluster spec from the Domain spec).
=> OWLS-95596: Scale cluster through Operator REST API  by patching Cluster Resource

Jenkinsfile.kindnightly, Jenkinsfile.oke
This  PR updates the nightly Jenkin file
(a) Kind Version to 1.13.0
(b) Kubectl version to 1.21.12
(c) WDT URL to  https://objectstorage.us-phoenix-1.oraclecloud.com/n/weblogick8s/b/wko-system-test-files/o/weblogic-deploy-main.zip
(d) WIT URL to https://objectstorage.us-phoenix-1.oraclecloud.com/n/weblogick8s/b/wko-system-test-files/o/imagetool-main.zip
=> Update jenkin files for Kind/K8s and WDT/WIT downlaod URL

common/src/main/java/oracle/kubernetes/common/logging/MessageKeys.java, common/src/main/resources/Operator.properties, operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java, operator/src/main/java/oracle/kubernetes/operator/ServerStatusReader.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/http/client/HttpAsyncRequestStep.java, operator/src/main/java/oracle/kubernetes/operator/http/client/HttpResponseStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ServerDownIteratorStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ServerDownStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStep.java, operator/src/main/java/oracle/kubernetes/operator/tuning/TuningParameters.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/KubernetesExecFactoryFake.java, operator/src/test/java/oracle/kubernetes/operator/ServerStatusReaderTest.java, operator/src/test/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStepTest.java
Owls 100719 - Fix for HTTP request failures with status code 400 for shutdown. When shutting down the servers that are not part of the domain config, the shutdown step was getting executed twice for some servers. This resulted in duplicate HTTP calls that resulted in  "ServerLifecycleException: java.lang.IllegalStateException" error.
This PR also has changes to poll the server status after issuing the shutdown request using HTTP. It allows the pod termination to wait until the server has reached the shutdown state and the server process has exited. If the shutdown request fails after two attempts, we proceed to terminate the pod. Finally, it has changes to handle the HTTP timeout failures and perform a retry when the HTTP request times out.
Integration test run (in progress) - …
=> Owls 100719 - Fix server shutdown with HTTP failures and changes to poll the server status after shutdown

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
Fix NullPointerException in integration-test/oracle.weblogic.kubernetes.assertions.impl.Kubernetes.isOperatorPodReady
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/11515/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/11514/
=> fix NullPointerException in integration-test/oracle.weblogic.kubernetes.assertions.impl.Kubernetes in release/3.4

operator/pom.xml, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java, operator/src/test/java/oracle/kubernetes/operator/makeright/IntrospectionValidationTest.java
Enabled the introspection validation test to verify the introspection logic. This involved simplifying some of it, including ensuring that the actual mismatch validation happens whenever the logic completes.
=> Clean up mismatch validation

operator/src/main/resources/scripts/modelInImage.sh, operator/src/main/resources/scripts/utils.sh, operator/src/main/resources/scripts/utils_base.sh
I noticed some incorrect messages from `traceDirs` function in the introspector logs when printing the contents of certain directories. We forward ported changes from `release/3.4` branch and `traceDirs` function is bit different in 3.4 branch. This PR has changes to fix these log messages.
=> Fixes for the incorrect introspector messages from `traceDirs` caused by changes forward ported from 3.4.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java
When imagepullPolicy is set to Never and run in a multi node cluster the test will fail if a new pod is spin a different worker where the images are not present locally. This change sets the imagepullPolicy to Always in non-kind env and verifies the pods are rolled when imagepullPolicy.
- https://build.weblogick8s.org:8443/job/wko-okd-test/427/console
=> Change image pull policy based on the environment

operator/integration-tests/model-in-image/deploy-operator.sh
Fix stand-alone version of mii test to label it's domain ns so the operator can find it...
(Account for new 4.x operator behavior to search for labels by default)
=> Fix standalone mii it test

documentation/3.3/content/userguide/aks/_index.md, documentation/3.4/content/userguide/aks/_index.md, documentation/staging/content/managing-domains/aks/_index.md
We have https://github.com/oracle/weblogic-azure/pull/177 to remove UAMI and Application Gateway Ingress Controller SP from azure marketplace offer, this pr is to remove UAMI and SP from aks user guide corresponding.
Signed-off-by: galiacheng <haixia.cheng@microsoft.com>
modified:   documentation/3.3/content/userguide/aks/_index.md
modified:   documentation/3.4/content/userguide/aks/_index.md
modified:   documentation/staging/content/managing-domains/aks/_index.md
=> remove input for UAMI and AGIC SP from aks user guide.

operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStep.java, operator/src/main/resources/scripts/stop-server.py, operator/src/main/resources/scripts/stopServer.sh
Owls 95882 part 1 - This PR has couple of fixes for the stop server script, (1) there was a right brace missing and (2) shutdown call was being made with unexpected argument properties. In addition, I have made changes to capture the script output in the exited container logs. Finally, it sets the pod deletion grace period seconds to 0 when the server has already shutdown.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11634/
=> Owls 95882 part 1 - Fixes for the stop server script, changes to capture script output and make grace period dynamic

integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Pod.java
ItMiiUpdateDomainConfig.testMiiUpdateDynamicClusterSize test failed intermittently waiting for the pods to roll as the pods took little longer.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11640/
=> increase retry time for pods to roll

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java
- Forward port the change image pull policy changes from 3.4 release
- Change wait time to longRetry for domain event tests
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11647/
=> port imagepullpolicy test  changes to main

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/ActionConstants.java
With latest WDT/WITbranch
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11722/
ItDiagnosticsFailedCondition passed at
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11734
With https://objectstorage.us-phoenix-1.oraclecloud.com/n/weblogick8s/b/wko-system-test-files/o/weblogic-deploy-main.zip and
https://objectstorage.us-phoenix-1.oraclecloud.com/n/weblogick8s/b/wko-system-test-files/o/imagetool-main.zip
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11724
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11743/
=> remove wdt.version from pom.xml

operator/src/main/resources/scripts/startNodeManager.sh
This PR is for release/3.4 branch
jenkins (in progress) https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12035/
=> Update startNodeManager.sh to use port test instead of grepping log message to determine if nodemanager is running

operator/src/main/resources/scripts/startNodeManager.sh
Use port test instead of grep log message to determine if nodemanager is running
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12054/
=> Forward port startNodeManager.sh fix to main

Jenkinsfile, Jenkinsfile.kindnightly, kindtest.sh
With this change, no need to change the maven profile to integration-tests while running individual tests.
The kind script and Jenkinfile  will automatically override the profile to integration-tests
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12115/ (single test with default)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12118/ (all test and integration-tests) (-)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12119/ (all test and default )
https://build.weblogick8s.org:8443/job/WebLogic%20Kubernetes%20Operator%20Kind/view/change-requests/job/PR-3333/6
=> Modify kindtest.sh to choose right profile to run individual tests

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/ImageBuilders.java, integration-tests/src/test/resources/bash-scripts/buildLocaleImage.sh
Here is the integration test scenario
Updated the OCIR repo with new Weblogic 12.2.1.4 image with Japanese Locale (phx.ocir.io/weblogick8s/test-images/weblogic:12.2.1.4-jp )
Integration test create Domain with this image. 
Check few  Japanese characters in WebLogic server log. 
Jenkin Result  
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12303/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12325/
=> Integration test for Japanese Locale

operator/src/main/java/oracle/kubernetes/operator/http/rest/RestBackendImpl.java, operator/src/test/java/oracle/kubernetes/operator/http/rest/RestBackendImplTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java
For merging to cluster-reference branch
Changes to RestEndPointImpl to find the correct Cluster Resource for performing the `scale` REST API operation. The Cluster resource has to be referenced in the `spec.clusters` of the Domain resource, and must be in the same namespace as the Domain resource.
=> Restendpoint fix

integration-tests/src/test/java/oracle/weblogic/domain/ClusterList.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDBOperator.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDBOperator.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCreateAuxImageWithImageTool.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCustomSslStore.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart1.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModels.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorRestart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsShutdownOption.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Cluster.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FmwUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MiiDynamicUpdateHelper.java
Changes to ItMiiDynamicUpdatePart1 and ItMiiDynamicUpdatePart2 for v9. Other classes which use scaleCluster methods are also modified for just the method call.
Jenkins results - failures because of defects
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12342/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12351/
Defects
https://jira.oraclecorp.com/jira/browse/OWLS-101872
https://jira.oraclecorp.com/jira/browse/OWLS-101921
=> Changes to ItMiiDynamicUpdatePart1 and ItMiiDynamicUpdatePart2 for v9

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalNodePortService.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSystemResOverrides.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12411/testReport/oracle.weblogic.kubernetes/
=> modify the ItConfigDistributionStrategy, ItExternalNodePortService, ItSystemResOverrides tests to use v9 cluster resources

operator/src/main/resources/scripts/livenessProbe.sh, operator/src/main/resources/scripts/startServer.sh, operator/src/main/resources/scripts/utils.sh
The idea is to copy the source file to a temporary file in the same directory as the target location and then use `mv` to update the target location atomically.
=> Copy situational configuration using a temporary file and mv to improve concurrency

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDBOperator.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDBOperator.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOCILoadBalancer.java
conversion of ItDBOperator, ItIstioDBOperator to use v9 cluster resource
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12547/
One of the test in both IT classes fails due to its dependence on domain life cycle scripts which Huiling is working on.
=> conversion of ItDBOperator, ItIstioDBOperator to use v9 cluster resource

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
`DomainPresenceInfo` created for `MakeRightDomainOperation` for Domain watch responses don't have cluster resources. This causes `isAnyClusterGenerationChanged()` to return true, and `shouldContinue()` in `DomainProcessorImpl` to return true when the domain generation hasn't changed. 
Change is not to perform generation check of `Cluster` resources from `shouldContinue()`. This is ok since `MakeRightDomainOperation` for Cluster watch responses are created with `withExplicitRecheck`.
Test `testMiiMultiClustersRollingRestart` is re-enabled and passed: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12554
jenkins: More tests passed and no regression compared to cluster-reference branch:
cluster-reference branch: …
=> owls-101782 - fix test failure in ItMultiDomainModelsWithLoadBalancer.testMiiMultiClustersRollingRestart in cluster-reference branch

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
The test performs the following:
1. modify the WebLogic domain to increase the cluster size; 
2. patch the domain resource to have a new introspectVersion;
3. patch the cluster resource to increase its replica count.
Step#3 fails because the operator has not completed the re-introspection caused by step #2, and therefore, the new cluster size is not reflected in the cluster's status. 
The fix is to wait for the cluster's status is updated before proceeding to step#3.
The failing test case passed with the changes (https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12590/ ).
=> OWLS-101923 fix integration test code in cluster-reference

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ClusterUtils.java
Modify integration test case to cover what is intended to test.
The test case does the following:
- patch cluster resource above max of replicas, which failed as expected.
- patch domain with new introspect number
- check domain event to be generated for replicas too high.
Because step #1 failed, the change to the cluster's replicas does not even get to the operator, and therefore, the operator does not know about it, not to mention generating a Failed condition (and events).
In order for an invalid replicas to be accepted and reach to the operator, the cluster resource itself should not have a replicas set, and the domain resource's replicas and introspectVersion need to be changed in a single patch operation.
There are two approaches to make sure that the cluster resource does not have …
=> OWLS-102288 fix test code

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModels.java
Modified the usecase to patch the cluster resources instead of domain resource to scale the cluster
Refer : OWLS-102278
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12774/testReport/oracle.weblogic.kubernetes/ItMultiDomainModels/    ( all test passed )
=> Test modification for ItMultiDomainModels

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDiagnosticsCompleteAvailableCondition.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomainModelInPV.java
remove the extra character in patch string in ItDiagnosticsCompleteAvailableCondition 
add cluster resource in ItMiiDomainModelInPV 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12794/
=> Fixfor failures in ItMiiDomainModelInPV and ItDiagnosticsCompleteAvailableCondition

operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java, operator/src/test/java/oracle/kubernetes/operator/PodWatcherTest.java
This addresses an issue found by Dongbo, in which running the WaitForPodDeletedStep  can report a Kubernetes error when it notes that the pod has been deleted by getting a 404.
=> Use delete-specific response step

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDiagnosticsCompleteAvailableCondition.java
The fix is to patch the domain resource with higher than max cluster size and verify the domain status conditions after removing cluster replicas from cluster resource. 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12813/
=> Fix for testCompleteAvailableConditionWithReplicaExceedMaxSizeAndIntrospectVersionChanged

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainResourceBasicTest.java
The following NPE caused multiple test failures in integration test suite, ItMiiUpdateDomainConfig:
{"timestamp":"2022-09-07T04:07:52.087895584Z","thread":28,"fiber":"fiber-616 NOT_COMPLETE","namespace":"ns-tbldqx","domainUID":"mii-add-config","level":"SEVERE","class":"oracle.kubernetes.operator.DomainProcessorImpl","method":"logThrowable","timeInMillis":1662523672087,"message":"Exception thrown","exception":"\\\njava.lang.NullPointerException: Cannot invoke \"oracle.kubernetes.weblogic.domain.model.ClusterSpec.setReplicas(java.lang.Integer)\" because \"clusterSpec\" is null\\\n\tat oracle.kubernetes.weblogic.domain.model.DomainSpec$CommonEffectiveConfigurationFactory.setReplicaCount(DomainSpec.java:1189)\\\n\tat oracle.kubernetes.weblogic.domain.model.DomainResource$PrivateDomainApiImpl.s …
=> OWLS-102281: [v9cluster] cluster fails to restart with new restartVersion in domain resource

operator/scripts/scaling/scalingAction.sh, operator/src/test/sh/scaling/apis3.json, operator/src/test/sh/scaling/scalingActionTest.sh
Updates the scalingAction.sh script in release/3.4 branch to request v8 version of Domain resource, so it would work in domains managed by Operator 3.4 in a k8s cluster with Operator 4.0 and v9 Domain CRD installed, and operator Webhook running.
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12772/
=> OWLS-101608 - update scalingAction.sh for operator 3.4 to work in k8s clusters with operator 4.0 installed

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java
Fixed the test logic to avoid the failure if order of execution has changed.
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/193
=> fixed test logic to avoid the failure if test order execution changed

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java
ItMultiDomainModelsWithLoadBalancer#testLivenessProbe failed intermittently in release/3.4. Add the verification the sample app is accessible from the admin server pod.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12880/
=> fix ItMultiDomainModelsWithLoadBalancer#testLivenessProbe in release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/resources/domain/domain-v8.yaml, integration-tests/src/test/resources/domain/mii-domain-v8.yaml
Fix tools download URL's not to look for version number. 
Use secret to pull images in the domain.yaml's for upgrade tests as its needed for OCIR in OKE env.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12999/ - upgrade tests on kind
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/114/ - upgrade tests on oke
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13010/ - full suite on kind
gate tests passed.
=> fix tools download url and image secret for upgrade tests

operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java, operator/src/test/java/oracle/kubernetes/operator/PodWatcherTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/CrdHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/work/TerminalStep.java
Owls 102429 - Fix for unexpected server restart after roll completes
Before the [change ](https://github.com/oracle/weblogic-kubernetes-operator/commit/68aea63e3da07d9ed1a622fc44e9db933aa5c513) in PR [3356](https://github.com/oracle/weblogic-kubernetes-operator/pull/3356), the `onSuccess` method of `resumeIfReady` step returned null action to terminate the child fiber. According to my understanding, `resumeIfReady` is the response step for the step that we create to check the latest resource value (backstop check for missed watch events) and that step is executed in a new child fiber that is created in `checkUpdatedResource` method. If the resource is ready, then the child fiber should terminate with a `null` action. I have also made a change to the `ResponseStep` to not log the failure …
=> Owls 102429 - Fix for unexpected server restart after roll completes

operator/src/test/java/oracle/kubernetes/operator/DeploymentLivenessTest.java, operator/src/test/java/oracle/kubernetes/operator/DeploymentReadyTest.java
Fix two operator unit tests that were leaving temp directories behind in /tmp...
=> minor oper unit test fix: cleanup tmp files once done with them

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRetryImprovements.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java
have to create a new branch to syncup with main :( so closed https://github.com/oracle/weblogic-kubernetes-operator/pull/3419
test cases:
where the operator keeps retrying until the problem is fixed outside of the domain spec, for example, a missing secret is created.
log a clear message in the domain Failed condition with the cause, actions to fix the problem, and indicates that the next retry time and when the retry will stop.
when the operator stops retrying when the maximum retry time is reached (negative case with a deliberately-set-low domain.spec.failureRetryLimitMinutes).
when he operator starts retrying in the intervals specified in domain.spec.failureRetryIntervalSeconds
Jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13029 …
=> Added integration test for WKO Retry Improvements: implement the handling of Severe Failures

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart1.java
please refer to PR https://github.com/oracle/weblogic-kubernetes-operator/pull/3434 for detailed triage result
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13096
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13097
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13098
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13099
=> backport the fix of intermittent failure in ItMiiDynamicUpdatePart1.testMiiUpdateDynamicClusterSize into r3.4

documentation/domains/Cluster.json, documentation/domains/Domain.json, documentation/domains/Domain.md, documentation/domains/index.html, kubernetes/crd/domain-crd.yaml, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainResource.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/MonitoringExporterSpecification.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainCommonConfigurator.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainV2Test.java
The monitoring exporter specification now supports resource requirements. For example:
```
monitoringExporter:
image: monexp:latest
imagePullPolicy: IfNotPresent
resources:
limits:
cpu: "0.25"
configuration:
queries:
```
=> OWLS-101705 Support resource limits on the monitoring exporter container

common/src/main/java/oracle/kubernetes/common/utils/SchemaConversionUtils.java, common/src/test/java/oracle/kubernetes/common/utils/SchemaConversionUtilsTest.java, common/src/test/resources/oracle/kubernetes/common/utils/aux-image-30-sample.yaml, common/src/test/resources/oracle/kubernetes/common/utils/converted-domain-sample.yaml
During conversion from v9 to v8, cluster resources are reintegrated into the domain content. There is a unit-test that was meant to ensure that this cluster content was properly downgraded to v8, such as having the v8 versions of enumeration values.
That unit-test was, unfortunately, broken. This change corrects the unit-test and moves the reintegration of cluster resources earlier in the flow of the webhook such that the other methods that modify constants and other content work correctly.
=> Reintegrate cluster content earlier during webhook conversion to v8

common/src/main/java/oracle/kubernetes/common/logging/MessageKeys.java, common/src/main/resources/Operator.properties, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/utils/OperatorUtils.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerStatus.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/OperatorUtilsTest.java
When the domain is not available, include a message which explains why.
There were also some bugs in edge cases for the Available and Completed statuses that were missed because of a unit test error.
=> OWLS-102534 Display explanation when Available is false

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart1.java
----------------------------------------------------------------
When the test failed on nightly below, server managed-server4 is upand running but not ready to receive JMS message yet because JNDI [ClusterJmsServer@managed-server4@jms.DistributedQueue] is not fully ready. That caused the JMS message sent to it got rejected and the test failed
-----------------------------------------------------
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/187/artifact/logdir/jenkins-wko34-kind-nightly-parallel-187/wl_k8s_test_results/diagnostics/ItMiiDynamicUpdatePart1/ItMiiDynamicUpdatePart1.out/*view*/
<09-08-2022 13:11:47> <INFO> <oracle.weblogic.kubernetes.utils.CommonTestUtils lambda$runClientInsidePod$22> <java returned EXIT value 255>
<09-08-2022 13:11:47> <INFO> …
=> Fixed intermittent failure in ItMiiDynamicUpdatePart1.testMiiUpdateDynamicClusterSize

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WebLogicImageTool.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FmwUtils.java
OWLS-102533 - Change to the FMW integration tests to override the default YAML size limit to accomodate the change in latest version of SnakeYAML to limit the incoming data.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13146/
=> OWLS-102533 - override the default YAML size limit to accomodate the SnakeYAML change

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorFmwUpgrade.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java
Jenkins Results
(a) Remove 3.2.x Upgrade Tests
(b) Move the ItMultiDomainModelsWithLoadBalancer class into sequential run
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/819
=> Remove 3.2.x Upgrade Test 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDiiSample.java
The added debugging getInstanceAndContainerHostInfo() is based on suggests of slack discussion :  https://proddev-paas-fmw.slack.com/archives/C998UPSCT/p1662994428736839
On Kind new passed 5 times in a row
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13116/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13117/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13118/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13119/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13120/
=> Debug/fix intermittent nightly ItFmwDiiSample failure

kubernetes/samples/scripts/domain-lifecycle/clusterStatus.sh, kubernetes/samples/scripts/domain-lifecycle/helper.sh, kubernetes/samples/scripts/domain-lifecycle/introspectDomain.sh, kubernetes/samples/scripts/domain-lifecycle/restartServer.sh, kubernetes/samples/scripts/domain-lifecycle/rollCluster.sh, kubernetes/samples/scripts/domain-lifecycle/rollDomain.sh, kubernetes/samples/scripts/domain-lifecycle/scaleCluster.sh, kubernetes/samples/scripts/domain-lifecycle/startCluster.sh, kubernetes/samples/scripts/domain-lifecycle/startDomain.sh, kubernetes/samples/scripts/domain-lifecycle/startServer.sh, kubernetes/samples/scripts/domain-lifecycle/stopCluster.sh, kubernetes/samples/scripts/domain-lifecycle/stopDomain.sh, kubernetes/samples/scripts/domain-lifecycle/stopServer.sh
Owls 102818 - Changes to the lifecycle scripts to explicitly use v8 API version so that they work correctly even when v9 is installed.
Integration test runs -
https://build.weblogick8s.org:8443/job/wko-kind-34-with-webhook/47/
https://build.weblogick8s.org:8443/job/wko-kind-34-with-webhook/45/
https://build.weblogick8s.org:8443/job/wko-kind-34-with-webhook/44/
https://build.weblogick8s.org:8443/job/wko-kind-34-with-webhook/43/
=> Owls 102818 - Changes to the lifecycle scripts to explicitly use v8 so they work correctly even when v9 is installed

operator/src/main/resources/scripts/auxImage.sh, operator/src/main/resources/scripts/utils.sh, operator/src/main/resources/scripts/utils_base.sh
Introduce variable `AUXILIARY_IMAGE_COMMAND_LOGS_DIR` to shell scripts for name of directory containing output from running the `AUXILIARY_IMAGE_COMMAND`. Defaults to `compatibilityModeInitContainerLogs`.
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13183/
=> OWLS-101725 - Grep Review: grep for "compatibilityModeInitContainerLogs" 

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
OWLS-102533 - Increase the WDT YAML max file size to 25MB (from 20MB) as one of the test creates a file bigger than 20MB .
Integration test run results at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13243/console
=> OWLS-102533 - increase the WDT YAML max file size to 25MB in integration tests.

operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ClusterStatus.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainStatusPatchTest.java
Although the the 'Observed Generation' attribute is reported in the Cluster status initially, it disappears when the Domain Status is updated.
=> OWLS-102367: WKO 4.0 bug: Cluster resource 'Observed Generation' status goes missing after a few minutes idle time

operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
OWLS-102819 - Fix for the issue of two introspector jobs created when applying the domain and the cluster resource at the same time. When the make-right is triggered due to added cluster, the DPI cache has stale domain resource and introspector Job is created with the wrong owner reference. This causes the first introspector job to be deleted by the "k8s garbage collector" as part of the garbage collection of stale domain.
This change updates the DPI cache with the live domain resource read at the beginning of make-right cycle. 
Integration test results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13254/
=> OWLS-102819 - Update the DPI cache with the live domain resource at the beginning of make-right.

operator/src/main/resources/scripts/auxImage.sh, operator/src/main/resources/scripts/utils.sh, operator/src/main/resources/scripts/utils_base.sh
- ItAuxV8DomainImplicitUpgrade tests failed due to misplaced double quote in checkCompatibilityModeInitContainersWithLegacyAuxImages() function. This is now fixed.
- Updated scripts to check for successful auxiliary image command execution using existence of `.suc` file instead of searching for `successfully` string in output 
ItAuxV8DomainImplicitUpgrade pases: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13293/
jenkins (still running): https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13296/
=> OWLS-102929 - [wko-nightly] Fix ItAuxV8DomainImplicitUpgrade test, OWLS-101724 Grep Review: grep for "successfully"

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WebLogicImageTool.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FmwUtils.java
Backport PR #3443 (fix for OWLS-102533) to 3.4 release.
=> Backport changes for OWLS-102533 - override the default YAML size limit to accomodate the SnakeYAML change

integration-tests/src/test/java/oracle/weblogic/domain/Configuration.java
Remove these flags from oracle.weblogic.domain.Configuration as they are not used by the Operator
@ApiModelProperty("Use online update.")
private Boolean useOnlineUpdate = false;
@ApiModelProperty("Rollback the changes if the update require domain restart.")
private Boolean rollBackIfRestartRequired = false;
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13314
=> remove these properties from oracle.weblogic.domain.Configuration

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRetryImprovements.java
use case for FATAL error:
1. create a domain and specifying the same server name twice.
2. check FatalDomainInvalidError msg in both domain status and Operator log
3. Operator with stop retry immediately
4. After duplicated server is removed and introspectVersion is changed, the Operator will start retry automatically
use case for WARNING error:
1. create a domain-in-image domain with replica count = 6 that exceeds the maximum cluster size of 5. The domain should  start but with WARNING message.
2. verify that a clear message is logged in Operator logs and the domain with the cause.
3. reduce replicas back to the maximum cluster size
4. verify that WARNING message is gone in domain status message
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13333/ …
=> Added tests for WKO Retry Improvements: Implement the handling of Fatal and Warning Failures

common/src/main/java/oracle/kubernetes/common/utils/SchemaConversionUtils.java
Fix for `ItInitContainers` integration test failures in the interop environment. This change ensures that the conversion webhook doesn't overrride the existing init containers under `serverPod` stanza when creating and adding the init containers for the auxiliary images.
Integration test run results - https://build.weblogick8s.org:8443/job/wko-kind-34-with-webhook/114/
=> Fix to retain existing init containers under serverPod when adding the init containers for the auxiliary images.

common/src/main/java/oracle/kubernetes/common/logging/MessageKeys.java, common/src/main/resources/Operator.properties, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItValidateWebhookReplicas.java, operator/src/main/java/oracle/kubernetes/operator/webhooks/resource/DomainUpdateAdmissionChecker.java, operator/src/test/java/oracle/kubernetes/operator/webhooks/AdmissionCheckerTestBase.java, operator/src/test/java/oracle/kubernetes/operator/webhooks/AdmissionWebhookTestSetUp.java, operator/src/test/java/oracle/kubernetes/operator/webhooks/ResourceUpdateAdmissionCheckerTest.java, operator/src/test/java/oracle/kubernetes/operator/webhooks/WebhookRestTest.java
The validating webhook currently only reports the first invalid cluster when the domain's replicas is changed to a value that exceeds the cluster size of more clusters in a domain. 
The changes in this PR reports all invalid clusters. 
Full integration test run had one failure, which is the same as nightly run. 
This branch: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13364/
Nightly: https://build.weblogick8s.org:8443/job/wko-kind-nightly-parallel/1069/
=> Owls102830 - report errors for all invalid clusters

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRetryImprovements.java
Since we enforced validation check for fatal errors in new domain resources. Now a fatal error is not retried any more. So changed testRetryOccursAsExpectedAndThrowFatalFailures to a negative test case, testRetryFatalFailuresNegative
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13401
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13402
=> Resolve ItRetryImprovements.testRetryOccursAsExpectedAndThrowFatalFailures

operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
Use the domain down plan when the domain has a metadata.deletionTimestamp. Once we merge this to main I'll work on a backport to release/3.4.
This should resolve the deadlock we discussed in the scrum.
=> Use down plan when domain has deletionTimestamp

operator/integration-tests/model-in-image/mii-sample-wrapper/mii-domain.yaml.template-JRF-AI, operator/integration-tests/model-in-image/mii-sample-wrapper/mii-domain.yaml.template-WLS-AI
Add changes to MII samples domain resource templates that were missed by [PR 3485](https://github.com/oracle/weblogic-kubernetes-operator/pull/3485).
ItMiiSample* tests passed: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13455/testReport/oracle.weblogic.kubernetes/
=> OWLS-103230 - [wko-nightly] Mii samples failed with MII sample domain resources in git do not align with integration test templates

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, kubernetes/samples/scripts/create-weblogic-domain/model-in-image/utils/wl-pod-wait.sh
Owls 103231 - Following changes to support the interop environments with 3.4 operator and 4.0 webhook.
- Changes to retry the failed domain custom resource patch operation in ItKubernetesDomainEvents tests to prevent failures in interop branch. 
- Change to remove setting of FOREGROUND propagation policy in delete options.
- Change to wl-pod-wait.sh script to explicitly get the v8 version of the domain.
Integration test results - https://build.weblogick8s.org:8443/job/wko-kind-34-with-webhook/195/
=> Owls 103231 - Changes to retry the failed patch operation in ItKubernetesDomainEvents tests and explicitly get the v8 version of domain

common/src/main/java/oracle/kubernetes/common/utils/SchemaConversionUtils.java, common/src/test/java/oracle/kubernetes/common/utils/SchemaConversionUtilsTest.java
OWLS-103314 - The ItMiiSample tests are failing since the `V8` domain has an unsupported reason "ServersReady" for the "Available" condition in the domain status. This change renames the reason when converting domain from `v8` to `v9` and then restores the reason when converting the domain back from `v9` to `v8`. @rjeberhard Presently the reason is renamed from "ServersReady" to "Internal", please let me know if it should be renamed to something else.
Integration test results - https://build.weblogick8s.org:8443/job/wko-kind-34-with-webhook/195/
=> OWLS-103314 - Fix for the ItMiiSample tests failures by renaming and restoring unsupported available condition reason.

operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java
Use the doEnd(packet) method to end the fiber processing instead of returning "null" next action. With "null" next action, the `doPotentialRetry` method of ResponseStep logs a ASYNC_NO_RETRY message since the RetryStrategy in the packet is null.
Integration test results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13488/
=> Use the doEnd method instead of returning null next action

documentation/3.4/content/userguide/istio/istio.md
This update the OpenShift 3.4 settings for `localHostBindingEnabled` in the Istio use case for the updated OpenShift version.
=> Openshift mesh 3.4 update

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporterWebApp.java
Backport the (https://github.com/oracle/weblogic-kubernetes-operator/pull/3532) 
test change due to WebLogicMonitoring Exporter header change 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13612
=> backport MonitoringExporter Test change into release/3.4

operator/src/main/java/oracle/kubernetes/operator/CoreDelegateImpl.java, operator/src/main/java/oracle/kubernetes/operator/WebhookMain.java, operator/src/main/java/oracle/kubernetes/operator/authentication/Helpers.java, operator/src/main/java/oracle/kubernetes/operator/helpers/BasePodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainValidationSteps.java, operator/src/main/java/oracle/kubernetes/operator/helpers/EventHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/FluentdHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/operator/http/rest/RequestDebugLoggingFilter.java, operator/src/main/java/oracle/kubernetes/operator/http/rest/model/DomainActionType.java, operator/src/main/java/oracle/kubernetes/operator/steps/InitializeWebhookIdentityStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStep.java, operator/src/main/java/oracle/kubernetes/operator/webhooks/utils/GsonBuilderUtils.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/FluentdSpecification.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/EventTestUtils.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ResourceVersionTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/RollingHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/webhooks/WebhookRestTest.java, operator/src/test/java/oracle/kubernetes/operator/wlsconfig/WlsDomainConfigTest.java, operator/src/test/java/oracle/kubernetes/operator/work/TerminalStep.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainResourceSpecTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainValidationTest.java
- Fix and enable some unit test cases that were commented out when cluster resource was integrated.
- Move a duplicate method createEnv() into a common base class.
- Fix some IntelliJ warnings.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13609/
=> Various code cleanup

documentation/domains/Cluster.json, kubernetes/crd/cluster-crd.yaml, kubernetes/samples/quick-start/domain-resource.yaml, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ClusterSpec.java
OWLS-103643 part 1
- Change to the quick start cluster resource name to include domain-uid to follow the best practice.
- Added valiation for the ClusterSpec.ClusterName to be non-null.
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13628/console
=> OWLS-103643 - Change to the quick start cluster resource name to include domain-uid and cluster-name validation

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java, operator/src/test/java/oracle/kubernetes/operator/makeright/FailureReportingTest.java
This PR skips the status initialization during domain recheck and renames the packet flag SKIP_UPDATE_DOMAIN_STATUS_IF_NEEDED to DOMAIN_RECHECK_OR_SCHEDULED_STATUS_UPDATE.
It also removes `skipUpdateDomainStatusIfNeeded` flag from the MakeRightDomainOperationImpl and instead uses `wasStartedFromEvent` method to identify if make-right is started by the explicit domain recheck. 
Integration test run results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13636/console.
=> Skip status initialization during domain recheck and rename SKIP_UPDATE_DOMAIN_STATUS_IF_NEEDED flag

operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/modelInImage.sh
This PR is to add support for the standalone app deployment in WDT which include archive jms, jdbc, wldf modules xml.   The operator will store any standalone xml file deployed in the domain in the domain config zip and restore them before starting the server.
=> Support wdt app module deployment

operator/src/main/resources/scripts/auxImage.sh
Owls 103821 - Fix for the MII AI restart failure after k8s shutdown and restarted. This PR checks for the presence of a marker file in the emptyDir to detect if aux image initialization has already completed.
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13677/console
=> Owls 103821 - Check for a marker file in the emptyDir to detect if aux image init has already completed

documentation/3.4/content/userguide/prerequisites/introduction.md
Add support for Kubernetes v1.24.0
=> update k8s support

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DbUtils.java
Jenkins
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13644
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13654
=> Fixed [wko-nightly] ItFmwDynamicClusterMiiDomain test class failing lntermittently

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModels.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java
backport [wko-nightly] NullPointerException in TestAssertions#domainStatusReasonMatches to release/3.4
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13665/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13671/
=> backport [wko-nightly] NullPointerException in TestAssertions#domainStatusReasonMatches to release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDiagnosticsCompleteAvailableCondition.java
Integration test changes to match the new behavior of Domain Available condition status set to `True` when admin server is running and cluster is intentionally shut down.
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13706/
=> owls 103828 - Integration test changes to match the new behavior of Domain Available condition

kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl, kubernetes/charts/weblogic-operator/templates/_utils.tpl
OWLS-103910 - Fix for the issue with "helm upgrade" deleting existing webhook deployment. This change re-creates the webhook deployment if the existing webhook deployment is from the same namespace.
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13720/
=> OWLS-103910 - Create the webhook deployment if the existing webhook is from the same namespace.

documentation/4.0/content/release-notes.md
Update the release notes to mention the change in default values for wdtInstallHome and wdtModelHome when auxiliary images are configured.
=> Mention the change in default values for wdtInstallHome and wdtModelHome when auxiliary images are configured.

kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl, kubernetes/charts/weblogic-operator/values.yaml
Requested by a customer who has been editing the Helm chart as a workaround. Will backport this to 4.0 and 3.4 once merged to main.
=> Add support for tolerations to operator's Helm chart

operator/src/main/java/oracle/kubernetes/operator/LabelConstants.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
OWLS-103645 - Add `observedDomainGeneration` and `observedClusterGeneration` information to the pods labels to simplify the determination of the progress of all significant resource changes as they flow through a domain.
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13784/
=> OWLS-103645 - Add domain and cluster 4.0 'observedGeneration' to pod labels.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManagedCoherence.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoadBalancerUtils.java
Fix create ingress failed with default ingressClass
Add the ingressClass when creating the ingress.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13826/
=> Fix create ingress failed with default ingressClass

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart1.java
From https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/266/artifact/logdir/jenkins-wko34-kind-nightly-parallel-266/wl_k8s_test_results/diagnostics/ItMiiDynamicUpdatePart1/ItMiiDynamicUpdatePart1.out/*view*/,
the error is:
--------------------
<11-08-2022 13:32:48> <INFO> <oracle.weblogic.kubernetes.actions.impl.primitive.Kubernetes getPodCreationTimestamp> <Pod doesn't exist or pod metadata is null>
<11-08-2022 13:32:48> <SEVERE> <oracle.weblogic.kubernetes.extensions.IntegrationTestWatcher handleTestExecutionException> <org.opentest4j.AssertionFailedError: Got null PodCreationTimestamp ==> expected: not <null>
at oracle.weblogic.kubernetes.ItMiiDynamicUpdatePart1.testMiiUpdateDynamicClusterSize(ItMiiDynamicUpdatePart1.java:397)
Analysis:
--------------
In the line 386, …
=> Fixed ItMiiDynamicUpdatePart1.testMiiUpdateDynamicClusterSize failed intermittently on nightly

okdtest.sh
OKD test run:
https://build.weblogick8s.org:8443/job/wko34-okd/66/consoleFull
++ kubectl get crd
++ grep weblogic
+ kubectl delete crd clusters.weblogic.oracle 2022-11-21T17:38:43Z domains.weblogic.oracle 2022-11-21T17:38:42Z
customresourcedefinition.apiextensions.k8s.io "clusters.weblogic.oracle" deleted
customresourcedefinition.apiextensions.k8s.io "domains.weblogic.oracle" deleted
=> improve OKD cleanup script

kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl
Add specific containers.securityContext entries in the helm chart when installing in the OpenShift environment;  without these entries, OpenShift responds with warnings,  although everything seems to work fine.
=> Add specific securityContext for containers in OpenShift environment.

Jenkinsfile, Jenkinsfile.kindnightly, Jenkinsfile.oke
Updating helm version to latest 3.10.2 to fix this failure.
<11-28-2022 13:09:32> <INFO> <oracle.weblogic.kubernetes.actions.impl.primitive.Helm exec> <Command failed with errors Error: INSTALLATION FAILED: execution error at (traefik/templates/deployment.yaml:3:8): ERROR: Helm >= 3.9.0 is required
>
=> update helm version to 3.10.2

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java
MII domain resource is patched with a change that would cause introspection to fail, and the test expects no server pods should be rolled. If there is an existing introspector job running for the pre-patched version of the domain resource, the introspector job could complete successfully and proceed to start rolling server pods.
Update test to also patch introspectVersion so operator would abort the current introspection if there is one.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14264/
=> OWLS-102744 [wko-nightly] testErrorPathDomainWithFailCustomMountCommand failure 3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java, kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain.sh
Change in the image in Jenkins causing the domain in image tests to fail. We have to use the DEFAULT TAG when trying to replace the image in domain-inputs file.
https://build.weblogick8s.org:8443/job/wko40-kind-nightly-parallel/34/
=> Nightly 4.0 ItWlsSamples failures fix

validateCLI.docker.dat
After pulling the latest main branch, the operator build started to fail on my Mac laptop with the following error.
ERROR: The 'validateCLI.sh' in directory '/Users/dongboxiao/weblogic-kubernetes-operator' detected invalid direct uses of the Kubernetes or image builder CLIs. Kubernetes CLI calls should use the KUBERNETES_CLI env var or java constant instead of directly using 'kubectl'. And image builder CLI calls should use the WLSIMG_BUILDER env var or java constant instead of directly using 'docker'. To add usage exceptions, add a sed regex expression in ./validateCLI.kubectl.dat or ./validateCLI.docker.dat for 'kubectl' and 'docker' exceptions respectively. Please fix the following:
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java:1228:    final …
=> Add more files in validateCLI.sh exception .dat file

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
Port 3713 to main, the fix is prevent failures when using other than PS4 images to run the tests.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14370/
=> port 3713 to main

pom.xml
pass bash as executable and rest of the parameters as arguments, otherwise this fails when running targets in windows OS
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14400/
=> pass bash as executable and rest of the parameters as arguments

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRetryImprovements.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java
Added new test to cover New feature: https://jira.oraclecorp.com/jira/browse/OWLS-93072 - WKO 4.0 Retry: Add "introspect failure retry count exceeded error" msg to domain status failure msg 
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14297
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14299
=> Added test for retry improvements to cover introspect failure retry count exceeded error msg to domain status failure msg

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiClusterResource.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PodUtils.java
Since introspector pod is created and deleted within seconds, the existing conditionfactory objects are not useful to catch the introspector pod lifecycle. Introducing this custom condition factory to start the checking right away.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14526/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14527/
=> Introduce custom condition factory

operator/src/main/java/oracle/kubernetes/operator/WaitForReadyStep.java, operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/http/rest/RestBackendImpl.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainResource.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java
Several code points were using the domainUid rather than the domain resource name (metadata.name) when attempting to read or update the domain resource. 
Cleaned-up the parameters and JavaDoc in CallBuilder to make it clear that the name is required rather than the domainUID.
Finally, observed another bug in DomainResource where the domainHome default was calculated based on the value of `spec.domainUID` rather than on the value of the domainUid (which might default to `metadata.name`)
=> Consistently manage domain resources using name rather than domainUid

kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl
Adding an annotation to the webhook pod to make sure the Istio sidecar will not be injected into the pod,  otherwise, in the OpenShift mesh environment, we will get a certificate validation error when deploying a domain.
=> make sure webhook does not inject istio sidecar

operator/src/main/java/oracle/kubernetes/operator/Watcher.java, operator/src/main/java/oracle/kubernetes/operator/helpers/KubernetesUtils.java, operator/src/test/java/oracle/kubernetes/operator/WatcherTestBase.java, operator/src/test/java/oracle/kubernetes/operator/builders/WatchEvent.java, operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesUtilsTest.java
Merge the changes from PR 3700 to stop parsing the resource version in the existing PR to pause the watches during periodic list and resume with new resourceVersion.
Integration test results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14648/
=> Changes from PR 3700 to stop parsing the resource version.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRetryImprovementMisc.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java
- When Cluster resource replicas decreases to 0, Cluster resource Completed condition should remain False until all server pods have completed shutdown.
- Ensure cluster status is updated after domain status updated successfully
- Re-enables domain status conditions check in ItRetryImprovementMisc.testClusterReplicasToZero
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14650/
=> owls-104622  domain status cluster condition Complete type is always True when the cluster replicas changed to 0

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/annotations/DisabledOn12213Image.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/DisabledOn12213ImageCondition.java
Jenkins - 
https://build.weblogick8s.org:8443/job/wko-kind-weekly-multiconfig/ - tests were failing on 12.2.1.3 images before, now they pass as istio mii tests are disabled for 12.2.1.3 images because of known issue.
latest jenkins - 
https://build.weblogick8s.org:8443/job/wko-kind-weekly-multiconfig/80/
=> disable istio mii tests for 12.2.1.3 images

deployment/scripts/operator.sh, deployment/scripts/stop.sh, deployment/scripts/webhook.sh, kubernetes/charts/weblogic-operator/templates/_operator-clusterrole-general.tpl, kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl, kubernetes/charts/weblogic-operator/templates/_operator-role.tpl, kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorGeneratedFilesTestBase.java, operator/src/main/java/oracle/kubernetes/operator/BaseMain.java, operator/src/main/java/oracle/kubernetes/operator/OperatorMain.java, operator/src/main/java/oracle/kubernetes/operator/WebhookMain.java, operator/src/main/java/oracle/kubernetes/operator/helpers/WebhookHelper.java, operator/src/test/java/oracle/kubernetes/operator/OperatorMainTest.java, operator/src/test/java/oracle/kubernetes/operator/WebhookMainTest.java
The initial idea was that the webhook should delete the ValidatingWebhookConfiguration during its shutdown so that this resource would not be stranded. 
While working on that, I discovered that neither the webhook or operator were really cleanly shutting down -- that is, the runtime signal handler was never being called. Therefore, I put in a preStop handler and added handling to make sure that either process would get to complete its shutdown behavior before exiting.
Then, I added the handling to the webhook to delete the VWC.
=> Proper shut down for operator and webhook; Have webhook delete VWC 

operator/src/main/java/oracle/kubernetes/operator/DomainProcessor.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightClusterOperation.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ClusterPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightClusterOperationImpl.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java
Owls 105072 - If the watch event notification is missed when a cluster resource is deleted, trigger the make-right to generate cluster DELETE event during explicit LIST. This PR caches the ClusterResourceInfo during the initial make-right and then checks for the delta during the explicit listing. If the cluster is present in the ClusterResourceInfo cache but is missing from the returned list, then it triggers  make-right to generate the event.
Integration test runs - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14875/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14874/
=> Owls 105072 - Changes to generate cluster deleted event when deleted cluster found during explicit LIST

operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java
OWLS-105263 - Generate a DOMAIN delete event when domain is deleted but is already present in the DomainPrecenseInfo cache.
=> OWLS-105263 - Fix for missing domain deletion event in integration test run.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModels.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PodUtils.java
Fix intermittent test issue when scaling down the cluster in ItMultiDomainModels.testScaleClustersAndAdminConsoleLogin.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15016/
=> Fix intermittent test issue when scaling down the cluster in ItMultiDomainModels.testScaleClustersAndAdminConsoleLogin

operator/src/main/java/oracle/kubernetes/operator/helpers/BasePodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
This adds another potential adjustment to recipe pods to match historical pods. In this case, pods created with 3.4.x have a default logHomeLayout of Flat while the default for 4.0.x is ByServers. Because of this, the recipe would not default to having a "LOG_HOME_LAYOUT" environment variable where it did not previously have one.
=> Resolve upgrade issue based on change to logHomeLayout

documentation/4.0/content/release-notes.md
Add description in known issues section of the release note about the intermittent deadlock when deploying `CoherenceModule` during server startup.
=> OWLS-104942: managed server fail to join the cluster after patching the domain with new restartVersion

operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java, operator/src/main/java/oracle/kubernetes/operator/PodAwaiterStepFactory.java, operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java, operator/src/main/java/oracle/kubernetes/operator/WaitForReadyStep.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/steps/ServerDownStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStep.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorDelegateStub.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/PodWatcherTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java, operator/src/test/java/oracle/kubernetes/operator/makeright/DomainUpPlanTest.java, operator/src/test/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStepTest.java
Owls 105422 - Changes to periodically read the domain resource to get latest server state while waiting for the server state to transition to SHUTDOWN. It also has changes to read the latest domain resource when the REST call to shut down the server fails.
Integration test runs - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15171/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15169/
=> Owls 105422 - periodically read the domain resource while waiting for the server to shut down.

.github/workflows/publish-github-pages.yml
actions/checkout v2 is deprecated.  Upgrading to v3
=> upgrade deprecated github action checkout@v2 to use v3

operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java, operator/src/main/java/oracle/kubernetes/operator/helpers/SecretHelper.java, operator/src/main/java/oracle/kubernetes/operator/http/client/HttpResponseStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/HttpRequestProcessing.java, operator/src/main/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStep.java, operator/src/test/java/oracle/kubernetes/operator/http/client/HttpAsyncTestSupport.java, operator/src/test/java/oracle/kubernetes/operator/http/client/HttpAsyncTestSupportTest.java, operator/src/test/java/oracle/kubernetes/operator/http/client/HttpResponseStub.java, operator/src/test/java/oracle/kubernetes/operator/steps/HttpRequestProcessingTest.java
When the operator runs, it obtains the current state of each server by invoking that server's REST API. The REST API creates a new session on each invocation unless it receives a Session cookie with a valid current session. This change handles the Set-Cookie header in the REST response, and sends a corresponding Session header back with each subsequent request, thus preventing the creation of additional sessions.
=> Add workaround to prevent WLS session growth on status requests

operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java, operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java, operator/src/main/java/oracle/kubernetes/operator/WaitForReadyStep.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/test/java/oracle/kubernetes/operator/JobWatcherTest.java
Fix intermittent failure in ItMiiAuxiliaryImage.testDomainStatusErrorPullingAI.
When introspector job failed, the Callback in WaitForJobReadyStep terminates the suspended fiber, and domain status is updated by a FailureStep created by DomainPlanCompletionCallback during fiber terminate processing. Occassionally, the WaitForJobReadyStep callback is invoked from the child fiber of the fiber being terminated, and FiberGate does not allow a fiber to be started for running the FailureStep.  This change removed the fiber terminate call and resume the suspended fiber so it can terminate itself with a doTerminate call.
jenkins: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15216/
No failure in 50 runs of ItMiiAuxiliaryImage
=> OWLS-105105 - [wko-nightly] domain status Failed condition does not exist after create a domain with non-exist Auxiliary Image

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java
The fix includes:
- Adjust the skip status update logic to check if all, instead of partial, cluster statuses have been initialized.
- Fix broken unit test code that was revealed by the new product code change to make sure that the unit test code does not generate a number of cluster status objects in the domain than specified in the spec.clusters.
- Fix ItKubernetesDomainEvents#testK8SEventsMultiClusterEvents to correctly check the cluster events that are related only to the cluster scale call.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15316/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15358/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15359/
=> Owls104307 fix intermittent issue in missing domain Available event 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
Fix createIngress failure in ItIntrospectVersion in OLCNE nightly run. 
Remove the unused createIngress() call in the test. 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15177/
=> Fix createIngress failure in ItIntrospectVersion in OLCNE nightly run

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java
The Operator Rest API does not handle cluster scaling when there are multiple same-named domains in different namespaces.
Changing the integration test code to workaround an intermittent test issue caused by two test domains using the same domainUid in different namespaces. Without this change, the ItKubernetesDomainEvents#testK8SEventsMultiClusterEvents may fail intermittently because of missing ClusterCompleted event.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15425/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15426/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15427/
=> Fix intermittent operator rest call issue by changing test code to use a different domainUid

operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/main/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStep.java, operator/src/test/java/oracle/kubernetes/operator/PodWatcherTest.java
Owls 105463 - Fix for ItKubernetesDomainEvents.testK8SEventsDelete test to generate DOMAIN_DELETED event when domain resource has deletion timestamp or not found during make-right. The integration test deletes the domain and cluster resource at the same time. The make-right is started by the cluster delete watch notification but the domain delete watch event is not received. This change generates the DELETED event (if its not being already generated) and sets `isDeleting` flag in DPI to `true` when creating the domain down plan due to deletion timestamp or domain not found during make-right.
In addition, it has changes to stop scheduled status updaters after the domain is deleted and changes to detect the server SHUTDOWN to resume the fiber when the server state is either UNKNOWN or …
=> Owls 105463 - Generate domain DELETED event when domain has deletion timestamp or not found during make-right

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsManagedByTwoOperators.java
fix log info in ItTwoDomainsManagedByTwoOperators.java.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15733/
=> fix log info in ItTwoDomainsManagedByTwoOperators.java

kubernetes/samples/scripts/domain-lifecycle/waitForDomain.sh
The root cause of the intermittent issue in ItMiiSampleWlsAux.testAIWlsUpdate1UseCase reported in OWLS-105608 is a race condition in sample script waitForDomain.sh, which is used by the test case to determine if the operator has done processing the changes to the domain resources.
The waitForDomain.sh script checks domain and cluster status periodically until the domain/clusters status matches what is expected (Success), or the expected statuses are not detected after a pre-defined period of time (Failure).  The expected conditions are domain Completed=true, the domain status' observedGeneration matches the domain's spec.generation, and each cluster's observedGeneration match its spec.generation.  
The problem is that the waitForDomain.sh script gets the values in the domain status one by …
=> OWLS-105608 Fix a race in waitForDomain sample script

operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/FluentdHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/StepContextConstants.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java
Resolves issue #3865 by decorating the Fluentd ConfigMap with the domain UID. Presently, the operator is not decorating these ConfigMap names and if two domains in the same namespace are both configured to use the Fluentd sidecar then the ConfigMaps clash.
Used our standard pattern to not have unexpected rolls on upgrade.
The clean-up logic will delete both the old and new ConfigMaps.
=> Decorate Fluentd ConfigMap with domainUID

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MonitoringUtils.java
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/48
=> backort changes from main for  monexp update

operator/src/main/java/oracle/kubernetes/operator/helpers/BasePodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodSecurityHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/BaseConfiguration.java, operator/src/test/java/oracle/kubernetes/operator/helpers/Matchers.java
All generated pods and containers will now have security context that meets the V8o and restricted requirements. This includes pods and containers for WebLogic Server instances, pods and containers for the introspector job, auxiliary image containers, and the container for the monitoring exporter.
=> Update pod and security context for all generated pods and containers

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ClusterUtils.java
the Nightly Failure https://build.weblogick8s.org:8443/job/wko-kind-nightly-parallel/1212/testReport/oracle.weblogic.kubernetes/ItMiiClusterResource/testSharedClusterResource/
error:
message: 'Domain domain7 failed due to ''Domain validation error'': Cannot reference
cluster resource ''shared-cluster'' because it is used by ''domain8''. Update
the domain resource to correct the validation error.'
reason: Failed
we do verify domain/cluster deleted using withStandardRetryPolicy. I can't see any other issue causing the failure of deleting the cluster. We can try to increate the waiting time from withStandardRetryPolicy to withLongRetryPolicy
to make sure we have enough time in case the env is picky
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16001/
=> [wko-nightly] Fix the failure from ItMiiClusterResource/testSharedClusterResource to delete shared-cluster

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicClusterMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DbUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java
Increase timeout value for DB and RCU. 
Add more logging information when get pod creation timestamp.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16082/
=> fix intermittent test issues in olcne

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/K8sEvents.java, operator/src/main/java/oracle/kubernetes/operator/ClusterResourceStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessor.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightDomainOperation.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightExecutor.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightOperation.java, operator/src/main/java/oracle/kubernetes/operator/ServerStatusReader.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ClusterPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/helpers/EventHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ResourcePresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightClusterOperationImpl.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightOperationImpl.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/EventHelperTest.java
- Add shouldContinue check to MakeRightClusterOperation.
- Add the DomainUID label to the Created/Changed/Deleted events if the cluster is referenced by a domain.
- Code cleanup
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16100/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16107/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16102/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16116/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16121/
=> Owls 106174 - improve handling of cluster resource Added/Modified/Deleted watch notifications

common/src/main/java/oracle/kubernetes/common/utils/SchemaConversionUtils.java
In some cases, init containers listed in the `serverPod` configuration for the WL server pod can depend on the init container(s) generated from `3.x/v8` aux image(s) configuration. This change is to put the init containers generated from 3.x/v8 aux image configuration at the top before listing other init containers in the `serverPod` spec.
=> Fix to list the init containers generated from 3.x/v8 aux image configuration at the top before other init containers.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingExporterUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java
Added above images to OCIR and updated the Test Constant file
phx.ocir.io/weblogick8s/test-images/docker/logstash
phx.ocir.io/weblogick8s/test-images/docker/fluentd-kubernetes-daemonset
phx.ocir.io/weblogick8s/test-images/docker/kibana
Note: This is backport for PR https://github.com/oracle/weblogic-kubernetes-operator/pull/3941
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16245
=> Release/3.4 Avoid docker pull for logstash,kibana,fluentd images

integration-tests/src/test/resources/bash-scripts/images.properties, integration-tests/src/test/resources/bash-scripts/install-istio.sh
Set custom docker registry to gcr.io/istio-release to avoid  docker.io/istio dependency during istio installation.
Jenkin run
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16249
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16255
=> Main: Modify install-istio.sh to remove docker.io dependency

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDedicatedMode.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRecoveryDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItValidateWebhookReplicas.java, kubernetes/samples/scripts/common/utility.sh
remove ItDedicatedMode.java from olcne profile since it will delete the domain crd in the test and can only run in sequential mode. It causes other tests fail when running in parallel mode. 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16238/
=> remove ItDedicatedMode.java from olcne profile 

operator/src/main/resources/scripts/model-wdt-create-filter.py, operator/src/main/resources/scripts/model_wdt_mii_filter.py, operator/src/test/python/test_wdt_mii_filter.py
This PR fixes the case where AdminServerName is specified or missing in the WDT model's topology section, but either not matching any server in the Server sections causing unexpected behavior as typical WDT/WLS expectation.
=> Port fix adminservername problem

operator/src/main/resources/scripts/model-wdt-create-filter.py, operator/src/main/resources/scripts/model_wdt_mii_filter.py, operator/src/test/python/test_wdt_mii_filter.py
This PR fixes the case where AdminServerName is specified or missing in the WDT model's topology section, but either not matching any server in the Server sections causing unexpected behavior as typical WDT/WLS expectation.
=> Fix adminservername problem

operator/src/main/java/oracle/kubernetes/operator/DomainProcessor.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightExecutor.java, operator/src/main/java/oracle/kubernetes/operator/helpers/EventHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodDisruptionBudgetHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/main/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStep.java, operator/src/main/java/oracle/kubernetes/operator/work/Fiber.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java, operator/src/test/java/oracle/kubernetes/operator/StuckPodTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainValidationStepTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/EventHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServicePresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/introspection/IntrospectionStatusTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainValidationTest.java
This contains fixes to a couple of problems in the operator code that may cause an in-flight make right operation to hit NPEs because the domain object in the DomainPresenceInfo (DPI) is null.
- Some K8S async calls (such as replace domain status or read a domain) may succeed with a null domain object in the response when the domain resource has been deleted. The operator uses the domain object in the response to update the corresponding DPI, which may be null out the domain object when the response contains a null result. The fix  is to only update the DPI when the domain object in the response is not null.
- In a periodical domain recheck, the operator reads all domains in each namespace, and then refreshes its "domains" map and detects all stranded domains. It first nulls out the …
=> Owls106230 fix NPEs caused by null domain object in the DomainPresenceInfo

integration-tests/src/test/resources/bash-scripts/install-istio.sh
Set custom docker registry to gcr.io/istio-release to avoid docker.io/istio dependency during istio installation.
Jenkin Run
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16273/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16271
=> release/3.4 Removed docker.io dependency during istio installation

operator/src/main/resources/scripts/introspectDomain.py
OWLS-106472 - Currently if there's no ServerTemplate configured in the dynamic server configuration, the server is considered to be part of a configured cluster. This change modifies the check for dynamic cluster to either look for presence of a ServerTemplate or `DynamicClusterSize` greater than 0. If the dynamic cluster is not referenced by a ServerTemplate, the subsequent validation in `validateDynamicClusterReferencedByOneServerTemplate` function will catch this and provide correct error message.
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16305/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16306/
=> OWLS-106472 - Improve error handling when Server template is not set for dynamic cluster.

vztest.sh
When there are no kind clusters running in the machine the 
`docker inspect kind | jq '.[0].IPAM.Config[0].Subnet'`  was returning null since no containers were running.
This caused the metal lb installation to fail and affecting vz installation.
To fix this issue moving the docker inspect to assign the subnet address after the kind cluster is created.
https://build.weblogick8s.org:8443/job/v8o-kind-nightly/44/
https://build.weblogick8s.org:8443/job/v8o-kind-nightly/43/
https://build.weblogick8s.org:8443/job/v8o-kind-nightly/42/
https://build.weblogick8s.org:8443/job/v8o-kind-nightly/41/
https://build.weblogick8s.org:8443/job/v8o-kind-nightly/40/
=> Change the network address assignment after the cluster creation

operator/src/main/resources/scripts/introspectDomain.py
OWLS-106472 - Currently if there's no ServerTemplate configured in the dynamic server configuration, the server is considered to be part of a configured cluster. This change modifies the check for dynamic cluster to either look for presence of a ServerTemplate or DynamicClusterSize greater than 0. If the dynamic cluster is not referenced by a ServerTemplate, the subsequent validation in validateDynamicClusterReferencedByOneServerTemplate function will catch this and provide correct error message.
=> Modified the check for dynamic cluster to look for either ServerTemplate or DynamicClusterSize > 0.

operator/src/main/java/oracle/kubernetes/operator/DomainNamespaces.java, operator/src/main/java/oracle/kubernetes/operator/Namespaces.java, operator/src/main/java/oracle/kubernetes/operator/OperatorMain.java, operator/src/test/java/oracle/kubernetes/operator/OperatorMainTest.java
The problem is that the operator may try to generate a Namespace_Watching_Stopped event for a namespace that is not even managed by the operator.  
With the fix, the operator skips the generation of a Namespace_Watching_Stopped in a domain namespace if
- the namespace is not managed by the operator.
- the operator got a Deleted event for the namespace, because generating an event in a non-existing NS will always fail.
- 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16316/
=> OWLS-106248 only create NS-Watch-Stopped event if NS was managed by the operator

operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
OWLS-106777 - Forward port fix for string index out of bounds exception in PodStepContext to main.
=> OWLS-106777 - Forward port fix for string index out of bounds exception in PodStepContext to main

operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
OWLS-106777 - Fix for string index out of bounds exception in PodStepContext
=> OWLS-106777 - Fix for string index out of bounds exception in PodStepContext

kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl
The indentation of `nodeSelector` and `affinity` elements were wrong because the webhook content is offset more than for the operator's deployment.
=> Fix indentation for webhook

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRetryImprovementMisc.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItValidateWebhookReplicas.java
Backport PR 3951 to main
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/16291/
=> Backport PR 3951 to main

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/TraefikParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoadBalancerUtils.java, integration-tests/src/test/resources/bash-scripts/images.properties, integration-tests/src/test/resources/traefik.template.properties
Added traefik ingress image to  
phx.ocir.io/weblogick8s/test-images/traefik-ingress/traefik:v2.9.6
Jenkin Run
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16294
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16295
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16297
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16304  (full run)
=> Remove docker dependency for traefik installation 

documentation/4.0/content/managing-domains/domain-lifecycle/scaling.md, documentation/4.0/content/managing-operators/the-rest-api.md, documentation/4.0/content/managing-operators/using-helm.md, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDiagnosticsCompleteAvailableCondition.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManageNameSpace.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItUsabilityOperatorHelmChart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/OperatorParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java, kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl, kubernetes/charts/weblogic-operator/templates/_operator-external-svc.tpl, kubernetes/charts/weblogic-operator/templates/_operator-internal-svc.tpl, kubernetes/charts/weblogic-operator/values.yaml, kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorGeneratedFilesTestBase.java, kubernetes/src/test/java/oracle/kubernetes/operator/helm/HelmOperatorValues.java, kubernetes/src/test/java/oracle/kubernetes/operator/utils/OperatorValues.java, operator/src/main/java/oracle/kubernetes/operator/BaseMain.java, operator/src/main/java/oracle/kubernetes/operator/CoreDelegate.java, operator/src/main/java/oracle/kubernetes/operator/DeploymentReady.java, operator/src/main/java/oracle/kubernetes/operator/KubernetesConstants.java, operator/src/main/java/oracle/kubernetes/operator/OperatorMain.java, operator/src/main/java/oracle/kubernetes/operator/http/metrics/MetricsServer.java, operator/src/test/java/oracle/kubernetes/operator/OperatorMainTest.java
Creating a draft PR so that I can run integration tests. Presently, I expect this to cause failures in existing integration tests.
Disable the operator REST endpoint by default. It can be enabled with a Helm variable.
=> Disable REST endpoint by default

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java
The operator REST api is disabled by default. Remove the unused externalRestHttpsPort code in ItOperatorWlsUpgrade.java.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16469/
=> remove unused externalRestHttpsPort code

documentation/3.4/content/userguide/managing-domains/model-in-image/usage.md, documentation/3.4/content/userguide/managing-fmw-domains/_index.md, documentation/4.0/content/managing-domains/managing-fmw-domains/_index.md, documentation/4.0/content/managing-domains/model-in-image/usage.md
Including all references to JRF and JRF-restricted domains, as per [WKO - Documentation Remove FMW Infra support in Model in Image pattern](https://jira.oraclecorp.com/jira/browse/OWLS-106404?filter=-1). This first pass is in the 4.0 docs; it will be duplicated in the 3.4 docs after incorporating technical review comments.
Acknowledged that these references must **also** be removed from the MII sample and sample docs.
=> Remove references to FMW

integration-tests/src/test/java/oracle/verrazzano/weblogic/ApplicationList.java, integration-tests/src/test/java/oracle/verrazzano/weblogic/ComponentList.java, integration-tests/src/test/java/oracle/verrazzano/weblogic/kubernetes/ItVzMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/IntegrationTestWatcher.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingUtil.java
The changes from this PR collects the logs for all artifacts in the verrazano-system, ingress-nginx, istio-system namespaces and also the ApplicationConfiguration, Component artifacts from the domain namespace.
The new artifacts are listed in this simulated fail run
https://build.weblogick8s.org:8443/job/v8o-kind-nightly/76/artifact/logdir/jenkins-v8o-kind-nightly-76/wl_k8s_test_results/diagnostics/ItVzMiiDomain/testCreateVzMiiDomain/
The normal Jenkins results with the changes
https://build.weblogick8s.org:8443/job/v8o-kind-nightly/77
=> Infra changes to collect logs from verrazzano installation

operator/src/main/java/oracle/kubernetes/operator/ClusterResourceStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java, operator/src/test/java/oracle/kubernetes/operator/calls/AsyncRequestStepTest.java
The problem reported in OWLS-107005 is that an async call failure is left in domain status after the condition is recovered, and even after the domain processing is successfully completed.
The fix includes:
- Don't add Failed condition at the low async request processing layer when the error code is 409 (conflict) because the operator will retry the request after refresh the resource.
- When the domain status Completed condition becomes true, clear Failed conditions.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16635/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16638/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16640/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new …
=> OWLS-107005 correct Failed condition handling at the async request processing layer

operator/src/main/resources/scripts/model-wdt-create-filter.py
This is a fix to the cover the edge case when the user did not specify AdminServerName and there is a server named adminserver - the filter wlll then have two server with same lowercased listen address and WebLogic does not allow that.
=> Fix adminserver name 34

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java, operator/src/main/java/oracle/kubernetes/operator/Namespaces.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/StuckPodTest.java
This is an improvement of generating domain created/changed event in the recheck code path in case that the domain watch events are missing.
Original solution in PR#3998 is to determine if and which event needs to be added to the make right operation in shouldContinue logic. It turned out that it is easier to correctly determine that in the DomainResourcesValidation code when the operator handles the results of listing resources from the K8S API server.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16706/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16707/
=> owls-106707 adjust domain Created and Changed events in recheck

operator/src/main/resources/scripts/model-wdt-create-filter.py
This is a fix to the cover the edge case when the user did not specify AdminServerName and there is a server named adminserver - the filter wlll then have two server with same lowercased listen address and WebLogic does not allow that.
=> Fix lowercase adminserver name

documentation/4.0/content/managing-operators/installation.md
Add a note to call out the 3.x to 4.x change to the default value of `domainNamespaceSelectionStrategy`.
=> Add note to upgrade doc

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLogging.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/LoggingExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingExporterUtils.java, integration-tests/src/test/resources/wdt-models/model.wlslogging.yaml
Removed our WebLogic Logging Exporter test from the main line as per Monica suggestion.
Jenkins Jobs
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16590
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16592
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16658
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16659
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16703
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16704
with latest changes:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16728
=> Remove WebLogic Logging Exporter integration test from WKO main

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java
The test was deleting a different cluster than intended and it was causing intermittent failures. The changes in this PR adds a new utility method to delete cluster by determining the correct index and then patching to remove it from the domain resource.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16782/
=> Delete the cluster at correct index to prevent intermittent test failures

documentation/4.0/content/_index.md, documentation/4.0/content/base-images/custom-images.md, documentation/4.0/content/base-images/patch-images.md, documentation/4.0/content/introduction/platforms/environments.md, documentation/4.0/content/managing-domains/choosing-a-model/_index.md, documentation/4.0/content/managing-domains/cicd/_index.md, documentation/4.0/content/managing-domains/configoverrides/_index.md, documentation/4.0/content/managing-domains/domain-lifecycle/restarting.md, documentation/4.0/content/managing-domains/manage-domains.md, documentation/4.0/content/samples/domains/domain-home-in-image/_index.md, documentation/4.0/content/samples/domains/fmw-domain-home-in-image/_index.md, documentation/4.0/content/security/domain-security/image-protection.md
Minor tweak to DII note text, add NOTE to Custom Images
=> Tweak DII note text

operator/src/main/resources/scripts/modelInImage.sh
WDT database wallet can now be in zip file format form in the archive,  this means MII needs to unzip the wallet after restoring from the archive when starting the server, otherwise, the data source driver parameter referencing the actual keystores will not exist in the file system
=> Support new structure in WDT archive for database wallets

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOpenshiftIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java, integration-tests/src/test/resources/openshift/servicememberroll.yaml, integration-tests/src/test/resources/opnshift/servicememberroll.yaml
- Fix ItConfigDistributionStrategy to accommodate the 12.2.1.3 driver name difference
- Fix IstioMiiDomain to move the mTLS mode changes before creating DestinationRule
- Fix ItOpenshiftIstioMiiDomain to fix serverStartPolicy from IF_NEEDED to IfNeeded for WKO 4.0
IstioMiiDomain with WLS Image - 14.1.1.0-8-ol8
https://build.weblogick8s.org:8443/view/Kind%20(WKO)/job/weblogic-kubernetes-operator-kind-new/16803
IstioMiiDomain with WLS Image - 14.1.1.0-slim-8-ol8
https://build.weblogick8s.org:8443/view/Kind%20(WKO)/job/weblogic-kubernetes-operator-kind-new/16804
ItConfigDistributionStrategy with WLS Image - 12.2.1.3 
https://build.weblogick8s.org:8443/view/Kind%20(WKO)/job/weblogic-kubernetes-operator-kind-new/16805
ItConfigDistributionStrategy with WLS Image - 12.2.1.4 …
=> Fix for Openshift certification, 12.2.1.3 mySql driver, and Istio related changes

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWDTModelNoServer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/resources/wdt-models/model-configuredcluster-noserver.yaml, integration-tests/src/test/resources/wdt-models/model-emptytopology.yaml, integration-tests/src/test/resources/wdt-models/model-hasadminservername-namedservernotinserver.yaml, integration-tests/src/test/resources/wdt-models/model-noadminservername-hasadminserver.yaml, integration-tests/src/test/resources/wdt-models/model-noadminservername-hasadminserverlowercase.yaml, integration-tests/src/test/resources/wdt-models/model-noadminservername-hasmyadminserver.yaml, integration-tests/src/test/resources/wdt-models/model-noadminservername-noserver.yaml
Backport to release/3.4: Add Functional Regression tests for OWLS-106473, OWLS-106637
https://build.weblogick8s.org:8443/view/Kind%20(WKO)/job/weblogic-kubernetes-operator-kind-new/16791/ (running with release/3.4 branch got the same failures, see the below job link)
https://build.weblogick8s.org:8443/view/Kind%20(WKO)/job/weblogic-kubernetes-operator-kind-new/16796/
=> Backport to release/3.4: Add Functional Regression tests for OWLS-106473, OWLS-106637

operator/src/main/java/oracle/kubernetes/operator/steps/HttpRequestProcessing.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/steps/MonitoringExporterStepsTest.java, operator/src/test/java/oracle/kubernetes/operator/steps/ReadHealthStepTest.java, operator/src/test/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStepTest.java
A customer selected a namespace name that started with a number. This is, perhaps surprisingly, legal, as per [Namespaces and DNS](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns), which states that, As a result, all namespace names must be valid [RFC 1123 DNS labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names)." and the definition of RFC-1123 labels requires that:
* contain at most 63 characters
* contain only lowercase alphanumeric characters or '-'
* start with an alphanumeric character
* end with an alphanumeric character
Sadly, if the final component of the hostname of a URL starts with a number than the URI is invalid. The customer saw many SEVERE messages in the log as the operator tried …
=> Add .svc suffix to make URI's consistently valid

documentation/4.0/content/introduction/platforms/environments.md, documentation/4.0/content/security/openshift.md
Updated the certified versions.
Reordered the OpenShift page to highlight the requirement to use the Helm variable, `kubernetesPlatform`, and its effect and to deemphasize the now less common use case of needing to create a custom security context constraint.
=> Update OpenShift documentation and certifications

operator/src/main/resources/scripts/createDomainOnPV.sh, operator/src/main/resources/scripts/utils.sh
When the introspector detects an existing JRF domain on PV, the introspector checks the major WebLogic version in the base image and makes sure that it is not upgraded/downgraded against the major version of the existing JRF domain.
=> OWLS-107875 check WebLogic version change in base image

documentation/4.0/content/managing-domains/accessing-the-domain/istio/istio.md
As per this JIRA [OWLS-108117](https://jira.oraclecorp.com/jira/browse/OWLS-108117):
- Standardized the example namespace name to be "weblogic-operator"
- Standardized the domain namespace name to be "sample-domain1"
One complaint unaddressed:
"3. Right location for domain.yaml file in not mentioned in the following command "kubectl apply -f domain.yaml"
@jshum2479 Please advise
=> update Istio support doc

kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service/create-domain-on-aks.sh
The [commit](https://github.com/oracle/weblogic-kubernetes-operator/commit/430f3d0b32801db0232fd6444a47c5447a765b16) removed keyword `function`, but it should add `()` instead.
- <img width="1246" alt="image" src="https://github.com/oracle/weblogic-kubernetes-operator/assets/4465723/f5a623e6-9345-4ca1-8596-5e2d193e43d4">
=> BugFix: Fix Wrong Function Syntax Error

kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service/create-domain-on-aks.sh
Refer to the doc: [The resource with name 'name' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription](https://learn.microsoft.com/en-us/answers/questions/1188413/the-resource-with-name-name-and-type-microsoft-con)
I got the same error when running the [create-domain-on-aks.sh](https://github.com/backwind1233/weblogic-kubernetes-operator/blob/3f51c35bd891bc90f227c7a61fdb146f1773facb/kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service/create-domain-on-aks.sh).
Fix bug: 'Microsoft.ContainerRegistry/registries' could not be found in subscription
=> BugFix 'Microsoft.ContainerRegistry/registries' could not be found  in subscription

documentation/site/content/managing-domains/aks/_index.md
This pull request modifies the `documentation/site/content/managing-domains/aks/_index.md` file to update the instructions for configuring Oracle WebLogic Server on Azure Kubernetes Service (AKS). The changes mainly involve updating the configuration steps, modifying the terminology used, and reordering some of the sections.
The most important changes include:
Updates to Configuration Steps:
* The instructions for the **Basics** configuration blade have been modified to simplify the process of moving to the next step. The user now simply clicks **Next** instead of **Next: Configure AKS cluster**.
* The **AKS** configuration blade now includes an **Advanced** section where users can specify additional optional configurations.
* The **TLS/SSL** configuration blade has been updated to …
=> Update aks use guide for autoscaling.
