oracle/weblogic-kubernetes-operator

site/installation.md
=> clarify the need to clone the repo before the build

site/installation.md
=> add details about maven to the install instructions

site/installation.md
=> add details of where to run the docker build

site/installation.md
=> update installation instructions to make build requirements clear

site/installation.md
=> clarify that image needs to be loaded on each k8s worker

pom.xml, wercker.yml
This PR adds a new pipeline that will run a sonar scan on the code and publish to our sonar server.
=> Add pipeline to run Sonar scan on the code

src/integration-tests/bash/run.sh
use flags on command line options now.  Internal JENKINS only.
=> update run.sh for new clean and install

src/main/java/oracle/kubernetes/operator/Main.java
Signed-off-by: Dongbo Xiao <dongbo.xiao@oracle.com>
=> Fix an issue in scale down to 0 replica

src/main/java/oracle/kubernetes/operator/Main.java
=> Add PodWatcher to Packet component

pom.xml, src/test/java/oracle/kubernetes/custom/TestDomainListWatcher.java, src/test/java/oracle/kubernetes/operator/HealthCheckHelperTest.java, src/test/java/oracle/kubernetes/operator/SecretHelperTest.java, src/test/java/oracle/kubernetes/operator/ServiceHelperTest.java, src/test/java/oracle/kubernetes/operator/WatchTest.java, src/test/java/oracle/kubernetes/operator/helpers/IngressHelperTest.java
This change turns on unit tests in the build, disabling the ones that don't currently work.
=> Enable the unit tests that are currently working, independent of platforms

src/integration-tests/bash/run.sh
The full run.sh passed locally.
Signed-off-by: Dongbo Xiao <dongbo.xiao@oracle.com>
=> Fine tune test case for creating domain with startupControl "ADMIN"

site/creating-domain.md
Add the new parameters to the table in weblogic-kubernetes-operator/site/creating-domain.md
=> Add NFS configration parameters to the document

kubernetes/internal/domain-job-template.yaml
Signed-off-by: Lily He <lily.he@oracle.com>
=> fix to issue #106

site/name-changes.md
Update the docs to say that the domains should be deleted before the operators.
=> Update the docs to say that the domains should be deleted before the operators

kubernetes/internal/weblogic-domain-apache-template.yaml, operator/src/test/java/oracle/kubernetes/operator/create/CreateDomainGeneratedFilesBaseTest.java, src/integration-tests/bash/run.sh
Signed-off-by: Dongbo Xiao <dongbo.xiao@oracle.com>
=> Update apache docker image

site/creating-domain.md
Mostly minor edits, except, please review the "Limitations of the create domain script" section.
=> first pass edit on creating domains doc

site/database.md
Minor edits. Not much text of substance in this file.
=> fixed typos

site/developer.md
I made the two edits Monica requested in this doc:
"It is git clone https://github.com/oracle/weblogic-kubernetes-operator.git"
"Please remove the mention of probelms with 1.9 and add new versions we certify"
=> incorporate Monica's edits

site/k8s_setup.md
=> minor edits

site/name-changes.md
I changed the capitalization scheme to line up with the other docs (we are using sentence capitalization versus title capitalization).
=> change capitalization scheme

README.md
As per Monica's request, changed Apache web server to Apache HTTP Server.
=> changed Apache web server to Apache HTTP Server

site/rest.md
=> minor text edits

site/installation.md
Please check content in the Load Balancing section (I copied the first paragraph from the README file). Particularly review this part in the section, "Note that this release provides only basic load balancing ...,"
=> first pass edits on install doc

site/installation.md
Some cleanup was needed in the "Build the Docker image for the operator using Wercker" section.
=> second pass edits

site/scaling.md
Fix nested list in "What does the operator do in response to a scaling request?" section.
=> fix nested list

README.md
Put Load Balancing section after Scaling a Cluster, and Shutting Down a Domain, right before Removing a Domain.
=> re-order sections

site/voyager.md
Please review edits, particularly, the re-wording of "Set up Voyager manually to WebLogic domain running in Kubernetes"
=> review/edit Voyager doc

README.md, site/installation.md
Added x-ref to the Voyager doc to the README and the installation doc.
=> added x-ref to Voyager doc

operator/src/main/java/oracle/kubernetes/operator/work/Fiber.java, operator/src/test/java/oracle/kubernetes/operator/work/StepTest.java
Fixes issue #267 
There was a race condition in Fiber's calling of the completion callback and when Future.get() would report that the Fiber was done.
=> Fix race condition in Fiber

kubernetes/delete-weblogic-domain-resources.sh, kubernetes/internal/utility.sh, src/integration-tests/bash/cleanup.sh
The change delete voyager when there are no voyager ingress left.
=> Fix for OWLS-65309

kubernetes/internal/create-weblogic-domain.sh, kubernetes/internal/delete-weblogic-domain-job-template.yaml, operator/src/test/java/oracle/kubernetes/operator/create/CreateDomainGeneratedFilesBaseTest.java, operator/src/test/java/oracle/kubernetes/operator/utils/DomainFiles.java, operator/src/test/java/oracle/kubernetes/operator/utils/GeneratedDomainYamlFiles.java, operator/src/test/java/oracle/kubernetes/operator/utils/ParsedDeleteWeblogicDomainJobYaml.java
=> generate job yaml to delete domain_home folder in create-weblogic-domain.sh

kubernetes/create-weblogic-operator-inputs.yaml, site/installation.md
=> Clarify that customers must build operator image

operator/src/main/java/oracle/kubernetes/operator/Main.java, operator/src/main/java/oracle/kubernetes/operator/Watcher.java, operator/src/main/java/oracle/kubernetes/operator/calls/AsyncRequestStep.java, operator/src/main/java/oracle/kubernetes/operator/calls/CallResponse.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfoManager.java, operator/src/main/java/oracle/kubernetes/operator/helpers/IngressHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/operator/steps/ConfigMapAfterStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/DeleteDomainStep.java, operator/src/main/java/oracle/kubernetes/operator/work/Step.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceInfoMatcher.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/ThreadFactoryTestBase.java, operator/src/test/java/oracle/kubernetes/operator/WatcherTestBase.java, operator/src/test/java/oracle/kubernetes/operator/builders/StubWatchFactory.java, operator/src/test/java/oracle/kubernetes/operator/work/StepChainTest.java
Added DomainPresence tests, improved reliability of tests, improved code readability
=> May cleanup 1

operator/src/main/java/oracle/kubernetes/operator/helpers/IngressHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/operator/steps/DeleteDomainStep.java
Fix steps which had been only halfway changed to use the new methods in ResponseStep
=> correct illegal state exception

operator/src/main/java/oracle/kubernetes/operator/helpers/AuthorizationProxy.java, operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java, operator/src/main/java/oracle/kubernetes/operator/helpers/HealthCheckHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/SynchronousCallFactory.java, operator/src/test/java/oracle/kubernetes/TestUtils.java, operator/src/test/java/oracle/kubernetes/operator/ClientFactoryStub.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/HealthCheckHelperTest.java
Rewrote HealthCheckHelperTest as a pure unit test, with greatly expanded code coverage.
=> convert HealthCheckHelperTest to pure unit test

operator/src/main/java/oracle/kubernetes/operator/DomainPresence.java, operator/src/main/java/oracle/kubernetes/operator/LabelConstants.java, operator/src/main/java/oracle/kubernetes/operator/Main.java, operator/src/main/java/oracle/kubernetes/operator/calls/RequestParams.java, operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java, operator/src/main/java/oracle/kubernetes/operator/steps/DefaultResponseStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/DeleteDomainStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/DeleteIngressListStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/DeleteServiceListStep.java, operator/src/main/java/oracle/kubernetes/operator/steps/ListPersistentVolumeClaimStep.java, operator/src/main/java/oracle/kubernetes/operator/work/FiberGate.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/work/AsyncCallTestSupport.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java
Added tests for removing stranded resources, added the logic so it now runs after the existing domains are read, and refactored some code for readability
=> domain presence refactoring 2

kubernetes/internal/create-weblogic-domain.sh, kubernetes/internal/weblogic-domain-apache-security-template.yaml, kubernetes/internal/weblogic-domain-apache-template.yaml
The create domain script generates an invalid apache yaml file when 
loadBalancerVolumePath is set and loadBalancerExposeAdminPort is false.
=> Issue 330:  Fix an issue in create domain script for one Apache use case 

kubernetes/internal/create-weblogic-domain.sh, kubernetes/internal/weblogic-domain-apache-template.yaml
=> Better handling optional elements in apache yaml file

kubernetes/internal/create-weblogic-domain.sh
=> add timebound wait until voyager controller pod is ready

src/integration-tests/bash/run.sh
update run.sh to work with latest namespace related changes in operator helm charts
=> Update 1 1 inttest

kubernetes/charts/weblogic-domain/templates/_create-domain-job.tpl, kubernetes/pom.xml, src/integration-tests/bash/run.sh, wercker.yml
Fixes the helm installation test failure that was causing the integration tests to fail. Moved the helm installation tests to the build step.
=> Helm wercker build

operator/src/main/resources/scripts/startServer.sh
Cleanup WL pod startServer.sh script to make it easier to understand, plus to fix a regression where it wasn't removing the potentially stale 'state' file.  Also, the script now recreates ‘startup.properties’ every time rather than skip if the file already exists…
Test status:  Passes local and Wercker 'QUICKTEST' integration test.
=> Cleanup WL pod startServer.sh script 

Dockerfile, integration-tests/pom.xml, kubernetes/pom.xml, model/pom.xml, operator/pom.xml, pom.xml, src/integration-tests/bash/run.sh, swagger/pom.xml, wercker.yml
Switch to the standard maven version numbering, using xx-SNAPSHOT during development
Select the built jar's version from the pom, and pass that to the Dockerfile
=> Maven versions

Dockerfile, integration-tests/pom.xml, kubernetes/pom.xml, model/pom.xml, operator/pom.xml, pom.xml, swagger/pom.xml, wercker.yml
Merge maven versions change into 1.1 branch
=> Maven versions 1.1

integration-tests/src/test/resources/setupenv.sh
Fix java test for Jenkins:
http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/129/
=> use POM version for Jenkins

kubernetes/samples/scripts/create-weblogic-domain-load-balancer/create-weblogic-sample-domain-load-balancer.sh
When use -e, the create script will also deploy the generated yaml files.
This is to fix a bug in the -e handling of Voyager LB.
@rjeberhard
=> Fix voyager sample -e option

kubernetes/samples/scripts/create-weblogic-domain-load-balancer/create-load-balancer-inputs.yaml, kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/create-pv-pvc-inputs.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain.sh, src/integration-tests/bash/run.sh
As we agreed - uncomment the domainUID in all sample input files.
It also does:
2) calculate the default value for persistentVolumeClaimName based on the value of the domainUID.
3) make the default domainName the same as the domainUID.
@rjeberhard @moreaut @tbarnes-us @anpanigr @vanajamukkara @maggiehe00
=> Make sure all non-optional input properties have a default value

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java, kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/README.md, kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/create-pv-pvc-inputs.yaml, kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/create-pv-pvc.sh, kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/pv-template.yaml, kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/pvc-template.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml
1) Initial README.md for create-pv-pvc.sh script.
2) Cleanup in the scripts and Java integration test code.
@anpanigr @maggiehe00 @vanajamukkara
=> WIP Sample pv doc and cleanup

site/architecture.md
=> change reference to Operator image

site/architecture.md
minor fix to make hyperlink hot
=> fix link to Docker image

kubernetes/samples/README.md, kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/README.md, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/README.md
1) Add README.md in the samples directory, which list all samples with a simple description.
2) Add more details about using wdt
3) Add more detail about shared pv/pvc (addressing QA's feedback)
4) Minor cleanups
@maggiehe00
=> Sample doc updates

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh
=> Fix a typo in samples

src/integration-tests/bash/cleanup.sh
delete ingress in cleanup script
=> fix cleanup for ingress

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
There are intermittent failures in WLDF scaling test case on Jenkins and in local runs.
Vanaj and I worked out a modification of the test case to make the test result more predictable.
=> Fix wldf scaling test

kubernetes/samples/charts/ingress-per-domain/README.md, kubernetes/samples/charts/ingress-per-domain/templates/traefik-ingress.yaml, kubernetes/samples/charts/ingress-per-domain/templates/voyager-ingress.yaml
https://jira.oraclecorp.com/jira/browse/OWLS-69745
=> handle uppercase wls cluster name in ingress-per-domain chart 

kubernetes/samples/charts/ingress-per-domain/README.md, kubernetes/samples/charts/traefik/README.md, kubernetes/samples/charts/voyager/README.md
Changed internal titles to sentence capitalization to align with other docs. Performed editing pass throughout the READMEs.
=> copy edit READMEs

integration-tests/pom.xml, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/ExecCommand.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Operator.java, kubernetes/internal/utility.sh, wercker.yml
1) Restored internal/utility.sh
2) Corrected usage of private docker registry secrets
3) Pump console output from domain creation scripts so that you can see how it's progressing.
=> Changes necessary to fix broken tests

kubernetes/samples/charts/ingress-per-domain/README.md, kubernetes/samples/charts/traefik/README.md, kubernetes/samples/charts/voyager/README.md
Mostly minor edits, trying to align Traefik and Voyager Helm chart samples.
=> additional edits

README.md
This PR updates the readme to tell users how they can get an invitation to join our public slack channel.
=> add slack invite details

model/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java, model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainSpec.java, model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Configurator.java, model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ServerSpec.java, model/src/test/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Test.java, model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample.yaml
Add configOverrides to domain spec with unit tests.
=> OWLS-70104 add config overrides

operator/src/main/java/oracle/kubernetes/operator/Workarounds.java, operator/src/main/java/oracle/kubernetes/operator/helpers/IngressHelper.java, operator/src/test/java/oracle/kubernetes/operator/helpers/CallTestSupport.java
This change removes a workaround for a since-fixed bug in the kubernetes client
=> remove workaround

operator/src/main/java/oracle/kubernetes/operator/DomainProcessor.java, operator/src/main/java/oracle/kubernetes/operator/Main.java, operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java, operator/src/main/java/oracle/kubernetes/operator/ServiceWatcher.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfoManager.java, operator/src/main/java/oracle/kubernetes/operator/helpers/LegalNames.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServerKubernetesObjects.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServerKubernetesObjectsManager.java, operator/src/main/java/oracle/kubernetes/operator/steps/DeleteDomainStep.java, operator/src/main/java/oracle/kubernetes/operator/work/Fiber.java, operator/src/main/java/oracle/kubernetes/operator/work/Step.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceInfoMatcher.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/MainTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServerKubernetesObjectsLookupTest.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java
Brings Jenkins back to just three failures:
[ERROR] Errors: 
[ERROR]   ITOperator.test5CreateConfiguredDomainInTest2NS:166->testDomainCreation:311->BaseTest.testAdminT3Channel:174 ? Runtime
[ERROR]   ITOperator.test8WlsLivenessProbe:234 ? Runtime WLS liveness probe is not worki...
[ERROR]   ITOperator.testBCreateDomainWithDefaultValuesInSampleInputs:284->testAllUseCasesForADomain:305->BaseTest.testClusterScaling:219 ?
=> Lots of work to improve resiliency and diagnosability

integration-tests/README.md, integration-tests/src/test/java/oracle/kubernetes/operator/ITOperator.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java, wercker.yml
changes made to shutdown the domain after test completes 
combined liveness probe test in another test as it uses the same domain
here is the jenkins run java-integration-tests branch
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/478/consoleFull
=> shutdown domain after test completes successfully

README.md
This is a Very Rough README first draft with lots of room for improvement, additions, changes, and restructuring where needed. Have at it!
=> re-do README

site/quickstart.md
Not sure why it looked so different in the repo than it did in my MD editor, but I tried to put it back into a reasonable format.
=> fix formatting issues

site/quickstart.md
=> fix broken link

kubernetes/samples/scripts/create-weblogic-domain/create-weblogic-credentials.sh, kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain-inputs.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/README.md, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml
1) Have explicit/hard-coded defaults
2) Correct help text in create-weblogic-credentials.sh
3) Update README files
=> Fix sample input defaults

kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/README.md
=> add create K8s resource command

kubernetes/samples/charts/util/setup.sh, kubernetes/samples/charts/voyager/README.md, site/ingress.md
1. Update setup.sh to get rid of Voyager CRD deletion deadlock.
2. Fix links in ingress.md.
3. Disable webhook in Voyager README.md.
=> Voyager update

src/integration-tests/introspector/checkBeans.inputt, src/integration-tests/introspector/checkBeans.py, src/integration-tests/introspector/createDomain.pyt, src/integration-tests/introspector/introspectTest.sh, src/integration-tests/introspector/override--jdbc-testDS.xmlt, src/integration-tests/introspector/util_subst.sh, src/integration-tests/introspector/wl-job.yamlt
Enhance mock/unit introspector test to test an encrypted secret override of a DataSource password-encrypted field.
=> Enhance mock/unit introspector test (again)

site/quickstart.md
I think this draft is close to final form. Please review it for accuracy and completeness.
=> Quick Start second draft

README.md
Very minor edits. Doc looks good!
=> literary review

kubernetes/samples/scripts/common/utility.sh, kubernetes/samples/scripts/common/validate.sh, kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md, kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain-inputs.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain.sh, kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/domain-template.yaml, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain.sh
The PR contains the following changes:
1) Add image, imagePullPolicy  and imagePullSecrets to create-domain-inputs.yaml.
2) Add the new elements to domain-template.yaml
3) Refactor the create-domain.sh for on pv sample and moved the related code to common validate.sh.
4) Update the README.md.
=> Add image, imagePullPolicy and imagePullSecrets to domain-home-in-image sample

src/integration-tests/introspector/checkBeans.py, src/integration-tests/introspector/wl-introspect-pod.yamlt
No risk to merge this into rc1.  
Corrects a regression in the test that causes the test to fail at the very last step.
=> minor fix to introspect mock/unit test

kubernetes/samples/README.md, kubernetes/samples/scripts/create-weblogic-domain-credentials/README.md, kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/README.md, kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md, kubernetes/samples/scripts/elasticsearch-and-kibana/README.md, kubernetes/samples/scripts/rest/README.md, site/persistent-volumes.md
=> review/edit sample READMEs

README.md, site/domains.md, site/helm-charts.md, site/user-guide.md, site/weblogic-docker-images.md
Lots of minor edits and clean-up.
=> review and edit

README.md
(fixed via pull 716 / OWLS-70905)
=> Remove Issue 727 from README.md known issues list 

kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md, site/domains.md
Couldn't get your edits into the previous PR (#747) so I opened this new one.
=> incorporate edits from Dongbo and Mark

site/scaling.md
Updated two URLs to the 12.2.1.3.0 docs. Other minor edits.
=> update doc URLs

site/quickstart.md
Added doc note to curl command in the quick start guide.
=> add doc note

kubernetes/samples/charts/ingress-per-domain/templates/voyager-ingress.yaml
otherwise the voyager stats can not show up in browser
=> fix selector of voyager-stats

site/helm-charts.md
Fixes minor syntax issue found in examples in "Install the Helm Chart" doc
=> fix helm install --set syntax in examples

README.md, kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/README.md, kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/README.md, site/domain-resource.md, site/domains.md, site/helm-charts.md, site/quickstart.md, site/recent-changes.md, site/weblogic-docker-images.md
=> clean-up odds and ends

site/developer.md, site/scaling.md
From Bob D:
Fixed CURL command in scaling.md.
From Michael G:
Added warning regarding integration tests cleanup.
=> incorporate edits

README.md
Remove Known Issue #722 from the Main README.
=> remove known issue

operator/src/main/java/oracle/kubernetes/operator/TuningParametersImpl.java
Let's debate what these defaults should be...
=> Adjust default probe tuning

site/config-overrides.md
QA (Sankar, Huiling, Xian) have reviewed the changes.
=> Custom overrides doc update.

site/architecture.md, site/domain-resource.md, site/domains.md, site/install.md, site/k8s_setup.md, site/persistent-volumes.md, site/prepare-k8s.md, site/quickstart.md, site/rest.md, site/user-guide.md, site/weblogic-docker-images.md, site/wlst.md
Reviewed all the docs in the site directory and cleaned up details as needed.
=> fine-tune edits

site/quickstart.md
Add information for accessing the WLS Administration Console.
=> update Quick Start

site/user-guide.md
This text came from the v1.1 README. Monica wanted it put back into the User Guide.
=> add security considerations back to User Guide

kubernetes/pom.xml, model/pom.xml, operator/pom.xml, pom.xml, swagger/pom.xml
Fix #869 by correcting header in pom files.
=> Correct pom file header

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/main/java/oracle/kubernetes/operator/steps/WatchDomainIntrospectorJobReadyStep.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java
Resolve https://jira.oraclecorp.com/jira/browse/OWLS-71734
This has passed quicktest and  the full integration test suite locally
=> WIP: cache the JobWatcher by namespace

README.md
Edit blog URL to point to operator 2.0 blog
=> change blog URL

integration-tests/README.md, integration-tests/src/test/java/oracle/kubernetes/operator/ITOperator.java, integration-tests/src/test/resources/domainadminonly.yaml, integration-tests/src/test/resources/domainonpvwdt.yaml, integration-tests/src/test/resources/domainonpvwlst.yaml, integration-tests/src/test/resources/domainrecyclepolicy.yaml, integration-tests/src/test/resources/domainsampledefaults.yaml
Mainly doc changes and some comments.
@rjeberhard this PR is ready to merge.
=> Updated java integration tests README.md with new changes 

site/quickstart.md
minor quick-start doc update:  createDomain.sh -> create-domain.sh
=> minor doc fix

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh
=> ready to merge:  Update wdt version to 0.17

site/config-overrides.md
Clarification suggested by Brian Dueck.
=> doc update

site/domain-resource.md, site/install.md, site/weblogic-docker-images.md
* Added alternative method for installing operator Helm chart (to install.md)
* Added check WLS and patch version info to Creating or obtaining WebLogic Docker images (weblogic-docker-images.md)
* Changed text regarding domain resource YAML file example and cross-reference (domain-resource.md)
=> updates to three documents

integration-tests/src/test/java/oracle/kubernetes/operator/ITServerDiscovery.java
Completed JIRA OWLS-71985 - QA - Migrate Server Discovery test suite to github
all 8 test passed on Wercker and Jenkins
=> Server discovery tests

test
Reverts oracle/weblogic-kubernetes-operator#939
=> Revert "testing"

docs-source/content/_index.md, docs-source/content/developerguide/building.md, docs-source/content/developerguide/requirements.md, docs-source/content/quickstart/create-domain.md, docs-source/content/quickstart/introduction.md, docs-source/content/reference/_index.md, docs-source/content/reference/domain-resource.md, docs-source/content/reference/javadoc.md, docs-source/content/reference/swagger.md, docs-source/content/release-notes.md, docs-source/content/samples/simple/ingress/_index.md, docs-source/content/security/_index.md, docs-source/content/userguide/_index.md, docs-source/content/userguide/managing-domains/_index.md, docs-source/content/userguide/managing-domains/accessing-the-domain/wlst.md, docs-source/content/userguide/managing-domains/domain-in-image/base-images/_index.md, docs-source/content/userguide/managing-domains/domain-lifecycle/_index.md, docs-source/content/userguide/managing-domains/domain-lifecycle/restarting.md, docs-source/content/userguide/managing-domains/domain-lifecycle/scaling.md, docs-source/content/userguide/managing-domains/domain-lifecycle/startup.md, docs-source/content/userguide/managing-domains/domain-resource.md, docs-source/content/userguide/managing-operators/_index.md, docs-source/content/userguide/managing-operators/using-the-operator/_index.md, docs-source/content/userguide/overview/k8s-setup.md, docs-source/content/userguide/overview/prepare.md
A complete review of all the pages; addressed input and reviewer's comments (as best possible); fixed whatever needed it. Whew.
=> revisions, edits, and fixes

.gitignore, docs-source/content/developerguide/documentation.md
This PR adds some initial documentation on how to write documentation.  
No tests - documentation only change.
=> add documentation on how to write documentation

docs-source/content/security/certificates.md, docs-source/content/userguide/introduction/introduction.md, docs-source/content/userguide/managing-domains/_index.md, docs-source/content/userguide/managing-operators/_index.md
Incorporating suggestions from the team.
=> fix some stuff

model/src/main/java/oracle/kubernetes/operator/LabelConstants.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/Main.java, operator/src/main/java/oracle/kubernetes/operator/ServiceWatcher.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/helpers/KubernetesServiceType.java, operator/src/main/java/oracle/kubernetes/operator/helpers/KubernetesUtils.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServerKubernetesObjects.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java, operator/src/main/java/oracle/kubernetes/operator/steps/ReadHealthStep.java, operator/src/main/java/oracle/kubernetes/operator/utils/WlsDomainConfigSupport.java, operator/src/main/java/oracle/kubernetes/operator/wlsconfig/UpdateDynamicClusterStep.java, operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/MainTest.java, operator/src/test/java/oracle/kubernetes/operator/ServiceWatcherTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesUtilsTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperDeletionTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTestBase.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServicePresenceTest.java
This resolves issue https://jira.oraclecorp.com/jira/browse/OWLS-72885
I have refactored access to the service fields in DomainPresenceInfo and ServerKubernetesObjects, so that now all accesses should go through ServiceHelper.
=> Cluster scaling

operator/src/main/java/oracle/kubernetes/operator/rest/RestBackendImpl.java, operator/src/test/java/oracle/kubernetes/operator/rest/RestBackendImplTest.java
Addresses https://jira.oraclecorp.com/jira/browse/OWLS-72764
=> use patching to scale clusters

docs-source/content/security/secrets.md
Updates the information about the secrets being used that was noted by Tom B.
=> Update documentation on Kubernetes secrets used by the operator

docs-source/content/userguide/managing-operators/using-the-operator/the-rest-api.md
Updated the Sample operator REST client script to reflect that the SSL certs and keys come from a secret.
=> OWLS-73008 SAMPLE OPERATOR REST CLIENT SCRIPT SHOULD BE UPDATED IN DOCUMENT

docs-source/content/userguide/managing-domains/configoverrides/_index.md
Reviewed develop branch, Hugo (docs-source) docs to make sure that they were up-to-date with those in the develop /site branch.
=> update to develop branch

README.md
This PR updates some issues in the main readme with bad links.
=> remove the weirdness that crept into the main readme

docs-source/content/quickstart/install.md
On the develop branch, updated the version number in the Quick Start install command from 2.0-rc2 to 2.0.1.
=> update version number, jenkins-ignore

docs-source/content/_index.md, docs-source/content/developerguide/backwards-compatibility.md, docs-source/content/developerguide/documentation.md, docs-source/content/faq/cannot-pull-image.md, docs-source/content/quickstart/get-images.md, docs-source/content/quickstart/prerequisites.md, docs-source/content/reference/domain-resource.md, docs-source/content/reference/javadoc.md, docs-source/content/reference/swagger.md, docs-source/content/release-notes.md, docs-source/content/userguide/introduction/architecture.md, docs-source/content/userguide/managing-domains/domain-lifecycle/restarting.md, docs-source/content/userguide/managing-operators/using-the-operator/the-rest-api.md, docs-source/content/userguide/managing-operators/using-the-operator/using-helm.md
Update operator version number to 2.1 in the docs. Release date and release notes are TBD.
Other minor doc edits.
=> update operator version number, jenkins-ignore

src/scripts/scaling/scalingAction.sh
Get WLDF scaling test to pass in jenkins by updating domain crd version in k8s rest api call in scalingAction.sh
Passed jenkins http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/1382/
=> WIP - OWLS-73066 - - WLDF SCALING IS NOT WORKING ON OPERATOR JENKINS RUN

site/v1.1/installation.md
Fix yet another "last" broken link in the archived docs.
=> fix link, jenkins-ignore

docs-source/content/userguide/cicd/_index.md, docs-source/content/userguide/cicd/how-to-copy-domains.md, docs-source/content/userguide/cicd/tools.md
A few very minor edits. Also, changed the Copy Domains title to line up with the others and left "How to copy domains" in the description; if you disagree with this change, I'll reverse it.
=> minor edits, jenkins-ignore

docs-source/content/reference/domain-resource.md, docs-source/content/userguide/introduction/introduction.md
Updated Kubernetes prerequisite version levels; also minor wording change
=> update K8s prereqs, jenkins-ignore

operator/src/main/java/oracle/kubernetes/operator/helpers/KubernetesVersion.java, operator/src/test/java/oracle/kubernetes/operator/helpers/VersionCheckTest.java
Exclude 1.10.*, which does not support CRD updates
=> update kubernetes versions

docs-source/content/developerguide/documentation.md, docs-source/content/userguide/introduction/introduction.md
For 2.2 release, update K8s min requirements, and OpenShift.
=> update K8s req; jenkins-ignore

integration-tests/USECASES.MD, integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java, integration-tests/src/test/java/oracle/kubernetes/operator/ITMultipleClusters.java, integration-tests/src/test/java/oracle/kubernetes/operator/ITOperator.java, integration-tests/src/test/resources/domain-home-on-pv/create-domain-two-configured-cluster.py, integration-tests/src/test/resources/domain-home-on-pv/create-domain-two-mixed-cluster.py
Adding Multiple clusters in domain controlled by operator.
1. testCreateDomainTwoConfiguredCluster - creates 2 configured cluster each having 2 managed servers
2. testCreateDomainTwoMixedCluster - creates a dynamic and a configured cluster
=> Multipleclustertests

docs-source/content/userguide/managing-domains/persistent-storage/_index.md
This edit fixes a minor mistake I made on this document's original review. Sorry Craig.
=> fix minor edit, jenkins-ignore

integration-tests/JRFUSECASES.MD, integration-tests/README.md, integration-tests/src/test/java/oracle/kubernetes/operator/JrfInOperatorTest.java
=> add JRFUSECASES.MD

docs-source/content/userguide/managing-domains/fmw-infra/_index.md
Some corrections that I found while working through the FMW infra sample.
=> Corrections to FMW sample documentation

integration-tests/src/test/java/oracle/kubernetes/operator/JrfInOperatorAdvancedTest.java, integration-tests/src/test/java/oracle/kubernetes/operator/JrfInOperatorTest.java, integration-tests/src/test/resources/domain-home-on-pv/create-jrfdomain-admin-port-enabled.py, integration-tests/src/test/resources/domain-home-on-pv/create-jrfdomain-auto-custom-sit-config.py, integration-tests/src/test/resources/jrfdomainonpvwlst.yaml
fix some test logic in jrf tests
=> update jrf tests

docs-source/content/quickstart/get-images.md
I edited this one file according to what I think needs to be changed for the relocation of WebLogic images to OCR. Please let me know if I am on the right track with the changed text, so I can fix the other mentions in the repo.
=> change image pull, jenkins-ignore

integration-tests/README.md, integration-tests/USECASES.MD, integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java, integration-tests/src/test/java/oracle/kubernetes/operator/ITPodsRestart.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java, integration-tests/src/test/resources/OperatorIT.properties, integration-tests/src/test/resources/domaininimagewdt.yaml, integration-tests/src/test/resources/domaininimagewlst.yaml, integration-tests/src/test/resources/setupenv.sh, src/integration-tests/kubernetes/command-job-template.yaml
Fix the integration tests to use OCR instead of docker store for WLS images.
=> Changes to integration tests to use OCR

docs-source/content/quickstart/prerequisites.md, docs-source/content/userguide/introduction/_index.md, docs-source/content/userguide/introduction/introduction.md
I revised some section titles and descriptions to help users more easily find the operator prerequisites. Please let me know if you have additional suggestions.
=> clarify prerequisites, jenkins-ignore

docs-source/content/quickstart/get-images.md
Minor update to a cross-reference in the Base Images doc (to better help users find the info for getting images from OCR).
=> minor x-ref update, jenkins-ignore

integration-tests/README.md, integration-tests/src/test/java/oracle/kubernetes/operator/utils/DBUtils.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/OracleDB.java, integration-tests/src/test/resources/jrfdomainadminonly.yaml, integration-tests/src/test/resources/jrfdomainonpvwlst.yaml, integration-tests/src/test/resources/jrfdomainonpvwlst2.yaml, integration-tests/src/test/resources/jrfdomainrecyclepolicy.yaml, integration-tests/src/test/resources/jrfdomainsampledefaults.yaml, integration-tests/src/test/resources/oracledb.properties, integration-tests/src/test/resources/setupenv.sh
Changed the fmw infra docker image to container-registry.oracle.com/middleware/fmw-infrastructure:12.2.1.3
updated the README.md
=> change jrf docker image to OCR

docs-source/content/samples/simple/domains/fmw-domain/_index.md, docs-source/content/userguide/managing-domains/domain-in-image/base-images/_index.md, docs-source/content/userguide/managing-domains/fmw-infra/_index.md, kubernetes/samples/scripts/create-fmw-infrastructure-domain/create-domain-inputs.yaml
Reviewed, edited, and added the updated FMW Infra doc and sample docs, that point to the new image location.
=> added FMW Infra docs, updated by Monica, jenkins-ignore

docs-source/content/userguide/managing-domains/fmw-infra/_index.md
Last doc changes for 2.2 release, except release date.
=> final cleanup of FMW doc, jenkins-ignore

docs-source/content/samples/simple/domains/fmw-domain/_index.md, docs-source/content/userguide/managing-domains/fmw-infra/_index.md
Added x-refs to obtaining the FMW image in two places. 
Also, removed a repeated section in the FMW Infra domains doc.
=> added x-refs to image, jenkins-ignore

docs-source/content/samples/simple/domains/fmw-domain/_index.md
Adding to the FMW domains sample to present all the information that users will need.
=> add more info to FMW domain sample, jenkins-ignore

integration-tests/README.md, integration-tests/USECASES.MD, integration-tests/pom.xml, integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java, integration-tests/src/test/java/oracle/kubernetes/operator/ITMonitoringExporter.java, integration-tests/src/test/java/oracle/kubernetes/operator/ITMultipleClusters.java, integration-tests/src/test/java/oracle/kubernetes/operator/ITOperator.java, integration-tests/src/test/java/oracle/kubernetes/operator/ITPodsRestart.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java, integration-tests/src/test/resources/OperatorIT.properties, integration-tests/src/test/resources/domaininimagewdt.yaml, integration-tests/src/test/resources/domaininimagewlst.yaml, integration-tests/src/test/resources/setupenv.sh, integration-tests/src/test/resources/wldf/wldf-policy.yaml
Fix the setupenv to use OCR to pull WLS images for shared cluster(external jenkins).
Also domain in image using WLST test will also be run in QUICKTEST.
=> Fix integration tests running in external Jenkins OCI env

docs-source/content/userguide/managing-domains/domain-lifecycle/scaling.md
In response to Bug 29725640 - RBAC POLICY SHOULD BE CORRECTED ON DOCS FOR WLDF SCALING TO WORK, I updated the RBAC policy example in the scaling doc.
=> update RBAC policy example, jenkins-ignore

src/integration-tests/introspector/introspectTest.sh, src/integration-tests/introspector/wl-create-domain-pod.pyt
- use a different mysql driver
- retry cleanup if it fails
=> minor test fixes

integration-tests/src/test/java/oracle/kubernetes/operator/ITMonitoringExporter.java
fixed path for samples from exporter GitHub project
=> fixed path for exporter github project

operator/src/main/resources/scripts/introspectDomain.py
We discovered that when a domain is restarted following an edit of configuration using the console, that the introspector script would sometimes fail reading beans that were no longer present.
This change wraps those bean lookups in a function that handles the exceptions better.
=> Resolve failure in introspection following a console edit

docs-source/content/_index.md
Updated the main README with the current release date and number.
=> fix release date and number, jenkins-ignore

integration-tests/USECASES.MD, integration-tests/src/test/java/oracle/kubernetes/operator/ITOperator.java, integration-tests/src/test/java/oracle/kubernetes/operator/ITPodsRestart.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java
adding test for precreateService attribute in existing test - testDomainOnPVUsingWLST which is a QUICKTEST.
And some code refactoring.
=> adding test for precreateService attribute

docs-source/content/quickstart/get-images.md, docs-source/content/quickstart/install.md, docs-source/content/userguide/introduction/architecture.md, docs-source/content/userguide/managing-domains/domain-lifecycle/restarting.md, docs-source/content/userguide/managing-operators/using-the-operator/using-helm.md
Yikes. No excuses. Thanks Craig.
=> update docs to operator v2.2.1

site/README.md, site/v2.1/README.md, site/v2.2.0/README.md
I assume this can also be merged to master.
=> README wording update

docs-source/content/_index.md, docs-source/content/quickstart/create-domain.md, docs-source/content/quickstart/get-images.md, docs-source/content/samples/simple/domains/domain-home-in-image/_index.md, docs-source/content/samples/simple/domains/domain-home-on-pv/_index.md, docs-source/content/samples/simple/domains/fmw-domain/_index.md, docs-source/content/userguide/managing-domains/domain-in-image/base-images/_index.md, docs-source/content/userguide/managing-domains/fmw-infra/_index.md
Incorporate suggestions from Russ, make other improvements, and edit some existing docs.
=> Improve Quick Start

docs-source/content/userguide/managing-operators/using-the-operator/using-helm.md
Update the user guide to describe how to use helm to enable debugging
=> document operator debugging

operator/pom.xml, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/KubernetesUtils.java, operator/src/test/java/oracle/kubernetes/LogMatcher.java, operator/src/test/java/oracle/kubernetes/TestUtils.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTestSetup.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectionLoggingTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectionStatusTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java
Initial domain status updating:
- any severe error logged by the introspector
- a failure to pull an image
=> Update domain status for image fetch or instrospector job failures

integration-tests/src/test/resources/setupenv.sh
pull base image for domain home in image tests
=> docker login to OCR

kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/wdt/wdt_model_configured.yaml, kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/wdt/wdt_model_dynamic.yaml
Added RCUDbInfo  to model file 
RCUDbInfo:
rcu_prefix : '@@PROP:rcuSchemaPrefix@@'
rcu_schema_password : Oradoc_db1
rcu_admin_password : Oradoc_db1
rcu_db_conn_string : '@@PROP:rcuDatabaseURL@@'
=> Modified the wdt model file to include RCUDbInfo

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh
download wdt in loop as sometimes its failing with 
curl: (5) Could not resolve proxy: www-proxy-hqdc.us.oracle.com; Name or service not known
=> try wdt download in loop

integration-tests/src/test/java/oracle/kubernetes/operator/ItPodsRestart.java
This is to comment out the failing Image test of ItPodsRestart
=> PR: owls-76364 comment out the failing test

integration-tests/src/test/java/oracle/kubernetes/operator/ItElasticLogging.java
=> added check to make sure downloading of wls logging exporter jar files completed

kubernetes/samples/scripts/common/utility.sh
=> one odd character

operator/pom.xml, swagger/pom.xml
I think I have it this time :)
Might be best to wait for the Jenkins job to be sure: http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2377/
=> fix missing dependencies

kubernetes/samples/scripts/terraform/README.md, kubernetes/samples/scripts/terraform/oke.create.sh
added the ability properly process the property file with commented out values, fixed typo in the README.md for terraform
=> added the ability properly process the property file with commented out values, fixed typo

operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/ServerConfigurator.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/BaseConfiguration.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCommonConfigurator.java, operator/src/test/java/oracle/kubernetes/operator/helpers/AdminPodHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
Passes jenkins http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2560/testReport/
=> OWLS-76720 (Resolves #1198) - Fixes missing valueFrom envVar values

integration-tests/pom.xml, integration-tests/src/test/java/oracle/kubernetes/operator/ItCoherenceTests.java, integration-tests/src/test/java/oracle/kubernetes/operator/ItOperatorUpgrade.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Operator.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java
fix coherence and operator upgrade tests which are failing intermittently when ran in parallel
=> fix coherence and operator upgrade tests

integration-tests/src/test/java/oracle/kubernetes/operator/JrfDomainOnPvWlst.java
Jenkins run: http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/2945/
=> initial compilation error fix

integration-tests/README.md, integration-tests/pom.xml, integration-tests/src/test/java/oracle/kubernetes/operator/ItOperatorUpgrade.java, integration-tests/src/test/resources/statedump.sh
quick test passed using both seq and parallel -
http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/2938/
http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/2937/
=> switch between seq or parallel runs using var

integration-tests/pom.xml, integration-tests/src/test/java/oracle/kubernetes/operator/ItJrfDomainOnPvWlst.java
Internal Jenkins job works as expected as
wls-integration-tests: http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/3109/
wls-jrf-integration-tests: http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/3110/
jrf-integration-tests: http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/3119/
external Jenkins:
wls-integration-tests: http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/672/
=> PR: Owls76920 change JRF domain class name starting with It

integration-tests/src/test/java/oracle/kubernetes/operator/ItElasticLogging.java
Jenkins job below kicked off
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3177/
=> Fixed a hanging issue jenkins-ignore

integration-tests/src/test/java/oracle/kubernetes/operator/ItElasticLogging.java
6 Jenkins jobs kicked off, 5 failed with issue either a pure parallel run issue or env setting issue. None of them were caused by ItElasticLogging
One job passed:
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3298/consoleFull
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 971.779 s - in oracle.kubernetes.operator.ItElasticLogging
=> Fixed issues running in parallel jenkins-ignore

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh
If the user changes the domain directory property, the directory may not exist.
=> Create domain sample on PV - ensure domain directory exists

docs-source/content/userguide/managing-domains/configoverrides/_index.md
Implements internal JIRA OWLS-77730
=> Update sit-cfg doc to note when _not_ to change external ports

integration-tests/src/test/java/oracle/kubernetes/operator/ItPodsShutdown.java
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3508/ and http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3507/ clean
=> added more checks for web app  readiness

integration-tests/src/test/java/oracle/kubernetes/operator/ItElasticLogging.java
the test passed ib both 3391 and 3392.
=> Added request-timeout jenkins-ignore

kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/create-domain.sh, kubernetes/samples/scripts/create-soa-domain/domain-home-on-pv/create-domain.sh, kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain.sh
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3679/
=> OWLS-78571 (Resolves #1252) - Config map not updated with new files on second run of create-domain.sh

kubernetes/samples/scripts/create-oracle-db-service/common/checkDbState.sh
External Jenkins quick test passed at: 821, 822, 823, 824, 825.
2 Full test: 826, 827 have other tests failure but JRF test passed with DB connection issue.
=> PR: fix DB connection issue on external Jenkins

kubernetes/samples/scripts/create-rcu-schema/create-rcu-schema.sh
Internal Jenkins passed at: 3877, 3878
External Jenkins failed at: 844, 845 but RCU creation passed with this fix.
=> PR: Fix the latest FMW image regarding RCU creation sample script

integration-tests/src/test/java/oracle/kubernetes/operator/ItMonitoringExporter.java, integration-tests/src/test/resources/exporter/createPromGrafanaMySqlCoordWebhook.sh
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3944 -internal Jen passed for MonExp
http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/872/ - external Jen passed
=> deleted debug commands 

operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdaterTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java
Watches for a status patch failure and retries by re-reading the domain and recomputing the patch.
=> When patching fails, re-read the domain and recompute the patch

integration-tests/src/test/java/oracle/kubernetes/operator/ItMonitoringExporter.java, integration-tests/src/test/resources/exporter/createPromGrafanaMySqlCoordWebhook.sh
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3982/ clean for MonExp
http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/893/ - external Jenkins clean
=> made conditional to create imagepull secret

integration-tests/src/test/java/oracle/kubernetes/operator/ItCoherenceTests.java, integration-tests/src/test/java/oracle/kubernetes/operator/ItDomainInImage.java, integration-tests/src/test/java/oracle/kubernetes/operator/ItManagedCoherence.java, integration-tests/src/test/java/oracle/kubernetes/operator/ItMultipleClusters.java, integration-tests/src/test/java/oracle/kubernetes/operator/ItOperatorUpgrade.java, integration-tests/src/test/java/oracle/kubernetes/operator/SitConfig.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
delete the domain in image created for the test at the end of the test
=> delete the domain in image created for the test

kubernetes/charts/weblogic-operator/templates/_operator-clusterrole-general.tpl
Remove permissions to cluster-level resources.
=> Fix an issue on OpenShift4

docs-source/content/userguide/managing-domains/domain-in-image/base-images/_index.md
New instructions for "Creating a custom image with patches applied."
=> create image with Image Tool

operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java, operator/src/main/java/oracle/kubernetes/operator/utils/Certificates.java, operator/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/utils/CertificatesTest.java
Add unit test, switched log message level and used a message key
=> Change log to INFO and omit stack trace

docs-source/content/faq/boot-identity-not-valid.md, docs-source/content/faq/cannot-pull-image.md, docs-source/content/faq/domain-secret-mismatch.md, docs-source/content/faq/external-clients.md, docs-source/content/faq/namespace-management.md, docs-source/content/faq/oci-fss-pv.md, docs-source/content/faq/oci-lb.md, docs-source/content/faq/volumes.md
Minor edits mostly to bring FAQ into alignment with operator style guidelines.
=> style edits

integration-tests/src/test/java/oracle/kubernetes/operator/ItMonitoringExporter.java, kubernetes/samples/charts/util/setup.sh
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1063/ passed for MonExporter
=> OWLS-80189, added support for helm3 in MonExp test

integration-tests/README.md, integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java, integration-tests/src/test/resources/OperatorIT.properties, integration-tests/src/test/resources/statedump.sh
quick test is clean on external jenkins - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1091/
=> Fix pod log generation in tests and add env var for max iterations

docs-source/content/faq/coherence-requirements.md
This PR adds more details about how to persist the iptables nat chain updates across reboots.
=> Improve the coherence requirements faq - re iptables

docs-source/content/userguide/managing-domains/model-in-image/debugging.md, docs-source/content/userguide/managing-domains/model-in-image/model-files.md, docs-source/content/userguide/managing-domains/model-in-image/overview.md, docs-source/content/userguide/managing-domains/model-in-image/reusing-rcu.md, docs-source/content/userguide/managing-domains/model-in-image/runtime-updates.md, docs-source/content/userguide/managing-domains/model-in-image/usage.md
Finished first pass edits to the user docs. Only one snafu I couldn't overcome. I was able to get the links in the Usage doc to go to the correct (numbered) sections, but I couldn't get two cross-references (one in Reusing an RCU database and one in Overview) that go to the "Prerequisites for JRF domain types" section to work.
=> first pass edits

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java, integration-tests/src/test/java/oracle/kubernetes/operator/ItOperator.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Operator.java
Clean full test run on external jenkins - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1192/
=> Save operator log before restarting operator in the test

integration-tests/src/test/resources/imagetool/build_download.sh
new fix release for Image Tool
=> Update Image Tool release number

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/InstallParams.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Installer.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WITParams.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WebLogicImageTool.java
Add actions for installer and WebLogicImageTool operations. The review goal is to make sure that style and interface is okay. The full impl will be added once the interface/style is in agreement.
=> Install wit actions interface

new-integration-tests/pom.xml, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleDomainValidation.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/ConfigMap.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Namespace.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/PersistentVolume.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/PersistentVolumeClaim.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Secret.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java
PR for feedback to validate usage of Kubernetes client API is correct and that I'm on the same page as everyone else on direction.
=> K8s client api initial impl for feedback on usage

operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/modelInImage.sh, operator/src/main/resources/scripts/startServer.sh, operator/src/main/resources/scripts/wdt_create_filter.py
Various fixes in shell script for model-in-image PR1478
=> Model in image namefixes

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleDomainValidation.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleOperatorValidation.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Domain.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Operator.java
Added assertion implementation for domain pods and services
=> Implemented the pod and service check assertions

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleOperatorValidation.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Operator.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/OperatorParams.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Traefik.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/TraefikParams.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Helm.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/HelmParams.java
Adding HelmParams class
OperatorParams, TraefikParams extend HelmParams
Implementation added in Helm class for install, upgrade, delete methods.
Operator, Traefik extend Helm now.
ItSimpleOperatorValidation - installs operator and verifies operator pod is running
=> adding helm implementation

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWITValidation.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/ActionConstants.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Command.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/CommandParams.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WITParams.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WebLogicImageTool.java
Add support to specifying additional env variables to command execution.
=> Add additional env to WIT execution

integration-tests/src/test/java/oracle/kubernetes/operator/ItModelInImageConfigUpdate.java, integration-tests/src/test/java/oracle/kubernetes/operator/MiiBaseTest.java
local run success and 5 test cases passed:
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3,210.989 s - in oracle.kubernetes.operator.ItModelInImageConfigUpdate
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Build Tools 1.0 .................................... SUCCESS [  1.189 s]
[INFO] weblogic-kubernetes-operator 3.0.0 ................. SUCCESS [  2.683 s]
[INFO] operator-swagger 3.0.0 ............................. SUCCESS [  7.367 s]
[INFO] json-schema 3.0.0 .................................. SUCCESS [  9.130 s]
[INFO] jsonschema-maven-plugin Maven Mojo 3.0.0 ........... SUCCESS [  8.207 s] …
=> Added two more tests to cover config update by creating an image w a new tag 

integration-tests/pom.xml
so that messages appear on one line
=> Fix the log format

integration-tests/src/test/java/oracle/kubernetes/operator/ItSitConfigDomainInImage.java, integration-tests/src/test/java/oracle/kubernetes/operator/ItSitConfigDomainInPV.java, integration-tests/src/test/java/oracle/kubernetes/operator/SitConfig.java, integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
Note: I don't have any of the multi node clusters free to test the change, will test on internal jenkins(single node) for now.
=> delete image only for domain in image tests

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleDomainValidation.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleOperatorValidation.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWITValidation.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Command.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Helm.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WebLogicImageTool.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/LoggedTest.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/Timing.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/logging/LoggingFacade.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/logging/LoggingFactory.java, new-integration-tests/src/test/resources/OperatorIntegrationTests.properties
Adding copy of facade from main code line.  Logging should be the same(similar) in both integration tests as main line.
=> Replace java.util.Logger with logging facade

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java, integration-tests/src/test/java/oracle/kubernetes/operator/MiiBaseTest.java
Started run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-integration-test-cluster-5/150/
=> use same image name but different tags for a it class

integration-tests/src/test/java/oracle/kubernetes/operator/ItModelInImageConfigUpdate.java
charry-pick the commit in https://github.com/oracle/weblogic-kubernetes-operator/pull/1566
=> WIP: Changes to push new image to Docker repo jenkins-ignore

operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java, operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java, operator/src/main/resources/Operator.properties
Add log for introspector job creation time
=> Add log for introspector job creation time

operator/src/main/resources/scripts/encryption_util.py, operator/src/main/resources/scripts/modelInImage.sh
This is for JIRA OWLS-81217.  When the runtime encryption secret is changed after creation and thenapplying update,  The introspector job failed and only shows the underlying text error message from the java crypto api
=> Errormsg 81217

docs-source/content/_index.md
Added a link to the tutorial and rearranged some sections on the Home page.
=> edit home page

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/IntegrationTestWatcher.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingUtil.java
Added changes to copy files from persistent volume used by the tests to a local file system.
=> Add support in diagnostic logging to archive PV

kubernetes/samples/scripts/create-rcu-schema/README.md, kubernetes/samples/scripts/create-rcu-schema/common/createRepository.sh, kubernetes/samples/scripts/create-rcu-schema/common/dropRepository.sh, kubernetes/samples/scripts/create-rcu-schema/common/template/rcu.yaml.template, kubernetes/samples/scripts/create-rcu-schema/create-rcu-schema.sh, kubernetes/samples/scripts/create-rcu-schema/drop-rcu-schema.sh
Hi @markxnelson @rjeberhard @mriccell @rdas0405,
This PR has fixes for #1610 -  
- Support for namespace
- Fix for image pull secret
- Support for sys and schema passwords
- Use output dir for creating rcu.yaml based on the template rather updating existing common/rcu.yaml directly
- Created "common/template/rcu.yaml.template" with imagePullPolicy as IfNotPresent.
- Use sys user instead of demo user scott which may not be available in all Database for connectivity check.
- Update README.md with latest changes
Please review and approve these changes.
Thanks,
Asha
=> Fix for issue 1610 in create-rcu-schema scripts

json-schema/src/main/java/oracle/kubernetes/json/SchemaGenerator.java, kubernetes/crd/domain-crd.yaml, kubernetes/crd/domain-v1beta1-crd.yaml
Change schema generator to support map type object
=> Fix missing custom labels and annotations specified in domain resource

docs-source/content/quickstart/get-images.md, docs-source/content/samples/simple/domains/model-in-image/_index.md
Fix some issues tom found in the docs post rc1 release
=> fix branch and image in mii sample/quickstart

docs-source/content/userguide/managing-domains/_index.md, operator/src/main/resources/scripts/introspectDomain.py
… plus other minor changes to introspector.
=> Improve introspector 'mixed cluster' error messages... 

kubernetes/samples/scripts/create-weblogic-domain/model-in-image/utils/wl-pod-wait.sh
Pani found this bug - thanks Pani!
=> fix hard coded ns in MII sample wl-pod-wait.sh helper script

operator/src/main/resources/scripts/introspectDomain.sh
This add the unzip command check to the MII image,  the container-registry image already have unzip but there may be a version at one point where the unzip is missing.  unzip was not used until we added wdt version check.
=> Add check for unzip

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDomainOnPV.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
Doing a null check instead of calling isEmpty since its not a Optional instance.
=> Null check the KIND_REPO

docs-source/content/samples/simple/domains/model-in-image/_index.md
Did a careful second pass literary edit on the entire sample doc. Aligned new sections to the original ones (initial use case and update1). Also, fixed/cleaned up some of the original wording.
=> second pass edit

kubernetes/samples/scripts/create-weblogic-domain/model-in-image/model-images/model-in-image__JRF-v1/model.10.yaml, kubernetes/samples/scripts/create-weblogic-domain/model-in-image/model-images/model-in-image__JRF-v2/model.10.yaml
Maggie - Please test this fix.
=> Mii sample jrf fix

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/BuildApplication.java, new-integration-tests/src/test/resources/bash-scripts/build_application.sh
Added utility to build applications using a WebLogic image container.
The applications can be built using 
BuildApplication.buildApplication(
Path application, 
Map<String,String> sysprops,      
String targets, 
String namespace);
=> Support for building appplications

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDomainInPV.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/ActionConstants.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Secret.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CleanupUtil.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DeployUtil.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OracleHttpClient.java, new-integration-tests/src/test/resources/python-scripts/application_deployment.py
- Adding deployment util to deploy applications to domain
- Adding a Java based HttpClient
- Fixed the Cleanup util to delete persistent volume claims before persistent volumes
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-model-in-image-tests/803/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/235/
=> Adding deployment util and Java HttpClient

kubernetes/samples/scripts/common/utility.sh, kubernetes/samples/scripts/create-oracle-db-service/README.md, kubernetes/samples/scripts/create-oracle-db-service/start-db-service.sh
(1) Add option to skip deploying node-port
(2) Add verification k8s service deploy succeeded.
=> Oracle DB Sample updates

docs-source/content/userguide/introduction/demo.md
Set draft to true, which hides the page.
=> hide demo video

docs-source/content/userguide/managing-operators/installation/_index.md
As per OWLS-82389 DOCUMENTATION FOR WEBLOGIC-OPERATOR UPGRADE PROCEDURE, added procedure for upgrading the operator.
=> doc operator upgrade

docs-source/content/samples/simple/domains/model-in-image/_index.md
Note this change is for master & 3.0.0-rc1 only (do not merge into develop)
=> MII sample doc update.

docs-source/content/faq/_index.md, docs-source/content/faq/boot-identity-not-valid.md, docs-source/content/faq/cannot-pull-image.md, docs-source/content/faq/coherence-requirements.md, docs-source/content/faq/configmaps.md, docs-source/content/faq/domain-secret-mismatch.md, docs-source/content/faq/external-clients.md, docs-source/content/faq/fan.md, docs-source/content/faq/namespace-management.md, docs-source/content/faq/node-heating.md, docs-source/content/faq/oci-fss-pv.md, docs-source/content/faq/oci-lb.md, docs-source/content/faq/volumes.md
Added headings and brief descriptions to the FAQ index page because the entry list has gotten so long.
=> add headings to FAQ index page

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInImage.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInPV.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMiiDomain.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAddCluster.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiIstioDomain.java, new-integration-tests/src/test/resources/bash-scripts/install-istio.sh
Test case added to  verify ISTIO configuration  in 
a) Model In Image  
b) Domain Home On PV 
Additionally  (a) optimized the usage of utility methods  in the Test Classes instead of creating locally (b) modified istio installation scripts to to do some additional check to ensure proper installation.
Multi Node Cluster Jenkin
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-model-in-image-tests/1134
Kind Cluster 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/664
=> Istio Configuration in MII Model and DomainHomeOnPV model 

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItJrfDomainInPV.java
After merging with develop branch that includes Vanaja's parallel PR #1791, this fix passed on kind cluster 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/679/testReport/
=> Fix Db port conflict for parallel run 

new-integration-tests/pom.xml, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiSample.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/ActionConstants.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/InstallParams.java, new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Installer.java
Make the download location more generic, and expose more download parameters via environment variables.
=> Make it easier to parameterize WDT/WIT download url

docs-source/content/quickstart/get-images.md, docs-source/content/userguide/managing-domains/domain-lifecycle/introspection.md, docs-source/content/userguide/managing-domains/ingress/_index.md
Update Traefik version to 2.2.1. as per OWLS-83509:Update documentation to declare support Traefik v 2.1.1 and change our Quick Start Sample
=> update Traefik version to 2.2.1.

docs-source/content/userguide/managing-operators/installation/_index.md
Vanity fix for the Upgrade section. Looks better now.
=> fix upgrade note

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCoherenceTests.java
Disabled ItCoherenceTests. Jira OWLS-83996 to triage an d fix the intermittent failures
=> Disable ItCoherenceTests, it fails on nightly intermittently

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
Fix NullPointerException in oracle.weblogic.kubernetes.assertions.impl.Kubernetes.isPodReady
Jenkins test result:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1143/
=> Fix NullPointerException in isPodReady method

docs-source/content/userguide/managing-domains/domain-resource.md, docs-source/content/userguide/managing-domains/model-in-image/usage.md
Typos in Domain Resource, however, be aware that WDT docs have been re-organized. @tbarnes-us, please check (I found only one broken link).
=> fix broken links

docs-source/content/samples/simple/ingress/_index.md, docs-source/content/userguide/managing-domains/ingress/_index.md
OWLS-84564: Correct Ingress documentation to correctly reflect Ingress support, as per Monica's request.
=> Correct Ingress documentation

kubernetes/charts/weblogic-operator/values.yaml
Added documentation for nodeSelector and affinity in values.yaml.
Due to a bad merge (presumably), we had two javaLoggingLevel entries, so deleted the second.
=> Document nodeSelector and affinity in values.yaml

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
see https://jira.oraclecorp.com/jira/browse/OWLS-84676
jerking results  https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2124/
=> OWLS-84676, added synchronized to execCommand to fix intermittent failures

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItUsabilityOperatorHelmChart.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2149/
=> fixed cleanup order to uninstall operator before cleaning sa to fix intermittent failures

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorUpgrade.java
Upgrade Tests on Jenkin
https://build.weblogick8s.org:8443/job/wko-kind-nightly-upgrade/54/
=> Added Upgrade Test from Release 3.0.2

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java
1. Change only to increase introspectJobFailureCount for introspect job failure only.
2. Move reset counter to the proper place if user fix the problem within the retry cycle.
=> Fix retry regression

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/ActionConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/ImageBuilders.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
Adding test to verify image update for WLS domain.
Kind new parallel test result 9/30
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2195/testReport/
=> Adding test to verify image update for WLS domain 

docs-source/content/quickstart/prerequisites.md, docs-source/content/security/service-accounts.md, docs-source/content/userguide/managing-operators/_index.md, docs-source/content/userguide/managing-operators/using-the-operator/using-helm.md
And amend cross-refs to https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-operators/#install-helm-and-tiller
=> remove Tiller

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2216
=> OWLS-84865, added extra cleanup for grafana 

operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/modelInImage.sh, src/integration-tests/bash/show_merged_model.sh
While waiting for cgbu to return to test it, I created this first.
=> Reduce jrfmii map size

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DbUtils.java
The Jenkins run passed at the following jobs:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2618/testReport/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2619/testReport/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2620/testReport/
=> Fix intermittent Oracle service conflict issue 

integration-tests/src/test/resources/bash-scripts/install-istio.sh
Based on Russ's review comment modified the istio installation scripts to eliminate intermittent installation issue
All integration suites including Istio suite passed 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2799/
=> modify istio installation script

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
Added tests to verify operator Domain Home In Image samples in integration tests
All 4 tests in ItSample.java passed on Jenkins
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2814/
Passed Jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2849
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2850
=> Added automations to verify domain in image samples using wlst and wdt

README.md, buildDockerImage.sh, docs-source/content/_index.md, docs-source/content/faq/namespace-management.md, docs-source/content/release-notes.md, docs-source/content/userguide/managing-domains/domain-lifecycle/restarting.md
Just a placeholder guess on the 3.1.0 release date. Updates for release notes, including descriptions of changes. I'll add the other changes as we commit them (OpenShift Dockerfile change, stuck Terminating pod fix, etc.)
=> Release note updates

operator/src/main/java/oracle/kubernetes/operator/Main.java, operator/src/main/java/oracle/kubernetes/operator/StuckPodProcessing.java, operator/src/main/java/oracle/kubernetes/operator/TuningParameters.java, operator/src/main/java/oracle/kubernetes/operator/TuningParametersImpl.java, operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java, operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java, operator/src/main/java/oracle/kubernetes/utils/SystemClock.java, operator/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/NamespaceTest.java, operator/src/test/java/oracle/kubernetes/operator/StuckPodTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/TuningParametersStub.java, operator/src/test/java/oracle/kubernetes/utils/SystemClockTestSupport.java
This backports the fix to 3.0.3
=> Detect and delete stuck pods

operator/src/main/java/oracle/kubernetes/operator/rest/resource/ClustersResource.java, operator/src/main/java/oracle/kubernetes/operator/rest/resource/DomainsResource.java, operator/src/main/java/oracle/kubernetes/operator/rest/resource/VersionsResource.java
Removed `entering` and `exiting` log messages that were flagged as issues (log forging) in Fortify scan.
=> Owls-62364 - Fix log forging issues found by Fortify

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
For  merging into dynamicupdate branch
Minor update to ItMiiDynamicUpdate test to also verify that servers did not roll during the dynamic update.
=> Add assertion to ItMiiDynamicUpdate test

integration-tests/pom.xml
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/71/
=> Added maven profile to run a set of integration tests for oke certification

src/integration-tests/model-in-image/run-test.sh, src/integration-tests/model-in-image/util-misc.sh
Extend the MII sample's 'update4' test to ensure there was no roll, and extend MII sample testing in general to add more tracing for pod state at each stage.  This completes the work for:
-  owls-85459/owls-85469, change password, verify no roll and that DB can be accessed
-  owls-85463, change connection pool property (pool size) without a roll
The full MII sample integration testing of a DS change is called when a database is available - which is only in the JRF path of the automated integration tests.  The WLS path in the integration testing skips fully testing the DS, but you can 'manually' test by running the tests stand-alone with the '-db' parameter (or '-assume-db' if the DB is already running).
=> MII dynamic update data source testing

operator/src/main/resources/scripts/modelInImage.sh, operator/src/main/resources/scripts/startServer.sh
This fix is for wdt archive and model containing domainLibraries which is not correctly handled in MII.
=> Fix domain lib

docs-source/content/userguide/istio/istio.md
Document - Istio 1.7.x and 1.6.x limitation.
=> doc Istio limitation

docs-source/content/userguide/managing-domains/domain-resource.md, docs-source/content/userguide/managing-domains/model-in-image/model-files.md, docs-source/content/userguide/managing-domains/model-in-image/usage.md
Document MII 'model home' setting.
=> Mii doc update

Dockerfile
Add labels conforming to https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys and overriding the values set in the base label.
Also made a small change to consolidate the ENV statements into a single statement.
=> Add labels to Dockerfile

build-tools/fortify/Filter_SecComply.txt
Add the official Fortify scan filter to reduce spurious complaints.
Results of scan shows many fewer issues. http://wls-jenkins.us.oracle.com/job/WKO_Fortify/5/WKO.pdf
=> Add Fortify configuration

json-schema/pom.xml, json-schema/src/test/java/oracle/kubernetes/json/KubernetesApiNamesTest.java, json-schema/src/test/java/oracle/kubernetes/json/SchemaGeneratorTest.java, json-schema/src/test/java/oracle/kubernetes/json/YamlDocGeneratorTest.java, kubernetes/pom.xml, kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorGeneratedFilesTestBase.java, kubernetes/src/test/java/oracle/kubernetes/operator/helm/CreateOperatorGeneratedFilesDebugEnabledIT.java, kubernetes/src/test/java/oracle/kubernetes/operator/helm/CreateOperatorGeneratedFilesOptionalFeaturesDisabledIT.java, kubernetes/src/test/java/oracle/kubernetes/operator/helm/CreateOperatorGeneratedFilesOptionalFeaturesEnabledIT.java, kubernetes/src/test/java/oracle/kubernetes/operator/helm/CreateOperatorInputsValidationIt.java, kubernetes/src/test/java/oracle/kubernetes/operator/helm/HelmOperatorValuesTest.java, kubernetes/src/test/java/oracle/kubernetes/operator/helm/OperatorChartIt.java, operator-build-maven-plugin/pom.xml, operator-build-maven-plugin/src/test/java/oracle/kubernetes/json/mojo/JsonSchemaMojoTest.java, operator-build-maven-plugin/src/test/java/oracle/kubernetes/mojo/shunit2/AnsiUtilsTest.java, operator-build-maven-plugin/src/test/java/oracle/kubernetes/mojo/shunit2/ShUnit2MojoTest.java, operator-build-maven-plugin/src/test/java/oracle/kubernetes/mojosupport/MojoTestBase.java, operator/pom.xml, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainTopologyTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/HealthCheckHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/rest/RestTest.java, pom.xml
Converted remaining unit tests to JUnit 5
Removed dependency on vintage library that allowed JUnit 4 tests to run.
=> Complete transition to JUnit 5

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
Fix IntrospectVersion test failure.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3758/
=> remove the assert for response code and wait until HTTP response 200 to check servers

docs-source/content/userguide/managing-domains/configoverrides/_index.md
Minor updates to the debugging section of the config override doc.
=> Config override doc update

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItUsabilityOperatorHelmChart.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4077/
=> fixed error msg to adapt helm 3.1.4 restrictions

docs-source/content/quickstart/create-domain.md
=> minor edit

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java
Jenkins results:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4126/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4129/
=> fix NPE in listNamespacedEvents method

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java
Add a new WorkManager test to MII domain with Dynamic Update enabled
Jenkin Run 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4167  
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4168
=> Add istio dynamic update test

kubernetes/samples/scripts/domain-lifecycle/README.md, kubernetes/samples/scripts/domain-lifecycle/clusterStatus.sh, kubernetes/samples/scripts/domain-lifecycle/helper.sh
OWLS-87876 - The cluster status script to view the domain resource cluster status of any WebLogic cluster. This script is a companion to the `scaleCluster.sh` script and is part of the domain lifecycle scripts.
=> OWLS-87876 - Cluster status script to view the domain resource cluster status of any WebLogic cluster.

docs-source/content/_index.md
Feel free to edit/tweak/make suggestions about the sentence wording; I wasn't 100% sure about how to describe the portal.
=> add Oracle support

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicClusterMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicDomainInImage.java, integration-tests/src/test/resources/wdt-models/model-fmw-dynamicdomain.yaml
Added FMW Integration test with Dynamic Cluster using MII
Jenkin Result
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4187 (parallel)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4196 (sequential)
=> Added FMW Integration test with Dynamic Cluster using MII

docs-source/content/userguide/managing-domains/model-in-image/usage.md
(The old wording predated the sample rewrite, which used to have a YAML template file.)
This merge is for master, please also merge it into develop...
=> Minor MII usage doc fix

operator/src/main/java/oracle/kubernetes/operator/http/HttpAsyncRequestStep.java, operator/src/main/java/oracle/kubernetes/operator/http/TrustAllX509ExtendedTrustManager.java
Creating as a draft for visibility to @russgold and @doxiao.
=> Trust all certificates when connecting to the management REST interface from the operator

documentation/3.2/content/userguide/managing-domains/domain-resource.md, documentation/domains/Domain.json, documentation/domains/Domain.md, documentation/staging/content/userguide/managing-domains/domain-resource.md, kubernetes/crd/domain-crd.yaml, kubernetes/crd/domain-v1beta1-crd.yaml, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/AdminServer.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/AdminService.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/BaseConfiguration.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerService.java
=> Clarify distinction between adminServer adminService and serverService

documentation/3.2/content/userguide/managing-domains/domain-lifecycle/introspection.md, documentation/3.2/content/userguide/managing-domains/model-in-image/runtime-updates.md, documentation/3.2/content/userguide/managing-operators/installation/_index.md, documentation/staging/content/userguide/managing-domains/domain-lifecycle/introspection.md, documentation/staging/content/userguide/managing-domains/model-in-image/runtime-updates.md, documentation/staging/content/userguide/managing-operators/installation/_index.md
Lightly cleanup/expand introspection discussion in the domain life-cycle doc, plus reference introspection related helper scripts from MII introspection related doc.
=> Minor lc doc updates

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WebLogicImageTool.java, operator/integration-tests/model-in-image/mii-sample-wrapper/build-model-image.sh
Parallel test:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4584/testReport/
All FMW related tests including tests in ItMiiSample  passed. Only one failure: racle.weblogic.kubernetes.ItMiiDynamicUpdate.testMiiRemoveTarget
Another earlier Jenkins job: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4581/testReport/
All FMW related tests passed also
=> Accommodate FMW image change chown=oracle:root 

operator/scripts/scaling/scalingAction.sh
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4751/testReport/oracle.weblogic.kubernetes/
=> Update scalingAction.sh to work with python 3.9.4

documentation/staging/content/_index.md, documentation/staging/content/developerguide/branching.md, documentation/staging/content/developerguide/contributing.md, documentation/staging/content/developerguide/documentation.md, documentation/staging/content/faq/namespace-management.md, documentation/staging/content/faq/newbie.md, documentation/staging/content/userguide/managing-domains/domain-lifecycle/scaling.md
Working with @tbarnes-us to update and improve WKO docs. First pass at Home page, add contributing info to the Developer Guide, and added FAQ from the wiki to the doc FAQ (Answers to commonly asked newcomer questions).
=> Doc enhancements

documentation/staging/content/faq/newbie.md
Removed XA transaction Q and A, as per Monica's request.
=> remove XA ref

kubernetes/samples/scripts/common/utility.sh
enabling server pod resources and also fix indents in the resources section.
=> add resources to Server Pods

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiSample.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/OperatorParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, operator/integration-tests/model-in-image/run-test.sh
Jenkins Results - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5404/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5403/ (full suite, still running)
=> Add tests to verify MII sample using common mount in WLS and FMW domains

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMonitoringExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/IstioUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MonitoringUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5424/
=> added test for Istio based domain with sidecar

documentation/staging/content/samples/simple/azure-kubernetes-service/domain-on-pv.md, kubernetes/samples/scripts/common/utility.sh, kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service/create-domain-on-aks-inputs.yaml, kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service/create-domain-on-aks.sh, operator/src/main/resources/scripts/model_wdt_mii_filter.py
For #2415 
- Add note for memory customization.
- Increate default memory
-  memory: 1.5Gi
=> Update WLS AKS Domain on PV guidance for memory considerations

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItStickySession.java
Use case:
-------------
Testing the sessionAffinity field for the per-cluster Service per customer's request.
QA approach:
----------------
1. Create and start a cluster domain with cluster.clusterService enabled by setting it to "ClientIP"
2. Send the HTTP requests to WLS cluster using the cluster address, domainUid + "-cluster-" + clusterName and cluster port 
3. Verify that server-affinity is achieved by cluster service based on HTTP session information
Jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5464 ( one failure is not caused by this PR)
=> Added Session Affinity test using  ClusterService

integration-tests/src/test/java/oracle/weblogic/domain/CommonMount.java, integration-tests/src/test/java/oracle/weblogic/domain/CommonMountVolume.java, integration-tests/src/test/java/oracle/weblogic/domain/DomainSpec.java, integration-tests/src/test/java/oracle/weblogic/domain/Model.java, integration-tests/src/test/java/oracle/weblogic/domain/ServerPod.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCommonMount.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCommonMountTest.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java, integration-tests/src/test/resources/commonmount/Dockerfile
Also adding infra classes and utility methods needed to test common mount feature.
Jenkins -
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5527/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/5528/ (full suite - still in progress)
=> Adding Integration test using multiple common mounts in a domain

documentation/staging/content/_index.md
Added Related Projects section to the Home page.
=> add related projects

operator/src/test/java/oracle/kubernetes/operator/helpers/ExternalServiceHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTest.java
Before I moved to the WKTUI project, I added some unit tests to support some functionality that had recently been added - but never checked them in. I figure, better late than never...
=> Add unit test coverage

documentation/staging/content/userguide/platforms/environments.md, documentation/staging/content/userguide/prerequisites/introduction.md
As per OWLS-91446 Documentation - Fix CRIO version supported in OLCNE
=> fix versions

documentation/staging/content/faq/security-validation.md
As per     OWLS-91424 - Document - Security validation in WebLogic console, created a FAQ to address the new security validations/warnings in WLS.
=> security validations FAQ

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
in https://ci-cloud.us.oracle.com/jenkins/wlsqa/job/wko-tmp/75/ , the test ItMiiUpdateDomainConfig fails intermittently due to the curl command to query JDBCSystemResources returns 502. Add the retry logic when running curl command. 
Jenkin result:
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/6011/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/6017/
=> fix intermittent test fauilure in ItMiiUpdateDomainConfig

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOpUpgradeFmwDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorFmwUpgrade.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java
External Jenkin  
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/362/
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/364/
=> Add Operator Upgrade Scenerio form Version 3.3.1 to main

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ItMiiSampleHelper.java
Jenkins job
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/6318 (parallel)
=> Changed the image names in MII sample script tests

integration-tests/pom.xml, operator/integration-tests/model-in-image/run-test.sh
OKD FMW Jenkins job passed at:
https://build.weblogick8s.org:8443/job/wko-okd-test/23/
OKD WLS 2 jobs, each failed with 1 different test
https://build.weblogick8s.org:8443/job/wko-okd-test/24/
https://build.weblogick8s.org:8443/job/wko-okd-test/25/
Kind-new Jenkins run with 1 failure at:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/6592/
=> Fix FMW Mii sample tests on OKD

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLivenessProbeCustomization.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
This PR is to fix intermittent nightly failures in ItLivenessProbeCustomization.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7076/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7069/
=> fix intermittent nightly failures in ItLivenessProbeCustomization

operator/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCommonConfigurator.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java
Added unit tests for new Istio related environment variables for introspector job.
=> Add unit tests for JobHelper changes in OWLS-92894

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRemoteConsole.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSystemResOverrides.java
OKD Jenkins Job
https://build.weblogick8s.org:8443/job/wko-okd-test/46/
Kind New Parallel run Job
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7081/
=> Fix WLS domain tests on OKD (ItRemoteConsole, ItSystemResOverrides)

documentation/staging/content/samples/azure-kubernetes-service/_index.md, documentation/staging/content/userguide/platforms/environments.md
Environment 'linux 7' and image additions based on recent slack post by Monica
=> update environments doc

documentation/staging/content/userguide/platforms/environments.md
add MarketPlace links per Monica's request
=> minor environments update

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PodUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7248/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7247/ - full suite, failures not related to the changes in this PR
=> Modify existing test to use low value for introspectorJobActiveDeadlineSeconds

documentation/staging/content/userguide/managing-domains/model-in-image/auxiliary-images.md, operator/src/main/resources/scripts/utils_base.sh
Update to the operator documentation to mention the image tool auxiliary image feature for creating the auxiliary images and fix for a bug in traceDirs utility function.
=> OWLS-94141 - Update operator documentation to reference image tool auxiliary image feature and fix a bug in traceDirs utility function.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRemoteConsole.java
Full test suite passed at:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7331/
=> fix the nigjtly ItRemoteConsole failure

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporterSideCar.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7538
=> OWLS-94707, fixed regression due model file change

integration-tests/pom.xml
The essential change of this PR is to add dockerLogin into OKD Jenkins Build script.
(Please see function dockerLogin() in https://build.weblogick8s.org:8443/job/wko-okd-test/configure)
OKD Jenkins job 
https://build.weblogick8s.org:8443/job/wko-okd-test/106/testReport/oracle.weblogic.kubernetes/
=> add ItMiiNewCreateAuxImage to okd profile

integration-tests/pom.xml
Jenkins
https://build.weblogick8s.org:8443/job/wko-okd-test/100
https://build.weblogick8s.org:8443/job/wko-okd-test/101
https://build.weblogick8s.org:8443/job/wko-okd-test/102
https://build.weblogick8s.org:8443/job/wko-okd-test/103
=> Enabled ItElasticLoggingFluentd to run on OKD

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java
Single Jenkins passed at:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7729/testReport/
Full suite at:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7728/testReport/
=> Backport integ test PR#2663 for ItMiiAuxiliaryImage to release/3.3

documentation/staging/content/userguide/platforms/environments.md
@tbarnes-us I had a hard time figuring out where/how to put this information within the framework of the Supported Environments doc. Feel free to weigh in on any suggestions/improvements.
=> support for DB and OraOperator

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/SessionMigrationUtil.java
Jenkins jobs
12/29
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7652
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7653
12/30
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7656
12/31
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7660
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7659
1/1
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7662/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7663
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7664
1/2
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7665 …
=> Test: investigate intermittent failures on three Session Migration tests

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMonitoringExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporterSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporterSideCar.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporterWebApp.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MonitoringUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PersistentVolumeUtils.java, integration-tests/src/test/resources/exporter/promvalues.yaml
https://build.weblogick8s.org:8443/job/wko-okd-test/126
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7911
=> added OKD support for MonitoringExporter tests

documentation/staging/content/userguide/managing-domains/accessing-the-domain/port-forward.md
copy doc changes for port-forwarding in OWLS-92959 to main.
=> OWLS-92959: port doc changes for OWLS-92959 to main

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioGatewaySessionMigration.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioSessionMigration.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporterSideCar.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSessionMigration.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/SessionMigrationUtil.java
created util methods in CommonTestUtils.java to be used by ItIstioGatewaySessionMigration.java, ItIstioSessionMigration.java, ItMonitoringExporterSideCar.java and ItSessionMigration.java
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/7992/
=> Created Utility methods for creating Yaml file with DOMAINUID param on fly

documentation/staging/content/userguide/aks/_index.md
As per Monica, Update description for "Password for WebLogic Deploy Tooling runtime encryption"
=> update password description

operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdateTestBase.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodCompatibilityTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/RollingHelperTest.java
Addresses:
- OWLS-93144: fix conditions for admin-only
- OWLS-95965: domain Completed condition must check Ready (not Running)
- NOJIRA: domain Available condition must check Ready (not Running)
=> Status update tuning

documentation/staging/content/userguide/managing-domains/model-in-image/auxiliary-images.md, kubernetes/samples/scripts/create-weblogic-domain/model-in-image/ai-docker-file/Dockerfile
Changes for WKO 4.0 AI documentation for runtime functionality and sample. I have also updated the description in sample Dockerfile to match the current domain specs.
=> OWLS-95638: WKO 4.0 AI documentation for runtime functionality and sample.

documentation/staging/content/_index.md, documentation/staging/content/userguide/managing-domains/accessing-the-domain/admin-console.md
Update links to the Remote Console from the GitHub repo to the public doc site.
=> update links to remote console docs

operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/model_wdt_mii_filter.py, operator/src/test/python/test_wdt_mii_filter.py
Set tunneling to false for istio replication channel per weblogic security recommendations.
=> Set istio replication channel tunneling to false

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart2.java
Jenkin Run 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8369/
=> Regression: Fixed ItMiiDynamicUpdatePart2 failure due WDT update

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCoherenceTests.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDedicatedMode.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLogging.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwBigCMMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicClusterMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItInitContainers.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioCoherenceTests.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioManagedCoherence.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMonitoringExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLivenessProbeCustomization.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManagedCoherence.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodTemplates.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsShutdownOption.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItStickySession.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItUsabilityOperatorHelmChart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Operator.java
Here are few tasks included in the PR
a. Remove clear test password form the test code
b. Resolution to operator image build failure in local run
c. Test change for WDT 2.0
https://build.weblogick8s.org:8443/job/wko33-kind-nightly-parallel/9/  (toolkits-srg) 
https://build.weblogick8s.org:8443/job/wko33-kind-nightly-parallel/7/  (entire run )
=> Backport clear text password/build failure/wdt update change to Release/3.3

operator/src/main/resources/scripts/introspectDomain.py
This PR is a backport of owls-9628 sitconfig replication channel settings regression
=> OWLS-96248 backport sitconfig replication channel regression

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/LoggingExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
Backporting the fix from PRs 
https://github.com/oracle/weblogic-kubernetes-operator/pull/2788
https://github.com/oracle/weblogic-kubernetes-operator/pull/2783
Currently running tests....
=> backport the fix for elastic search issue and listjobs from main branch

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLiftAndShiftFromOnPremDomain.java
Jenkins - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8889/
=> Fix tests for latest WDT changes

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorFmwUpgrade.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java
Jenkin Job 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8922
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8995
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8996
=> Added upgrade tests for Release 3.3.8

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage40.java
Jenkins - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9004/
=> modify negative tests to check domain events and operator log

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/K8sEvents.java
Triage ItMiiAuxiliaryImage test failure in release/3.3:
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/8981/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/8978/
=> triage ItMiiAuxiliaryImage test failure in release/3.3

documentation/staging/content/userguide/istio/istio.md
As per [OWLS-96761](https://jira.oraclecorp.com/jira/browse/OWLS-96761) DOCUMENT USING OPEN SHIFT SERVICE MESH WITH WKO. In addition to text, please review placement.
=> edit openshift-istio

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/AuxiliaryImageUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9140/
=> removed work around for wit issue after it was fixed

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java
Modified to check cluster status in loop to give more time.
Jenkins - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9236/
Note: Removing the extra spaces which are not needed is done by IDE. My change is adding method checkClusterStatus().
=> check cluster status in loop

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
Porting changes from release/3.3 ItIntrospectVersion tests
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9212/
=> Port PR2810  from release/3.3 to main

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java
Regarding The intermittent failure from ItMultiDomainModelsWithLoadBalancer.java, we got exit code 137 below
message: 'Exec lifecycle hook ([/weblogic-operator/scripts/stopServer.sh]) for Container
"weblogic-server" in Pod "miidomain-cluster-1-managed-server2_ns-eqqknh(ebce05bf-3bb1-44c0-b2b8-8347da18f56e)"
failed - error: command ''/weblogic-operator/scripts/stopServer.sh'' exited with
137: 
That could mean "not having enough RAM or out of memory". I added below back:
// set resource request and limit
resourceRequest.put("cpu", new Quantity("250m"));
resourceRequest.put("memory", new Quantity("768Mi"));
resourceLimit.put("cpu", new Quantity("2"));
resourceLimit.put("memory", new Quantity("2Gi"));
Jenkins Job:
I have kicked off 7 jobs in two day, this test never fail …
=> Fixed Intermittent failure on wko-nighty ItMultiDomainModelsWithLoadBalancer.testLivenessProbe test failure 

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ServerStartPolicyUtils.java
Jenkins - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9272/
=> forward port - fix intermittent nightly failure in ItServerStartPolicyConfigCluster

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporter.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java
Fixing 3.4 test failures.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9337
=> Fix for ItMultiDomainModelsWithLoadBalancer and ItMonitoringExporter tests

README.md
Update release number and date in the WKO README file.
=> update release number and date

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainRecheck.java, operator/src/main/java/oracle/kubernetes/operator/Namespaces.java, operator/src/main/java/oracle/kubernetes/operator/ServerStatusReader.java, operator/src/main/java/oracle/kubernetes/operator/StuckPodProcessing.java, operator/src/main/java/oracle/kubernetes/operator/Watcher.java, operator/src/main/java/oracle/kubernetes/operator/calls/AsyncRequestStep.java, operator/src/main/java/oracle/kubernetes/operator/http/HttpAsyncRequestStep.java, operator/src/main/java/oracle/kubernetes/operator/logging/LoggingContext.java, operator/src/main/java/oracle/kubernetes/operator/logging/LoggingFormatter.java, operator/src/main/java/oracle/kubernetes/operator/logging/ThreadLoggingContext.java, operator/src/main/java/oracle/kubernetes/operator/steps/MonitoringExporterSteps.java, operator/src/test/java/oracle/kubernetes/operator/logging/LoggingFormatterTest.java
Resolves https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=oracle_weblogic-kubernetes-operator&open=AX-UMDdY-DqrUt7naJ1p
=> Resolve sonar warning by using a thread-specific version of LoggingContext 

documentation/staging/content/quickstart/install.md, documentation/staging/content/userguide/managing-operators/installation.md, documentation/staging/content/userguide/managing-operators/namespace-management.md, documentation/staging/content/userguide/managing-operators/overview.md, documentation/staging/content/userguide/managing-operators/preparation.md, documentation/staging/content/userguide/managing-operators/using-helm.md
Update the Helm reference doc as per [OWLS-95907](https://jira.oraclecorp.com/jira/browse/OWLS-95907): Operator User Guide Feedback and Updates for 4.0. also, minor edits elsewhere to conform to Oracle Style Guide.
=> update the Helm ref

Jenkinsfile
Added back the Sonar Quality Gate but turned off the aborting of the build if the Quality Gate is not met.
=> Sonar Quality Gate

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Domain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
Backport ItMultiDomainModelsWithLoadBalancer to reduce memory usage to release/3.3
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9431/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9430/
=> Backport ItMultiDomainModelsWithLoadBalancer to reduce memory usage to release/3.3

documentation/staging/content/userguide/managing-operators/common-mistakes.md
Change the examples from using the file-based operator Helm chart to the one in the GitHub chart repository, as per [OWLS-95907](https://jira.oraclecorp.com/jira/browse/OWLS-95907): Operator User Guide Feedback and Updates for 4.0.
=> fix-examples

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwSample.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLBTwoDomainsApache.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsManagedByTwoOperators.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/PersistentVolumeClaim.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonLBTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PersistentVolumeUtils.java
Fix crio-pipeline PV exists issue when creating PV in release/3.3
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9555/
=> Fix crio-pipeline PV exists issue when creating PV in release/3.3

documentation/staging/content/userguide/managing-operators/the-rest-api.md
Update the REST Services doc as per [OWLS-95907](https://jira.oraclecorp.com/jira/browse/OWLS-95907): Operator User Guide Feedback and Updates for 4.0.
=> REST services updates

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwSample.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLBTwoDomainsApache.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsManagedByTwoOperators.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/PersistentVolumeClaim.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonLBTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PersistentVolumeUtils.java
Backport crio-pipeline PV exists issue when creating PV in release/3.4
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9605/
=> Backport crio-pipeline PV exists issue when creating PV in release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PortInuseEventWatcher.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9805
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9806
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9807
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9842
=> do a null check before parsing the last timestamp of a event object

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLogging.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java
Not seeing the failures  in 8 jobs from elk_nightly
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9630
to
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9638
with latest changes, the failures  are not seen in 10 jobs from elk_nightly
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9767
to
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9776
=> Fixed Intermittent failure of ItElasticLogging and ItElasticLoggingFluentd 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItUsabilityOperatorHelmChart.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9863/
=> Backport UsabilityTest to 3.4

operator/src/main/resources/scripts/auxImage.sh
=> changing script to require bash

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDedicatedMode.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLivenessProbeCustomization.java
1) Remove the commented tests from ItDedicatedMode
2) Remove the test method dependency in  ItCustomLivenessProbe
Jenkin Run ( in progress) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9886/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9889
=> Backport changes to ItDedicatedMode and ItCustomLivenessProbe Test into release/3.3 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDedicatedMode.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLivenessProbeCustomization.java
Backport the changes from release/3.3
Remove the commented tests from ItDedicatedMode
Remove the test method dependency in ItCustomLivenessProbe
Jenkin Run
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9916
=> Backport PR 2930 into release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9949
=> Split method to 3 different tests for granularity 

integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/ImageBuilders.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PortInuseEventWatcher.java
Port the changes from main PRs 2898 and 2907 to release/3.3
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9976
=> port PR 2898 and 2907 to release/3.3

integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/ImageBuilders.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PortInuseEventWatcher.java
Port the changes from main PRs 2898 and 2907 to release/3.4
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9975/
=> port PR 2898 and 2907 to release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioSessionMigration.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/SessionMigrationUtil.java
Fixes for the issue described in JIRA https://jira.oraclecorp.com/jira/browse/OWLS-97650
Jenkins job passed:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9969/
The test passed in 6 Jenkins jobs below
from:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9964/
to 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9969/
=> Fixed intermittent failure on ItIstionSessionMigration in release/3.3,  wko-nightly

documentation/staging/content/quickstart/install.md, documentation/staging/content/userguide/base-images/access-images.md
Follow-up, minor fixes from previous PR.
=> edits from Tom

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCrossDomainTransaction.java
Refer Jira OWLS-98531
Jenkin Run: 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10064 (individual)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10065 (all)
=> Sync  ItCrossDomainTransaction tests from main

documentation/staging/content/userguide/managing-domains/_index.md
Update Manage WebLogic Domains doc as per [OWLS-95907](https://jira.oraclecorp.com/jira/browse/OWLS-95907): Operator User Guide Feedback and Updates for 4.0.
=> doc updates

integration-tests/src/test/java/oracle/weblogic/domain/DomainSpec.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java
Some minor fixes found during backport of owls-91993 fluentd feature
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10123/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10123/
=> Fluentd minor fix

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/KubernetesConstants.java, operator/src/main/java/oracle/kubernetes/operator/TuningParameters.java, operator/src/main/java/oracle/kubernetes/operator/TuningParametersImpl.java, operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapConsumer.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java, operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java, operator/src/main/resources/Operator.properties, operator/src/test/java/oracle/kubernetes/operator/helpers/PodPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/TuningParametersStub.java
jenkins (in progress) https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10169/
=> Backport OWLS-96896 Restart evicted pods to release/3.4

operator/src/main/resources/scripts/modelInImage.sh
Fix minor script comparison warnings
=> fix script error compare condition

operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java
The NPE is preventing new code merges https://github.com/oracle/weblogic-kubernetes-operator/pull/2948
=> Fix NPE when no domainConfig is defined in unit test

documentation/staging/content/quickstart/cleanup.md, documentation/staging/content/samples/domains/domain-home-in-image/_index.md, documentation/staging/content/samples/domains/domain-home-on-pv/_index.md, documentation/staging/content/samples/domains/fmw-domain-home-in-image/_index.md, documentation/staging/content/userguide/base-images/custom-images.md, documentation/staging/content/userguide/managing-domains/domain-resource.md, documentation/staging/content/userguide/managing-domains/model-in-image/auxiliary-images.md, documentation/staging/content/userguide/managing-domains/model-in-image/model-files.md, documentation/staging/content/userguide/managing-domains/model-in-image/overview.md, documentation/staging/content/userguide/managing-domains/model-in-image/runtime-updates.md, documentation/staging/content/userguide/managing-domains/model-in-image/usage.md
Text edits and updates as per [OWLS-95907](https://jira.oraclecorp.com/jira/browse/OWLS-95907): Operator User Guide Feedback and Updates for 4.0.
=> updates and edits

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/K8sEvents.java
sync K8sEvents in main with release/3.4
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10399/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10394/
=> Sync K8sEvents test changes in main with release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItUsabilityOperatorHelmChart.java
ItUsabilityOperatorHelmChart is fixed: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10566/
=> Fix ItUsabilityOperatorHelmChart after changes to Helm default values

integration-tests/src/test/java/oracle/weblogic/domain/DomainSpec.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10646/
=> Fix ItKubernetesDomainEvents.testK8sEventsFailedLifeCycle by specifying retry limit

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ItMiiSampleHelper.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10645/
=> remove image tag for sample source check

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ItMiiSampleHelper.java
kind new result
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10656/
On OKD:
https://build.weblogick8s.org:8443/job/wko-okd-test/338/
=> backport miisample fix PR#3080

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightDomainOperation.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java, operator/src/main/java/oracle/kubernetes/operator/tuning/TuningParameters.java, operator/src/main/java/oracle/kubernetes/operator/work/FiberGate.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/PodPresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/ServicePresenceTest.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberGateTest.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java
This is basically some code cleanup that I believe will be helpful in moving forward on the retry behavior.
=> Russ retry prep

documentation/2.5/content/reference/domain-resource.md, documentation/2.6/content/reference/domain-resource.md, documentation/3.0/content/reference/domain-resource.md, documentation/3.1/content/reference/domain-resource.md, documentation/3.2/content/reference/domain-resource.md, documentation/3.3/content/reference/domain-resource.md, documentation/3.4/content/reference/domain-resource.md
Modify the hard-coded link to each older version of the domain resource doc to correspond to the corresponding doc version.
=> update links to older domain resource docs

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java
kind new:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10723/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10725/
=> backport PR3095 to main branch 

documentation/3.4/content/userguide/platforms/environments.md, documentation/staging/content/introduction/platforms/environments.md
Update OpenShift support as per [OWLS-99636](https://jira.oraclecorp.com/jira/browse/OWLS-99636) Change supported version of OpenShift in Operator docs
=> update openshift support

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt_k8s_model_template.yaml
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10918/
=> Add clusters and replicas to sample model file

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalLbTunneling.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOCILoadBalancer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/NginxParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoadBalancerUtils.java, integration-tests/src/test/resources/bash-scripts/images.properties, integration-tests/src/test/resources/bash-scripts/install-istio.sh, integration-tests/src/test/resources/bash-scripts/syncTestImagesRepo.sh
Back porting these PR from main to release/3.4
https://github.com/oracle/weblogic-kubernetes-operator/pull/3092
https://github.com/oracle/weblogic-kubernetes-operator/pull/3082
Also add script to pull images from source repos and add it in to local repo.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10915/
=> Back port PR 3082 and 3092 to release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicyDynamicCluster.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11004/
=> Adding test to scale beyond max dynamic size

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
=> add overwrite option

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11022/
=> remove check for warning message in operator pod log as its intermittent

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DbUtils.java
Backport PR 3152 from main to release/3.4 to fix nightly failure
=> backport pod name fix from main to release/3.4

documentation/staging/content/quickstart/_index.md, documentation/staging/content/quickstart/cleanup.md, documentation/staging/content/quickstart/create-domain.md, documentation/staging/content/quickstart/install.md, documentation/staging/content/quickstart/prepare.md, documentation/staging/content/quickstart/summary.md
Changed my mind on some style issues. Just cleaned up the Quick Start look, all minor edits.
=> cleanup-style

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicyDynamicCluster.java
This PR restores the deleted tests having serverStartState in the name as the subsequent tests depend on these tests. This fixes the failures in `ItServerStartPolicyDynamicCluster#testDynamicClusterScale` and `testScaleBeyondMaxClusterSize` nightlies.  Also changed the tests names/description to remove serverStartState from it to avoid confusion.
Integration test run started at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11184/
=> Restore the deleted tests having serverStartState in the name as subsequent tests depend on them

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLiftAndShiftFromOnPremDomain.java, integration-tests/src/test/resources/bash-scripts/syncTestImagesRepo.sh
(a) Backport the changes to ItLiftAndShiftFromOnPremDomain  on main
(b) Update the script syncTestImagesRepo.sh 
Jenkin Run 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11224/
=> Backport the changes to ItLiftAndShiftFromOnPremDomain 

operator/integration-tests/model-in-image/run-test.sh
Owls 100113 - Forward port the fix for PR #3207 to main.
=> Forward port the fix for Owls 100113 (PR 3207) to main.

documentation/3.4/content/faq/node-selector.md, documentation/3.4/content/faq/security-validation.md, documentation/staging/content/faq/node-selector.md
An FAQ to address [OWLS-100227](https://jira.oraclecorp.com/jira/browse/OWLS-100227): Document how to set NodeSelector for the WL Server Pods.
=> FAQ for nodeSelector

documentation/3.3/content/userguide/aks/_index.md, documentation/3.4/content/userguide/aks/_index.md, documentation/staging/content/managing-domains/aks/_index.md
Signed-off-by: galiacheng <haixia.cheng@microsoft.com>
Changes to be committed:
modified:   documentation/3.3/content/userguide/aks/_index.md
modified:   documentation/3.4/content/userguide/aks/_index.md
modified:   documentation/staging/content/managing-domains/aks/_index.md
=> AKS guidance for new feature "Bring your own VNET for Application Gateway"

documentation/staging/content/managing-domains/accessing-the-domain/istio/istio.md
This PR updates the documentation for wko 4.0 with the new Istio implementation.
=> doc update for Istio in WKO 4.0

Jenkinsfile.oke
https://build.weblogick8s.org:8443/job/wko-oke-nightly-parallel/139/
=> updated k8 version in OKE runs

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DbUtils.java, integration-tests/src/test/resources/bash-scripts/images.properties, integration-tests/src/test/resources/dboperator/oracle-database-operator.yaml, integration-tests/src/test/resources/dboperator/singleinstancedatabase.yaml
Update the Oracle database Operator to version 0.2.0
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11489/
=> Upgrade DB operator to version 0.2.0

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLiftAndShiftFromOnPremDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Installer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/resources/bash-scripts/discover_domain.sh
kind new with released WDT 2.3.1
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11540/
(ItLiftAndShiftFromOnPremDomain failed as expected)
kind new with latest WDT main branch 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11542/
(ItLiftAndShiftFromOnPremDomain passed)
On OKD single ItLiftAndShiftFromOnPremDomain with latest WDT main branch
https://build.weblogick8s.org:8443/job/wko-okd-test/422/
=> backport PR3242 plus new fix to address WDT imagePullSecrets issue

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLiftAndShiftFromOnPremDomain.java
kind new:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11571/
On OKD single test:
https://build.weblogick8s.org:8443/job/wko-okd-test/425/
=> backport image pull secrets fix into main branch

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsShutdownOption.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11588/
Running entire kind parallel run 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11589
=> OWLS-101056 - fixed log msg to avoid test failure in the case of REST call failure 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesDomainEvents.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorDelegate.java, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightDomainOperation.java, operator/src/main/java/oracle/kubernetes/operator/OperatorMain.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCondition.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorDelegateStub.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTestSupport.java, operator/src/test/java/oracle/kubernetes/operator/FailureRetryTest.java, operator/src/test/java/oracle/kubernetes/operator/makeright/FailureReportingTest.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java, operator/src/test/java/oracle/kubernetes/utils/SystemClockTestSupport.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainConditionTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainResourceRetryTest.java, pom.xml
Now automatically schedules retries when a severe failure occurs.
(also included an update to an integration test that was not cleaning up after itself)
=> Russ owls 101001 part1

documentation/domains/Cluster.json, documentation/domains/Domain.json, documentation/domains/Domain.md, kubernetes/crd/domain-crd.yaml, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightDomainOperation.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightExecutor.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCondition.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/FailureRetryTest.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java, operator/src/test/java/oracle/kubernetes/utils/SystemClockTestSupport.java
Ensure that processing stops when we get an ABORTED condition, and that changing certain parameters allows us to continue.
=> Handle recovery from aborted processing

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingUtil.java
https://build.weblogick8s.org:8443/job/wko-oke-nightly-parallel/155/
https://build.weblogick8s.org:8443/job/wko-oke-nightly-parallel/156/
https://build.weblogick8s.org:8443/job/wko-oke-nightly-parallel/157/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11615/
=> OWLS-101078 - fixed test to check log after specific time to avoid intermittent failures in ItServerStartPolicy

documentation/domains/index.html, operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java, operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java, operator/src/main/java/oracle/kubernetes/operator/MakeRightDomainOperation.java, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java, operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorDelegateStub.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java, operator/src/test/java/oracle/kubernetes/operator/FailureRetryTest.java, operator/src/test/java/oracle/kubernetes/operator/helpers/EventHelperTest.java, operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java
My last PR had reported less than 100% code coverage, so I did some investigation and found places where we were not only lacking tests, but also had code whose purpose wasn't clear. This change attempts to remedy that.
=> Improve unit tests and code clarity

documentation/staging/content/managing-operators/using-helm.md, documentation/staging/content/samples/elastic-stack/operator/_index.md, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
Also include minor doc edits from feedback from PR #3271
=> owls-99631 add unit tests to verify correct service created during scale up and scale down when preCreateService is enabled

operator/src/main/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStep.java, operator/src/test/java/oracle/kubernetes/operator/steps/ShutdownManagedServerStepTest.java
Owls 101059 - Changes to retry the failed REST call only if server is not already shut down or shutting down. This PR also changes to log the REST call failure error message only if the server is not already shut down. 
Integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11641/console
=> Owls 101059 - Improve retry behavior for shutdown using REST call

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItAddNewDynamicClusterUsingWlst.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDynAsConfigCluster.java, integration-tests/src/test/resources/python-scripts/create-dynamic-cluster.py
Jenkins jobs
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11629
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11630
Jenkins jobs with latest changes:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11649
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11650
=> Added test to create a new dynamic cluster in the domain using online WLST and verify server starts successfully

operator/src/main/resources/scripts/stopServer.sh
OWLS-95973 - This PR has the changes to the stop server script to wait for a timeout value and then issue a "kill -9" to the node-manager and WebLogic server processes before the pod is destroyed. It allows 3 seconds for the NFS v3 manager to detect the process destruction and release the file locks after the "kill -9" is issued. If the server is gracefully shutdown during the timeout period, then the background processes is killed by k8s.
Integration test run at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11648/
=> OWLS-95973 - Limit the abandoned NFS v3 locks by issuing a kill -9 just before pod destruction.

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/AppBuilder.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11905
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11906
=> Added debugger to gain more useful info for JIRA OWLS-101365 in case it happens again

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonLBTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FmwUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/IstioUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MonitoringUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ServerStartPolicyUtils.java
Jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11808
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11818
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11819
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11820
=> Test for WKO Retry Improvements: enhance the existing integration test cases

integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/ActionConstants.java
Kind job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11913/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/11924/
=> Backport removing wdt.version from pom.xml

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDBOperator.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwBigCMMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWDT.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWLST.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicClusterMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FmwUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12299/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12300/
=> Update ItFmw* classes to use v9 cluster resources

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ServerStartPolicyUtils.java, kubernetes/samples/scripts/domain-lifecycle/helper.sh, kubernetes/samples/scripts/domain-lifecycle/rollCluster.sh, kubernetes/samples/scripts/domain-lifecycle/scaleCluster.sh, kubernetes/samples/scripts/domain-lifecycle/startCluster.sh, kubernetes/samples/scripts/domain-lifecycle/stopCluster.sh
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12341/
I have to created this new PR for the changes for updating ItServerStartPolicyConfigCluster and ItPodsRestart to use v9 ClusterResource because syncing up with [cluster-reference] using git doesn't work. So I am closing PR https://github.com/oracle/weblogic-kubernetes-operator/pull/3334
=> Updated ItServerStartPolicyConfigCluster and ItPodsRestart to use v9 ClusterResource

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/InitializationTasks.java
Refer to PR on release/3.4 branch
https://github.com/oracle/weblogic-kubernetes-operator/pull/3341
Jenkin Run
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12375/
=> Port Integration Test with Japanese locale into main 

documentation/3.4/content/userguide/aks/_index.md, documentation/staging/content/managing-domains/aks/_index.md
See https://github.com/oracle/weblogic-azure/pull/192
Signed-off-by: galiacheng <haixia.cheng@microsoft.com>
Changes to be committed:
modified:   documentation/3.4/content/userguide/aks/_index.md
modified:   documentation/staging/content/managing-domains/aks/_index.md
=> Include MySQL support in aks user guide

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DbUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PodUtils.java
latest results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12478/
Failures are due to https://jira.oraclecorp.com/jira/browse/OWLS-101921
=> v9 changes, check operator log instead of introspector log

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCustomSslStore.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodTemplates.java
Modify ItPodTemplates, ItMiiCustomSslStore class to use v9 Cluster template
Jenkin Job
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12508/ ( all passed )
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12529/
=> Modify ItPodTemplates, ItMiiCustomSslStore class to use v9 Cluster template

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/IstioUtils.java
fix ItIstioSessionMigration, ItIstioGatewaySessionMigratio create cluster resource failure due to merge conflicts
fix ItIstioSessionMigration, ItIstioGatewaySessionMigratio create cluster resource failure due to merge conflicts
=> fix ItIstioSessionMigration, ItIstioGatewaySessionMigratio create cluster resource failure due to merge conflicts

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLogHomeFlatStructure.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12596/
=> Fix ItLogHomeFlatStructure

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLogHomeFlatStructure.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart1.java
Fixed the test based on new behavior in Operator 4.0 for https://jira.oraclecorp.com/jira/browse/OWLS-101872
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12660/
=> fix ItMiiDynamicUpdatePart1

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorFmwUpgrade.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12808/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12810/
=> Modify ItOperatorFmwUpgrade for v9 cluster reference

kubernetes/samples/scripts/domain-lifecycle/helper.sh, kubernetes/samples/scripts/domain-lifecycle/rollCluster.sh, kubernetes/samples/scripts/domain-lifecycle/scaleCluster.sh, kubernetes/samples/scripts/domain-lifecycle/startCluster.sh, kubernetes/samples/scripts/domain-lifecycle/startServer.sh, kubernetes/samples/scripts/domain-lifecycle/stopCluster.sh, kubernetes/samples/scripts/domain-lifecycle/stopServer.sh
Cleanup of cluster and server lifecyle scripts. 
- Removed duplicate functions.
- Fixed parameters names and comments
- Removed comments about the date when changes are made.
Integration test results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12835/
=> Cluster and server lifecycle scripts cleanup and fix a potential issue with the cluster roll script

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/197/
=> fixed expected msg

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MonitoringUtils.java
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/201
=> Backported version support and updated monexporter web app version to 2.0.7 for release 3.4 

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java
backport the fix for ItMultiDomainModelsWithLoadBalancer#testLivenessProbe in release/3.4 to Main
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/12957/
=> backport the fix for ItMultiDomainModelsWithLoadBalancer#testLivenessProbe in release/3.4 to Main

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/204/
=> backport to release/3.4 - fix tools download url

Jenkinsfile, Jenkinsfile.kindnightly, Jenkinsfile.oke, integration-tests/pom.xml, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
Current tests failed to install Grafana with k8s1.25. Updated Grafana version to 6.38.6
https://build.weblogick8s.org:8443/job/wko-kind-nightly-parallel/1056
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/122
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13148/
=> updated grafana version to 6.38.6

operator/src/main/java/oracle/kubernetes/operator/makeright/MakeRightDomainOperationImpl.java, operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
OWLS-102464 - Changes to prevent unexpected introspector runs when shutting down.
When the cluster resource is deleted immediately after the domain resource is deleted, two deletion watch events are created at around the same time. If the cluster deletion comes in second, then the make-right that runs is based on the cluster deletion and the operator was accidentally doing a "domain up" assuming that the domain resource still exists. The introspection was running due to "domain up" plan execution.
This change validates that the domain resource exists earlier in a make-right before executing a "domain up" plan.
=> OWLS-102464 - Changes to prevent unexpected introspector runs when shutting down.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java
Adjust the testcase error message.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13162/
=> Fix for oracle.weblogic.kubernetes.ItMiiDynamicUpdatePart3.testOperatorLogIntrospectorMsg  failure

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDiiSample.java
kind new:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13189/
=> backport pr3430 to release/3.4

Jenkinsfile.oke, kubernetes/samples/scripts/terraform/oke.delete.sh
https://build.weblogick8s.org:8443/job/wko-oke-nightly-parallel/277/
=> Added extra cleanup to avoid left over artifacts in case of shell script intermittent failures  in OKE cluster

common/src/main/java/oracle/kubernetes/common/utils/SchemaConversionUtils.java, operator/src/main/java/oracle/kubernetes/operator/http/rest/RestBackendImpl.java, operator/src/main/java/oracle/kubernetes/operator/webhooks/resource/ConversionWebhookResource.java
The logging is still difficult to read because the log is output in JSON and the string constants get encoded. Still, these logging points are much better.
=> Improve fine logging from webhook

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItValidateWebhookReplicas.java
Resolve ItValidateWebhookReplicas failure in OKE
https://build.weblogick8s.org:8443/job/wko-oke-nightly-parallel/284/ (OKE)
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/13326/ (kind-new)
=> Resolve ItValidateWebhookReplicas failure in OKE

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/OperatorParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/InitializationTasks.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MiiDynamicUpdateHelper.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13316
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13317
=> removed domainPresenceFailureRetryMaxCount and domainPresenceFailureRetrySeconds from QA test framework

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMultiDomainModelsWithLoadBalancer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoadBalancerUtils.java
backport ItMultiDomainModelsWithLoadBalancer test class failing intermittently in release/3.4 to Main
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/13404/
=> backport ItMultiDomainModelsWithLoadBalancer test class failing intermittently in release/3.4 to Main

documentation/3.4/content/developerguide/contributing.md
=> fix link to OCA

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiClusterResource.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItProductionSecureMode.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Cluster.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ClusterUtils.java
Add more tests for RestartVersion, ServerStartPolicy attributes
Add tests for Configured Cluster
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13462
=> Add tests for Cluster Resource attributes

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItHorizontalPodAutoscaler.java
HorizontalPodAutoscaler test is failing on OKE as it may take some time in some environments to get the metrics. Adding check to wait for the HPA till it gets the current cpu utilization metric before loading the CPU.
https://build.weblogick8s.org:8443/job/wko-oke-nightly-parallel/306/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13513/
=> verify hpa can get the current cpu utlization

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Secret.java, kubernetes/samples/charts/util/setupLoadBalancer.sh
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13581
https://build.weblogick8s.org:8443/job/wko34-okd/21
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13600/  (all tests )
=> use retry for getting token and verifying the http response from admin server

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRetryImprovements.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Pod.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PodUtils.java
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13531
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13532
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13546
Need to re-create this PR to syncup with main. So close the old PR https://github.com/oracle/weblogic-kubernetes-operator/pull/3518
=> Added tests for WKO Retry Improvements: Add a test in operator usability for failureRetryLimitMinutes

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporterWebApp.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13580/
=> OWLS-103561 - fixed monitoring exporter title

documentation/staging/content/quickstart/cleanup.md, documentation/staging/content/quickstart/create-domain.md
OWLS-103643 - Changed the quick start sample cluster resource name to include domain UID as per the best practice.
=> OWLS-103643 - Change to the quick start sample cluster resource name to include domain UID.

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Secret.java
extract service account secret from secret annotation in Openshift
https://build.weblogick8s.org:8443/job/wko34-okd/42/
=> extract service account secret from secret annotation in Openshift

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorFmwUpgrade.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorUpgradeWithIstio.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java
Added new Upgrade tests from release/3.4 to main
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13650/
=> Add  upgrade tests for release/3.4.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOpenshiftIstioMiiDomain.java, integration-tests/src/test/resources/opnshift/servicememberroll.yaml
These changes are made to make the istio test pass in Openshift environment.
=> Fix istio tests in Openshift

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOpenshiftIstioMiiDomain.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13730
=> Exclude console tests on class ItOpenshiftIstioMiiDomain for slim image

ItOpenshiftIstioMiiDomain.java, integration-tests/src/test/resources/opnshift/servicememberroll.yaml
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13729/
=> Backport ItOpenshiftIstioMiiDomain class from release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDiiSample.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13786/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13787/
=> backport FmwDiiSample change to release/4.0

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCoherenceTests.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13676/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13674/
=> Fixed ItCoherenceTests.testCoherenceServerRollingRestart test class failing intermittently

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManagedCoherence.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoadBalancerUtils.java
Backport [wko-nightly] create ingress failed with default ingressClass to release/3.4
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13853/
=> Backport [wko-nightly] create ingress failed with default ingressClass to release/3.4

integration-tests/src/test/java/oracle/weblogic/domain/Configuration.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOpenshiftIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/OperatorParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13888
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13975
=> Backport ItOpenshiftIstioMiiDomain

integration-tests/src/test/java/oracle/weblogic/domain/ProbeTuning.java, integration-tests/src/test/java/oracle/weblogic/domain/ServerPod.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLivenessProbeCustomization.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
Backport [wko-nightly] ItLivenessProbeCustomization#testCustomLivenessProbeFailureThresholdSuccessThreshold fails intermittently to release/3.4
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13927/
=> Backport [wko-nightly] ItLivenessProbeCustomization#testCustomLivenessProbeFailureThresholdSuccessThreshold fails intermittently to release/3.4

documentation/4.0/content/managing-domains/domain-resource.md, documentation/domains/Cluster.json, documentation/domains/Cluster.md, kubernetes/crd/cluster-crd.yaml, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ClusterService.java
OWLS-89704 - Documented `clusterService.sessionAffinity` cluster spec element and updated generated desciption.
=> OWLS-89704 - Documented `clusterService.sessionAffinity` cluster spec element and updated generated desciption.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConfigDistributionStrategy.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Secret.java
port prs 3533 and 3579 to 4.0
Jenkins 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13973
=> port prs 3533-3579 to 4.0

integration-tests/src/test/java/oracle/weblogic/domain/Configuration.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOpenshiftIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/OperatorParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/OperatorUtils.java
Refer to https://github.com/oracle/weblogic-kubernetes-operator/pull/3658
Complete Jenkin Run
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14143/
=> Backport ItOpenshiftIstioMiiDomain to release/4.0

documentation/3.4/content/userguide/platforms/environments.md, documentation/4.0/content/introduction/platforms/environments.md
As per OWLS-104620, https://jira.oraclecorp.com/jira/browse/OWLS-104620
=> Document new certifications

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporterSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/resources/exporter/promvalues.yaml
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/300
=> OWLS-104590 - updated prometheus to supported version

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/305
=> Backport the change on PR3713 into release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/resources/exporter/promvalues.yaml
Updated prom and Grafana supported versions in the tests
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14313
=> updated supported version for grafana and prom

kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-in-image/create-domain.sh
=> fix nightly regression in IT FMW

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
https://build.weblogick8s.org:8443/job/wko40-kind-nightly-parallel/63
=> Fixed WLS version hard coded value in 4.0 line

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/14994/
=> fixed hard coded wls version (WEBLOGIC_VERSION) in main

documentation/3.3/content/userguide/aks/_index.md, documentation/3.4/content/userguide/aks/_index.md, documentation/4.0/content/managing-domains/aks/_index.md
Update AKS user guide for https://github.com/oracle/weblogic-azure/pull/230.
=> Update aks user guide for passwordless PostgreSQL support.

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/14
=> back port from main, fixed hardcoded wls version

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
https://build.weblogick8s.org:8443/job/wko40-kind-nightly-parallel/63
=> Fixed WLS version hard coded value in release/4.0 

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java
Jenkins:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15336
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15337
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15338
=> Moved patchDomainResourceWithNewIntrospectVersion method from Domain.java to DomainUtil.java

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart2.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/resources/wdt-models/model.delete.sysresourcesbyconfigmap.yaml
Using WDT main branch (3.0)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15792/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15824/
Using WDT latest
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15793/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15825/
=> OWLS-105782 Fix how to delete system resource added eariler by configMap

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15764
=> OWLS-103358, OWLS-106012 - fixed intermittent failures and adapted wdt3.0 changes

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MonitoringUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15928/
=> Updated tests to use 2.1.1 Monitoring Exporter version

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorFmwUpgrade.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorWlsUpgrade.java
Jenkin Results
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15834/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15888/
=> Add upgrade tests for Release 4.0.3 and 4.0.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart2.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/resources/wdt-models/model.delete.sysresourcesbyconfigmap.yaml
Using wdt 3.0 on kind new:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15969/
=> Backport PR3862 to release/4.0

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart2.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdatePart3.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java, integration-tests/src/test/resources/wdt-models/model.delete.sysresourcesbyconfigmap.yaml
Using wdt 3.0 on kind new:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15971/
=> backport pr3862 to release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalLbTunneling.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalNodePortService.java
Refer to https://github.com/oracle/weblogic-kubernetes-operator/pull/3887
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16015
=> Backport resolution to OWLS-104983 into release/4.0

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalLbTunneling.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItExternalNodePortService.java
Refer 
https://github.com/oracle/weblogic-kubernetes-operator/pull/3887
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16018/
=> Backport resolution of OWLS-104983 to release/3.4

okdtest.sh
https://build.weblogick8s.org:8443/job/wko34-okd/113/ 
just to show the script works
This line was added earlier but was accidentally overridden  by the KUBERNETES_CLI change later
=> Re-add being deleted crd cleanup

okdtest.sh
https://build.weblogick8s.org:8443/job/wko34-okd/114/
just to show the script works
=> add crd cleanup on OKD

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsManagedByTwoOperators.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DbUtils.java
backport PR 3866 and 3884 to release/4.0
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15989/
=> backport PR 3866 and 3884 to release/4.0

Jenkinsfile.oke, jenkinsScript.sh, okdtest.sh
Started  Kind Nightly 
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/974/
https://build.weblogick8s.org:8443/job/wko-kind-nightly-parallel/1226/
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/287/
=> Remove docker login from Jenkin script

jenkinsScript.sh, okdtest.sh
Remove docker login 
Jenkin Run
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/61/
=> Remove Docker Login from release/3.4

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItHorizontalPodAutoscalerCustomMetrics.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16280/
=> back port changes for intermittent test issue in HPA custom metrics test

operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/model-wdt-create-filter.py, operator/src/main/resources/scripts/model_wdt_mii_filter.py
This fixes a problem where the WDT model has no servers defined but with configured cluster defined.  This should causes a validation error.
=> Fix problem with a wdt without any servers defined but with cluster

operator/src/main/resources/scripts/introspectDomain.py, operator/src/main/resources/scripts/model-wdt-create-filter.py, operator/src/main/resources/scripts/model_wdt_mii_filter.py
This fixes a problem where the WDT model has no servers defined but with configured cluster defined.  This should causes a validation error.
=> Port fix model without anyservers

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Pod.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16434/
=> Modify the pod restart testcase with image update

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java
use introspector pod name instead of introspector job name when check introspector pod status
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/16329/
(the test failure is caused by OWLS-106814)
=> use introspector pod name instead of introspector job name when check introspector pod status

jenkinsScript.sh
https://build.weblogick8s.org:8443/job/wko34-kind-nightly-parallel/83/
=> Updated jenkinScript.sh to accept both java version and openjdk version output for checking java version

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItAddNewDynamicClusterUsingWlst.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItConsensusLeasingValidation.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDataHomeOverride.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDomainInPVUsingWDT.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwDynamicDomainInPV.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItHorizontalPodAutoscaler.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLiftAndShiftFromOnPremDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMaxConcurOptions.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCreateAuxImageWithImageTool.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCustomSslStore.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiSampleFmwMain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/ItRetryImprovementMisc.java
Add Cluster Resource tests into olcne profile
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16510/ (kind new)
https://build.weblogick8s.org:8443/job/wko-olcne-main-nightly/244/ (ocne run)
=> Add Cluster Resource tests into olcne profile

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWDTModelNoServer.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java, integration-tests/src/test/resources/wdt-models/model-configuredcluster-noserver.yaml, integration-tests/src/test/resources/wdt-models/model-emptytopology.yaml, integration-tests/src/test/resources/wdt-models/model-hasadminservername-namedservernotinserver.yaml, integration-tests/src/test/resources/wdt-models/model-noadminservername-hasadminserver.yaml, integration-tests/src/test/resources/wdt-models/model-noadminservername-hasadminserverlowercase.yaml, integration-tests/src/test/resources/wdt-models/model-noadminservername-hasmyadminserver.yaml, integration-tests/src/test/resources/wdt-models/model-noadminservername-noserver.yaml
add Functional Regression tests for OWLS-106473, OWLS-106637
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16674/
=> add Functional Regression tests for OWLS-106473, OWLS-106637

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsShutdownOption.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16718/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16762/
=> Fix for intermittent failure to start domain in ItPodsShutdown class

operator/src/main/resources/scripts/modelInImage.sh
Backport support of new WDT archive format that support zipped database wallet file
=> Back port WDT-107353, support new WDT archive using zipped database wallet file

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MonitoringUtils.java, integration-tests/src/test/resources/bash-scripts/images.properties, integration-tests/src/test/resources/exporter/grafanavalues.yaml, integration-tests/src/test/resources/exporter/promvalues.yaml
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16786/
=> Update prometheus images to avoid failures on local run

integration-tests/src/test/java/oracle/verrazzano/weblogic/kubernetes/ItVzMiiDomain.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/VerrazzanoUtils.java
This PR adds a new test in existing VZ IT class integration-tests/src/test/java/oracle/verrazzano/weblogic/kubernetes/ItVzMiiDomain.java  
https://build.weblogick8s.org:8443/view/WKO(Nightly)/job/v8o-kind-nightly/95
https://build.weblogick8s.org:8443/view/WKO(Nightly)/job/v8o-kind-nightly/104/
=> v8o: Add a testcase to use auxilary image in MII domain

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiCreateAuxImageWithImageTool.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind/11/
=> added fix for ItMiiCreateAuxImageWithImageTool failure due change of list for supported PackageManagers

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/TraefikParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonLBTestUtils.java, integration-tests/src/test/resources/traefik.template.properties
https://build.weblogick8s.org:8443/job/wko-kind-nightly-parallel/1294/
=> updated traefik install due helm chart values change

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/TraefikParams.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonLBTestUtils.java, integration-tests/src/test/resources/traefik.template.properties
https://build.weblogick8s.org:8443/job/wko40-kind-nightly-parallel/176
=> backport for traefik helm chart changes

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/366
=> Fix for intermittent failure for ItMultiDomainModelsScale

documentation/4.0/content/introduction/platforms/environments.md
As per [OWLS-107916](https://jira.oraclecorp.com/jira/browse/OWLS-107916) Update OpenShift certified versions
(@mriccell  Not sure if you wanted me to include the supported versions that you have marked as "This has not changed.")
=> update open shift support

operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java, operator/src/main/java/oracle/kubernetes/operator/helpers/PersistentVolumeClaimHelper.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainResource.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/InitializeDomainOnPV.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/IntrospectorJobEnvVars.java, operator/src/main/resources/scripts/introspectDomain.py, operator/src/test/java/oracle/kubernetes/operator/helpers/PersistentVolumeClaimHelperTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainV2Test.java, operator/src/test/resources/oracle/kubernetes/weblogic/domain/model/domain-sample-6.yaml
OWLS-108027 - Changes to conditionally wait for PVC to bind and minor cleanup.
=> OWLS-108027 - Changes to conditionally wait for PVC to bind and minor cleanup.

common/src/main/java/oracle/kubernetes/common/logging/MessageKeys.java, common/src/main/resources/Operator.properties, operator/src/main/java/oracle/kubernetes/operator/helpers/DomainValidationSteps.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainResource.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainValidationMessages.java, operator/src/main/java/oracle/kubernetes/weblogic/domain/model/KubernetesResourceLookup.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainValidationTest.java, operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainValidationTestBase.java
Validation OPSS wallet password in the specified secret at the java level for both MII and InitializeDomainOnPV cases.
=> OWLS-108025 Validate walletPassword in wallet password secrect

operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java, operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java
OWLS-107980 - Fix for unexpected introspector failure message in the operator logs.
=> OWLS-107980 - Fix for unexpected introspector failure message in the operator logs.

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItHorizontalPodAutoscalerCustomMetrics.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/K8sEvents.java, integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PodUtils.java
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/16905/
=> Added more debug info for intermittent HPA test failure

documentation/4.0/content/samples/azure-kubernetes-service/includes/prerequisites-01.txt, documentation/4.0/content/samples/azure-kubernetes-service/includes/prerequisites-02.txt
Changes:
- Add assignment requirements statement to domain on a pv and model in image sample.
=> WLS on AKS sample: add assignment requirements statement

documentation/site/content/managing-domains/domain-lifecycle/scaling.md
While attending a customer meeting with @mriccell , I observed that the scaling document would benefit with a reference to this blog post from Monica. See #4266 .
=> Edburns msft 4266 additional scaling blog post and video

documentation/site/content/samples/azure-kubernetes-service/domain-on-pv.md, documentation/site/content/samples/azure-kubernetes-service/includes/create-aks-cluster-storage.txt
1. Add doc tip for nfs.
2. Fix toc error.
=> Add doc tip for nfs

documentation/site/content/samples/azure-kubernetes-service/domain-on-pv.md, documentation/site/content/samples/azure-kubernetes-service/includes/download-samples-zip.txt, documentation/site/content/samples/azure-kubernetes-service/model-in-image.md, kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service/create-domain-on-aks.sh
This pull request involves updates to the documentation and scripts for setting up a WebLogic Kubernetes Operator on Azure Kubernetes Service (AKS). The main changes include updating version numbers, improving parameter preparation instructions, and fixing minor syntax issues.
* **Updated WebLogic Kubernetes Operator version**:
* Changed from `v4.1.8` to `v4.2.5` in multiple files to ensure compatibility with the latest release. (`documentation/site/content/samples/azure-kubernetes-service/includes/download-samples-zip.txt`, `documentation/site/content/samples/azure-kubernetes-service/model-in-image.md`, `kubernetes/samples/scripts/create-weblogic-domain-on-azure-kubernetes-service/create-domain-on-aks.sh`) [[1]](diffhunk://#diff-d98cf6841edd5201c4f29b711714e2d24afaf58c853ee6d6d55944c07bf6 …
=> Update AKS sample

documentation/site/content/samples/azure-kubernetes-service/domain-on-pv.md
modified:   documentation/site/content/samples/azure-kubernetes-service/domain-on-pv.md
- `rm -rf`.
=> On branch edburns-msft-6360-validate-script-locations

documentation/site/content/managing-domains/aks/_index.md
modified:   documentation/site/content/managing-domains/aks/_index.md
=> On branch edburns/o-572-remove-key-vault-mentions
