src/integration-tests/bash/cleanup.sh

Small change in acceptance test 'cleanup.sh' heuristic for detecting whether a kubernetes resource is namespaced.    
Passes integration test at https://app.wercker.com/Oracle/weblogic-kubernetes-operator/runs/integration-test/5a833d537f0b540001bbf1c2?step=5a833d5a646727000192e637
Also passes local tests.

Cleanup cleanup 1

---

src/integration-tests/bash/run.sh

The run_wlst_script function uses a variable "pyfile" that is not initialized to format the WLST command output file name. Changed it to the right variable "pyfile_lcl".
Signed-off-by: Dongbo Xiao <dongbo.xiao@oracle.com>

Fix pyfile output names in run_wlst_script

---

src/main/java/oracle/kubernetes/operator/Main.java
src/main/java/oracle/kubernetes/operator/helpers/HealthCheckHelper.java
src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
src/main/java/oracle/kubernetes/operator/logging/LoggingFormatter.java

Part of the delay in starting WebLogic servers is that the servers can no locate other servers via DNS if the other servers reside in Pods that aren't yet Ready.  This is because the default behavior is for Services to not expose endpoints that aren't yet ready.
There is an annotation for <= 1.7 and a Service field for 1.8+.

Allow server Services to expose DNS before Pod is ready

---

src/integration-tests/bash/run.sh
src/main/java/oracle/kubernetes/operator/helpers/AnnotationHelper.java
src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java

See Issue #27 for details.
Passes run.sh with QUICKTEST=true locally.    Passes Wercker too.    A full run fails during scaling due to an unrelated issue.   I don't think this particular change needs a full run to vet it since there are no Prometheus tests (yet).
@rjeberhard @russgold @bhabermaas

Issue-27: Create prometheus annotations on pods

---

src/integration-tests/bash/run.sh
src/main/java/oracle/kubernetes/operator/helpers/AnnotationHelper.java
src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java

Expand integration test 'QUICKTEST' mode to include domain lifecycle, operator lifecycle, and domain scaling tests.     This should only be checked in once the tests are stabilized.   This change is branched off of pending push 'Issue-27'.

Integration test 1

---

wercker.yml

This PR "saves" the artifacts created during the integration-test phase, i.e. `/pipeline/output/k8s-dir` so that is can be easily downloaded from the wercker web interface. 
After the integration-test pipeline has run, you can obtain the artifacts by clicking on the "Download artifacts" button under the "Run integration tests" heading - see the image below:

Store artifacts from integration-test so they can be easily downloaded

---

kubernetes/create-domain-job-inputs.yaml
kubernetes/create-domain-job.sh
kubernetes/internal/persistent-volume-template.yaml

The fix contains following content:
1. Add NFS related configuration in kubernetes/internal/persistent-volume-template.yaml
2. Add two configurable parameters (persistenceType and nfsServer) in kubernetes/create-domain-job-inputs.yaml
3. Update kubernetes/create-domain-job.sh
3.1 Validate the two input parameters. The value of persistenceType must be hostPath or nfs. If using nfs, nfsServer must be specified.
3.2 Generate the correct persistent volume yam file based on input parameters.
4. Fix a typo.  validatePersistenVolumeName --> validatePersistentVolumeName
Jenkins passed http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator/86/

Add persistent volume configuration to support NFS

---

kubernetes/create-weblogic-domain.sh
kubernetes/create-weblogic-operator.sh
src/test/scripts/unit-test-create-weblogic-domain.sh
src/test/scripts/unit-test-create-weblogic-operator.sh
src/test/scripts/unit-test-generate-weblogic-operator-cert.sh

Fix unit test and runtime script problem parsing 'cd' stdout that occurs on some linux boxes.
Unit tests now pass.
Local integration testing in progress (see also pending Wercker results).

Unit test and run-time fix

---

src/main/java/oracle/kubernetes/operator/Main.java
src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java

Earlier, we changed the lifetime of Services created by the operator.  Part of that change was correct, but unfortunately, part of it wasn't.
We are preserving the change to create a per-cluster Service and having this Service as the only backend of the cluster's Ingress.
However, this PR restores the original lifetime of the per-managed server Services to match that of the per-managed server Pod.  The ongoing work with dynamic clusters demonstrated that its better to delete the Services as Pods are deleted so that DNS lookups fail.  The WebLogic clustering subsystem more quickly identifies shutdown servers if their DNS lookups fail than if the DNS lookup is successful but the node manager is unavailable.

Restore per-managed server service lifetime

---

src/integration-tests/bash/cleanup.sh
src/integration-tests/bash/lease.sh
wercker.yml

**Test status:   Passes locally and Wercker.**
I think I traced down the problem with ‘lease.sh’ and a new problem with ‘cleanup.sh’ which was revealed after fixing lease.sh.   In both cases, it looks like kubectl client behavior changed.    
For example, I see failed runs on Wercker with version 1.10 client and passing runs with a 1.9 client.  
In lease.sh, a ‘kubectl replace -f’ stopped working with config-maps (it apparently has stricter usage requirements now), and in cleanup.sh the default output format of a ‘kubectl get’ appears to have changed.    
Fixes:
- Modify lease.sh to use 'k create' and  'k delete' pattern instead of 'k replace' pattern for config maps.   
- To use jsonpath instead of 'awk' when in k get queries for abandoned resources.  For some reason, awk has stopped …

Int test leasing 2

---

operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java
operator/src/test/java/oracle/kubernetes/operator/create/ConfigMapHelperConfigTest.java

The delete script for removing all domains does it by looking for kubernetes artifacts with a domainUID tag.  Currently, the operator creates a config map per domain namespace containing scripts that should be shared by all domains in that namespace, and tags it with a domainUID="" label.
This causes the delete script for removing all domains to remove this config map too, and, the next time the operator needs to create a domain in that namespace, it has to recreate the config map for the scripts in that namespace.
To prevent this, change the label on the config map from 'domainUid=""' to 'operatorName="<operatorNamespace>"' - that is, tag it as operator related instead of domain related.
Note: eventually we should add a script to remove the operator.  That script can use the …

Replace the domainUID="" label on the per-domain operator config map with an operatorName="<operatornamespace>" label

---

wercker.yml

pick up new version of the maven step which has fix for apache's change from md5 to sha1 checksums

fix checksum error in build

---

operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java
operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java
operator/src/main/resources/Operator.properties
operator/src/main/resources/scripts/livenessProbe.sh
operator/src/main/resources/scripts/readState.sh
operator/src/main/resources/scripts/readinessProbe.sh
operator/src/main/resources/scripts/start-server.py
operator/src/main/resources/scripts/startServer.sh
operator/src/main/resources/scripts/stop-server.py
operator/src/main/resources/scripts/stopServer.sh

The change includes following content
1. Move the shell and python scripts out of operator java helper source code to operator/src/main/resource/scripts
2. Modify the helper to load scripts from /scripts directory that in the operator jar file

simplify operator script maintenance

---

site/design.md

minor edits

---

site/developer.md

1.  Please review the Requirements section.
2. git clone https://github.com/oracle/weblogic-kubernetes-operator command, should it be
git clone https://github.com/oracle/weblogic-kubernetes-operator.git ?
3. In the Running integration tests, is this sentence ok or does it need to be modified or eliminated:
"Tests will run against Kubernetes 1.7.x and 1.8.x currently. There are some issues with 1.9, which are being worked on."

mostly minor edits

---

site/elk.md

I've re-worked this doc so it reads in English, however, I am not at all sure about its content. Let me know if I need to make additional changes.

re-worked this doc

---

site/apache.md

Basic editing pass. Two things to note:
1. I changed the capitalization scheme to line up with the other docs (we are using sentence capitalization versus title capitalization.
2. Because its official name is the Apache HTTP Server, if we refer to it as the Apache web server, we don't need to capitalize any word other than Apache.

editing pass

---

site/scaling.md

Minor edits, however, I removed this Note: In the technology preview release, only WebLogic Server configured clusters are supported by the operator, and the operator will scale up only to the number of Managed Servers that are already defined. Support for WebLogic Server dynamic clusters, and for scaling configured clusters to more servers than are defined, is planned for a future release.

minor edits; removed limitations note

---

kubernetes/internal/create-weblogic-domain.sh
kubernetes/internal/voyager-ingress-template.yaml
site/voyager.md
src/integration-tests/bash/run.sh

two changes to the Voyager Ingress resources:
1. Enable session sticky.
2. Loose the hostname-based routing since there is only one cluster in created WebLogic domain via create-weblogic-domain.sh.

Voyager update

---

operator/pom.xml
operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ClientPool.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java
operator/src/main/java/oracle/kubernetes/operator/steps/ConfigMapAfterStep.java
operator/src/main/java/oracle/kubernetes/operator/work/ThreadFactorySingleton.java
operator/src/test/java/oracle/kubernetes/TestUtils.java
operator/src/test/java/oracle/kubernetes/operator/ConfigMapWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java
operator/src/test/java/oracle/kubernetes/operator/DomainWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/IngressWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/PodWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/ServiceWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/WatcherTestBase.java
operator/src/test/java/oracle/kubernetes/operator/wlsconfig/WlsDomainConfigTest.java

The issue was that Main.begin was running the steps in a fiber on a separate thread, so that there was race conditions on when the async requests were made. This change isolates the step construction from running them, allowing the test to run them on a synchronous test fiber.
It also restructures setting up the steps to make it clearer what is going on.

Let unit test run resource list steps

---

operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java
operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java
operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfoFactory.java
operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfoManager.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServerKubernetesObjectsFactory.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServerKubernetesObjectsManager.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java
operator/src/test/java/oracle/kubernetes/operator/ServiceHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/IngressHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperConfigTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ServerKubernetesObjectsLookupTest.java

The intention is that you can lookup servers (across domains) using the server legal name (i.e. the Pod name).
This map must stay in-sync with the per-domain server maps held by the DomainPresenceInfo instances.

Keep server map in sync with domain presence info server maps

---

kubernetes/internal/generate-security-policy.sh

bash string substitution such as: for i in ${TARGET_NAMESPACES//,/ } may result in "Bad substitution error" in some environments such as under dash shell in ubuntu. Proposed fix is to ensure generate-security-policy.sh is run with bash.

specify bash in generate-security-policy.sh

---

operator/src/main/java/oracle/kubernetes/operator/Main.java

Proposed change to address the issue where domain is not started due to "Watch event ignored for domain with domain UID domain1 because no change to domain specification” in operator log when a new domain is added.

fix issue where operator mistaken a new domain as existing one

---

src/integration-tests/bash/run.sh
wercker.yml

These changes will fix the hanging of the `mvn -P integration-tests install` in `run.sh` and will also fail the pipeline if `run.sh` fails

Mark build timeout

---

operator/src/main/java/oracle/kubernetes/operator/Workarounds.java
operator/src/main/java/oracle/kubernetes/operator/helpers/IngressHelper.java
operator/src/main/java/oracle/kubernetes/operator/steps/DefaultResponseStep.java
operator/src/test/java/oracle/kubernetes/LogMatcher.java
operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/IngressHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/steps/DeleteIngressListStepTest.java
operator/src/test/java/oracle/kubernetes/operator/work/AsyncCallTestSupport.java
operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java

Rewrote disabled IngressHelperTest as a pure unit test
Refactored IngressHelper
Implemented workaround for bug in k8s Java client
Note: IngressHelper has only one method, which creates a CreateClusterStep, and is called once (outside of the tests) from the steps package. Maybe that step should be extracted and moved to the steps package and IngressHelper should be removed entirely?

Ingress helper test

---

operator/src/main/java/oracle/kubernetes/operator/http/HttpClient.java
operator/src/test/java/oracle/kubernetes/operator/http/HttpClientTest.java

Add support for headless service in HttpClienet.getServiceURL(). Before this fix, the method always build URL from service clusterIP, which results in invalid URL for headless service.

Support headless service in HttpClient.getServiceURL()

---

kubernetes/create-weblogic-domain-inputs.yaml
kubernetes/internal/create-weblogic-domain.sh
operator/src/test/java/oracle/kubernetes/operator/create/CreateDomainInputsValidationTest.java

Add code to the create domain script to check whether the specified loadBalancerVolumePath and the required file under the directory exist. If either one does not exist, the script fails with a validation error.
@rjeberhard @rosemarymarano

Issue#330: Add validation for Apache loadBalancerVolumePath

---

operator/src/main/java/oracle/kubernetes/operator/Main.java

Saw the following NPE in operator log file from a failed jenkins integration test run:
{"timestamp":"07-24-2018T21:28:48.035+0000","thread":43,"level":"WARNING","class":"oracle.kubernetes.operator.Watcher","method":"watchForEvents","timeInMillis":1532467728035,"message":"Exception thrown: {0}","exception":"\njava.lang.NullPointerException\n\tat java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)\n\tat java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)\n\tat oracle.kubernetes.operator.Main.dispatchServiceWatch(Main.java:894)\n\tat oracle.kubernetes.operator.Watcher.handleRegularUpdate(Watcher.java:144)\n\tat oracle.kubernetes.operator.Watcher.watchForEvents(Watcher.java:121)\n\tat oracle.kubernetes.operator.Watcher.doWatch(Watcher.java:94)\n\tat …

replace put with remove in Main.dispatchServiceWatch method

---

kubernetes/create-weblogic-domain-inputs.yaml
kubernetes/internal/create-weblogic-domain.sh
operator/src/test/java/oracle/kubernetes/operator/create/CreateDomainInputsValidationTest.java

Add validation in create-weblogic-domain.sh to check if the specified directory and the required Apache config file exist or not. The script fails if either is missing.
@rjeberhard

Issue #330: Add validation for loadBalancerVolumePath

---

src/integration-tests/bash/cleanup.sh
src/integration-tests/bash/run.sh

updated integration test src/integration-tests/bash/run.sh and cleanup.sh to use helm charts - 1.0 style domain charts and 2.0 style operator helm charts, instead of scripts.
wercker test would still be using install scripts with this change. Will continue to get wercker to work with helm charts in OWLS-67340

integration tests with helm charts

---

operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java

The operator already set some internally environment variables when it creates the WLS server pods. This change allows a custom env to refer to the following internal env: 
DOMAIN_NAME, SERVER_NAME, DOMAIN_HOME, ADMIN_NAME and ADMIN_Port.
For example, 
- name: JAVA_OPTIONS
value: "-Dweblogic.StdoutDebugEnabled=false -Dtangosol.coherence.role=$(SERVER_NAME)"
@mriccell @rjeberhard

Allow a server Pod env to refer to envs that are established internally by the operator

---

src/integration-tests/bash/run.sh
wercker.yml

This proposed change should address the intermittent wrecker test failure due to T3channel test. 
- The FQDN of the OCI instance used in the URL for connecting to the T3 channel service does not work if the admin server pod happens to be running on a k8s node on the same OCI instance as specified in the OCI_K8S_WORKER0_HOSTNAME env var in wercker. It does however work if the admin server pod is running on a k8s node that resides on a different OCI instance. The test is modified to use the public IP address of the OCI instance, OCI_K8S_WORKER0_IP in the URL for connecting to the T3 channel service.
- Fixed test code that wait for the T3Channel service to be available.
passed jenkins http://wls-jenkins/job/weblogic-kubernetes-operator/486/ and wrecker
passed wercker integration-test-185 …

Fix wercker t3channel test

---

operator/src/main/java/oracle/kubernetes/operator/Main.java
src/integration-tests/bash/run.sh

1. Remove code that install helm from setup_jenkins in src/integration-tests/bash/run.sh. helm installation is already done by devops-k8s-install.sh.
2. Address NPE seen in recent jenkin failures such as http://wls-jenkins/job/weblogic-kubernetes-operator/511/consoleText 
{"timestamp":"08-15-2018T16:29:57.346+0000","thread":36,"level":"WARNING","class":"oracle.kubernetes.operator.Watcher","method":"watchForEvents","timeInMillis":1534350597346,"message":"Exception thrown: {0}","exception":"\njava.lang.NullPointerException\n\tat java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)\n\tat java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)\n\tat oracle.kubernetes.operator.Main.dispatchServiceWatch(Main.java:963)\n\tat …

Remove jenkins helm install runsh

---

operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java

Use WLS managed server name, instead of listenAddress, when handling startupControl=ALL.  This resolves instability of managed servers due to changed env properties when startupControl=ALL. This bug fix is much more simple than the previous fix for this issue.

updated fix for OWLS-67651: startupControl=ALL instability

---

kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorInputsFileTest.java
operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsRetriever.java
operator/src/test/java/oracle/kubernetes/operator/MainTest.java
operator/src/test/java/oracle/kubernetes/operator/wlsconfig/WlsRetrieverTest.java

Proposed changes to fix java integration tests failures on jenkins
1) Noticed that DELETE domain watch events were sent even after the domain was re-created in the domain lifecycle test. Adding check for domain metadata creationTimeStamp so delete domain event for old domain creation won’t be processed.
2) WlsRetriever$WithHttpClientStep sometimes called with a null service. This results in invalid URL for getting the configuration from WLS admin server, and WlsRetriever would retry using the same invalid URL. WithHttpClientStep constructor would now reject null service parameter and throw IllegalArgumentException. WlsRetriever will eventually get called with a valid admin server service object.
3) Unrelated to java integration test - Update operator version number in …

Java int test fix

---

operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/main/resources/scripts/livenessProbe.sh
operator/src/main/resources/scripts/readState.sh
operator/src/main/resources/scripts/readinessProbe.sh
operator/src/main/resources/scripts/start-server.py
operator/src/main/resources/scripts/startServer.sh
operator/src/main/resources/scripts/stop-server.py
operator/src/main/resources/scripts/stopServer.sh
operator/src/test/java/oracle/kubernetes/operator/helpers/AdminPodHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
src/integration-tests/bash/run.sh

WL Pod liveness, readiness, start, stop script update: 
* use env vars instead of command line args
* parameterize domain-home + domain-uid + nodemgr-home
* reduce boot time by about 15 seconds (replace hard coded sleep and instead monitor node mgr output to find when it's ready)
* modify run.sh to provide finer-grained control over when to enable helm
https://jira.oraclecorp.com/jira/browse/OWLS-67684

Op20scriptenhdev

---

integration-tests/README.md
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java

One of the java integration test use case is failing with connection refused errors for rest calls.
After the operator helm chart is deleted and re-installed, the service is not ready immediately to take requests, rest call is failing with connection refused errors. Anthony suggested to add retry logic if this error is seen, the issue is not seen after a 5 sec sleep. It needs ~5 sec before the service can accept requests, added retry logic anyway.

adding retry logic for rest call

---

kubernetes/charts/weblogic-domain/templates/_domain-custom-resource.tpl
kubernetes/charts/weblogic-domain/templates/_traefik-security.tpl
kubernetes/charts/weblogic-domain/templates/_traefik.tpl
kubernetes/charts/weblogic-domain/templates/_voyager-ingress.tpl
kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateDomainGeneratedFilesBaseTest.java
kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateDomainGeneratedFilesOptionalFeaturesEnabledTestBase.java
kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateDomainGeneratedFilesVoyagerTestBase.java
kubernetes/src/test/java/oracle/kubernetes/operator/create/ScriptedDomainYamlFactory.java
kubernetes/src/test/java/oracle/kubernetes/operator/helm/CreateDomainGeneratedFilesInvalidDNSNameIT.java
kubernetes/src/test/java/oracle/kubernetes/operator/helm/CreateDomainGeneratedFilesInvalidDNSNameVoyagerIT.java
kubernetes/src/test/java/oracle/kubernetes/operator/helm/CreateDomainGeneratedFilesOptionalFeaturesDisabledIT.java
kubernetes/src/test/java/oracle/kubernetes/operator/helm/CreateDomainGeneratedFilesVoyagerIT.java
kubernetes/src/test/java/oracle/kubernetes/operator/helm/HelmDomainYamlFactory.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/DomainYamlFactory.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/ParsedKubernetesYaml.java

In preparation for removing the domain chart piecemeal, ensure that it has the same functionality as the scripts, so that nothing is lost.

Use additional tests to upgrade helm charts to match scripts

---

integration-tests/src/test/resources/setupenv.sh

Tag operator image with latest which will be used later to push to a registry on jenkins. Currently jenkins runs are failing on develop branch, which will fix the issue.

tag operator image to latest for jenkins

---

site/scaling.md

Automatic Scaling of WebLogic Clusters on Kubernetes, as per Pani's request.

remove references to Blog

---

model/src/main/java/oracle/kubernetes/weblogic/domain/v1/DomainStorage.java

Add toString(), equals() and hashcode() to DomainStorage.
This causes intermittent issues when the new storage element is used in the domain resource.
@anpanigr @vanajamukkara @maggiehe00

Fix an intermittent issue caused by missing equals in DomainStorage

---

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/LoadBalancer.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/PersistentVolume.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java
integration-tests/src/test/resources/domain3.yaml
integration-tests/src/test/resources/domain4.yaml
integration-tests/src/test/resources/wldf/wldf.py
kubernetes/samples/scripts/common/validate.sh
kubernetes/samples/scripts/create-weblogic-domain-load-balancer/create-load-balancer-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain-load-balancer/create-load-balancer.sh
kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/create-pv-pvc-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/create-pv-pvc.sh
kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/pv-template.yaml
kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/pvc-template.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/common/utility.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-job-template.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/delete-domain-job-template.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/domain-custom-resource-template.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/wdt_model_configured.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/wdt_model_dynamic.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wlst/create-domain.py
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/test/java/oracle/kubernetes/operator/helpers/AdminPodHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
src/integration-tests/bash/run.sh

1) Default domainHome to /shared/domains/domainUID
2) Default logHome to /shared/logs/domainUID
3) Support custom pvc 
4) Support shared pv/vpc - added a new input property for pv/pvc base name
5) Decouple the output location of the pv/pvc, domain, and load balancer scripts
6) Modify the integration test code to work with the new samples - did not change the test logic, which means we still have one pv per domain.
Note: currently there is an intermittent issue in the integration test with the changes. 
Item #1 and #2 are based on the following summary in the slack channel on 10/12/2018.
Tom Moreau [11:35 AM]
Here's a summary of our domain pv decisions (I ran this by Ryan this morning):
1)    the architectural statement (which does not imply large amounts of work for 2.0):   previously, we …

Support custom PVC, default domain home and default log home

---

model/pom.xml
model/src/main/java/oracle/kubernetes/weblogic/domain/AdminServerConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/ClusterConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfiguratorFactory.java
model/src/main/java/oracle/kubernetes/weblogic/domain/ServerConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v1/Domain.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v1/DomainSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v1/DomainV1Configurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v1/ServerSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v1/ServerSpecV1Impl.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/BaseConfiguration.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Configurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ServerSpecV2Impl.java
model/src/test/java/oracle/kubernetes/json/GenerateSchema.java
model/src/test/java/oracle/kubernetes/weblogic/domain/DomainTestBase.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v1/DomainStorageTest.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v1/DomainV1Test.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Test.java
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample-3.yaml
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample.yaml
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServersUpStepTest.java

Moves the image fields from BaseConfiguration to the domain spec.
Adds unit tests for DomainStorage
Restricts nodePort to the admin server in v2
Reflects the above changes in the domain resource samples

Domain cleanup

---

kubernetes/charts/weblogic-operator/templates/_operator-clusterrole-general.tpl
kubernetes/charts/weblogic-operator/templates/_operator-clusterrole-namespace.tpl
kubernetes/charts/weblogic-operator/templates/_operator-clusterrole-nonresource.tpl
kubernetes/charts/weblogic-operator/templates/_operator-clusterrolebinding-auth-delegator.tpl
kubernetes/charts/weblogic-operator/templates/_operator-clusterrolebinding-discovery.tpl
kubernetes/charts/weblogic-operator/templates/_operator-clusterrolebinding-general.tpl
kubernetes/charts/weblogic-operator/templates/_operator-clusterrolebinding-nonresource.tpl
kubernetes/charts/weblogic-operator/templates/_operator-role.tpl
kubernetes/charts/weblogic-operator/templates/_operator-rolebinding-namespace.tpl
kubernetes/charts/weblogic-operator/templates/_operator-rolebinding.tpl
kubernetes/charts/weblogic-operator/templates/_operator.tpl
kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorGeneratedFilesTestBase.java
kubernetes/src/test/java/oracle/kubernetes/operator/helm/OperatorChartIT.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/GeneratedOperatorObjects.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/KubernetesArtifactUtils.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/ParsedApacheSecurityYaml.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/ParsedKubernetesYaml.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/ParsedTraefikSecurityYaml.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/ParsedVoyagerOperatorSecurityYaml.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/ParsedWeblogicOperatorSecurityYaml.java
src/scripts/initialize-internal-operator-identity.sh

There are two fixes here to get the script working that generates the internal keys and certificates for the operator's REST interface:
1) The path to keytool was wrong
2) The operator didn't have permission to create CMs and Secrets in its own namespace

Add operator role, rolebinding and fix keytool path

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/LoadBalancer.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/PersistentVolume.java
kubernetes/samples/scripts/create-weblogic-domain-load-balancer/create-load-balancer.sh
kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/README.md
kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/create-pv-pvc.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain.sh

The samples keep the following output dir hierarchy with this change:
"\<user-specified-outputdir\>\/weblogic-domains/\<domainUID\>" for domain artifacts.
"\<user-specified-outputdir\>/pv-pvcs" for pv/pvcs
"\<user-specified-outputdir\>/load-balancers/\<domainUID\>" for load balancers 
@anpanigr @vanajamukkara @maggiehe00 

Restore output dir hierarchy in samples

---

model/src/main/java/oracle/kubernetes/weblogic/domain/v1/DomainSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v1/ExportedNetworkAccessPoint.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/AdminServer.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/BaseConfiguration.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/Cluster.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Configurator.java
model/src/test/java/oracle/kubernetes/weblogic/domain/DomainTestBase.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/AdminServerTest.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/BaseConfigurationTestBase.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/ClusterTest.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Test.java
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample-3.yaml

The scaling test was failing because the equals() method on the Domain has ignoring v2 properties. The change also corrects the location of the exportedNetworkAccessPoints property, moving it from the domain to the adminServer.

Fix scaling test

---

model/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/EffectiveConfigurationFactory.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v1/DomainSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v1/DomainV1Configurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Configurator.java
model/src/test/java/oracle/kubernetes/weblogic/domain/DomainTestBase.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v1/DomainV1Test.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Test.java
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample-2.yaml
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample.yaml
operator/src/test/java/oracle/kubernetes/operator/rest/RestBackendImplTest.java

This restores the ability to configure the default replica count at the domain level, initializing it to 0.

Make default replica count configurable in v2

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/resources/domain1.yaml
integration-tests/src/test/resources/domain2.yaml
integration-tests/src/test/resources/domain3.yaml
integration-tests/src/test/resources/domain4.yaml
integration-tests/src/test/resources/domain5.yaml
integration-tests/src/test/resources/domain6.yaml
integration-tests/src/test/resources/domain7.yaml
kubernetes/samples/scripts/create-weblogic-domain-load-balancer/create-load-balancer-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain-load-balancer/create-load-balancer.sh
kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/README.md
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/README.md
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh

1) Add doc for create-domain sample scripts.
2) Update the WDT script to use WDT version 0.14 and use the new feature for domain home location.
3) Remove domainName from the create-domain-inputs files
4) Update Java integration test domain inputs files.
Java integration test passed on Jenkins: http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/263/
@anpanigr @vanajamukkara @maggiehe00

Sample domain doc, uptake WDT 0.14 and remove domainName

---

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java
integration-tests/src/test/java/oracle/kubernetes/operator/ITOperator.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/LoadBalancer.java
integration-tests/src/test/resources/charts/traefik/host-routing.yaml
integration-tests/src/test/resources/charts/traefik/values.yaml
integration-tests/src/test/resources/domain2.yaml
integration-tests/src/test/resources/domain3.yaml
integration-tests/src/test/resources/domain4.yaml
integration-tests/src/test/resources/domain5.yaml
integration-tests/src/test/resources/domain6.yaml
integration-tests/src/test/resources/domain8.yaml

Tests are changed to use load balancer helm chart for traefik instead of sample scripts.
One load balancer is used for all the domains with host routing for ingress.
Apache load balancer test is commented for now as its not yet changed to helm chart.
On jenkins, integration tests have intermittent failures on develop branch, I see the same failures when ran with these changes. Dongbo is aware of these failures.
http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/275/console
@anpanigr @doxiao

change java integration tests to use load balancer helm chart for traefik

---

model/src/main/java/oracle/kubernetes/weblogic/domain/v1/ServerSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/BaseConfiguration.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ProbeTuning.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ServerPod.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ServerSpecV2Impl.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v1/DomainV1Test.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Test.java
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample-2.yaml
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample.yaml

OWLS-69904: This change moves the already-implemented fields under a new serverPod element.

Move env, livenessProbe and readinessProbe under serverPod

---

json-schema-maven-plugin/src/main/java/oracle/kubernetes/json/mojo/ExternalSchema.java
json-schema-maven-plugin/src/main/java/oracle/kubernetes/json/mojo/JsonSchemaMojo.java
json-schema-maven-plugin/src/main/java/oracle/kubernetes/json/mojo/Main.java
json-schema-maven-plugin/src/main/java/oracle/kubernetes/json/mojo/MainImpl.java
json-schema-maven-plugin/src/test/java/oracle/kubernetes/json/mojo/JsonSchemaMojoTest.java
json-schema-maven-plugin/src/test/java/oracle/kubernetes/json/mojo/TestMain.java
json-schema/src/main/java/oracle/kubernetes/json/SchemaGenerator.java
json-schema/src/test/java/oracle/kubernetes/json/SchemaGeneratorTest.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ProbeTuning.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ServerPod.java

With this change, it is now possible to configure the plugin to:
- disable the "additionalProperties" field (required for K8s CRD validation)
- generate object fields in-line rather than using the $ref field (required for K8s CRD validation)
- specify the name and location of the file to generate (needed to generate one for validation and one for the website)

Support more options for schema generation

---

model/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Configurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ServerSpec.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Test.java
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample.yaml

1) Add weblogicConfigurationOverridesSecretNames to domain spec.
2) add unit tests
Note: part2 will be done in another PR, which will update domain introspector job to mount the specified secrets. Part2 needs to be done in the introspector branch or in develop branch after the introspector branch is merged.
Questions @rjeberhard @moreaut @mriccell : shall we shorten the attribute name  weblogicConfigurationOverridesSecretNames? We have another long name in the domain spec: weblogicConfigurationOverridesConfigMapName, which I think can be shortened as well.

OWLS-69262 part1: add weblogicConfigurationOverridesSecretNames to domain spec

---

model/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Configurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ServerSpec.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Test.java
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample.yaml

Change weblogicConfigurationOverridesSecretNames  to configOverrideSecrets.

Shorten weblogicConfigurationOverridesSecretNames 

---

kubernetes/create-weblogic-operator-inputs.yaml

On Docker hub the image available under: oracle/weblogic-kubernetes-operator path.

fix weblogic-kubernetes-operator image path

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java

changed curl command to send request to different domains using the below format for traefik host routing ingress..
curl --silent -H 'host: domain1.org' http://${HOSTNAME}:30305/testwebapp/
Now the request is sent to the correct domain. earlier the webapp request was not sent to the correct domain and the test was failing with 
[ERROR] test5CreateConfiguredDomainInTest2NS(oracle.kubernetes.operator.ITOperator) Time elapsed: 626.775 s <<< ERROR!
java.lang.RuntimeException: FAILURE: Load balancer can not reach server domain4-managed-server1
now its failing with below error because of the issue - https://jira.oraclecorp.com/jira/browse/OWLS-70125
[ERROR] test5CreateConfiguredDomainInTest2NS(oracle.kubernetes.operator.ITOperator)  Time elapsed: 1,316.09 s  <<< ERROR! …

fix curl command to send request to different domains

---

operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java
operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceMonitor.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServerKubernetesObjectsManager.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ServerKubernetesObjectsLookupTest.java

Added logic to monitor the behavior of the test that is failing in wercker. It should have virtually no impact in production (just calling some setters).
An earlier version of this did fail - only enough to rule out some possible sources of error. I have added some more logic in hopes of figuring out what is going on.

Monitor failing test

---

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java
integration-tests/src/test/java/oracle/kubernetes/operator/ITOperator.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java
wercker.yml

Below changes are made
adding more frequently failing liveness probe test to QUICKTEST with more debug messages
removed domain lifecycle and operator lifecycle tests from QUICKTEST as they never failed
Ready to merge

changes in what to run in QUICKTEST and add debug for liveness probe test

---

operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java
operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsDynamicServerConfig.java
operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsServerConfig.java
operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServersUpStepTest.java

WlsDomainConfig.getServerConfigs() returns all managed servers, whether or not they are part of a cluster. There is currently no way to obtain only those that are not clustered. This leads the ManagedServersUpStep to check those servers twice: once as though they are not clustered, and once as though they are clustered. 
When the serverStartPolicy is IF_NEEDED, that leads named managed servers always to be run, which is incorrect.
This change has the step process the clusters first, recording the servers found locally, in order to avoid checking them as though they are not clustered. It fixes both OWLS-70348 and OWLS-70351.
Note: the introspector branch will provide a new method that returns only the non-clustered servers. At that point, the additional logic will no longer be needed in …

Handle named servers according to their cluster association

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java
kubernetes/samples/scripts/delete-weblogic-domain-resources.sh

- Moved the sh script from kubernetes/ to kubernetes/samples/scripts/.
- Removed support of special domain UID value "all", which would remove all domain resources in a cluster, regardless of domain UIDs.

OWLS-70324: make delete-weblogic-domain-resources.sh a sample, remove delete all domains option

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java

Updated to reflect there is no more domainUID-labeled ingress.

Fixing Broken Tests of Deleting Domain Sh

---

operator/src/main/resources/scripts/introspectDomain.py

Fixes error found in admin server log file:
<Error loading the situational config files: weblogic.descriptor.DescriptorException: Unmarshaller failed: com.bea.xml.XmlException: javax.management.InvalidAttributeValueException: The Name attribute cannot be modified after the MBean domain1:Name=AdminServer,Location=managed-server3,Type=ServerConfig has been created.>
by removing  'combine-mode="replace"'
from <network-access-point><name> attribute in the situational config file generated in the introspect domain job.

Fix situational config file loading error found in admin server log

---

site/quickstart.md

Trying this again. "A Very Rough first draft of a Quick Start Guide. The steps/categories seem OK but we need to fill them in with the actual commands that users will perform. This guide is a tutorial for users to create a WebLogic Kubernetes deployment in a Kubernetes cluster. It must contain every detail needed to accomplish the goal with verification steps where needed. I'm putting it out there for the SMEs to fill in the details."
Tom, I think I (adequately) addressed your comments from my first go around; if not, please let me know.

add Quick Start Guide to docs

---

kubernetes/samples/scripts/delete-weblogic-domain-resources.sh

- Fixed path to internal/utility.sh.
- Updated to remove more references to special domain value "all" (no longer supported).

Fixing "internal/utility.sh: No such file or directory"

---

operator/src/main/resources/scripts/startServer.sh
operator/src/main/resources/scripts/stopServer.sh

Speed up the performance of shutting down the mocked servers by
having stopServer.sh create a marker file that says that stopServer.sh was called,
and by having startServer.sh poll every 5 seconds and exit as soon as it finds the marker file.
(v.s. startServer.sh looping forever, so that the pod never stops naturally thus kubernetes
has to wait until its timeout is reached then kill the pod)

Speed up mock server pod shutdown

---

integration-tests/src/test/java/oracle/kubernetes/operator/ITOperator.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java
integration-tests/src/test/resources/OperatorIT.properties
integration-tests/src/test/resources/domain-home-on-pv/create-domain-auto-sit-config.py
integration-tests/src/test/resources/domain-home-on-pv/create-domain-script.sh
integration-tests/src/test/resources/domain-home-on-pv/create-domain.py
integration-tests/src/test/resources/domain11.yaml

Changes made to shutdown the domain even if the test fails on jenkins. 
Run cleanup.sh at the end for jenkins
Leave the domain running if the test fails on standalone mode
Reduced the number of iterations for pod/server status checking(which means from ~8 mins to ~4 mins) as there are issues which need to be fixed, there is no point in waiting longer time. 
Other changes for testing automatic sit config overrides which are not enabled in the test
wercker ran fine, Quick test ran fine on jenkins, testing full test suite on jenkins.
http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/609/console
full test suite run 
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/610/consoleFull
@rjeberhard so far so good on the full …

shutdown domain in all cases on jenkins and more

---

operator/src/main/resources/scripts/introspectDomain.py

Added code to generate an error if the user does not include a version.txt file in their situational config directory.
The version.txt must have the content "2.0" to be accepted in Operator 2.0.  Future versions could use this versioning to guide parsing or the custom config files. Could is the operative word...

OWLS-70527 : version.txt support in situational config

---

model/src/main/java/oracle/kubernetes/weblogic/domain/ClusterConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/EffectiveConfigurationFactory.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/Cluster.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/Domain.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Configurator.java
model/src/test/java/oracle/kubernetes/weblogic/domain/DomainTestBase.java
operator/src/main/java/oracle/kubernetes/operator/helpers/RollingHelper.java

Proposal: implement Cluster.maxUnavailable, but have it just be an Integer (the absolute number of servers) rather than IntOrString.  We would therefore drop support for values like, "10%" and instead only support an absolute number.
The default would be 1.
We would still defer (probably forever) supporting maxSurge.

Support maxUnavailable

---

kubernetes/samples/scripts/create-weblogic-domain-pv-pvc/create-pv-pvc-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/domain-template.yaml

1) Correct the volumeMount configuration in domain-home-in-image
2) Revert an intentional change (introduced in PR#583) in create-pv-pvc inputs file.

Correct volumeMount config in domain-home-in-image sample plus a cleanup

---

kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain.sh

Right now, the domain-home-in-image Docker project uses unpatched WebLogic 12.2.1.3 image oracle/weblogic:12.2.1.3-developer.  This option allows us to test with 19c or patched 12.2.1.3 image.

Add customization of base image in domain-home-in-image sample

---

operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java
operator/src/main/resources/scripts/introspectDomain.py

Fix a problem found by @vanajamukkara where custom override secret macros such as ${secret:mysecretname.username} could not be resolved because the Operator pod was not mounting a path named 'mysecretname' in the expected location for the introspector job.   
For example, an override secret named 'secret-name' with key 'secret-key' was showing up in '/weblogic-operator/config-overrides/secret-key' instead of the expected '/weblogic-operator/config-overrides/secret-name/secret-key'.
This fix passes local ad-hoc testing.

Fix bug in override secret mount path

---

site/config-overrides.md

This is the initial draft of the config overrides documentation.

Config overrides site doc

---

model/src/main/java/oracle/kubernetes/weblogic/domain/v2/BaseConfiguration.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainSpec.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java
operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java
operator/src/test/java/oracle/kubernetes/operator/helpers/DomainIntrospectorJobTest.java

Fix for 'running servers' count for doing introspection job.  Also added some logic for looking at 'Server Start' policy for best effort in determining if we're  going from zero to one or more managed server pods.

OWLS-70593: OPERATOR: CUSTOM OVERRIDE CONFIG MAP DOES NOT TAKE EFFECT WHEN DYNAMICALLY ADDED

---

site/helm-charts.md

Since the certificate and key for the external REST interface are not in secrets for 2.0, should we add a warning about securing Helm, possibly a link to https://docs.helm.sh/using_helm/#securing-your-helm-installation ?
Is the "Debugging options" section of values.yaml relevant for customers, or just developers?
The "Common mistakes and solutions" section is fairly long and maybe out of place? Would it be better as a second document linked from this one, or part of a more general troubleshooting guide?
I think this should be linked from user-guide.md, under "Create and manage the operator".

WIP: OWLS-66906 helm charts doc

---

operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ConfigMapHelperTest.java

Log the introspect validation errors to the operator log and set the introspect job to complete.

OWLS-68437: handle the introspection validation errors at operator runtime

---

kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/domain-template.yaml

1) add a command line option to keep using the previously cloned project dir. This allows customers to re-generate the images after modifying the WDT model files.
2) Fix hard-coded image value in the domain yaml file
3) Correct credentials override for WDT case.
@anpanigr

Add an option to not alway clone the docker images project plus bug-fixing

---

json-schema-maven-plugin/src/main/java/oracle/kubernetes/json/mojo/Main.java
model/src/main/java/oracle/kubernetes/weblogic/domain/ClusterConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/DomainConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/ServerConfigurator.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ManagedServerSpecV2Impl.java
operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java
operator/src/main/java/oracle/kubernetes/operator/helpers/CRDHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsDomainConfig.java

Fixed javadoc warnings and errors to get mvn javadoc:javadoc to run successfully on 2.0-rc1 branch

Fix javadoc to get successful mvn javadoc:javadoc in 2.0-rc1 branch

---

site/config-overrides.md

Just a few notes:
*We are using sentence capitalization instead of title capitalization.
*Operator is not capitalized, as are most other terms, not capitalized unless they refer to a proper name.
*The doc reference will have to be to the 19c release, which of course, it not yet available.
In general, the doc looks very good.

first pass review

---

site/server-lifecycle.md

Updated the section that describes when the operator restarts servers to match the 2.0 operator code.

Update the server restart rules to match the 2.0 operator code

---

model/src/main/java/oracle/kubernetes/weblogic/domain/v2/Domain.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/main/resources/scripts/introspectDomain.py
operator/src/main/resources/scripts/introspectDomain.sh
operator/src/main/resources/scripts/startNodeManager.sh
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
src/integration-tests/introspector/introspectDomainProxy.sh
src/integration-tests/introspector/introspectTest.sh
src/integration-tests/introspector/wl-introspect-pod.yamlt

This check-in has two fixes:
- A: Adds missing support for putting logs in their default locations when logHomeEnabled is false (logHomeEnabled flag was being ignored)
- B: Generates correct sit-cfg overrides when original Log settings aren't set -- e.g. use "add" sit-cfg verb instead of "replace" (log files would end up in their default location instead of getting overridden)
Work-around, if not applying this check-in:
- Set 'logHome' to a location that has write-permission (helps with problem A above, not problem B)
Changes in this check-in:
- modify Operator to set LOG_HOME env var to '' when logHomeEnabled is false,
- modify startNodeManager.sh script to call mkdir ${DOMAIN_HOME}/servers/${SERVER_NAME}/logs instead of mkdir ${LOG_HOME} when LOG_HOME is '',
- modify startNodeManager.sh …

Fixes for WebLogic Server and Node Manager .log and .out locations

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java

integration test should override default logHome value of /shared/logs/domain1 from kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml

integration test should not always use /shared/logs/domain1 as logHome

---

operator/src/main/java/oracle/kubernetes/operator/Watcher.java
operator/src/main/java/oracle/kubernetes/operator/builders/WatchBuilder.java
operator/src/main/java/oracle/kubernetes/operator/builders/WatchI.java
operator/src/main/java/oracle/kubernetes/operator/builders/WatchImpl.java

When a watch fails, the client is sometimes rendered unusable, but we have been returning it to the pool, so that subsequent watch calls also fail. This is a short-term fix for that. When the exception is detected, we force the watch implementation to get a new client to be returned to the pool in place of the bad one.
A cleaner fix will move the responsibility for the client pooling to the Watcher itself.

discard client on watch failure; extend socket timeout

---

model/src/main/java/oracle/kubernetes/weblogic/domain/v2/ServerPod.java
site/server-lifecycle.md

Make the site doc in server-lifecycle.md that talks about when the operator automatically rolls pods match the operator runtime.
Add domain resource schema doc to say that customer supplied pod and service label names can't start with 'weblogic.'.

Develop server lifecle site doc pod obsolete fix

---

site/helm-charts.md
site/quickstart.md

This PR updates the documentation to fix two issues reported by @bollinenisravan  
1. The quickstart listed `-v` as an option on the create-domain script in domain-in-image, but it is not a valid option in that script.
2. If you do not remove the 1.x CRD, create domain will fail with a version incompatibility error:
`Error from server (BadRequest): error when creating "/scratch/output/uidomain/weblogic-domains/uidomain/domain.yaml": the API version in the data (weblogic.oracle/v2) does not match the expected API version (weblogic.oracle/v1)`

Doc updates bad param and explicitly remove 1.x - fixes #731

---

README.md
operator/src/main/java/oracle/kubernetes/operator/Watcher.java
operator/src/main/java/oracle/kubernetes/operator/builders/WatchI.java
operator/src/main/java/oracle/kubernetes/operator/builders/WatchImpl.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ClientPool.java
operator/src/main/java/oracle/kubernetes/operator/helpers/Pool.java
operator/src/test/java/oracle/kubernetes/operator/builders/WatchBuilderTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ClientPoolTest.java

We had identified a problem, whereby a Kubernetes ApiClient would be returned to the client pool and reused, even if it had failed and could no longer succeed. I put in a quick fix for it.
This is a simpler change, with unit tests.

Clean up fix for failed clients being returned to the pool

---

kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/properties-template.properties
site/quickstart.md

This PR contains the following changes:
1) Add additional info in the quickstart doc and sample readme to help the remote K8S cluster (such as OKE) use cases (based on the experience of a sale person reported in wls-operator-support channel)
2) Tag the generated image with what is specified by the "image" input property
3) Remove a reference to Derby in sample README and properties template file (related to OWLS-70765).
4) Minor clean up to the comments in the sample inputs file.

Quickstart doc and sample updates (based on internal early accepters experience)

---

docs/domains/Domain.json
docs/domains/index.html
json-schema/src/main/java/oracle/kubernetes/json/EnumClass.java
json-schema/src/main/java/oracle/kubernetes/json/SchemaGenerator.java
json-schema/src/test/java/oracle/kubernetes/json/SchemaGeneratorTest.java
model/src/main/java/oracle/kubernetes/operator/ServerStartPolicy.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/BaseConfiguration.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/Cluster.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/DomainSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/v2/Server.java

Moved serverStartPolicy field down one level in order to allow different options for domain, servers and clusters.
Used qualifier to select enum values

allow different startup policies for domains, servers and clusters

---

kubernetes/samples/scripts/common/utility.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain-inputs.yaml

The pull request contains following change:
1. Call validateDomainPVC under conditionally
domainHomeInImage is false (domain home on pv case) Or logHomeOnPV is true.
2. Update the documentation to clarify the logHomeOnPV parameters relationship
Jenkins passed. http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/830/

OWLS-71186 Update log home on PV sample

---

operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java

Fix the generated introspector config map labels.
Note: there was no existing unit tests for the labels and it's too late in 2.0 to add them, so I filed https://jira.oraclecorp.com/jira/browse/OWLS-71227 to do the work post 2.0.

OWLS-71193

---

README.md
site/helm-charts.md
site/quickstart.md
site/recent-changes.md
site/weblogic-docker-images.md

This PR includes:
* Updating the current version, where specified, from 2.0-rc1 to 2.0-rc2.
* Updating the informal warning to remove earlier versions of the operator, to include removing 2.0-rc1 completely.
* Hmm, thought I had updated Recent Changes doc in this PR; might have to do another commit.

updates for rc2

---

operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTest.java

Fix OWLS-71194 (add the weblogic.clusterName label to the per-server service if the server is clustered).

OWLS-71194

---

kubernetes/samples/scripts/common/utility.sh

Restore the "image" substitution line that was mistakenly changed to the same as the domain-home-on-pv case as part of the script refactoring in PR#733.
The Jenkins job with this PR is in progress (http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/836).

Fix a regression in domain home in image sample

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java

One of the integration tests was depending on there only being one config map with the domain uid label (weblogic-domain-cm).  Now there is another one (<domainuid>-weblogic-domain-introspector-cm).

WIP OWLS-71193 - update affected integration tests

---

kubernetes/samples/charts/ingress-per-domain/README.md
kubernetes/samples/charts/ingress-per-domain/templates/traefik-ingress.yaml
kubernetes/samples/charts/ingress-per-domain/templates/voyager-ingress.yaml
kubernetes/samples/charts/ingress-per-domain/values.yaml
site/quickstart.md

I've updated the ingress-per-domain helm chart (including the site doc) and hand tested it against traefik.
Maggie's going to try this branch against a p4 test she already has for this chart.  She'll test it against traefik and voyager.
Lily, I made the following changes to the ingress-per-domain helm chart to make it consistent with our other helm charts and samples:
1) use the helm install --namespace arg to get the domain namespace (v.s. wlsDomain.namespace in values.yalm)
2) renamed svcPort in values.yaml to managedServerPort
3) added a version label to the generated ingresses and services
4) renamed the generated ingresses and services to start with the domain uid instead of the helm release name.
See http://aseng-wiki.us.oracle.com/asengwiki/display/ASDevWLS/2.0+Naming+Summary and …

Develop ingress per domain fixes

---

kubernetes/samples/charts/traefik/README.md
kubernetes/samples/charts/traefik/values.yaml
kubernetes/samples/charts/util/setup.sh
kubernetes/samples/charts/voyager/README.md
site/quickstart.md

1. onessl is only needed by voyager, not traefik. And it's only needed if voyager's ValidatingWebhook is enabled. Since we disable the ValidatingWebhook in our sample, no need to download and use onessl. So remove all the reference to onessl.
2. stick Traefik image to v1.7.4 to get stable results.

remove reference to onessl

---

kubernetes/charts/weblogic-operator/values.yaml
kubernetes/src/test/java/oracle/kubernetes/operator/helm/HelmOperatorValuesTest.java
site/quickstart.md

Set the default for image in our helm chart values to oracle/weblogic-kubernetes-operator:2.0, so that it will be right when we release 2.0.
Update the quick start instructions to *NOT* say to tag 2.0-rc2 as 2.0 -- this would lead to confusion later.
The helm install step had already been updated to include "--set image=oracle/weblogic-kubernetes-operator:2.0-rc2".
When we release 2.0, we'll update the quick start to remove these references to 2.0-rc2.

Use oracle/weblogic-kubernetes-operator:2.0 and update quickstart instructions

---

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/README.md

The default of the "configuredManagedServerCount" in the inputs and README are "5", but the description of the default domain started by the script says the cluster size is "2".

Fix domain home on pv sample readme about the size of the cluster.

---

kubernetes/samples/charts/apache-webtier/README.md
kubernetes/samples/charts/apache-webtier/templates/cluster-role-binding.yaml
kubernetes/samples/charts/apache-webtier/templates/cluster-role.yaml
kubernetes/samples/charts/apache-webtier/templates/deployment.yaml
kubernetes/samples/charts/apache-webtier/templates/secret.yaml
kubernetes/samples/charts/apache-webtier/templates/service-account.yaml
kubernetes/samples/charts/apache-webtier/templates/service.yaml
kubernetes/samples/charts/apache-webtier/values.yaml

Changes in this PR:
1) replace imageRegistry, image, imageTag in values.yaml with just image that has the full image name
2) remove the 'release' label (for symmetry with the other samples) (service account, cluster role, cluster role binding, secret, service, deployment)
3) remove the 'app' label (for symmetry with the other samples (service account, cluster role, cluster role binding, secret, service - keep it on the deployment)
4) add a weblogic.resourceVersion: loadbalancer-v2 label (service account, cluster role, cluster role binding, secret, service, deployment)

OWLS-71197

---

site/helm-charts.md
site/quickstart.md

Including:
* Noting that the guide assumes a single node cluster.
* Moved up the instruction to grant the Helm service account the cluster-admin role.
* Changed the “kubectl log” command to “kubectl logs” (in both files).
* Added the path for the kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain-inputs.yaml file.

incorporate edits from Bob D

---

operator/src/main/resources/scripts/introspectDomain.py
site/config-overrides.md
src/integration-tests/introspector/override--config.xmlt

_Description:_
- QA testing recently discovered that when a sit-cfg override file of config.xml doesn't include the domain-name, then some of the overrides within may be silently ignored.   This now confirmed by two different testers using two different tests @davisn9 and Huiling Zhao.
- The problem occurred in (1) a custom override file that had become moderately complex (it introduced debug overrides in addition to some other overrides), and (2) in a custom override file that only has a single override.
- Note that pretty much all internal testing of the sit-cfg feature prior to the operator project happened to specify the domain-name. 
_This update includes:_
- Add a domain-name stanza to the internal sit-cfg the introspector generates for overriding listen-addresses and log …

An override file sometimes needs a domain name

---

kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml
site/quickstart.md
site/user-guide.md

Updated info:
* Quick Start Guide (removed patching instructions)
* User Guide (added info regarding Docker store image)
* create-domain-inputs.yaml files (added info regarding Docker store image)
Unrelated, customer request: Added note to Quick Start about requiring `JAVA_HOME` to be set to a Java JDK version 1.8 or later.

update patched image info

---

operator/src/main/resources/scripts/introspectDomain.py

This pull fixes a problem introduced by pull #797:
Patched 12.2.1.3 images still need the expiration sit-cfg field (unlike 19.1), so put back the line that was removed in pull 797.   Plus set the expiry further into the future 2099 instead of 2020.
Test status:
-Testing by @doxiao passes.   
-Local tests pass.
-Passes Wercker test.

Fix problem with pull 797.

---

operator/src/main/resources/scripts/introspectDomain.py

Fix for pulls #797 and #820: the calculated DOMAIN_NAME value in introspectDomain.py should be discovered via wlst instead of from a domain env var. @alai8 discovered that the domain env var isn't necessarily in sync with the 'actual' value.

Get domain name from domain home instead of env var.  Try#2.

---

operator/src/main/resources/scripts/introspectDomain.py

Goes on top of pulls #826 #820 #797

sit cfg domain: skip setting domain name in internal sit-cfg

---

site/config-overrides.md
site/domains.md

Minor update:
- Point to brand-new new 'restart.md' doc from 'config-overrides' and 'domains'.
- Make clear that 'version.txt' is not the version of the config override contents, and so must always stay '2.0' (it's the version of the config overrides schema).

Custom overrides doc update.

---

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/common/utility.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/wdt_model_configured.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/wdt_model_dynamic.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wlst/create-domain.py

The PR includes the following:
1. The setup logic is already in the Operator runtime, so we remove the logic from the domain-home-on-pv sample scripts.
2. Remove the unused code.
3. Address review comments - clean up the wlst script and wdt model to get rid of setting log location and server listen addresses.
Jenkins passed http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/957/

OWLS-69366 Remove log and address setup from domain home on pv sample

---

operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ConfigMapHelperTest.java

If the introspector determines the domain is invalid  (due to validation errors) then log the errors and terminate the fiber by returning next action with and 'null' step.   Correctly terminating the fiber resolves the NPE.

Owls 71453: Operator logs NPE after (correctly) logging introspector validation errors.

---

operator/src/main/resources/scripts/introspectDomain.py
operator/src/main/resources/scripts/startServer.sh
site/config-overrides.md
src/integration-tests/introspector/createDomain.pyt
src/integration-tests/introspector/override--diagnostics-myWLDF.xmlt

Store wldf override module files in the 'DOMAIN_HOME/diagnostics' directory, not the 'DOMAIN_HOME/wldf' directory.  
Test status: Passes local 'mock' tests & QA tests.

Config overrides wldf fix

---

operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/StepContextBase.java
operator/src/main/java/oracle/kubernetes/operator/helpers/StepContextConstants.java
operator/src/test/java/oracle/kubernetes/operator/helpers/AdminPodHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java

Pass custom env vars configured under serverPod attribute, either configured at domain spec level or at domain.adminServer level, to the container for the introspector job.
Also did some refactoring and introduced a common parent abstract class StepContextBase to allow AdminPodStepContext, ManagedPodStepContext, and DomainIntrospectorJobStepContext classes to share common code.
Passes jenkins http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/968/

Owls-71580 Pass custom env vars to introspect job

---

kubernetes/samples/scripts/common/domain-template.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/README.md
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/README.md
model/src/test/java/oracle/kubernetes/weblogic/domain/DomainTestBase.java
model/src/test/java/oracle/kubernetes/weblogic/domain/v2/DomainV2Test.java
model/src/test/resources/oracle/kubernetes/weblogic/domain/v2/domain-sample.yaml
operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/StepContextBase.java
operator/src/main/resources/scripts/introspectDomain.sh
operator/src/test/java/oracle/kubernetes/operator/helpers/JobHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
site/domains.md
src/integration-tests/introspector/wl-pod.yamlt

This is a regression caused by owls-71580 when we start passing en vars to introspector job. The WLS container is preconfigured with USER_MEM_ARGS="-Djava.security.egd=file:/dev/./urandom". When this env var is overridden, the introspector script would take a longer time to run. In Pani's environment, it took longer than the timeout of 60s specified in job.template.spec.activeDeadlineSeconds. This results in the introspector job failing with DeadlineExceeded
Changes made in this PR:
- The operator should always explicitly set USER_MEM_ARGS to `-Djava.security.egd=file:/dev/./urandom` if the domain.yaml does not specify this env var.  (This will override any value that the docker image itself might be setting.)
- If the domain.yaml specifies USER_MEM_ARGS of “” or any value, then honor the …

OWLS-71901-OPERATOR FAILS TO BRING UP WEBLOGIC DOMAIN WITH SITCONFIG OVERRIDE CONFIGURATION

---

site/rest.md
site/v1.1/rest.md

rest.md said X-RequestedBy, should have been X-Requested-By - this typo caused a customer a lot of grief!

Fix X-RequestedBy typo - should be X-Requested-By

---

kubernetes/samples/scripts/elasticsearch-and-kibana/elasticsearch_and_kibana.yaml

The following change in elasticsearch_and_kibana.yaml from the samples has broken the deployment of elasticsearch.
- name: ES_JAVA_OPTS
value: -Xms2014m -Xmx1024m
This results in "Error occurred during initialization of VM Initial heap size set to a larger value than the maximum heap size".
The fix is to make the values the same which is the recommendation from elasticsearch.

Fix ES_JAVA_OPTS to prevent Initial heap size failure

---

kubernetes/charts/weblogic-operator/values.yaml

logStashImage parameter in file weblogic-kubernetes-operator/kubernetes/charts/weblogic-operator/values.yaml now contains "logstash:6.6.0" value.
Container based on image logstash:6.6.0 solved the "/var/lib/logstash is not writable" error
Signed-off-by: Denis Maggiorotto <denis.maggiorotto@sunnyvale.it>

Issue #876 fix

---

operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java

This PR fixes a problem in the readiness probe.  The previous code set the probe to "/weblogic" which will result in the server returning a 302 redirect.  In cases where the cluster is behind a load balancer and WebLogic has been configured with a frontend host/port so that external clients can use applications deployed in the cluster, the 302 will redirect to the load balancer address, and kubelet will not be able to hit this address successfully.  The readiness probe will show as failed (503), because the endpoints have not been added to the cluster service (and therefore the ingress) yet, because the pod is not yet considered ready.  So you get a chicken and egg problem.
This change fixes the readiness probe to use "/weblogic/" (with the trailing slash).  This will not result in a 302, …

Fix readiness probe.

---

site/quickstart.md

Change command from $ curl -v -H 'host: sample-domain1.org' http://your.server.com:30305/weblogic/ to $ curl -v -H 'host: sample-domain1.org' http://your.server.com:30305/weblogic/ready

edit CURL command for ReadyApp

---

integration-tests/src/test/resources/domain-home-on-pv/create-domain.py

Somehow integration-tests/src/test/resources/domain-home-on-pv/create-domain.py got incorrect configuration. Fixing it by copying the file from samples.
Jenkins passed with this change - http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/1071/consoleFull

READY TO MERGE: fix create-domain.py 

---

operator/src/main/java/oracle/kubernetes/operator/work/Fiber.java

Fixes a deadlock when the javaLoggingLevel includes FINER log level by removing the
synchronized block from the Fiber.getName() method. The currentThread field in Fiber class is made volatile so getName() can still obtain the most up-to-date value.
Example of deadlock:
`"engine-operator-thread-1":
at oracle.kubernetes.operator.work.Fiber.getName(Fiber.java:661)
- waiting to lock <0x000000042b116548> (a oracle.kubernetes.operator.work.Fiber)
at oracle.kubernetes.operator.work.Fiber.toString(Fiber.java:675)
at oracle.kubernetes.operator.logging.LoggingFormatter.format(LoggingFormatter.java:111)
at java.util.logging.StreamHandler.publish(StreamHandler.java:211)
- locked <0x000000055cdd49a8> (a java.util.logging.FileHandler)
at java.util.logging.FileHandler.publish(FileHandler.java:701)
- …

OWLS-71954 remove synchronize block from Fiber.getName() to avoid deadlock

---

operator/src/main/java/oracle/kubernetes/operator/Watcher.java
operator/src/test/java/oracle/kubernetes/operator/WatcherTestBase.java
operator/src/test/java/oracle/kubernetes/operator/builders/WatchEvent.java

We found two issues with watches while certifying on OpenShift.  Both issues involved use cases where the API server needs to return an HTTP 401 "Gone" status because the resource version used when the watch was started has aged out.
The expected behavior is that the V1Status contains a message that encodes a "good" resource version as part of the error message.  The error message from OpenShift does not include this good resource.
Additionally, we found that the Kubernetes Java client can incorrectly parse the status if the "target" type of the watch contains similar enough fields, e.g. V1ConfigMap.  In these cases, the watch response is of type ERROR; however, the status is not available.
In each case, the correct behavior is to use a resource version of "0".

Handle watch status that is missing or for 410 doesn't include good resource version

---

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-job-template.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/delete-domain-job-template.yaml

This pull request includes changes to the domain-home-on-pv scripts for the istio environment.
The changes are:
- included the container name in the **kubectl logs** command so the command works when there are multiple containers in the pod (for example, istio-proxy container included in pod)
- included annotation **sidecar.istio.io/inject: "false"** in the create and delete jobs to prevent istio injection for these jobs
- removed the deprecated **--show-all** option for **kubectl get pods** command
Jira: https://jira.oraclecorp.com/jira/browse/OWLS-72018

Changes to domain-home-on-pv scripts for istio environment

---

kubernetes/samples/charts/util/setup.sh
kubernetes/samples/charts/voyager/README.md

Update setup.sh:
1. Parameterize release name for Voyager and Traefik operator.
2. Change the release name of Voyager to avoid redundant words in the generated k8s resources.
For more information see https://jira.oraclecorp.com/jira/browse/OWLS-71184.

OWLS-71184 REDUNDANT WORD VOYAGER,APACHE OR IN LBER SERVICE NAME

---

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java
operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java
operator/src/main/java/oracle/kubernetes/operator/steps/WatchPodReadyAdminStep.java
operator/src/test/java/oracle/kubernetes/operator/DomainUpPlanTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupportTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
operator/src/test/java/oracle/kubernetes/operator/helpers/TuningParametersStub.java
operator/src/test/java/oracle/kubernetes/operator/helpers/UnitTestHash.java
operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java

The initial approach for testing kubernetes calls implemented in AsyncCallTestSupport / CallTestSupport turns out to be rather cumbersome for complex cases. The developer needs to define exactly the calls to be made.
This change adds an alternative, KubernetesTestSupport, which takes advantage of the pattern used for call names and translates them into changes to in-memory resources. Tests can then simply look at the results to see if the correct resource changes have been made.
This strategy is demonstrated in DomainUpPlanTest.whenAdminPodCreated_hasListenPort, which verifies the functionality added to fix OWLS-72015, which was not so easy to test, previously.

Add Kubernetes stub-style testing

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/resources/statedump.sh
wercker.yml

This branch cherry-picks instrumentation changes from `investigation` branch owls-72310:
- kubectl describe various k8s resources across all namespaces during integration test 'archive' step.
- show WL version during wercker lease/clean step.
- show additional information when integration test webapp deploy fails
Test status:  Passes locally and on Wercker.

Add more debugging output to integration tests.

---

integration-tests/src/test/resources/setupenv.sh

docker login and docker pull was commented in my previous PR which makes the tests to fail if the image doesn't image locally. reverting the change.

docker pull is needed in setup.env to get the wlthinclient jar

---

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java

The issue reported in OWLS-71987, HTTP requests not load balanced to the newly scaled up server, cannot be reproduced. This change re-enables the tests as well as adding logging of service and pods info for debugging purposes in case the test fails again.

OWLS-71987 - Re-enable load balancing test and add logging of service and pods info if it fails

---

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java
integration-tests/src/test/java/oracle/kubernetes/operator/ITOperator.java
integration-tests/src/test/java/oracle/kubernetes/operator/ITServerDiscovery.java
integration-tests/src/test/java/oracle/kubernetes/operator/ITUsabilityOperatorHelmChart.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/resources/statedump.sh

Changed new test ITUsabilityOperatorHelmChart not to be called on wercker, this will fix the lease failures.
archive and cleanup is done after every IT class, so made changes to create PV_ROOT and RESULT_ROOT dirs in initialize() method in BaseTest and also moved some common code to BaseTest.java

READY TO MERGE: Fix wercker lease failures and some code refactoring

---

docs-source/README.md
docs-source/content/developerguide/documentation.md

Create a README for `docs-source` that directs the reader to proper section of the [documentation site](https://oracle.github.io/weblogic-kubernetes-operator/) and make it clear that only the `content` folder should be updated when submitting an update.

Add README file for new documentation sources

---

kubernetes/samples/charts/ingress-per-domain/templates/traefik-ingress.yaml
kubernetes/samples/charts/util/setup.sh

By default, Voyager controller monitors both k8s standard Ingress class and Voyager Ingress class. With this change Voyager controller will only monitor Voyager Ingress class.  This can help to run the two supported Ingress Controllers: Voyager and Traefik, on the same k8s cluster at the same time without interfering with each other. Voyager is monitoring its own Voyager Ingress class and Traefik is monitoring k8s-provided Ingress class.
Another change is to fix annotation problem in chart ingress-per-domain.

configure Voyager to only watch Voyager ingress class

---

site/quickstart.md

In the docker pull command, in the Quick Start guide, from 2.0 to 2.0.1.

update operator version number

---

docs-source/content/faq/cannot-pull-image.md

This PR fixes the capitalization of "Docker" in example commands where it should be `docker` not `Docker`

fix capitalization of 'Docker' in example commands

---

docs-source/content/_index.md

Updated the Hugo docs main README to align with the repo main README with regard to backward compatibility.

update backward incompatibility statement, jenkins-ignore

---

docs-source/content/quickstart/install.md

In the Quick Start guide, install command, updated the version number from 2.0-rc2 to 2.0.1.

fix version number, jenkins-ignore

---

docs-source/content/userguide/managing-domains/domain-lifecycle/restarting.md
docs-source/content/userguide/managing-operators/using-the-operator/using-helm.md

In two docs, "Using Helm" and "Restarting," from version 2.0 to 2.0.1.

updated operator version number, jenkins-ignore

---

docs-source/content/security/secrets.md
docs-source/content/userguide/managing-operators/installation/_index.md

Update the documentation to show how to specify the image pull secret for the operator's image using the Helm chart when the image is part of a private registry.

Add information about setting an operator image pull secret

---

docs-source/content/userguide/managing-domains/domain-lifecycle/scaling.md

In the Scaling doc, fixed two broken links to the scalingAction.sh script.

fix broken links, jenkins-ignore

---

operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java
operator/src/test/java/oracle/kubernetes/operator/helpers/CallBuilderTest.java

I should have deleted this call when changing the scaling to use patching, but didn't notice it.
The logic never belonged in CallBuilder, which serves as an interface to Kubernetes. If we ever need something of the kind again, it would be better built in a utility class, with unit tests that don't need to hit a web server.
The main motivation to remove this now is that some of the tests for it were failing intermittently.

Delete superfluous ReplaceDomainWithConfictRetry

---

build-tools/pom.xml
buildtime-reports/pom.xml
integration-tests/pom.xml
json-schema-maven-plugin/pom.xml
json-schema-maven-plugin/src/test/java/oracle/kubernetes/json/mojo/JsonSchemaMojoTest.java
json-schema/pom.xml
kubernetes/pom.xml
model/pom.xml
operator/pom.xml
pom.xml
src/integration-tests/bash/krun.sh
src/integration-tests/introspector/util_krun.sh
swagger/pom.xml
wercker.yml

This change:
- Requires minimum Maven (3.5.2) and JDK (11) versions
- Updates Maven plugin dependencies 
- Updates other dependencies
- Small number of Java code changes for JDK 11 (e.g. asm library)

Require JDK 11, Maven plugin and dependency versions

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Operator.java

The first change is required to get the integration tests pass on the new jenkins(shared cluster) setup when IP address is used.
Fixed the intermittent failure for testDomainInImageUsingWLST on Jenkins.
Jenkins passed - http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/1490/console

use IP in sans if hostname contains IP address, fix domain in image tests

---

operator/pom.xml
operator/src/main/java/oracle/kubernetes/operator/rest/AuthenticationFilter.java
operator/src/main/java/oracle/kubernetes/operator/rest/RestServer.java
operator/src/test/java/oracle/kubernetes/TestUtils.java
operator/src/test/java/oracle/kubernetes/operator/rest/RestTest.java
operator/src/test/java/oracle/kubernetes/operator/wlsconfig/WlsDomainConfigTest.java

This new approach to RestTest tests the resources and filters using JerseyTest and the in-memory container. It should test everything the old one does except for the actual web server behavior, which should be tested via the integration tests.

Rewrite RestTest to use in-memory container

---

site/v1.1/installation.md

Fix same typo in the archived install doc on the master branch

fix typo, jenkins-ignore

---

operator/src/main/java/oracle/kubernetes/operator/helpers/AnnotationHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java
operator/src/main/java/oracle/kubernetes/operator/helpers/LegalNames.java
operator/src/main/java/oracle/kubernetes/operator/helpers/OperatorServiceType.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ServicePresenceTest.java

The operator did not recognize the external channel services defined in 2.0 (and 2.0.1). As a result, it did not add them to the DomainPresenceInfo when it started, and therefore did not delete them as needed on an upgrade. That led the processing step chain to abort, as the newly created service tried to use the same port.
This change uses the spec type "NodePort" to recognize an external service. It also can handle services and pods which did not have any annotations.

Recognize v2.0 external channel services

---

docs-source/content/userguide/managing-domains/configoverrides/_index.md

Fixed the spacing (onto two lines) of two examples in the step-by-step, bulleted items.

fix example spacing, jenkins-ignore

---

docs-source/content/userguide/managing-domains/domain-lifecycle/scaling.md
src/scripts/initialize-external-operator-identity.sh
src/scripts/initialize-internal-operator-identity.sh
src/scripts/scaling/scalingAction.sh

I discovered that Kubernetes behavior doesn't match what they document, so updating the scripts to locate the master's REST URL the same way as the clients do.

Use env. variables for Kubernetes master address

---

docs-source/content/userguide/managing-domains/persistent-storage/_index.md

Based on @qvdang investigation and my review of the finding we should update the documentation to reference the use of the GID annotation for a persistent volume used with domain home on pv use case since this will prevent need for wide open 777 directory permissions.
Please review... Thanks, -Craig

Documenation for using a GID annotated Persistent Volume - Resolves #931

---

operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java
operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/RollingHelper.java
operator/src/main/java/oracle/kubernetes/operator/work/Step.java
operator/src/test/java/oracle/kubernetes/operator/DomainUpPlanTest.java
operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServersUpStepTest.java

There were several broken use cases where cluster rolling would not honor the minimum unavailability setting.  One significant problem was that the cluster rolling support assumed that it could always roll at least one server.  With this change, this code will wait if there are not-yet-ready servers that are in the process of starting.  Also, servers that are terminating, but still ready, are not counted as ready for the purpose of maintaining the minimum availability.

Wait for other servers to become ready during a cluster rolling

---

integration-tests/README.md
integration-tests/src/test/java/oracle/kubernetes/operator/ITMultipleClusters.java
integration-tests/src/test/java/oracle/kubernetes/operator/ITStickySession.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java
integration-tests/src/test/resources/domaininimagewdt.yaml
integration-tests/src/test/resources/domaininimagewlst.yaml

This PR is to fix full integ test issue with VOYAGER since not like TRAEFIK, VOYAGER requires unique webport because there are multiple voyager instances created for the different domains/backends . The fix includes:
1) resolving NPE if the domain doesn't explicitly set voyagerWebPort
2) ensuring uniqueness of voyagerWebPort if "LB_TYPE" is set to "VOYAGER"
Full test suite Jenkins passed at:  http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/1615/console

PR (ready to be merged): Voyager JIRA OWLS-73062

---

integration-tests/src/test/java/oracle/kubernetes/operator/ITPodsRestart.java

Use the kubectl command instead of java api to get the status of pods. Apparently the java api's are not reliable to get the pod status.

Use the kubectl command instead to get pod status

---

docs-source/content/userguide/managing-domains/domain-in-image/base-images/_index.md

WLS image location changed in this doc to point to OCR, including how to obtain credentials required for image access.

update WLS image location, jenkins-ignore

---

integration-tests/src/test/java/oracle/kubernetes/operator/ITUsabilityOperatorHelmChart.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Operator.java

OWLS-74223 : ITUsabilityOperatorHelmChart.testCreateWithMissingTargetDomainInstall test fails.
The problem was that the override file had domainNamespaces:[], which is an empty set and causes the .domain-namespaces.tpl to skip the generation of the namespace role binding.  This, in turn, caused the operator HealthCheckHelper to take much longer and timeout.  Fix the test so that it generates the helm override values.yaml file without a domainNamespace at all so that he operator default value is used.  Also, add a new test which passes an empty string as the domainNamespaces entry, this simulates the QuickStart install instructions where --set "domainNamespaces={}" is used.

OWLS-74223 : Missing DomainName test fails

---

src/scripts/operator.sh

For JDK 11, the debug listen address specified in operator.sh must use a wildcard hostname or else you cannot connect with a remote debugger.  I tested this fix with both OKE and Mac Docker Desktop with Kubernetes.

OWLS-74827 : DEBUG listen address must use wildcard instead of hostname

---

docs-source/content/quickstart/create-domain.md
docs-source/content/samples/simple/credentials/_index.md
docs-source/content/samples/simple/domains/domain-home-in-image/_index.md
docs-source/content/userguide/managing-domains/prepare.md

Fixed docs to meet Oracle style guidelines with regard to passwords. "Don't use: welcome1" "To indicate a password in Oracle documentation, use the word password in italic." In markdown, because I couldn't format italics inside a code block, I used angle brackets instead.

removed welcome1, jenkins-ignore

---

build-tools/src/main/resources/weblogic-kubernetes-operator/checkstyle/customized_google_checks.xml
build-tools/src/main/resources/weblogic-kubernetes-operator/checkstyle/java.header

Added checkstyle rule to enforce copyright header in Java files.  Checkstyle enforcement needs to be enforced before this will assist.

Checkstyle Copyright Headers

---

operator/src/main/resources/scripts/introspectDomain.py
operator/src/main/resources/scripts/introspectDomain.sh
operator/src/main/resources/scripts/livenessProbe.sh
operator/src/main/resources/scripts/monitorLog.sh
operator/src/main/resources/scripts/readState.sh
operator/src/main/resources/scripts/startNodeManager.sh
operator/src/main/resources/scripts/startServer.sh
operator/src/main/resources/scripts/stopServer.sh
operator/src/main/resources/scripts/traceUtils.sh
operator/src/main/resources/scripts/utils.py
operator/src/main/resources/scripts/utils.sh
operator/src/main/resources/scripts/wlst.sh
operator/src/test/java/oracle/kubernetes/operator/helpers/ConfigMapHelperTest.java
src/integration-tests/introspector/introspectTest.sh
src/integration-tests/introspector/util_fsplit.sh
src/integration-tests/introspector/util_subst.sh
src/integration-tests/introspector/util_testwlversion.sh
src/integration-tests/introspector/wl-create-domain-pod.sh

This change adds WebLogic version and WebLogic patch checks.
- It fails the introspector job and wl pod startup for unsupported versions.
- Requires 12.2.1.3 or higher.
- If 12.2.1.3, also requires patch 29135930.  
- The failure messages are logged to job/pod's log and include the name of an env var users can specify in the Domain resource to bypass checks: 
- `"Error: WebLogic version='$cur_wl_ver' and the Operator requires WebLogic version '${exp_wl_ver}' or higher. To bypass this check, set env var SKIP_WL_VERSION_CHECK to 'true'."` 
- `Error: The Operator requires that WebLogic version '12.2.1.3' have patch '$exp_wl_12213_patches'. To bypass this check, set env var SKIP_WL_VERSION_CHECK to 'true'.`
- Instead of using `weblogic.version` or `opatch`, this check determines the WebLogic …

Add WebLogic version and WebLogic patch checks

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItElasticLogging.java
integration-tests/src/test/resources/operator_elk.yaml
kubernetes/samples/scripts/elasticsearch-and-kibana/elasticsearch_and_kibana.yaml

have tested 5 scenarios:
1.	ELK Stack 5.6.16 + Exporter doc type = “_doc”
Test failed. No WLS logs pushed to Elasticsearch repository
2.	ELK Stack 5.6.16 + Exporter doc type = “doc”
Test passed. WLS logs pushed to Elasticsearch repository
3.	ELK Stack 6.8.0 + + Exporter doc type = “_doc”
Test passed. WLS logs pushed to Elasticsearch repository
4.	ELK Stack 6.8.0 + Exporter doc type = “doc”
Test passed. WLS logs pushed to Elasticsearch repository
5.      ItElasticLogging also passed using ELK Stack 6.8.0 + Exporter doc type = “doc”
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 250.547 s - in oracle.kubernetes.operator.ItElasticLogging

upgraded ELS Stack from 5.6.16 to 6.8.0

---

kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl
kubernetes/charts/weblogic-operator/templates/_validate-inputs.tpl
kubernetes/charts/weblogic-operator/values.yaml
kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorGeneratedFilesDebugEnabledTestBase.java
kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorGeneratedFilesOptionalFeaturesDisabledTestBase.java
kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorGeneratedFilesOptionalFeaturesEnabledTestBase.java
kubernetes/src/test/java/oracle/kubernetes/operator/create/CreateOperatorGeneratedFilesTestBase.java
kubernetes/src/test/java/oracle/kubernetes/operator/helm/HelmOperatorValues.java
kubernetes/src/test/java/oracle/kubernetes/operator/helm/HelmOperatorValuesTest.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/OperatorValues.java
kubernetes/src/test/java/oracle/kubernetes/operator/utils/YamlUtils.java
src/scripts/operator.sh

Replaces PR #1154, which had been done against `master`
* simplifies putting the operator into debug by disabling the probes when debug is enabled, and
* allows the operator to be set not to suspend, meaning that a developer can attach after it is running. This is controlled by the `suspendOnDebugStartup` setting, which defaults to `false`.

Owls 75227 - simplify debugging the operator

---

operator/src/main/resources/scripts/introspectDomain.sh
operator/src/main/resources/scripts/startNodeManager.sh
operator/src/main/resources/scripts/utils.sh
operator/src/main/resources/scripts/wlst.sh

smarter defaulting for ORACLE_HOME, MW_HOME, and WL_HOME
also includes a minor fix to utils.sh tracing (affects only introspector mock/unit test)

smarter defaulting for ORACLE_HOME, MW_HOME, and WL_HOME

---

integration-tests/README.md
integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItOperator.java
integration-tests/src/test/resources/setupenv.sh

This PR contains changes ..
- remove call to testAdminT3ChannelWithJms which depends on thinclient.jar, so that the integration tests can be run on slim images too. See JIRA OWLS-76081
- fix readme format
- setupenv.sh change - remove k8s installation step from tests for Jenkins run as its done in the Jenkins configuration before the tests are called
- setupenv.sh change - remove code which pulls the WL image to copy the thinclient jar as its not needed now.

skip test which depends on thinclient.jar for slim image

---

operator/src/main/resources/scripts/introspectDomain.py
operator/src/main/resources/scripts/startNodeManager.sh
src/integration-tests/introspector/wl-create-domain-pod.pyt

- Fix introspector so that it properly skips WL config templates that don't reference a cluster (currently it throws an exception), as requested by internal customer via internal bug OWLS-76014 
- Expand introspector 'mock' test to include such templates
- Echo config.xml to introspector log as a FINE (to aid in debugging), this will also show up in the operator log if operator log level is FINE/FINER/FINEST.
- Remove use of unknown jython name 'UndeclaredThrowableException'

Fix introspector to handle WL config templates that don't reference a cluster.

---

docs-source/content/samples/simple/storage/_index.md

Document: specify unique baseName while sharing PV/PVC across domains

OWLS-76121

---

pom.xml

We received the following:
Details:
CVE-2019-14379
More information
moderate severity
Vulnerable versions: < 2.9.9.2
Patched version: 2.9.9.2
SubTypeValidator.java in FasterXML jackson-databind before 2.9.9.2 mishandles default typing when ehcache is used, leading to remote code execution.
CVE-2019-14439
More information
moderate severity
Vulnerable versions: < 2.9.9.2
Patched version: 2.9.9.2
A Polymorphic Typing issue was discovered in FasterXML jackson-databind 2.x before 2.9.9.2. This occurs when Default Typing is enabled (either globally or for a specific property) for an externally exposed JSON endpoint and the service has the logback jar in the classpath.
This PR updates jackson-databind to take the patch for this CVE and also updates any other out-of-date dependency ahead of a …

Update dependencies, including jackson-databind for CVE

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItOperator.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java

This PR has changes -
to allow custom weblogic image in domain home in image tests. Weblogic image specified using the env variables IMAGE_NAME_WEBLOGIC and IMAGE_TAG_WEBLOGIC should be used when creating domain home in image.
fix intermittent NPE
internal jenkins is clean - http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2148/consoleFull
external jenkins is clean - http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/482/consoleFull

Owls76144 - use custom weblogic image in domain home in image tests

---

docs-source/content/faq/coherence-requirements.md
docs-source/content/userguide/managing-domains/fmw-infra/_index.md

This PR adds some documentation on additional considerations for running Coherence in Kubernetes, added as a result of several questions from customers.

add documentation for coherence requirements

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItSitConfig.java

The fix will cleanup the k8s secret created for JDBC override tests and will restore the original secret name after the test is done.

Fixing the secrets change

---

docs-source/content/developerguide/integration-tests.md

I added a link to the integration test page in the repo. I considered adding the specific information that @vanajamukkara specified ("At a minimum OCR_USERNAME and OCR_PASSWORD need to be supplied as ENV variables. OCR_SERVER - if you are not using container-registry.oracle.com"), however, it was different from the advice given in https://jira.oraclecorp.com/jira/browse/OWLS-76361 ("I would recommend removing OCR_USERNAME, OCR_PASSWORD from the equation. Jenkins provides the login capability and protects the credentials.  Passing them as ENV variables complicates the environment unnecessarily. For running outside of Jenkins, just make the first step "Do docker login to phx.ocir...")
I suggest putting the correct details in the integration test page in the repo to which this doc is …

added link to integration tests page

---

operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java

This change passes ADMIN_NAME, ADMIN_PORT, ADMIN_PORT_SECURE, and AS_SERVICE_NAME env vars to an introspector job when the job is being rerun on an existing domain (the original job is what gathers this information).

Pass admin server info as env vars to additional runs of the introspector

---

model/src/main/java/oracle/kubernetes/weblogic/domain/model/Domain.java
model/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java
model/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainValidationFailure.java
model/src/main/java/oracle/kubernetes/weblogic/domain/model/ManagedServer.java
model/src/test/java/oracle/kubernetes/weblogic/domain/DomainTestBase.java
model/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainV2Test.java
model/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainValidationTest.java
operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java
operator/src/main/java/oracle/kubernetes/operator/helpers/DomainStatusPatch.java
operator/src/main/java/oracle/kubernetes/operator/helpers/DomainValidationStep.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/KubernetesUtils.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/DomainValidationStepTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectionLoggingTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectionStatusTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java

Adds semantic validation of the domain resource itself. If it fails, updates the domain status. If it succeeds, allows the introspection to run.

Validate domain resource before running introspector

---

buildtime-reports/pom.xml
swagger/pom.xml

Remove leftover references to the defunct operator-model module.
Jenkins job http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2375/

remove reference to operator-model

---

kubernetes/samples/scripts/common/utility.sh

The below change to utility.sh has caused failures in integration tests.
https://github.com/oracle/weblogic-kubernetes-operator/commit/f25de2eae8557cf511dbc797367c0a8ace30d779#diff-3eca7b10cf452dd7e50ad787bed51ce6
failures - http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2379/testReport/
Fixing it..
Submitted Jenkins - http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2389/

Fix sed in utility.sh

---

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/resources/OperatorIT.properties
kubernetes/samples/scripts/common/utility.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-job-template.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh

external jenkins ran clean - http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/562/
internal jenkins still running - http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/2493/

Integration tests should take the env variable for WDT version to download

---

operator/src/main/java/oracle/kubernetes/operator/rest/model/ScaleClusterParamsModel.java

This change resolves an insecure binder configuration issue reported from code scanning such that the ScaleClusterResource POST parameter handling will now only use properties defined in the model.
For more context on the annotation, see https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations#property-inclusion

Ignore unknown properties during REST processing

---

operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java
operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java
operator/src/main/java/oracle/kubernetes/operator/WaitForReadyStep.java
operator/src/test/java/oracle/kubernetes/operator/JobWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/PodWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/WatcherTestBase.java

Massive refactoring of the WaitForReadyStep functionality in the Domain and Pod watchers, expanding test coverage, simplifying the code, and extracting some common functionality. This will create a firmer foundation for the next change, which will actually monitor certain introspection job failures not currently being detected.
Kudos to @alai for getting better code coverage in the JobWatcher than I originally had in the PodWatcher.
The main test and functionality changes are related to the fact that the steps have to consider three cases in which the resource is found to be ready:
1. It is ready when the step is created
2. It is detected as a ready on a callback, and
3. It became ready between the time we created the step and the time we registered the callback
All "isReady" …

Simplify WaitForReadyStep

---

operator/src/main/resources/scripts/livenessProbe.sh
operator/src/main/resources/scripts/readState.sh
operator/src/main/resources/scripts/stopServer.sh
operator/src/main/resources/scripts/utils.sh

Append PATH with $JAVA_HOME/bin if $JAVA_HOME is set before calling jps
Tested on modified WebLogic image where java binaries are not found in PATH env var, but only in $JAVA_HOME/bin, and pods are started and remained in ready state.
Passed jenkins http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2605/testReport/

OWLS-76806 (Resolves #1231) - scripts such as livenessProbe.sh should use JAVA_HOME if set

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItMonitoringExporter.java
pom.xml

Currently, Checkstyle is only enabled on main, not unit test or integration test sources.

Enable checkstyle on test sources

---

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java
operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java
operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/test/java/oracle/kubernetes/operator/NamespaceTest.java

More clean up of stale objects (domain presence infos and introspector jobs) for a deleted and recreated namespace. 
This helps a previously existing domain to be successfully recreated after its namespace is deleted/recreated, and deleted from and then added back to operator's domainNamespaces list.

OWLS-73891 part2 - clean up stale states about introspector jobs and domain presence infos

---

docs-source/content/quickstart/create-domain.md
docs-source/content/userguide/managing-domains/domain-lifecycle/startup.md

Added to the Startup and Shutdown doc and to the Quick Start Guide.

 Add note to advise against using console for starting/stopping servers

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItPodsRestart.java

ItPodsRestart test passed more than 6 hrs nightly full test at: http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/2766/testReport/
10-03-2019 02:52:11 INFO  
oracle.kubernetes.operator.ItPodsRestart testServerPodsRestartByChangingZImage SUCCESS - testServerPodsRestartByChangingZImage

PR: owls-77057 fix nightly full test failure for changing image test of ItPodsRestart

---

docs-source/content/security/certificates.md
docs-source/content/security/openshift.md
docs-source/content/security/rbac.md
docs-source/content/security/secrets.md
docs-source/content/security/service-accounts.md
docs-source/content/userguide/introduction/introduction.md

Update the published documentation with more details of the requirement with OpenShift to use the `anyuid` security context.

Add OpenShift security section for anyuid security context

---

kubernetes/samples/scripts/create-rcu-schema/common/createRepository.sh
kubernetes/samples/scripts/create-rcu-schema/common/dropRepository.sh
kubernetes/samples/scripts/create-rcu-schema/create-rcu-schema.sh
kubernetes/samples/scripts/create-rcu-schema/drop-rcu-schema.sh

Updated the sample rcu creation scripts to work for both FMW and SOA Infra domain.  
Following modification were made to the scripts create-rcu-schema.sh/drop-rcu-schema.sh 
in the directory kubernetes/samples/scripts/create-rcu-schema
No change to the script interface. Based on the image String, the script will add the extra components and variables while creating the rcu for  FMW and SOA Infra  using the following logic
======= create-rcu-schema.sh ====
[[ $fmwimage =~ .*soasuite.* ]] && rcuType=soa
[[ $fmwimage =~ .*fmw-infr.* ]] && rcuType=fmw
=========
Starting of oracle DB Service remains same using the script start(stop)-db-service.sh
I run QUICK test on my branch to see any Regression on sample
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/2784/console …

Modified rcu script to support both SOA and FMWInfra Domain

---

docs-source/content/_index.md
docs-source/content/userguide/introduction/introduction.md
docs-source/content/userguide/overview/k8s-setup.md

This PR updates the documentation to make our prereqs and supported platforms clearer.
Specifically, it calls out that we do not support dev/test options like kind, minikube,minishift.

Update prereq information in docs

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItPodsRestart.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java

ItPodsRestart passed in the full test suite run: http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/2874/testReport/oracle.kubernetes.operator/
Both ItPodsRestart and ItOperator passed at:http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/2859/testReport/oracle.kubernetes.operator/

OWLS-77092: Fix ItPodsRestart failure during parallel run in same k8s cluster

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java

operator upgrade test fix. fixed the image name when tests run in external jenkins so that each of the test uses its own image.

Testsinparallel opupgrade

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItElasticLogging.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItStickySession.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/LoadBalancer.java

I found the cause why creating Voyager ingress failed with the error
Error: apiVersion "voyager.appscode.com/v1beta1" in ingress-per-domain/templates/voyager-ingress.yaml is not available
it's a timing issue. I found that after I added print-out of logs from Voyager pod to further debug, % of passed tests increased. So I then increased the waiting time between upgradeVoyagerNamespace and createVoyagerIngress from 20 sec to 60 sec. Now the tests passed three times in a row
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3022/consoleFull
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3023/consoleFull
http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3025/console
below is msg from passed test: …

WIP:Fixed Voyager issue when running StickySession test

---

integration-tests/pom.xml

After the change, 
Internal Jenkins:
JRF domain test is picked up by quicktest of  wls-jrf-integration-tests 
http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/3026/testReport/oracle.kubernetes.operator/
external Jenkins:
http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/667/testReport/

PR: Fix Jrf quicktest suite issue

---

docs-source/content/quickstart/introduction.md

Based on Paul's feedback about the quickstart - in particular the load balancing examples not working *as written* on new OKE clusters with no public IPs - I am adding a notice to the quickstart to make it clearer that you may need to adjust the instructions for different versions of k8s

Add a note to the quickstart about variations between k8s versions

---

operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java
operator/src/main/java/oracle/kubernetes/operator/steps/ServerDownStep.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/ClusterConfigurator.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/BaseConfiguration.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCommonConfigurator.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerSpec.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerSpecCommonImpl.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServersUpStepTest.java

Minor changes to preCreateServerServices behavior by removing precreated services for managed servers when both admin server and all managed servers in the cluster are being brought down.                      
Issue fixed (OWLS-76689):
In SOA domains, the startup of admin server involves JNDI lookup of managed servers, restarting the admin server was found to be very slow, when the preCreateServerServices feature was enabled. This is due to each managed server host name was able to resolve due to the existence of precreated server services, so the JNDI lookup will attempt to connect to each managed server until the configured timeout value in the JNDI lookup, since the managed servers are not running. With this change, each lookup of the managed server will result in a …

OWLS-76689 - SOA:ADMINSERVER TAKING TIME TO RESTART USING SERVERSTARTPOLICY(NEVER TO IF_NEEDED) ON OKE CLUSTER 

---

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-job-template.yaml

Several customers have reported difficulty creating a domain on a persistent volume because default file permissions on the volume are set to only give permission to the root user.  This change uses an initContainer to give permission to the "oracle" (1000) user.

Prepare file permissions on persistent volume using an init container

---

operator/src/main/java/oracle/kubernetes/operator/calls/FailureStatusSource.java
operator/src/main/java/oracle/kubernetes/operator/calls/ForbiddenErrorBuilder.java
operator/src/main/java/oracle/kubernetes/operator/calls/UnrecoverableErrorBuilder.java
operator/src/main/java/oracle/kubernetes/operator/calls/unprocessable/UnprocessableEntityBuilder.java
operator/src/main/java/oracle/kubernetes/operator/helpers/DomainStatusPatch.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java

When an update to a pod, service or job fails with 403 (forbidden), abort and record the result in the domain status

Handle forbidden status from Async call

---

operator/src/main/java/oracle/kubernetes/operator/helpers/CrdHelper.java
operator/src/test/java/oracle/kubernetes/operator/helpers/CrdHelperTest.java

Without this change, Kubernetes was reporting a warning in the status of the CRD.

Correct issue with CRD not generating structural schema

---

kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/common/utility.sh
kubernetes/samples/scripts/create-soa-domain/domain-home-on-pv/common/utility.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/common/utility.sh
operator/src/main/resources/scripts/introspectDomain.sh
operator/src/main/resources/scripts/startServer.sh
operator/src/main/resources/scripts/utils.sh
src/integration-tests/introspector/util_subst.sh

Implements JIRA `(OWLS-77081) add file security tracing - show user & file permissions`
Adds runtime tracing to introspector & start-server.  
Adds tracing to the three pv samples 'create domain job' path.
Sample output:
```
@[2019-11-18T20:07:55.755 UTC][introspectDomain.sh:281][FINE] id = 'uid=1000(oracle) gid=1000(oracle) groups=1000(oracle)'
@[2019-11-18T20:07:55.772 UTC][introspectDomain.sh:285][FINE] Directory trace for DOMAIN_HOME=/shared/domains/domain1 (before)
ls -ld /shared/domains/domain1/*:
drwxr-x--- 2 oracle oracle 4096 Nov 18 20:07 /shared/domains/domain1/autodeploy
drwxr-x--- 2 oracle oracle 4096 Nov 18 20:07 /shared/domains/domain1/backup_config
drwxr-x--- 6 oracle oracle 4096 Nov 18 20:07 /shared/domains/domain1/bin
drwxr-x--- 8 oracle oracle 4096 Nov 18 20:07 …
```

add file ownership tracing to introspect-job/server-pod, and to sample pv create-domain-job scripts

---

docs-source/content/samples/simple/domains/domain-home-in-image/_index.md
docs-source/content/samples/simple/domains/domain-home-on-pv/_index.md
docs-source/content/userguide/introduction/introduction.md

Updated all instances of, "The operator requires Oracle WebLogic Server 12.2.1.3.0 with patch 29135930 applied," to "The operator requires either Oracle WebLogic Server 12.2.1.3.0 with patch 29135930 applied, or Oracle WebLogic Server 12.2.1.4.0."

update WLS image version

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/JrfDomain.java

The functional tests are specifying an image pull secret in the domain CRD that is never used in the tests. This causes domain validation to be added in owls-76750 to fail.

Remove unneeded image pull secret

---

docs-source/content/samples/simple/ingress/_index.md
docs-source/content/userguide/managing-domains/ingress/_index.md

I did not put the Traefik notice in the Quick Start guide because it is a declared walk-through for demonstration purposes only. However, if you want me to put it there also, I will.

add Traefik notice

---

docs-source/content/userguide/managing-domains/_index.md
docs-source/content/userguide/managing-domains/domain-resource.md
operator/src/main/resources/scripts/startNodeManager.sh
src/integration-tests/introspector/introspectTest.sh
src/integration-tests/introspector/wl-introspect-pod.yamlt
src/integration-tests/introspector/wl-pod.yamlt

To separate JVM arguments (memory and java options) for WLS managed server instances and the node manager instance, the following environment variables can be used:
- JAVA_OPTIONS - Java options for starting WL server
- USER_MEM_ARGS - JVM mem args for starting WL server
- NODEMGR_JAVA_OPTIONS - Java options for starting Node Manager instance
- NODEMGR_MEM_ARGS - JVM mem args for starting Node Manager instance
The following behavior occurs depending on whether or not NODEMGR_JAVA_OPTIONS and NODEMGR_MEM_ARGS is defined:
- If NODEMGR_JAVA_OPTIONS is not defined then any values defined for JAVA_OPTIONS are applied to the Node Manager instance.  
- If NODEMGR_MEM_ARGS is not defined then default ("-Xms64m -Xmx100m") values are applied.
To apply the defined NODEMGR_MEM_ARGS to the node …

OWLS 72829: Separate JVM arguments for NM and server instance

---

integration-tests/pom.xml
integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItCoherenceTests.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItDomainInImage.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItElasticLogging.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItInitContainers.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItJrfPvWlst.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItManagedCoherence.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItMonitoringExporter.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItMultipleClusters.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItOperator.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItOperatorTwoDomains.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItPodTemplates.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItPodsRestart.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItPodsShutdown.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItServerDiscovery.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItSessionMigration.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItSitConfigDomainInImage.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItSitConfigDomainInPV.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItStickySession.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java
integration-tests/src/test/resources/setupenv.sh
src/integration-tests/bash/cleanup.sh

and fix NPE when a test fails to start operator
testDomainOnPVusingWdt was failing on external jenkins, fixed it.
http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/770/
quicktest on exernal jenkins - http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/771/
quicktest on internal jenkins - http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3772/

Fix ItOperator testDomainOnPvUsingWdt test on external Jenkins

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Operator.java

The image property is not properly set when running in shared cluster for upgrade tests. This fix looks for the presence of operatorImageName, and operatorImageTag regardless of where the test is running and then sets the image property in operatorMap.

Opupgradefix

---

docs-source/content/faq/configmaps.md
docs-source/content/faq/volumes.md

Added FAQ entries to explain how to add per-server persistent volume claims and config maps.
I could not find information on what is actually required to get the new entries added to the index page, or the reason for the headers on other such pages that include dates and weight. Is that documented somewhere?
Note: this requires creating both a volume and a volumeMount entry. If we aren't attempting to support the full range of persistent volumes, but only these two, we might consider simplifying to a single entry. As it is, we should add some validations, including the existing of a matching volume for every volume mount, and possibly also some validation that the specified resource (PVC or ConfigMap) actually exists.

add FAQs for mapping PVC and ConfigMap to instances

---

docs-source/content/userguide/managing-domains/domain-resource.md
operator/src/main/resources/scripts/startNodeManager.sh
src/integration-tests/introspector/introspectTest.sh
src/integration-tests/introspector/wl-pod.yamlt

NM_MEM_ARGS environment variable will, by default, include the java security property '-Djava.security.egd=file:/dev/./urandom', if not already defined.  This is to help speed up the Node Manager startup, especially when the system has low entropy.   Also updated 'Domain Resource' section of user guide documentation to include defaulting information about 'NODEMGR_MEM_ARGS' environment variable.

Nm mem args

---

operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/AdminServer.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCommonConfigurator.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/AdminServerTest.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainStatusTest.java

The getAdminService method was changing the AdminServer object in a way that changed the behavior of equals(), causing repeated domain updates. This corrects that.

Make getAdminService idempotent

---

operator/src/main/resources/scripts/startNodeManager.sh

Generate a NM thread dump if NM times out. Also fix NM .out dump to stdout.

Improve node manager debugging

---

Dockerfile

This PR changes the operator to run as a non-root user.  This is implemented in response to requests from specific users, plus general security hygiene improvement. 
Passed quicktest -> 
http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/880/testReport/oracle.kubernetes.operator/
output showing that operator is running as user 1000(oracle) and files are owned by that use and group
[root@mark weblogic-kubernetes-operator]# k get pods 
NAME READY STATUS RESTARTS AGE
weblogic-operator-759c44db4f-525h9 0/1 Running 0 5s
[root@mark weblogic-kubernetes-operator]# k exec -ti weblogic-operator-759c44db4f-525h9 /bin/bash
bash-4.2$ id
uid=1000(oracle) gid=1000(oracle) groups=1000(oracle)
bash-4.2$ ls -al
total 892
drwxr-xr-x. 1 oracle oracle 4096 Jan 22 14:44 .
drwxr-xr-x. …

[OWLS-79168] Run operator as non-root user

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItJrfPvWlst.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/DbUtils.java

Internal Jenkins passed at: http://wls-jenkins.us.oracle.com/view/weblogic-operator/job/weblogic-kubernetes-operator-javatest/3975/testReport/
External Jenkins passed at: http://build.weblogick8s.org:8080/job/weblogic-kubernetes-operator-quicktest/890/testReport/
Locally I simulated "abort test" scenario to verify the fix.

PR: Owls 79241 improve JRF domain cleanup logic

---

docs-source/themes/hugo-theme-learn/layouts/partials/menu-footer.html

Remove the build badge  which is not using https, does not have a valid cert, and which is not being used 'right' anyway - not pointing to a consistent branch.

Remove the build badge 

---

docs-source/content/faq/oci-fss-pv.md

Add documenation FAQ item about updating the `initContainers` with a different command for OCI FSS persistent volume handling as the domain-on-pv example fails when using OKE and a PV from OCI FSS.
This is the first cut at the information and I'm using the command that was initially discussed. I'm happy to change this command along with wording or the basic content layout I have started here.
The FAQ is trying to present the basic issue with some references and more details about how the problem shows up and where to go make the change.
Thanks, -Craig

Add FAQ entry for persistent volume using OCI FSS

---

docs-source/content/faq/oci-fss-pv.md

Rosemary, Ryan, Tom, so I'm adding the weight entry to this new FAQ as all the FAQ entries have one on `develop` branch.
I picked the highest number and I would suggest merging this for consistency and then "someone" should follow up and decide on actual ordering because there are gaps in the numbers and two .md files with the same `weight` excluding the sample page.
If you really want this PR to fix/adjust all the `weight` entries that is fine... Just tell me what order you want them in and I will add the files to the PR...
Thanks, -Craig

Add weight to OCI FSS FAQ entry

---

integration-tests/pom.xml
operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/main/java/oracle/kubernetes/operator/helpers/CrdHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/HealthCheckHelper.java

1. Cherry-pick Marina's pom change to disable the monitoring exporter test that is hanging
2. No longer skip CRD operations based on the pre-auth, health check results, but stick with the pattern of trying the operation and having the operator handle failures
3. Clean-up some of the unnecessary pre-auth, access checks given the reduction in privileges.
Quick test is clean; waiting on full test, but looking good.

Fix what is broken

---

integration-tests/pom.xml
kubernetes/pom.xml
operator/pom.xml
pom.xml
swagger/pom.xml

- Remove direct dependency on Guava since this comes transitively
- Reduce scope of kjetland to test
- Add direct dependency on bouncy castle to update version.  
Note: kubernetes/client-java have updated bouncy castle to the latest version, but not yet released a version that includes this update.

Dependency review

---

docs-source/content/samples/simple/elastic-stack/weblogic-domain/_index.md

This PR updates the fluentd sample that we have in the docs.  The current sample passes through the `timestamp` as a `string` which means you cannot do time-based queries like "before x" or "between x and y" or "in the last 15 minutes".
The PR updates the sample so that the special `@timestamp` field will be added, with type `time` and with the same value as the `string timestamp`.  This will allow users to do time based queries.

Update fluentd example

---

src/integration-tests/bash/cleanup.sh

Various updates to cleanup script:
- Additional tracing throughout
- Added a 'dry run' mode. This is useful for debugging the script itself. If you pass '-dryrun' on the command line, then the script will proceed without deleting anything - it will just echo potential delete commands - plus it will reduce it's wait-for-pods timeouts (since we know the pods aren't going away).
- Add timestamps to trace statements
- Remove its delete of tiller.
- Remove its direct delete of namespaces.
- Add new deletes before attempting its 'usual' deletes:
- Delete domains and wait up to 60 seconds for their pods to go away (assumes operators will do this)
- Delete operator deployments
- Delete any leftover WLS and introspector pods and wait up to 60 seconds for them to go away
- Modify the 'old' path a …

Make cleanup script more orderly in its deletes.

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/resources/model-in-image/miisection-toaddin-domain-template.yaml
kubernetes/samples/scripts/common/domain-template.yaml
kubernetes/samples/scripts/common/utility.sh
kubernetes/samples/scripts/common/validate.sh

Remove mii section from samples domain-template.yaml as suggested by Tom/Dongbo as this file is used only for domain on pv and domain in image samples.
Integration tests append mii section to the domain-template.yaml
added comments in samples scripts utility.sh and validate.sh
Clean full test run on external jenkins - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1181/

Remove mii section from samples domain-template.yaml

---

docs-source/content/quickstart/cleanup.md
docs-source/content/quickstart/create-domain.md
docs-source/content/quickstart/install.md
docs-source/content/samples/simple/rest/_index.md
docs-source/content/security/certificates.md
docs-source/content/security/secrets.md
docs-source/content/userguide/introduction/introduction.md
docs-source/content/userguide/managing-domains/accessing-the-domain/_index.md
docs-source/content/userguide/managing-domains/accessing-the-domain/wlst.md
docs-source/content/userguide/managing-operators/installation/_index.md

Removed all refs to Helm 2.x except for SOA domain prereqs. (And, edited two user guide headings to align them with the others.)

remove mention of Helm 2.x

---

src/integration-tests/bash/cleanup.sh

Modified the clean up scripts to loop thru the NameSpace which has active Helm Deployment for the deletion of Helm Deployment.  The new logic will take care of  both Helm 2.x/3.x

Enhance Helm chart deletion Logic in cleanup.sh Script  

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItModelInImageConfigUpdate.java

The test deletes a existing JDBC data source and application using the model file with ! annotation on the resources.
The tests are passed locally.
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,798.153 s - in oracle.kubernetes.operator.ItModelInImageConfigUpdate
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] Reactor Summary:
[INFO]
[INFO] Build Tools 1.0 .................................... SUCCESS [  1.150 s]
[INFO] weblogic-kubernetes-operator 3.0.0 ................. SUCCESS [  2.748 s]
[INFO] operator-swagger 3.0.0 ............................. SUCCESS [  8.218 s]
[INFO] json-schema 3.0.0 .................................. SUCCESS [ 10.684 s]
[INFO] jsonschema-maven-plugin Maven Mojo 3.0.0 …

adding config delete and app delete tests using mode file

---

new-integration-tests/pom.xml
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleDomainValidation.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java

1. Added support for create/delete of service accounts
2. Changed Kubernetes.deleteNamespace() to use GenericKubernetesApi
3. Added create and delete service account calls to ItSimpleDomainValidation.testCreatingDomain() test.
4. Added dependency on 'io.kubernetes:client-java-extended' module for use of GenericKubernetesApi

Additional mii integration test support for K8s resources

---

src/integration-tests/bash/cleanup.sh

Modify the filter expression to delete few NameSpace(s) created by Integration Test. Due to this we see lot of hanging NameSpaces ever after successful completion of Tests

Enhance the cleanup script to include deletion of few namesapce(s) 

---

operator/src/main/resources/scripts/modelInImage.sh

This is a temporary work around for WDT returning 1 instead of 0,  when the model has only credential secrets but no other custom secret, in this case the operator will not mount the directory ```/weblogic-operator/config-overrides-secrets``` and WDT checks whether the directory exists and return 1 for warning if not there.

Missing secret dir fix

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItJrfPvWlst.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java

This PR is to improve stability of JRF domain on external Jenkins  by enabling custom MaxIterations count for verifyDomainCreated from 40 to 80.
Latest clean Jenkins run after code refactoring:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1236/

PR: enable custom MaxIterations count for verifyDomainCreated

---

operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java

Fixes `ConcurrentModificationException` from `JobWatcher.getOrCreateFor()` as described in OWLS-80829
Also fixes `ConcurrentModificationException` from `DomainStatus.getServers()` and `getClusters()` in the `Array sort()` method calls.

OWLS-80829 - Fix ConcurrentModificationException in JobWatcher and DomainStatus

---

docs/domains/Domain.json
docs/domains/Domain.md
docs/domains/index.html
kubernetes/crd/domain-crd.yaml
kubernetes/crd/domain-v1beta1-crd.yaml
operator/src/main/java/oracle/kubernetes/utils/OperatorUtils.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/ClusterStatusTest.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainStatusTest.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/ServerStatusTest.java

PR 1531:
- Lack of assert messages in ServerStatusTest
https://github.com/oracle/weblogic-kubernetes-operator/pull/1531/files#r403143296 (OWLS-80945)
- Clarify sorting method in javadoc for OperatorUtils.createSortedMap()
https://github.com/oracle/weblogic-kubernetes-operator/pull/1531/files#r403139882 (OWLS-80943)
PR 1532:
- javadoc for DomainSpec.getHttpAccessLogInLogHome()
https://github.com/oracle/weblogic-kubernetes-operator/pull/1532#discussion_r403218811
- minor javadoc fix to description for includeServerOutInPodLog in DomainSpec
PR 1536:
- DomainStatus javadoc fix
https://github.com/oracle/weblogic-kubernetes-operator/pull/1536#discussion_r403405689
- Add more unit tests to DomainStatusTest for DomainStatus.getServers() and getClusters() …

Resolve docs and testing review comments from PRs 1531, 1532, and 1536

---

Dockerfile

Updates the operator's Dockerfile to use the OpenJDK 11.0.7 JRE.
Based on a discussion with Aurelio, I've changed the Dockerfile to start with oraclelinux:7-slim and to download the OpenJDK 11.0.7 JRE installer rather than base on an openjdk:11-oracle image.  This saves 200MB!!!
With 11.0.7, we should now be able to run against k8s 1.16+.

Use OpenJDK 11.0.7 JRE

---

buildDockerImage.sh
new-integration-tests/pom.xml
new-integration-tests/src/test/java/oracle/weblogic/domain/ServerPod.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleDomainValidation.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleOperatorValidation.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Docker.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
new-integration-tests/src/test/resources/wdt-models/model1-wls.yaml

Adding test for Mii end to end use case :
create unique namespace for operator
create unique namespace for domain 
create service account for operator
install operator
verify operator pod is running
create image using model file
create domain using model in image
verify domain is created
verify admin and managed pods are started and ready
verify admin and managed services are running
delete domain 
delete domain image
uninstall operator
delete service account
delete domain namespace
delete operator namespace
Adding Docker Primitive class.
Calling buildDockerImages.sh from pre-integration-test phase in pom.xml

Adding test for mii end to end use case

---

docs-source/content/_index.md
docs-source/content/userguide/introduction/_index.md
docs-source/content/userguide/introduction/introduction.md

An attempt to elevate the visibility and access to the prerequisites and supported environments. Despite the previous link in a Note on the Home page, I thought this information might be more visible (i.e., read by more users) by placing it with the current release number and date published text.

call out prerequisites

---

operator/src/main/resources/scripts/modelInImage.sh

CGBU discovered a problem, when setting WLSDEPLOY_PROPERTIES with -Doracle.jdbc.fanEnabled in the domain resource, it caused the WDT create fails. The reason is -skipWLSModuleScanning is not a JVM properties and it caused the the wlst failed to start.  It shouldn't be there in the first place, I am removing for now. In order to add this, it requires a WDT enhancement.

Setting WLSDEPLOY_PROPERTIES cause WDT failed to start

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ExecCommand.java

Fix a problem in ExecCommand util. When both redirect and saveResults enabled, the stdout is not correctly saved because both work on the same InputStream.

Fix command stdout

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleDomainValidation.java

This PR addresses the cleanup failures in ItSimpleDomainValidation test suite, in case test fails and leave behind the various artifacts. By breaking up the code into BeforeAll, Test and After methods the artifacts are cleaned up even when test fails.

Break the code in to BeforeAll, Test and AfterAll blocks

---

integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java

we expect if to fail, and want to retry it until it is successful.  it
can fail because the web app has not had time to start up yet.  the
current code throws a runtime exception on a non-zero return code, which
causes this test to fail too fast and incorrectly.
I was investigating the failure in test  oracle.kubernetes.operator.ItDomainInImage.testDomainInImageUsingWdt.  Here is the relevant part of the log:
```
<04-26-2020 09:39:52> <INFO> <oracle.kubernetes.operator.BaseTest testAdminT3Channel> <Inside testAdminT3Channel>
<04-26-2020 09:39:52> <INFO> <oracle.kubernetes.operator.utils.TestUtils kubectlexecNoCheck> <Command to call kubectl sh file kubectl -n itdomaininimage-domainns-2 exec -it itdomaininimage-domain-9-admin-server  -- mkdir -p /u01/oracle/apps>
<04-26-2020 09:39:53> …
```

do not fail the whole test if the curl command returns a non-zero status

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ExecCommand.java

Fix intermittent issues on Jenkins in exec command util.
1) revert the changes that perform mark and reset.
2) force the thread to join so that the copied input stream is ready to be read for getting the stdout.

Fix exec command

---

integration-tests/src/test/java/oracle/kubernetes/operator/ItElasticLogging.java

This test failed with a file error, it is not clear why, so this PR seeks to add some extra logging to help with problem determination.
Example failure: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1375/testReport/oracle.kubernetes.operator/ItElasticLogging/testWlsLoggingExporter/
```
java.lang.NullPointerException
at java.base/java.io.File.<init>(File.java:276)
at oracle.kubernetes.operator.ItElasticLogging.downloadWlsLoggingExporterJars(ItElasticLogging.java:523)
at oracle.kubernetes.operator.ItElasticLogging.testWlsLoggingExporter(ItElasticLogging.java:336)
```

WIP: Add some debugging for ITElasticLogging test

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleDomainValidation.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/IntegrationTestWatcher.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingUtil.java

If a exception is thrown in BeforeAll, BeforeEach and AfterEach methods the extension is catching that but not re throwing it, which causes the test to continue if those methods fail.
The fix is to re throw the throwable in the LifecycleMethodExecutionExceptionHandler methods.
Changed the code to get the LOGS_DIR to store diagnostic logs from TestConstants.java
Changed the volumeName in persistent volume claim to pv name.

Rethrow the exception caught in the BeforeAll, BeforeEach and AfterEach

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleDomainValidation.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleOperatorValidation.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/IntegrationTestWatcher.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CleanupUtil.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingUtil.java

Deletes all the artifacts in the namespaces left behind by the tests.
First it deletes the WebLogic domain if exists, then uninstalls the operator
Finally deletes everything else in the namespace. Waits for up to 3 minutes for the cleanup to be complete.

Cleanup artifacts in Kubernetes cluster

---

operator/src/main/resources/scripts/modelInImage.sh

This PR provides two additional checks
1.  Minimum WDT version 1.7.3
2.  Check and fail if user put unsupported file extension in the model directories, supported are .yaml, .properties, or .zip (only in the image)

Check fileext wdt

---

operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java
operator/src/main/java/oracle/kubernetes/operator/work/Step.java
operator/src/test/java/oracle/kubernetes/operator/work/StepChainTest.java

Fixes an issue causing one of the managed servers to not startup with cluster replica of 2, when operator logging level is set to FINER or FINEST. 
Cause
- This is due to the log message
`LOGGER.finer(CURRENT_STEPS, na.next);`
in Fiber.java:586 getting a StackOverflowError from `Step.toString()` when there is a loop in the na.next chain.
```
DomainStatusUpdaterStep$ProgressingStep @7205
next -> AsyncRequestStep @7209  (for createPod)
next -> PodStepContext$CreateResponseStep @7213
next -> AsyncRequestStep @7209 (for createPod)
next -> PodStepContext$CreateResponseStep @7213
...
```
Fix
- `DomainStatusUpdater.createRetry()` does not need to chain both `updaterStep` and `next`, as next is included in the chain of `updaterStep.next`
- Also modify `Step.chain(`) method to avoid creating loop

Managed server not starting with FINER logging level

---

docs/domains/Domain.json
docs/domains/Domain.md
docs/domains/index.html
kubernetes/crd/domain-crd.yaml
kubernetes/crd/domain-v1beta1-crd.yaml
operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java
operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStep.java
operator/src/main/java/oracle/kubernetes/operator/steps/ReadHealthStep.java
operator/src/main/java/oracle/kubernetes/operator/utils/WlsDomainConfigSupport.java
operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsDynamicServersConfig.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerStatus.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
operator/src/test/java/oracle/kubernetes/operator/DomainStatusUpdaterTest.java
operator/src/test/java/oracle/kubernetes/operator/steps/ReadHealthStepTest.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainStatusTest.java

This PR fixes the following:
- Desired State in server status should not be 'RUNNING' if the server will not be started due to replicas value or serverStartPolicy. It is now shown as 'SHUTDOWN'.
- Server status and cluster status ordering not working since the use of status subresource.
- Server status missing for configured servers in a cluster.
- Health state for configured servers in a cluster were not read.

OWLS-81272 - Fix domain status for 'desired state'

---

docs-source/content/userguide/managing-operators/using-the-operator/using-helm.md

As per "OWLS-80278 - Helm 3 documentation needs to inform user that `helm list` is per namespace," I changed the description of the helm list command. Also, please advise regarding `helm ls` found in Frequently asked questions > Managing domain namespaces, at https://oracle.github.io/weblogic-kubernetes-operator/faq/namespace-management/

change helm list command

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSimpleOperatorValidation.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Operator.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingUtil.java

Add namespaced events in the collected logs list
Fix the persistent volume claim log file name
Fix the isPodReady test assertion to check for pod readiness instead of Running status
Change the domain/operator wait time from 5 to 10 minutes.

Fix assertion and add events log to the logs list

---

docs-source/content/faq/namespace-management.md

OWLS-80278 - Helm 3 documentation needs to inform user that `helm list` is per namespace, part II. Edit `helm ls` command in Managing Domain Namespaces FAQ.

update helm ls

---

docs/domains/Domain.json
docs/domains/Domain.md
docs/domains/index.html
kubernetes/crd/domain-crd.yaml
kubernetes/crd/domain-v1beta1-crd.yaml
operator/src/main/java/oracle/kubernetes/operator/KubernetesConstants.java
operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/ClusterConfigurator.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/EffectiveConfigurationFactory.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/Cluster.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/Domain.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainCommonConfigurator.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java
operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServersUpStepTest.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/DomainTestBase.java

Introduce a new Cluster CRD element `allowReplicasBelowMinDynClusterSize` that if set to true (the default), the operator would allow replicas count to be set below the minimum dynamic cluster size configured in the WebLogic domain home configuration. 
This allows users to shut down all servers in a dynamic cluster by setting the cluster replicas count to 0. This also prevents managed servers in a dynamic cluster from starting by operator even if the replicas is 0. This was the behavior before OWLS-79994.
To prevent WLDF from scaling below the min dynamic cluster size, set  `allowReplicasBelowMinDynClusterSize` to false.

OWLS-80960 - Allow replicas count to drop below min dynamic cluster size

---

operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainSpec.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/DomainTestBase.java

Fix regression introduced in owls-80960 causing managed servers not starting up when no cluster spec is specified for a dynamic cluster in the domain CRD.

Handle null cluster in isAllowReplicasBelowDynClusterSizeFor

---

integration-tests/src/test/resources/setupenv.sh
integration-tests/src/test/resources/wdt/config.cluster.topology.yaml
operator/src/main/resources/scripts/introspectDomain.py
src/integration-tests/introspector/introspectTest.sh
src/integration-tests/introspector/util_build_mii_image.sh
src/integration-tests/introspector/util_download_mii_tools.sh

- issue https://github.com/oracle/weblogic-kubernetes-operator/issues/1457: 
- update introspector job's jython script to work around an off-line WLST bug in SSL bean access (an attempt to access the bean when it's disabled throws an NPE)
- update 'old WDT integration test' to reproduce/test
- fix stand-alone introspector test's MII path (depended on scripts that were removed)
- add option to old integration tests to bypass its desire for a docker login when running locally

fix issue 1457 (and sundry)

---

operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ObjectPatch.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerStatus.java
operator/src/test/java/oracle/kubernetes/operator/helpers/DomainStatusPatchTest.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainStatusTest.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/ServerStatusTest.java

This address two issues that caused the operator to send status updates repeatedly:
1. Our server status reader sometimes fails to get the status for a server. The code was defaulting to SHUTDOWN, meaning that we would intermittently change the state of a server to SHUTDOWN and then back to the real value. The code now defaults to the previous state of a server, if known.
2. The ServerStatus object has a volatile field called `isAdminServer` used for sorting to ensure that the admin server is listed first in the domain status; unfortunately, it was also included in the equals() method, meaning that it always looked as though the status had changed and needed to be updated. Since the field is volatile, that did nothing, so we updated the status about once a second. It has now been removed …

Endless status updates

---

kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl

Make resource requests and limits configurable for operator pod. Resource requests and limits can be configured by specifying below 4 properties in values yaml file.  
cpuRequests  
memoryRequests
cpuLimits
memoryLimits

added option to configure operator pod resource requests and limit

---

integration-tests/src/test/java/oracle/kubernetes/operator/BaseTest.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItDomainInImage.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItManagedCoherence.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItMonitoringExporter.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItMultipleClusters.java
integration-tests/src/test/java/oracle/kubernetes/operator/ItUsabilityOperatorHelmChart.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/Domain.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/LoadBalancer.java
integration-tests/src/test/java/oracle/kubernetes/operator/utils/TestUtils.java
integration-tests/src/test/resources/deploywebapp.py
integration-tests/src/test/resources/resolveServiceName.py
integration-tests/src/test/resources/statedump.sh

1. add checks to resolve the managed server service names from admin pod
2. print cluster status in py script before deploy
3. retry for app deployment
4. fixed managed coherence and multiple cluster tests for pods ready check and services created check.
With all these changes, I see good results on cluster-10. On cluster-1(quicktest) there are still ~15 failures on this branch vs ~30 failures on develop branch.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1464/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest/1460/
Only two failures on cluster-10 - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-quicktest-10/74/

retry for app deployment and other fixes

---

kubernetes/samples/scripts/create-soa-domain/domain-home-on-pv/wlst/create-domain-script.sh

Hi @markxnelson @rjeberhard,
This pull request is to back-port the java_home fix to version 2.4.0 branch which the early access customers are using for SOA deployment.
The issue is that, in latest fmw infra images the java home is changed to different location and set as JAVA_HOME. To address this for SOA deployment scripts we need this fix.
Kindly review and approve this.
Also please add @rdas0405  and @vivek-sam  to this PR as reviewers.
Thanks
Samba

WIP: backport java_home fix to version 2.4.0

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItScaleMiiDomainNginx.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItUsabilityOperatorHelmChart.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Nginx.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Domain.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonUtils.java

Convert ItUsabilityOperatorHelmChart#testDeleteOperatorButNotDomain to JUnit5 test framework.
Move commonly used test methods to CommonUtils.java.
Since I keep getting Jenkins run failure in PR 1647, I will create a new PR and close 1647.
Possible reason for the Jenkins failure is my branch name was too long. 
The Jenkins error in PR 1647:
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/workspace/weblogic-kubernetes-operator-model-in-image-tests
No credentials specified
> git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
> git config remote.origin.url https://github.com/oracle/weblogic-kubernetes-operator # timeout=10
Cleaning workspace
> git rev-parse --verify HEAD # …

convert ItUsabilityOperatorHelmChart to JUnit5

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAddCluster.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiConfigMap.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiConfigMapOverride.java
new-integration-tests/src/test/resources/wdt-models/model.jdbc.yaml

Here is the usecase description 
(a)  Add a cluster with default spec level replica count i.e. ZERO.  Update the domainRestartVersion to trigger a rolling restart.  Make sure no server from the new cluster is in RUNNING state.
(b) Add a configured cluster to a deployed MII Domain using a sparse model file. 
(c) Add a dynamic cluster to a deployed MII Domain using a sparse model file. 
Make sure the managed servers from the new cluster are in RUNNING state after updating the domainRestartVersion and spec level replica count to a non-ZERO value
Extra Update -  Add a JMS/WLDF configuration to MiiDomain using sparse model files.  Verify the Configuration/Runtime for the JMS/WLDF system resource using REST API 
External Jenkin Run(s) …

Add config/dynamic cluster to MiiDomain

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiChangeAdminCredentials.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Command.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Application.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Domain.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java

Add a new Junit5 test case to patch an existing domain resource with a new domain credentials secret that contains new credentials. 
The test performs two patches to the domain spec:
1) change the domain spec's  webLogicCredentialsSecret to a new secret
2) change the domain spec's restartVersion to trigger a rolling restart of server pods.
The test verifies the following:
1) the domain spec's webLogicCredentialsSecret and restartVersion are updated;
2) the server pods are recreated;
3) the server pods' restartVersion label is updated;
4) the new credentials are valid.

Test change domain credentials secret

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItDomainOnPV.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAddCluster.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiChangeAdminCredentials.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiConfigMap.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiConfigMapOverride.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java

Add the new rolling restart assertion (verifyRollingRestartOccurred) to following ItClasses  ItMiiConfigMapOverride, ItMiiAddCluster and ItMiiChangeAdminCredentials
Added following utility method(s) to utils/CommonTestUtils.java
getPodCreationTime()
Removed local methods checkPodCreated/checkServiceCreated to replace with methods from 
utils/CommonTestUtils.java
Added a new action method patchDomainResourceWithNewRestartVersion() to restart a domain with new Restart Version.
External Jenkin Runs
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/182/  ( all passed)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-model-in-image-tests-10/181/    ( all passed )

Add new rolling re-start assertion to ItClasses

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiMultiModel.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java
new-integration-tests/src/test/resources/wdt-models/multi-model-one-ds.20.yaml
new-integration-tests/src/test/resources/wdt-models/multi-model-two-ds.10.yaml

Add a test that creates a MII domain that has two WDT model files in its configmap, and verifies that the resultant configuration is as expected.

Test multiple model files in domain's configmap

---

operator/src/main/java/oracle/kubernetes/weblogic/domain/model/DomainStatus.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerStatus.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainStatusTest.java

Potential fix for OWLS-82442 - server state incorrectly reported as RUNNING even after server is shut-down due to scale down action. Intermittently state of old matching server is RUNNING but health is null (this could be due to race condition). This PR checks if health of old matching server is null then it doesn't update new state with state of old matching server.

Intermittent status issue fix

---

operator/src/main/java/oracle/kubernetes/weblogic/domain/model/ServerPod.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java

Without this change, I was seeing concurrent modification exceptions and duplicated elements in the merged data structures. It looks like we already had similar problems because I was able to use logic similar to what we have for other types in `serverPod`.

Correct affinity merging logic

---

operator/src/test/java/oracle/kubernetes/operator/DomainUpPlanTest.java
operator/src/test/java/oracle/kubernetes/operator/NamespaceTest.java

Fixes test failure in WatchBuilderTest on Linux that is caused by NamespaceTest having a value of domainPresenceRecheckIntervalSeconds in MainTuning that is too low. 
Example of test failure (could happen in a different test in WatchBuilderTest):             
[ERROR] whenServiceWatchSpecifiesParameters_verifyAndReturnResponse(oracle.kubernetes.operator.builders.WatchBuilderTest)  Time elapsed: 0.005 s  <<< ERROR!
io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:45387
at oracle.kubernetes.operator.builders.WatchBuilderTest.whenServiceWatchSpecifiesParameters_verifyAndReturnResponse(WatchBuilderTest.java:203)
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:45387
at …

fix error in WatchBuilderTest.tearDown() caused by NamespaceTest

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItScaleMiiDomainNginx.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Secret.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/IntegrationTestWatcher.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java

Add the test infrastructure support for scaling a cluster using REST API.
Jira task: https://jira.oraclecorp.com/jira/browse/OWLS-82419
Jenkins result: https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/279/
The test oracle.weblogic.kubernetes.ItSessionMigration.testSessionMigration failed on develop branch too. See https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/268/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-model-in-image-tests-10/266/

scale a cluster using REST API

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiMultiModel.java

Remove the REPO_NAME from the image name in ITMIIMultiModel test's BeforeAll method because the common utility method it uses, createMiiImageAndVerify(), already adds REPO_NAME.

Fix image name

---

operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java

Fix for OWLS-81419: Domain status does not reflect status when the MII introspect job fails

Fix for OWLS-81419

---

operator/src/main/resources/scripts/introspectDomain.py

Fix a bug in introspector that caused the SSL NodePort not being exposed by the admin server external service.
Jenkins job is still running https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/287/

Fix a customer issue when SSL is enabled

---

operator/src/main/resources/scripts/utils.sh

It looks like something in the Operator, or some other location, might have changed so that it adds some sort of whitespace character to the domain secret MD5 file that it puts in the introspector configmap.  This caused a domain secret mismatch error. The fixed code now ignores the whitespace when comparing...

fix domain secret mismatch: ignore any whitespace diff

---

operator/src/main/resources/scripts/startServer.sh
operator/src/main/resources/scripts/tailLog.sh

Without this fix, there is often a substantial delay between the time when WLST tries to start a WL server in a pod and the time we start sending the WL server's stdout to the pod log.  (WLST doesn't seem to return control until the WL server has about reached the 'running' state - which can take a while - and the original code doesn't start its 'tail' until after WLST returns.)

start sending wls stdout to pod log earlier

---

Dockerfile

Update our Dockerfile to use GraalVM CE 19.3.2, which is based on OpenJDK 11.0.7+10, rather than the OpenJDK installation.
The resulting Docker image is slightly larger with GraalVM (383 MB vs. 343 MB); however, I believe this is sufficiently close especially since our last release was 538 MB.
We will continue to work with the GraalVM team over time to see if a smaller image is possible.

Use GraalVM CE 19.3.2.

---

operator/src/main/java/oracle/kubernetes/operator/helpers/BasePodStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/StepContextBase.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTestSetup.java
operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectorCMTestUtils.java
operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectorConfigMapTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTestBase.java

Customers noticed that we could not support safely draining a node prior to shutting down that node because `kubectl drain <node-name>` would return an error indicating that some of the pods were not governed by controllers. 
I reviewed the Kubernetes doc. on draining nodes and looked at the Kubernetes code. It turns out that we needed to mark the metadata of our resources with an owner reference so that `kubectl drain` knows it can safely delete pods on the target node because a controller will recreate and reschedule pods on an available node.
With this change, Kubernetes will delete our pods on a node that is being drained and the operator will respond by creating new pods that will then be scheduled on available nodes. 
Again, after reviewing the Kubernetes doc on ownership, it made …

Add owner references to resources associated with a specific domain

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/BuildApplication.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
new-integration-tests/src/test/resources/bash-scripts/build_application.sh

The fix involves   
- Removing the persistent volumes for mounting application source directory  to the pod , since PV_ROOT is shared only between the Kubernetes nodes. Jenkins client doesn't have access to the PV_ROOT  so its not working in Jenkins runs.
-   Instead of a Kubernetes job the utility will create a WebLogic pod and copies the source application folder to the pod and builds the application.    
- Once built the archives directory is copied back to the local file system for use by the test code.
Results
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-model-in-image-tests/1032
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/493/testReport/oracle.weblogic.kubernetes/

Fix build application utility

---

operator/pom.xml
operator/src/main/java/oracle/kubernetes/operator/calls/AsyncRequestStep.java
operator/src/main/java/oracle/kubernetes/operator/helpers/CrdHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ResponseStep.java
operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java
operator/src/main/resources/Operator.properties
operator/src/test/java/oracle/kubernetes/operator/calls/AsyncRequestStepTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/CrdHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java
operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java

Fixed retry logic in AsyncRequestStep (OWLS-82761) and changed CrdHelper so operator can recover gracefully from lack of RBAC for CRD.

Changes to fix retry logic and recover gracefully from lack of RBAC for CRD

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingUtil.java

The LoggingUtil.java uses oraclelinux:latest image to setup a pod to copy PV_ROOT contents.
The latest version tag was deleted from repo and this change uses 7as the tag.

Change image version from default, latest to 7

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorRestartWhenPodRoll.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Kubernetes.java

1) In ItMiiDomain testPatchAppV2 test case, stop the application availability thread when it detects a failure, instead of waiting for the patched application is accessible on all managed servers.
2) In ItOperatorRestartWhenPodRoll test case, check and wait for the operator pod to be restarted, instead of,  ready to close a window between async deletion of the operator and check for podIsReady.

Improve test verification

---

docs-source/content/faq/resource-settings.md
kubernetes/samples/scripts/common/domain-template.yaml
kubernetes/samples/scripts/common/jrf-domain-template.yaml
kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-in-image/create-domain-inputs.yaml
kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-in-image/create-domain.sh
kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/create-domain-inputs.yaml
kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/create-domain.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/create-domain-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml
kubernetes/samples/scripts/create-weblogic-domain/manually-create-domain/domain.yaml
kubernetes/samples/scripts/create-weblogic-domain/model-in-image/domain-resources/JRF/mii-initial-d1-JRF-v1.yaml
kubernetes/samples/scripts/create-weblogic-domain/model-in-image/domain-resources/JRF/mii-update1-d1-JRF-v1-ds.yaml
kubernetes/samples/scripts/create-weblogic-domain/model-in-image/domain-resources/JRF/mii-update2-d2-JRF-v1-ds.yaml
kubernetes/samples/scripts/create-weblogic-domain/model-in-image/domain-resources/JRF/mii-update3-d1-JRF-v2-ds.yaml
kubernetes/samples/scripts/create-weblogic-domain/model-in-image/domain-resources/WLS/mii-initial-d1-WLS-v1.yaml
kubernetes/samples/scripts/create-weblogic-domain/model-in-image/domain-resources/WLS/mii-update1-d1-WLS-v1-ds.yaml
kubernetes/samples/scripts/create-weblogic-domain/model-in-image/domain-resources/WLS/mii-update2-d2-WLS-v1-ds.yaml
kubernetes/samples/scripts/create-weblogic-domain/model-in-image/domain-resources/WLS/mii-update3-d1-WLS-v2-ds.yaml
src/integration-tests/model-in-image/mii-sample-wrapper/mii-domain.yaml.template-JRF
src/integration-tests/model-in-image/mii-sample-wrapper/mii-domain.yaml.template-WLS

Changes for OWLS-80384 - Verify that operator deployment and WebLogic pods have good default cpu/memory resources. 
Changed WLS samples to use below defaults - 
- Min and Max heap size of 256MB and 512MB
- Memory requests of 768MB and CPU request of 250m
Changed JRF samples to use below defaults -
- Min and Max heap size of 512MB and 1024MB for admin server and 256MB and 1024MB for managed servers
- Memory requests of 1280MB and CPU request of 500m
Created first draft of FAQ document for resource requests/limits and Java options for heap size considerations.

Default resources java options

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItJrfDomainInPV.java

Move the KIND_REPO check before calling the DbUtils.setupDBandRCUschema to set the image repos for dbimage and fmwimage.
Before fix
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/618/testReport/junit/oracle.weblogic.kubernetes/ItJrfDomainInPV/oracle_weblogic_kubernetes_ItJrfDomainInPV/
<07-02-2020 20:22:54> <INFO> <oracle.weblogic.kubernetes.ItJrfDomainInPV initAll> <Start DB and create RCU schema for namespace: ns-hmxx, RCU prefix: jrfdomainpv, dbPort: 30,000 dbUrl: oracledb.ns-hmxx.svc.cluster.local:1521/devpdb.k8s **dbImage: container-registry.oracle.com/database/enterprise:12.2.0.1-slim,  fmwImage: container-registry.oracle.com/middleware/fmw-infrastructure:12.2.1.4 isUseSecret: true**>
<07-02-2020 20:22:54> <INFO> …

Fix for ItJrfDomainInPV failures in kind cluster

---

kindtest.sh

Kind includes a built-in simple CNI called kindnet; however, it's possible to use other CNI implementations with Kind clusters. Since Calico is becoming more prominent, I've started with that implementation.
This change adds an option for the CNI implementation supporting Calico and with kindnet still the default.
I'm using the default install YAML's from the Calico site, which use a "v1" CRD and so only work on K8s 1.16 or greater.

Make Calico CNI an option when running tests with Kind

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/LoggingUtil.java

Currently YAML representation of pod log is written, fixing that to write the string without getting the YAML representation.
Now, the pod logs looks like - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-model-in-image-tests/1159/artifact/RESULT_ROOT/diagnosticlogs/ItMiiDomain/testCreateMiiDomain/ns-efgl.pod.domain1-admin-server.container.weblogic-server.log
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-model-in-image-tests/1159/artifact/RESULT_ROOT/diagnosticlogs/ItMiiDomain/testCreateMiiDomain/

Write pod logs as string to the file

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java

Create an unique Voyager release name for each test suite using Voyager as LBer to fix the error below:
<06-29-2020 20:13:21> <INFO> <oracle.weblogic.kubernetes.actions.impl.primitive.Helm exec> <Command failed with errors Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ClusterRole, namespace: , name: voyager-release

Create an unique Voyager release name for each test suite jenkins-ignore

---

operator/src/main/java/oracle/kubernetes/operator/steps/ReadHealthStep.java
operator/src/test/java/oracle/kubernetes/operator/steps/ReadHealthStepTest.java

Remove the default "cluster.local" search path when creating host-name for health check REST URL. This search path can be different for different cloud providers for e.g. it's ".svc.occloud" in GBU CNE team's environment. If the services are in same cluster, just adding namespace to service-name should be sufficient.

correct host-name in health check REST url when Pod IP is null

---

docs-source/content/userguide/introduction/demo.md

YouTube video for WKO 2.0 is now displayed (was previously hidden due to a permission loss).

un-hide demo video

---

kubernetes/samples/scripts/create-rcu-schema/create-rcu-schema.sh
kubernetes/samples/scripts/create-rcu-schema/drop-rcu-schema.sh

Hi,
This is the fix for bug 31480432. Fix is to remove the -t flag from the kubectl commands used for RCU.
Please review.
Thanks
Samba

Removed -t flag from create and drop rcu scripts

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/KubernetesExec.java

We just changed the sample and the product code already does not use TTYs for `kubectl exec` calls.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/748/

Don't use a TTY for execs

---

docs-source/content/userguide/managing-domains/configoverrides/_index.md

.../foo.md#bar --> .../foo/_index.md#bar

Fix broken hugo doc relrefs using a link formatting workaround: 

---

Dockerfile

The latest openjdk build is 12. Change Dockefile to set the correct JAVA_URL:
ENV JAVA_URL https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz

update the JAVA_URL in Dockerfiles

---

new-integration-tests/src/test/resources/apps/coherence-proxy-client/buildRunProxyClient.sh

ItCoherenceTest hangs on wko-kind-nightly and kind-new
https://build.weblogick8s.org:8443/job/wko-kind-nightly/33/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/781
Changes in the PR:
1. timeout the java process in 1  minute by adding "timeout --kill-after=5 --signal=SIGKILL 1m "
2. enable the debug by adding "-Dtangosol.coherence.log.level=9"
Last time ItCoherenceTest passed was on https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/764
it first failed on "develop" branch run, https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/771
There is no useful info for debugger, only shows the failure is from calling "coherence-proxy-client/buildRunProxyClient.sh", with exit code = 202
ItCoherenceTest still PASSES on …

Added timeout and debugger to fix hanging issue on kind-new and Jenkins

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManagedCoherence.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/AppBuilder.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
new-integration-tests/src/test/resources/apps/CoherenceApp/build.xml
new-integration-tests/src/test/resources/apps/CoherenceApp/ear/CoherenceApp.java
new-integration-tests/src/test/resources/apps/CoherenceApp/ear/META-INF/application.xml
new-integration-tests/src/test/resources/apps/CoherenceApp/ear/META-INF/weblogic-application.xml
new-integration-tests/src/test/resources/apps/CoherenceApp/gar/META-INF/MANIFEST.MF
new-integration-tests/src/test/resources/apps/CoherenceApp/gar/META-INF/cache-config.xml
new-integration-tests/src/test/resources/apps/CoherenceApp/gar/META-INF/coherence-application.xml
new-integration-tests/src/test/resources/apps/CoherenceApp/gar/META-INF/pof-config.xml
new-integration-tests/src/test/resources/apps/CoherenceApp/gar/pof/Contact.java
new-integration-tests/src/test/resources/apps/CoherenceApp/gar/pof/ContactId.java
new-integration-tests/src/test/resources/wdt-models/coherence-managed-wdt-config.properties
new-integration-tests/src/test/resources/wdt-models/coherence-managed-wdt-config.yaml

use case: Test association of a Coherence Cluster with multiple WebLogic server clusters by 
* Create domain with two clusters, cluster-1 and cluster-2 and associate them with a Coherence cluster
* Deploy the EAR file to cluster-1 that has no storage enabled
* Deploy the GAR file to cluster-2 that has storage enabled
* Verify that data can be added and stored in the cache and can also be retrieved from cache.
Jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/824/
one failure, oracle.weblogic.kubernetes.ItMiiSample.testJrfInitialUseCase is unrelated to this PR
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-model-in-image-tests-10/549/ 
has less failures than result from develop run at …

OWLS-81928 - JUnit5: Convert ItManagedCoherence (testCreateCoherenceDomainInImageUsingWdt) test 

---

docs/domains/index.html
operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java
operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectionStatusTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupportTest.java

- Updated KubernetesTestSupport so that it replaceDomain preserves the old status.
- Added interface to synchronous domain status replace

Test support: don't update status on replace if defined as subresource

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporter.java

added extra steps to clean up intermittent leftovers from prometheus and grafana artifacts (cluster role bindings, cluster roles)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/906/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/907/

added extra steps to clean up intermittent leftovers from prometheus and grafana artifacts

---

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java
operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java
operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java
operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorDelegateStub.java
operator/src/test/java/oracle/kubernetes/operator/JobWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/IntrospectionStatusTest.java

Changes for OWLS-82011 to reflect introspector status in domain status in below conditions -
1. Missing image
2. Missing PV/C mount
3. Introspector job timeout (deadline exceeded)

Changes for OWLS-82011 to reflect introspector status in domain status

---

kubernetes/samples/scripts/common/utility.sh

added extra properties required for domain creation of Oracle Identity Governance
Signed-off-by: Tanmay Garg<tanmay.garg@oracle.com>
This needs to be available in release/2.6.0 branch as well.

added extra properties required for domain creation 

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java

Revert the ENV variable Change from RESULTS_ROOT to RESULT_ROOT since jenkin job uses the environment variable RESULT_ROOT  not RESULTS_ROOT even if the value is stored in a variable name RESULTS_ROOT

Resolution to Jenkin log archive issue

---

kubernetes/samples/charts/apache-samples/custom-sample/README.md
kubernetes/samples/charts/apache-samples/default-sample/README.md
kubernetes/samples/charts/apache-webtier/README.md

Currently WKO doc refers to helm 2.x syntax on Apache LoadBalancer Document. Need to update the helm install/uninstall command on the README.md files 
Refer to JIRA 
https://jira.oraclecorp.com/jira/browse/OWLS-83785

Update Apache doc for helm 3.x syntax

---

operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java
operator/src/test/java/oracle/kubernetes/operator/JobWatcherTest.java

Revert the change that checks for BackoffLimitExceeded error from intro job in case of failure.

Revert backofflimit check

---

kubernetes/charts/weblogic-operator/templates/_operator-secret.tpl

Customer OFSS discovered that the Operator's internal REST interface is not started after first executing a 'Helm upgrade' command and then recycling/restarting the Operator pod.
The Operator's helm chart manages the 'weblogic-operator-secrets' Kubernetes Secret and the 'Helm upgrade' command reverts the Secret to its original chart content, which is empty.  Subsequent restart of the Operator pod disables the start of the internal REST interface due to the missing private key. 
This change uses the 'lookup' function to check if the 'weblogic-operator-secrets' Kubernetes Secret exists and if so, stores the 'internalOperatorKey' to a template variable and sets the value when recreating the resource.  During install of the chart, the Secret resource creation behaves the same as before where …

Helm upgrade command removes private key from Kubernetes secret 'weblogic-operator-secrets'

---

operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java
operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStep.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/BaseConfiguration.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTestSetup.java
operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStepTest.java
operator/src/test/java/oracle/kubernetes/operator/utils/WlsDomainConfigSupport.java

Changes for OWLS-83431 - Create Pods one-at-a-time waiting on scheduling

Changes for OWLS-83431

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCrossDomainTransaction.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/BuildApplication.java

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1155/
This test was failing only in parallel run. Removed @MustNotRunInParallel and @Slow annotation.

Debugcdttest

---

src/scripts/initialize-internal-operator-identity.sh

initialize-internal-operator-identity.sh  keytool command specify the parameter -srcstorepass twice.

duplicate -srcstorepass parameter used in script

---

docs-source/content/userguide/managing-operators/using-the-operator/using-helm.md
kubernetes/charts/weblogic-operator/templates/_operator-dep.tpl

Owls 83534 - Changes to allow setting nodeAffinity and nodeSelector values in operator Helm chart and related doc change

Owls 83534 - Changes to allow setting nodeAffinity and nodeSelector values in operator Helm chart

---

docs-source/content/userguide/managing-domains/_index.md
operator/src/main/resources/scripts/introspectDomain.sh
operator/src/main/resources/scripts/startNodeManager.sh
operator/src/main/resources/scripts/utils.sh
src/integration-tests/introspector/wl-create-domain-pod.pyt
src/integration-tests/introspector/wl-pod.yamlt

This pull covers the work for JIRA OWLS-83859:
* add log rotation for node manager .out/.log
* enhance log rotation for introspector .out
* document log rotation for WLS .out and .log

log rotation enhancements and doc

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorUpgrade.java

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1415/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1416/
Failure is because of product bug - https://jira.oraclecorp.com/jira/browse/OWLS-84141, Test now asserts when helm upgrade fails.

Adding assertions in upgrade test

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/extensions/ImageBuilders.java

There are quite few images are built when the tests starts to run, but sometimes the docker login , push/pull of images fail and the tests is aborted after spending about an hour. This PR aims to retry those steps when it fails due to network glitch or something.
Ran the tests multiple times and I don't see the failures now.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1635/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1633/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1632/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1631/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1630/ …

Retry docker login, image push/pull from/to repos

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCoherenceTests.java

The test was disabled due to an issue in the test framework. It's fixed now and we bring this test back
Passed Jenkins Jobs
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1565/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1580/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1582/
there is one failure that is not from ItCoherence test
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1581/

Re-enable ItCoherenceTests

---

docs-source/content/userguide/managing-domains/ingress/_index.md

Added NGINX to the note that describes the ICs that we support in production, as per OWLS-84127: WKP Document that Nginx is supported in production environments

add NGINX for production ICs

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsShutdownOption.java

Single test is passed at
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1673/testReport/oracle.weblogic.kubernetes/ItPodsShutdownOption/testShutdownProps/
Need to get this PR in to fix the broken load.

PR: correct the errors for ItPodsShutdownOption

---

kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wdt/create-domain-script.sh
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/wlst/create-domain-script.sh

These changes are required to the samples so that the domain could be created in openshift when working with default scc. I have tested this in my oci linux and am able to start the domain using the create-domain.sh script.

sample changes needed to work in openshift with default scc

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManagedCoherence.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/BuildApplication.java

Occasionally, exec into the pod where an application is built fails with a non-zero exit code. The application builds successfully and the app seems to exist for the test to continue. This exit code is returned by kubernetes client api, so temporarily commenting out the assertion that checks for exitvalue of 0.  Now, any It test that calls buildApplication() to build an app, has to check that the packaged app exists before proceeding with the test. Seems like all the existing tests do that now since the run in kind cluster passed yesterday - 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1808/

fix build application not to assert exec false exit value

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WebLogicImageTool.java

imagetool fails with "[SEVERE ] Response code: -1, message: docker command failed with error: unable to convert uid/gid chown string to host mapping: cant find gid for group oracle: no such group: oracle". Since it will be a while before the next release of WIT, checking in a temporary fix.
Jenkin Run 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1825/

temporarily adding chown option to imagetool command

---

operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/main/java/oracle/kubernetes/operator/helpers/AuthenticationProxy.java
operator/src/main/java/oracle/kubernetes/operator/rest/RestBackendImpl.java
operator/src/test/java/oracle/kubernetes/operator/helpers/AuthenticationProxyTest.java

When namespace selection strategy is configured to be 'Dedicated', requests to the Operator's REST endpoint fail authentication.  Authentication checks were always cluster scoped.  The fix is for REST endpoint authentication to be namespace scoped when in 'Dedicated' namespace selection strategy,

OWLS-84517: Scaling failed when setting Dedicated to true

---

new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItCoherenceTests.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorRestart.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/ItPodsRestart.java
new-integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Pod.java
new-integration-tests/src/test/resources/wdt-models/model.jms2.yaml

Modified the existing test which patches the domain with config map to create JMS server to use LOG_HOME env var to log on PV for JMS message log file.
Also fixed the rolling restart assertions which were reporting incorrect error messages.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1940/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1945/ - known failures 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1951/ - just started a run after syncing to latest develop

Configure JMS Server logs on PV and verify

---

kubernetes/charts/weblogic-operator/templates/_utils.tpl
kubernetes/charts/weblogic-operator/templates/_validate-inputs.tpl

Add a check in helm templates for the existence of the specified service account in an operator installation because Helm V3 does not check it anymore. 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2038/

owls84294 check existence of sa in helm templates

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java

The ItIntrospectVersion and ItConfigDistributionStrategy are using the same persistent volume names which are derived from domainUid + "-pv" 
When these tests are running in parallel the pv creatiopn fails in one of the test due to the fact that pv are cluster objects.
This PR changes the domain name used in the test to be different to avoid this conflict.
Jenkins test results
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2114/

Change domain name

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java

Enable the disabled test cases for standalone managed servers now that the issue has been fixed by PR#1941.
The ItServerStartPolicy test suite passed in Jenkins https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2121/.

OWLS-84380 enable disabled test cases

---

operator/src/main/resources/scripts/introspectDomain.py

ODL configuration is written to a logging.xml file under $domain/config/fmwconfig/servers/<server name> and not in config.xml file, archive the directories for any customization may have been supplied by user's customization.

Fix missing ODL configuration that may presents in the model

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsLoadBalancers.java

We see the test failed intermittently in nightly run both on sequential and parallel run. 
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/4/
https://build.weblogick8s.org:8443/job/wko-kind-nightly-parallel/124/
disable it for now. Once the debug is done and the test is stable, re-enable it.

disable ItTwoDomainsLoadBalancers.testApacheLoadBalancingCustomSample

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomainModelInPV.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WebLogicImageTool.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WitParams.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
integration-tests/src/test/resources/wdt-models/modelinpv-with-war.yaml

Added a  test case to use Image Tool's new --wdtModelHome to specify a custom location in the image, instead of the default location /u01/wdt/models, for the WDT model files.
The test does the following
1. Extended the WebLogicImageTool action to
a) add a new parameter wdtModelHome, to specify the desired wdt model home
b) add --wdtModelHome option in the WIT command line to pass the location to WIT.
2. Added a test case that
a) uses the new --wdtModelHome option to create an image where the wdt models are in a custom location.
b) creates a domain resource that sets spec.configuration.model.modelHome to the custom location that is specified in 2.a).
c) creates the domain resource and verify the server pods are created according to the spec and comesup
Jenkins Results …

Add a testcase for -wdtModelHome option to the imagetool

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java

Default OCR image name is correct, its failing when the tests ran locally by pulling the images from OCR. Fix is tested locally.

Fix default OCR image names

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItParameterizedDomain.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FileUtils.java
integration-tests/src/test/resources/wdt-models/domain-onpv-wdt-model.yaml
integration-tests/src/test/resources/wdt-models/model-multiclusterdomain-sampleapp-wls.yaml
integration-tests/src/test/resources/wdt-models/wdt-singlecluster-multiapps-usingprop-wls.yaml

Add test cases for dataHome override in domain custom resource.
Three use cases are added:
1) dataHome is not specified
2) dataHome is set to empty string
3) dataHome is set to a custom location
Jenkins test result:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2244/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2250/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2251/

Add Tests for DataHome Override in Domain Custom Resource

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsLoadBalancers.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/ApacheParams.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java

ItTwoDomainsLoadBalancers.testApacheLoadBalancingCustomSample failed recently due to the change in Apache custom sample chart. 
When we have custom Apache plugin configuration file custom_mod_wl_apache.conf, we used to specify the path of the file in the chart using volumePath. Couple of days ago it was changed to use persistentVolumeClaimName:
persistentVolumeClaimName: pv-claim-name
Updated this in test and re-enable the test.
Jenkins run result:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2225/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2228/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2229/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2230/

re-enable ItTwoDomainsLoadBalancers.testApacheLoadBalancingCustomSample

---

docs-source/content/userguide/introduction/introduction.md
docs-source/content/userguide/managing-fmw-domains/soa-suite/_index.md

As per OWLS-84881: Document certification of WebLogic on Kubernetes running in a Calico network fabric, added Calico to the operator prerequisites.

add Calico networking

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java

Without change when repo is OCR or OCIR both image names of DB and FMW image are wrong. This PR is to correct image name construction for them.
Jenkin kind cluster test result:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2293/testReport/
1 failure: ItParameterizedDomain.testParamsScaleClustersWithWLDF{Domain}[1] (from oracle.weblogic.kubernetes.ItMiiDomain)

correct image name construction of DB and FMW

---

operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobHelper.java

This PR reduces the timeout value of async delete job call from default value of 10 seconds to 1 second. This is to avoid the unexpected gap in time when job is deleted and recreated following a failure (as a result of retry operation).
Integration test results are at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2367/

OWLS-82012 Reduce job delete timeout value to avoid unexpected gap in time during retry of failed job

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java

In Jenkins run, we get intermittent failure when scaling cluster with WLDF. Adding the retry when coping files to admin server pod and chmod of the files on the admin server pod.
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/2375/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/2359/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/2358/
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/2357/

add retry when scaling cluster with WLDF

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java

Add  logic to make sure all the Services/Pods are ready after rolling start.
With this PR change the first 3 jobs on the KIND Jenkins passed in a row without any failure
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2379/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2380/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2381/
The second 3 jobs in a row
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2391/   -- all passed
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2392/ -- 1 failure
oracle.weblogic.kubernetes.ItMiiUpdateDomainConfig.testMiiUpdateWebLogicCredential
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new …

Improve nightly stability for ItIntrospectVersion.testUpdateImageName

---

docs-source/content/userguide/managing-operators/installation/_index.md

Using `helm upgrade --set image=` to upgrade operator to a newer operator version should be performed from the "upgrade to" branch of the source repository, which would contain fixes to helm templates that might not be present in the "upgrade from" branch.

Minor doc update on upgrading operator using helm upgrade

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorUpgrade.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java

Changed the test case to use the old default suffix when running older releases.
ITOperatorUpgrade tests passed in https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2462/

Fix ItOperatorUpgrade failures 

---

operator/src/main/java/oracle/kubernetes/operator/DomainNamespaces.java
operator/src/main/java/oracle/kubernetes/operator/DomainProcessor.java
operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java
operator/src/main/java/oracle/kubernetes/operator/EventWatcher.java
operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java
operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/main/java/oracle/kubernetes/operator/NamespacedResources.java
operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java
operator/src/main/java/oracle/kubernetes/operator/TuningParametersImpl.java
operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ConfigMapConsumer.java
operator/src/main/java/oracle/kubernetes/operator/helpers/KubernetesUtils.java
operator/src/main/java/oracle/kubernetes/operator/helpers/LegalNames.java
operator/src/main/java/oracle/kubernetes/operator/rest/RestBackendImpl.java
operator/src/main/java/oracle/kubernetes/operator/rest/RestConfigImpl.java
operator/src/main/java/oracle/kubernetes/operator/steps/WatchDomainIntrospectorJobReadyStep.java
operator/src/main/java/oracle/kubernetes/weblogic/domain/model/Domain.java
operator/src/test/java/oracle/kubernetes/operator/DomainPresenceTest.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java
operator/src/test/java/oracle/kubernetes/operator/JobWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/MainTest.java
operator/src/test/java/oracle/kubernetes/operator/NamespaceTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/HealthCheckHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupportTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/TuningParametersStub.java
operator/src/test/java/oracle/kubernetes/operator/rest/RestBackendImplTest.java
operator/src/test/java/oracle/kubernetes/operator/work/FiberTestSupport.java
operator/src/test/java/oracle/kubernetes/weblogic/domain/model/DomainValidationTest.java

This refactoring eliminates a lot of duplicate code and centralizes much of the processing of domain namespaces, including management of watchers. It also addresses some misuse of Kubernetes resource versions: according to the documentation, the initial reference version for a watcher should be taken from the result of a list operation. In two cases, configmaps and jobs, we were using resource versions from other resources.
In the current K8s implementation, that doesn't matter, as it currently uses the etcd modifiedIndex which is consistent for a server; however, that is subject to change.
This cleanup has highlighted some additional issues I hope to address in the next PR, including the fact that we do different processing for a namespace that was in existence before the operator …

Refactoring: extract domain namespaces code from main

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSystemResOverrides.java

The ItConfigDistributionStrategy and ItSystemResOverrides uses the same pv name for the domain. This results in a pv name clash when both these tests are running at the same time in parallel runs.
Fix is to change the domain name to be unique in both tests so that pv name which is derived from domainUID can be unique.

Change the domain name to be unique

---

integration-tests/src/test/resources/python-scripts/application_deployment.py
integration-tests/src/test/resources/python-scripts/changeListenPort.py
integration-tests/src/test/resources/python-scripts/create-jdbc-resource.py
integration-tests/src/test/resources/python-scripts/introspect_version_script.py

With WLS 14.1.1.0 image, the test ItParameterizedDomain#testParamsScaleClustersWithRestApi failed in the domain type domain on pv. The root cause is that in WLS 1411 the usage of "main" of python script got changed. This change caused the application failed to deploy using  the file integration-tests/src/test/resources/python-scripts/application-deployment.py.
See the release note: https://docs.oracle.com/en/middleware/standalone/weblogic-server/14.1.1.0/wlsrn/issues.html#GUID-2F716208-D9A4-4586-91E8-A340DCD0CBF0
This PR removed "if __name__ == 'main':" clause in the python scripts used in test.
Jenkins run:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2571/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/2574/ …

remove "if __name__ == 'main':" in the python scripts used in test 

---

operator/src/main/resources/scripts/introspectDomain.py
src/integration-tests/introspector/README
src/integration-tests/introspector/createStaticCluster.py
src/integration-tests/introspector/introspectTest.sh

With 14.1.1.0 WebLogic image, static/configured clusters are being mis-identified as dynamic clusters.  The workaround bug, where WLST throws an exception when there are no 'real' DynamicServers, may not occur as a DynamicServerMBean is returned although it is not configured with any dynamic servers:
```
<cluster>
<name>c1</name>
<dynamic-servers>
<maximum-dynamic-server-count>0</maximum-dynamic-server-count>
</dynamic-servers>
</cluster>
```
The above <cluster> configuration gets generated when running online WLST.  Validation errors similar to the following can be seen when a configured cluster is mis-identified as a dynamic cluster:
validationErrors:
- "The WebLogic dynamic cluster \"c1\"' is not referenced by any server template."
- "The WebLogic dynamic cluster \"c1\"'s dynamic …

OWLS 85530: OPERATOR INTROSPECTOR THROWS VALIDATION ERRORS FOR STATIC CLUSTER

---

operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/main/java/oracle/kubernetes/operator/MainDelegate.java
operator/src/main/java/oracle/kubernetes/operator/StuckPodProcessing.java
operator/src/main/java/oracle/kubernetes/operator/TuningParameters.java
operator/src/main/java/oracle/kubernetes/operator/TuningParametersImpl.java
operator/src/main/java/oracle/kubernetes/operator/calls/AsyncRequestStep.java
operator/src/main/java/oracle/kubernetes/operator/helpers/AsyncRequestStepFactory.java
operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java
operator/src/main/java/oracle/kubernetes/operator/logging/MessageKeys.java
operator/src/main/java/oracle/kubernetes/utils/SystemClock.java
operator/src/main/resources/Operator.properties
operator/src/test/java/oracle/kubernetes/operator/StuckPodTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java
operator/src/test/java/oracle/kubernetes/operator/helpers/TuningParametersStub.java
operator/src/test/java/oracle/kubernetes/utils/SystemClockTestSupport.java

This code looks for stuck pods, which is detects by comparing the current time with any deleted time stamp, allowing for the specified grace period. If any pods managed by the operator is terminated, but are still present after the grace period, the operator will force-delete them and run a new make-right on their domain(s).
Note: we need to do some code cleanup on the async calls. Adding new parameters to be checked by unit tests is increasingly difficult. It is time to introduce an object rather than passing in a list (see Clean Code, chapter 3, regarding function parameters).

Detect and shut down stuck server pods

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSamples.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java

Integration tests for domain lifecycle scripts added in OWLS-83995. Resolved merge conflicts in ItSamples class, these changes were pulled out from PR https://github.com/oracle/weblogic-kubernetes-operator/pull/2002.
Successful integration test run - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3000/

OWLS85912 - Integration tests for domain lifecycle scripts added as part of OWLS-83995.

---

docs-source/content/userguide/overview/k8s-setup.md

Update Docker and Kubernetes versions in the K8s setup doc, according to JIRA (OWLS-80570 K8S INSTALL STEP AND PRE-REQUISITE FOR KUBCTL AND DOCKER VERSION ARE NOT IN SYNC

fix K8s setup doc

---

operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java

OWLS-85910 - Display correct value of `domain.status.clusters[].minimumReplicas`  for dynamic clusters when `domain.spec.allowReplicasBelowMinDynClusterSize` is at its default (true).

owls-85910 - display correct minimumReplicas status for dynamic clusters

---

operator/src/main/java/oracle/kubernetes/operator/StuckPodProcessing.java
operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupportTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/RollingHelperTest.java

We've had a long-running issue where calls to delete a pod would fail even though the underlying deletion was successful. This failure was due to attempting to deserialize a Pod from the response even though the actual response from the REST call could either be a Pod or a Status depending on the timing of the underlying deletion operation.
The Java API handled this by only handling the Pod response and failing otherwise.
This is causing problems with the "stuck Terminating pod" deletion functionality because that activity is retried repeatedly interleaving with the operator's behavior to create a new pod -- therefore, the customer would see a pod deleted, immediately recreated, and then deleted again in a cycle that would go for five iterations.
This change replaces the pod deletion …

Response from pod delete REST call can be Pod or Status

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomain.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/TestAssertions.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Application.java

1. Use "kubectl exec" instead of Kubernetes Java client exec call to verify application accessibility.
2. Use Awaitility utilities instead of a while loop for retries.
3. Sync up with the completion of the main thread from the accounting thread.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3043/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3044/

Owls85476 attempt to fix intermittent integration test issues in nightlies

---

operator/src/main/resources/scripts/livenessProbe.sh

A WebLogic server's life-cycle state file is now essentially a public API:  at least one user alters it in order to force a pod restart (by setting its contents to FAILED_NOT_RESTARTABLE). This pull adds a code comment to help make sure that liveness probe's check of the file remains in place even if we move to a different life-cycle implementation in the future.

Add comment to liveness probe

---

kubernetes/samples/scripts/domain-lifecycle/helper.sh
kubernetes/samples/scripts/domain-lifecycle/stopServer.sh

OWLS 85938 - Server lifecycle script changes to use `domain.status.minimumReplicas` when allowReplicasBelowMinDynClusterSize is set to `false`. It also fixes a minor bug when setting server start policy to ALWAYS.
This change adds a check in stop script to see if replica count value is same as minimum replica count value and prevents script from incorrectly assuming that decreasing the replica count would shut down a server. Additionally, when replica count value of cluster is lower than minimum replica count, it resets the replica count value to minimum replica count value. This helps server start script to know the value of effective replica count.

OWLS 85938 - Server lifecycle script changes to use domain.status.minimumReplicas when stopping/starting server

---

docs-source/content/faq/resource-settings.md

Removed cross-ref from "Pod memory and CPU resources" FAQ to the Monitor a SOA Domain sample.

remove broken x-ref

---

docs-source/content/faq/oci-fss-pv.md
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInPV.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDomainModelInPV.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItParameterizedDomain.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsLoadBalancers.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-job-template.yaml
operator/src/main/resources/scripts/livenessProbe.sh
operator/src/main/resources/scripts/startServer.sh

This is part of making restrictive SCC work on OpenShift. In addition to the specific change to startServer.sh to only chmod when permitted, I noticed that many of the integration tests were initializing PV's with chown oracle:oracle rather than with oracle:root. I've updated those references too.

Update the startServer.sh copy functionality to only chmod owned files

---

kubernetes/charts/weblogic-operator/templates/_operator-cm.tpl
kubernetes/charts/weblogic-operator/templates/_operator-secret.tpl
src/scripts/initialize-internal-operator-identity.sh

When using 'helm upgrade' command for the operator, the 'weblogic-operator-secrets' data field is nil (empty or null) if there are no key/value pairs defined in the 'data' dictionary.  In this specific scenario, the 'internalOperatorKey' key is not defined and so the 'data' field of the 'weblogic-operator-secrets' Secret resource has no defined key/value pairs hence it is defined as 'nil' (null or empty).  The 'index' function cannot operate on a 'nil' object.  The fix was to add a condition check for '$secret.data'.
When doing an upgrade, if either the key or certificate of the operator's internal SSL identity is missing then the operator will generate a new one when the operator is re-started.

OWLS-86038: Helm upgrade error missing internalOperatorKey

---

docs-source/content/release-notes.md
docs-source/content/samples/simple/azure-kubernetes-service/_index.md

Fix x-refs and Azure sample operator version.

fix x-refs

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java

use case:
1. When a domain resource has spec.introspectVersion configured, all WebLogic server pods will have a label "weblogic.introspectVersion" set to the value of spec.introspectVersion.
2. When a domain resource has spec.introspectVersion configured, after a cluster is scaled up, new server pods have the label "weblogic.introspectVersion" set as well.
3. When the spec.introspectVersion is changed, all running server pods' weblogic.introspectVersion label is updated to the new value.
4. When a domain/cluster is rolling restarted without changing the spec.introspectVersion, all server pods' weblogic.introspectVersion label stay unchanged after the pods are restarted.
Passed Jenkins jobs:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3095   (sequential) …

Added tests to verify a new label to communicate latest introspect version

---

integration-tests/src/test/java/oracle/weblogic/domain/Model.java
integration-tests/src/test/java/oracle/weblogic/domain/OnlineUpdate.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiUpdateDomainConfig.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Domain.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java
integration-tests/src/test/resources/wdt-models/model.config.wm.yaml
integration-tests/src/test/resources/wdt-models/model.update.wm.yaml

This is for merging to `dynamicupdate` branch
Added new integration test `ItMiiDynamicUpdate` under integration-tests/src/test/java/oracle/weblogic/kubernetes/ for testing dynamic update of work manager configurations. First update adds a new work manager, min and max threads constraints, and a second update changes the count of the min and max threads constraint.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3120/

owls85464 - add MII dynamic update tests for changing work manager config

---

docs-source/content/release-notes.md
docs-source/content/userguide/introduction/introduction.md

As per OWLS-85984: WKO - Document Certification of Operator on TANZU K8s, added Tanzu support to the Release Notes and supported environments docs.

add Tanzu support

---

kubernetes/samples/scripts/domain-lifecycle/helper.sh
kubernetes/samples/scripts/domain-lifecycle/startCluster.sh
kubernetes/samples/scripts/domain-lifecycle/startDomain.sh
kubernetes/samples/scripts/domain-lifecycle/startServer.sh
kubernetes/samples/scripts/domain-lifecycle/stopCluster.sh
kubernetes/samples/scripts/domain-lifecycle/stopDomain.sh
kubernetes/samples/scripts/domain-lifecycle/stopServer.sh

1. Fixed the python yaml module issue on Mac OS by using yq instead of python
2. Fix validation error messages for start/stop cluster and domain scripts when no parameters are specified as part of OWLS-86060.

Fix for mac os and validation error messages when no parameters are specified (OWLS-86060)

---

docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md

Creating a sample for running operator on Tanzu Kubernetes grid.
The sample uses model-in-image domain and metallb loadbalancer for accessing applications deployed in cluster.
Also has example to configure nginx for accessing admin console.

Tanzu sample certification documentation

---

operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java

Fix for owls-85429. This change fixes 409 error response in ReplacePodResponseStep during pod replacement caused due to in-progress delete operation. The fix waits for pod delete operation to complete before starting pod create operation.

Fix for owls-85429 in operator 3.0.3 release

---

operator/src/test/java/oracle/kubernetes/operator/helpers/AdminPodHelperTest.java

Remove calls to add null pod watcher component in AdminPodHelperTest as it's not needed.

Fix to unit test for owls-85429

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java

Update the test methods in ItServerStartPolicy class to use new domain LifeCycle script instead of using patch commands. See the coverage in ItSamples.java. The  ItSamples class does not cover independent managed server and configured cluster and AdminServer shutdown.
Add some Negative Tests:
(a) can not shutdown admin server
(b) server/domain/cluster does not exists as passed thru command line
in a command line pass -c foo. ( where there is no such cluster foo in domain resource )
(c) start a manged server beyond limit
max Dynamic Cluster size is 3, you start a managed managed-server4
(d) shutdown Admin server and start/stop a manged server
padded Jenkins job:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3191 (parallel) …

Updated the ItServerStartPolicy Tests to use new domain LifeCycle script instead of using patch commands

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorUpgrade.java

Added a new test method to update operator from Version 3.0.4 to develop.
Extended the continuous application availability verification to use admin server in addition to managed server(s)
This will make sure none of the WebLogic sever got re-started during Operator version upgrade 
Upgrade Run
https://build.weblogick8s.org:8443/job/wko-tmp/114

Operator Upgrade from v3.0.4 to develop

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
integration-tests/src/test/resources/bash-scripts/install-istio.sh
integration-tests/src/test/resources/bash-scripts/uninstall-istio.sh

Modified Integration Test infra to support istio  v1.7.3
Note :  It requires minimum K8s version 1.16
Jenkin Parallel Run 
https://build.weblogick8s.org:8443/job/wko-tmp/118/  ( all ISTIO tests passed )

Modified Integration Test infra to add istio v1.7.3

---

docs-source/content/userguide/introduction/architecture.md

Documentation fix to mention the correct default value of liveness probe for server pods (45 seconds instead of 15 seconds). This PR is for the master branch since develop branch has some additional changes for liveness probe customization.

Documentation fix for the default value of server pod liveness probe period seconds

---

docs-source/content/userguide/managing-domains/domain-lifecycle/startup.md

Add a note on managed servers may not be able to start up while the admin server is shut down.

doc change - add note on shutting down adminServer

---

operator/src/main/java/oracle/kubernetes/operator/helpers/BasePodStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/test/java/oracle/kubernetes/operator/helpers/AdminPodHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ManagedPodHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/Matchers.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java

Populate the same set of environment variables that are populated in WebLogic server container to init containters. Added unit test for new behavior. 
Integration test url - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3194/

OWLS-77957 - Populate server and domain related env variables to init containers

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
operator/pom.xml
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/main/java/oracle/kubernetes/operator/steps/ActionResponseStep.java
pom.xml

Very minor updates to plugins to be compatible with JDK 15.0.1. When I updated the checkstyle plugin, this then required a few minor changes to Java files because of issues that were previously not detected.

Plugin updates to be compatible with latest JDK

---

operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodHelper.java
operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStep.java
operator/src/test/java/oracle/kubernetes/operator/helpers/DomainPresenceInfoTest.java
operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStepTest.java

Fixed the logic to start clustered managed server pods when admin server pod is not running. The previous logic was assuming that admin server pod is scheduled and ready when starting managed server pods.   Added a unit test for the new behavior. 
Integration test results at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3305

OWLS-86407 - Fixed the logic to start clustered managed server pods when admin server pod not running

---

integration-tests/pom.xml
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java

Added the following new test cases
ItServerStartPolicy.testStandaloneManagedRestart 
ItServerStartPolicy.testConfiguredServerLifeCycleWithoutAdmin  ( msi mode ) 
ItServerStartPolicy.testDynamicServerLifeCycleWithoutAdmin       (msi mode)
Added extra verification for starting/stopping a domain/cluster/servers with already started/stopped domain/cluster/servers
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3322/

OWLS-86409: Additional Managed Server LifeCycle Tests and update usecases without Admin Server  

---

operator-build-maven-plugin/src/main/java/oracle/kubernetes/mojo/shunit2/ShUnit2Mojo.java
operator-build-maven-plugin/src/test/java/oracle/kubernetes/mojo/shunit2/ShUnit2MojoTest.java
operator/src/main/resources/scripts/modelInImage.sh

This addresses two issues:
1. In some environments, copying values split across multiple volumes was joining the pieces in the wrong order. Setting the LOCALE as part of the copy addresses that.
2. The shunit2 plugin now honors the `skip.unit.tests` property

Shell unit test fix

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/TestActions.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/Pod.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java

This is a negative test for MII dynamic update - changing domain name at runtime (unsupported).
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3337/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3340/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3343/

negative test for changing domain name using MII dynamic update 

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java

Due to recent intermittent Jenkin failures in Istio Usecases, modify the integration test infra to install a given version of ISTIO based on a environment variable ISTIO_VERSION.  The default is v 1.7.3  that matches with Verrazzano usage.
public static final String ISTIO_VERSION =
Optional.ofNullable(System.getenv("ISTIO_VERSION")).orElse("1.7.3");
This PR gives a flexibility to run the integration test against a custom version of ISTIO which is being updated frequently.
https://build.weblogick8s.org:8443/job/wko-tmp/138/  ( v1.7.3 ) 
https://build.weblogick8s.org:8443/job/wko-tmp/139/  ( v1.7.6 )
None of the results are clean. We have similar failure in both runs.  
We have the JIRA  OWLS-86461 open to track the intermittent issue

Parameterize the istio version based on environment varaiable

---

operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStep.java

Fix for multiple pod restarts during rolling update. In a domain with multiple clusters, previously it was launching multiple roll commands (one for each cluster) during rolling update. With this change, the roll command gets launched only once after all managed servers are started. This change executes the ManagedServerUpAfter step after the servers in all the clusters get started instead of executing it after servers start in each cluster .

OWLS-86552 - Multiple pod restarts during rolling update fix. 

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/BuildApplication.java

ItCrossDomainTransaction test failing in nightly parallel runs the last 2 days. The method where it is failing is be called by a few other tests as well, but those tests pass. Trying to add some debug to figure what could be causing the failure.

adding debug info for crossdomainxaction test

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSessionMigration.java

When using curl version 7.61.1 , curl -b cookiefile doesn't work with a HTTP request that uses a managed server address, 
here is summery:
---------------------
cluster address + "-c" + "-b" – works
cluster address + "-D" + "-b" – not work
ms address + "-D" + "-b" – not work
ms address + "-c" + "-b" – not work
In  this PR, we changed Session migration test to use "-c" to dump a cookiefile and "-b" to read the cookiefile and pass it to a HTTP request built with WLS cluster address

Changed curl option to dump and read cookiefile

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItParameterizedDomain.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/K8sEvents.java

Integration test to verify the rolling restart behavior in a domain with multiple WLS clusters and making sure that pods are restarted only once. This is to catch the regression issue reported by OFSS team in OWLS-86552. 
Test performs rolling restart of a MII domain with 2 clusters by changing the `spec.imagePullPolicy` to `Never`  (from IfNotPresent). It verifies that DomainChanged, DomainProcessingStarted and DomainProcessingCompleted events are generated. Additionally it verifies that managed server pods in both clusters are killed and started exactly once by checking pod events. 
Integration test results - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3463/

OWLS-86606 - Integration test for multiple pod restarts regression issue in OWLS-86552

---

src/scripts/scaling/scalingAction.sh

Update get_domain_api_version in scalingAction.sh to use kubernetes /apis instead of /apis/apiextensions.k8s.io/v1beta1/customresourcedefinites to find the API version for the operator.
Also fixes a missing colon in python script generated for get_min_replicas, and removing it afterwards.
Example of /apis result returned from kubernetes:
```
{
"kind": "APIGroupList",
"apiVersion": "v1",
"groups": [
{
...
},
...
{
"name": "weblogic.oracle",
"versions": [
{
"groupVersion": "weblogic.oracle/v8",
"version": "v8"
},
{
"groupVersion": "weblogic.oracle/v7",
"version": "v7"
}
],
"preferredVersion": {
"groupVersion": "weblogic.oracle/v8",
"version": "v8"
}
}
]
}
```
get_domain_api_version would return v8 from `preferredVersion.version` of the group with name weblogic.oracle.  …

OWLS-86630 - scalingAction.sh needs adjustment in finding latest API version

---

operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServersUpStep.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java

OWLS-86816 - Operator generates domain processing events every time domain presence is rechecked even when there are no domain updates. This happens in cases where cluster's replica count is lower than the max cluster size. In such cases, `serversToStop` list in the `ManagedServersUpStep` contains servers that should not be started. Later in processing, the `ServerDown` step checks if the server pod is null and invokes `DeletePod` step only when the server pod is not null. 
This fix removes the servers that are already stopped (servers with null pod) from `serversToStop` list and it also checks whether server only needs it's service pre-created. In such cases, the domain processing events are not generated.

OWLS-86816 - Fix to generate domain processing event only when there domain updates

---

operator/src/main/java/oracle/kubernetes/operator/helpers/DomainPresenceInfo.java
operator/src/main/java/oracle/kubernetes/operator/helpers/EventHelper.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorTest.java

OWLS-86939 - The domain processing completed event is not generated during a scale up operation. This is because event type in the packet is not `domain processing starting` . The domain processing started event is generated during managed server pod creation which happens in a child fiber and packet in the child fiber is different from packet in the parent fiber. In ManagedServerIteratorUpStep, the packet is cloned and passed to each child fiber with additional info such as SERVER_NAME, SCAN etc.. Hence the `domain processing started` event type in not set in the parent packet. 
This proposed fix stores the event type/item in DomainPresenceInfo instead of storing it in the packet. I have added a unit test which reproduces the issue. Integration test results are at - …

Owls-86939 - Generate domain processing completed event when scaling up a cluster

---

operator/src/main/java/oracle/kubernetes/operator/DomainRecheck.java
operator/src/test/java/oracle/kubernetes/operator/MainTest.java

OWLS-87041 - OKD (Openshift) creates a large number of namespaces and domain is not started when namespaces are listed in multiple chunks. This is caused because the last chunk of namespaces (partial list) overwrites any previous chunks and only namespaces contained in the last chunk are started if they also happen to be part of the operator's target namespaces. 
This change collects the namespaces returned in all chunks in a bigger list so that all namespaces are started. Integration test link - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3595/ . There's a single test failure which is unrelated to this change.

OWLS-87041 - Fix to start namespaces when namespaces are listed in multiple chunks

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItFmwSample.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSamples.java

Here is the resolution 
a. Copy the samples directory  to a unique temporary directory 
b. Modify ItSample test class to run in a defined order. Class level annotation was missing
Jenkin Job:   https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3587/ 
( Only ItIntrospectoprVersionTest are failing even if there is no change to this class )

Resolved the sample test issue on parallel nigtly run

---

operator/src/main/resources/scripts/modelInImage.sh

validateModel.sh prints validation error of the model in stderr instead of stdout,  changing script to accommodate it.

Fix modelInImage.sh to capture WDT validateModel std error

---

buildDockerImage.sh
docs-source/content/faq/namespace-management.md
docs-source/content/quickstart/get-images.md
docs-source/content/quickstart/install.md
docs-source/content/userguide/introduction/architecture.md
docs-source/content/userguide/managing-domains/domain-lifecycle/restarting.md
docs-source/content/userguide/managing-operators/installation/_index.md
docs-source/content/userguide/managing-operators/using-the-operator/using-helm.md
kubernetes/charts/weblogic-operator/values.yaml
kubernetes/hands-on-lab/tutorials/install.operator.ocishell.md

Docker has removed the "oracle" repo. Therefore, you can no longer `docker pull oracle/weblogic-kubernetes-operator:3.1.1`. Thankfully, we have already pushed this image to ghcr.io and the Oracle Container Registry. This change updates the documentation and samples to pull as follows: `docker pull ghcr.io/oracle/weblogic-kubernetes-operator:3.1.1`.

Update all references to use ghcr.io for container images

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporter.java

If integration test runs against other then master branch from monitoring exporter GitHub project, instead of using prebuilt war file it builds web application. Due creation two different web apps for monitoring exporter, second build fails due existed build artifacts. Fixed by adding mvn clean. 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3729/

Fixed monitoring exporter web app build failure

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItElasticLoggingFluentd.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java
integration-tests/src/test/resources/wdt-models/fluentd.configmap.elk.yaml

add automated test to cover the fluentd use case described in
https://oracle.github.io/weblogic-kubernetes-operator/samples/simple/elastic-stack/weblogic-domain/
Passed Jenkins jobs
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3754 (parallel)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3753 (sequential)

Added Integration Tests for fluentd in Operator Environment

---

integration-tests/src/test/resources/python-scripts/application_deployment.py

Updated application_deployment.py test script to remove its usage of methods from Apache Commons IO package, which is causing InvalidJarIndexException when using linux-8-slim images. 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3840/
Testing ItIntrospectVersion with change and with test modified to use deployUsingWlst instead of deployUsingRest:
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3837/testReport/oracle.weblogic.kubernetes/ItIntrospectVersion/

OWLS-86750 - remove dependency on org.apache.commons.io from application_deployment.py

---

operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java

Added methods to add existing PDB info to DomainPresenceInfo during domain recheck. This is to avoid the conflict messages generated during PDB creation.

OWLS71169 - Added methods to add existing PDB info to DomainPresenceInfo during domain recheck.

---

kubernetes/samples/charts/apache-webtier/templates/deployment.yaml
kubernetes/samples/charts/apache-webtier/templates/service.yaml
kubernetes/samples/charts/apache-webtier/values.yaml

The apache-webtier chart was using an unnecessarily complex test for a Boolean value. This test stopped working at Helm version 3.5.0, because that version interpreted the statement as a function call. Replacing the test with a simpler expression resolved the issue.

Fix test for useNonPriviledgedPorts

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/Kubernetes.java

Fixing the oracle.weblogic.kubernetes.actions.impl.primitive.Kubernetes.listNamespacedEvents() to sort events based on creation timestamp.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3995/

use event creation timestamp to sort

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIntrospectVersion.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioCrossDomainTransaction.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInImage.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioDomainInPV.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioMiiDomain.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioTwoDomainsInImage.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItParameterizedDomain.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItProductionSecureMode.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/ItTwoDomainsLoadBalancers.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/TestConstants.java

Skip the WebLogic Console Tests based on the string "slim" in WebLogic Image
Add the following boolean variable in TestConstants.java
public static final boolean WEBLOGIC_SLIM =  WEBLOGIC_IMAGE_TAG.contains("slim") ? true : false;
In ItTestClass assert it before running console tests 
import static oracle.weblogic.kubernetes.TestConstants.WEBLOGIC_SLIM
import static org.junit.jupiter.api.Assumptions.assumeFalse;
public void testAdminConsoleLoginUsingAdminNodePort(Domain domain) {
assumeFalse(WEBLOGIC_SLIM, "Skipping the Console Test for slim image");
OR 
if (!WEBLOGIC_SLIM) {
String consoleUrl = "http://" + K8S_NODEPORT_HOST + ":" + istioIngressPort + "/console/login/LoginForm.jsp";
boolean checkConsole =
checkAppUsingHostHeader(consoleUrl, domainNamespace + ".org"); …

Skip WebLogic console test in slim images

---

operator/src/main/java/oracle/kubernetes/operator/DomainRecheck.java
operator/src/test/java/oracle/kubernetes/operator/MainTest.java

Backport PR#2180 to release 3.1.3 branch.

owls-87091 keep namespaces processed in batches - backport

---

operator/src/main/java/oracle/kubernetes/operator/PodAwaiterStepFactory.java
operator/src/main/java/oracle/kubernetes/operator/PodWatcher.java
operator/src/main/java/oracle/kubernetes/operator/WaitForReadyStep.java
operator/src/main/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStep.java
operator/src/test/java/oracle/kubernetes/operator/DomainProcessorDelegateStub.java
operator/src/test/java/oracle/kubernetes/operator/DomainUpPlanTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/PodHelperTestBase.java

OWLS-87753- Fix for starting managed servers when watch event notifications are missed.
This change creates waiters for each managed server pod in ManagedServerUpIterator step. These fibers are started in parallel with fibers that schedule and actually start the managed server pods. The waiter fibers invoke WaitForReady step for the corresponding managed server. At the time when WaitFotReady is invoked, managed server pods would not have been created. Hence it passes resourceName to the WaitForReady step instead of the initial resource. The managed server pod state is updated periodically in the DomainPresenceInfo when the callback onSuccess is invoked (every 5 seconds) in waitForReady step. The createReadAndIfReadyCheckStep uses domain-id and namespace from the packet instead of getting …

OWLS-87753 - Fix to start all managed server pods when watch event notifications not received in jumbo k8s cluster

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItSessionMigration.java

Add new test to cover update domain's annotations or labels failed if it contains slash in the name.
two failures from annotation-w-slash are same as failures from develop branch
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4028 (develop)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4029 (parallel)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4031 (parallel)
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4030 (sequential)

Add new test to cover update domain's annotations or labels failed if it contains slash in the name

---

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java
operator/src/main/java/oracle/kubernetes/operator/DomainResourcesValidation.java
operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java
operator/src/main/java/oracle/kubernetes/operator/Main.java
operator/src/main/java/oracle/kubernetes/operator/NamespacedResources.java
operator/src/main/java/oracle/kubernetes/operator/OperatorEventWatcher.java
operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java
operator/src/main/java/oracle/kubernetes/operator/calls/UnrecoverableErrorBuilder.java
operator/src/main/java/oracle/kubernetes/operator/helpers/CallBuilder.java
operator/src/main/java/oracle/kubernetes/operator/helpers/EventHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/JobStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodDisruptionBudgetHelper.java
operator/src/main/java/oracle/kubernetes/operator/helpers/PodStepContext.java
operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
operator/src/test/java/oracle/kubernetes/operator/MainTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/EventHelperTest.java
operator/src/test/java/oracle/kubernetes/operator/helpers/EventRetryStrategyStub.java
operator/src/test/java/oracle/kubernetes/operator/helpers/KubernetesTestSupport.java

This PR contains two features plus unit tests: 
1) leverage existing refresh-and-retry logic in AsyncRequestStep in replaceEvent operation;
2) populate the cached event objects with existing events on operator restart.
The integration test run in Jenkins https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3990.

Owls87514 add refresh/retry to event replace operation and populate events maps on operator startup

---

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java
operator/src/main/java/oracle/kubernetes/operator/helpers/RollingHelper.java

OWLS-87175 - Allow the make-right flow to continue when live info from the list is older than the cached info for etcd restore case. For etcd restore use-case, cached data can be newer than the live data since etcd snapshot might have been taken at some time in the past. Based on discussion with Ryan, the possibility of cached data being newer than live data is very rare in the normal scenario.  This change along with a fix for  OWLS-87553 (periodic backstop check in the WaitForReady step) seem to resolve the issue in 32401992 in both Fermin's and my local env.
Integration tests results are at - https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4069/ and manual tests in my env seem to work fine.

OWLS-87175 - Allow make right flow to continue when live data from the list older than cached data

---

operator/src/main/java/oracle/kubernetes/operator/JobWatcher.java
operator/src/test/java/oracle/kubernetes/operator/JobWatcherTest.java

This PR evaluates the job condition in addition to job status to determine if the job has failed. In "etcd restore" test, when job remains in the Pending state for more than `ActiveDeadlineSeconds`, the job condition is changed to "failed" but the job status remains null. This causes the fiber to get stuck in the `WaitForJobReady` step.

Check job condition to determine if job has failed in addition to checking job status

---

operator/src/main/java/oracle/kubernetes/operator/DomainProcessorImpl.java
operator/src/main/java/oracle/kubernetes/operator/DomainRecheck.java
operator/src/main/java/oracle/kubernetes/operator/DomainStatusUpdater.java
operator/src/main/java/oracle/kubernetes/operator/Namespaces.java
operator/src/main/java/oracle/kubernetes/operator/ProcessingConstants.java
operator/src/main/java/oracle/kubernetes/operator/helpers/EventHelper.java
operator/src/test/java/oracle/kubernetes/operator/MainTest.java

Changes in this PR:
1) let operator continue, instead of fail, when it hits Unauthorized error on creating NamespaceWatchingStopped event in the domain's namespace. This only happens when a namespace is not managed by the operator any more, and the permissions that are required to create an event in that namespace have been removed; the operator already logs this error.
2) clean up some classes based on warnings that IntelliJ points out.
3) minor refactoring in DomainRecheck as a followup to a review comment to PR#2180. 
Integration test run on Jenkins (completed with 2 known failures): https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4102/.

minor change plus code cleanup and refactoring

---

operator/src/test/java/oracle/kubernetes/operator/PodWatcherTest.java
operator/src/test/java/oracle/kubernetes/operator/ThreadFactoryTestBase.java
operator/src/test/java/oracle/kubernetes/operator/steps/ManagedServerUpIteratorStepTest.java

Backlog - Added a new unit test for OWLS-87553 fix and modified existing managed server startup tests to invoke WaitForReady step that performs periodic backstop checking in cases where watch event notifications are not delivered reliably.

Added new unit test for OWLS-87553 and modified existing managed server startup unit tests

---

operator/src/main/java/oracle/kubernetes/operator/helpers/ServiceHelper.java
operator/src/main/java/oracle/kubernetes/operator/steps/DeleteServiceListStep.java
operator/src/test/java/oracle/kubernetes/operator/helpers/ServiceHelperTest.java

owls-87625 - Operator 3.0.1 version created external NodePort service with "-external" suffix. Operator 3.1.x creates the external NodePort service with shorter name with "-ext" suffix. This is causing an issue when upgrading the Operator from 3.0.1 to 3.1.1 and changing the `restartVersion`.  This is because the port for the external NodePort service created by Operator 3.1.1 is already in use by the NodePort service created by Operator 3.0.1 with the old name (with "-external" suffix).
This change removes stranded old named node port service during the service replace call by listing services of NodePort type created by the Operator for this particular domain. It deletes the node port service returned by the list call and then replaces it with the new name. Integration test results - …

owls-87625 - Remove stranded old named node port service for the domain when deleting and replacing service

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiDynamicUpdate.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonMiiTestUtils.java
integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/CommonTestUtils.java

Modify MaxDynamicClusterSize and MinDynamicClusterSize using dynamic update.
Verify the cluster cannot be scaled beyond the modified MaxDynamicClusterSize value
and cannot be scaled below MinDynamicClusterSize when allowReplicasBelowMinDynClusterSize is set false.
Verify JMS message and connection distribution/load balance after scaling the cluster.
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4101/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4103/ (In progress)

Test changing MaxDynamicClusterSize and MinDynamicClusterSize using dynamic update

---

kubernetes/samples/scripts/domain-lifecycle/helper.sh

Owls 87209 - Domain lifecycle scripts fix in cases where domain/cluster specs are overridden at the individual managed server level. The script doesn't work correctly when `.spec.managedServers` section has pre-existing details for a particular managed server. For e.g Consider the below stanza where the `serverStartState` attribute is overridden for soa_server1.
spec:
managedServers:    
- serverName: soa_server1
serverStartState: RUNNING
This change adds the server start policy element for the managed server if the policy doesn't exist or replaces the policy if the policy already exists. Similarly, it unsets the policy and/or deletes the managed server element if managed server spec only has serverStartPolicy under it.

Owls 87209 - Domain lifecycle scripts fix in cases where domain/cluster specs are overridden at the individual managed server level

---

integration-tests/src/test/java/oracle/weblogic/kubernetes/ItServerStartPolicy.java

Added two new test cases `testManagedRestartWithConstantReplicaCount` and `testManagedRestartWithDynamicReplicaCount` covering SOA use-case issue reported in OWLS-87209. 
- Made a change to the `.spec.managedServers` section for `managed-server1` to remove the 'serverStartPolicy` and only have `serverStartState` in order to replicate the issue. Did some code cleanup and changes suggested by the IDE. 
External jenkins URL with the passed results -
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4158/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4159/
External jenkins URL without fix (old script) with failed results -\
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/4156/

OWLS-87819 - Integration tests for OWLS-87209, server stop and start scripts when spec is overridden at managed server level 

---

kubernetes/samples/scripts/domain-lifecycle/helper.sh

Backport of server lifecycle scripts fix in cases where domain/cluster specs are overridden at the individual managed server level (OLWS-87209).

Backport of OWLS-87209 fix to the server lifecycle script to 3.1.4 release

---

operator/src/main/java/oracle/kubernetes/operator/helpers/DomainValidationSteps.java
operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsClusterConfig.java
operator/src/main/java/oracle/kubernetes/operator/wlsconfig/WlsDomainConfig.java
operator/src/test/java/oracle/kubernetes/operator/wlsconfig/WlsDomainConfigTest.java

Backport portion of PR 2097 that fixes a bug that was found in validation of `serverName` specified in `managedServers`, in that a validation warning message such as the following is added even though the server name exists in a dynamic cluster:
`Managed Server 'managed-server1' specified in the domain resource does not exist in the WebLogic domain home configuration.`

Fixes incorrect server validation messages for dynamic server
